### ISSUE TITLE
[Question] Regarding Jquery usage in components

### ISSUE THREAD

**Issue by lgarro** [AngularClass/angular2-webpack-starter#1002]
My use case is the following:

Im building an app which frontend was built using regular html , css and jquery. If I add the script tags with the functions of jquery for certain UI behaviors it works fine only if I reload the page that uses it which makes since the window.onload is triggered there. 

My question is how can I translate something like this :

```
$('ul.tabs li').click(function(){
        var index = $(this).index();
        $('ul.tabs li').removeClass('active');
        $(this).addClass('active');
        $('.panes').hide();
        $('.panes').eq(index).show();
        return false
    });
```

or 

$(".gridder-tab").gridderExpander({
                scroll: true,
                scrollOffset: 100,
                scrollTo: "listitem",
                animationSpeed: 400,
                nextText: "",  
                prevText: "",  
                closeText: "",
                onStart: function () {
                    console.log("Gridder Inititialized");
                },
                onExpanded: function (object) {
                    console.log("Gridder Expanded");
                    $(".carousel").carousel();
                },
                onChanged: function (object) {
                    console.log("Gridder Changed");
                },
                onClosed: function () {
                    console.log("Gridder Closed");
                }
         });

to be injected from the component that uses it . I've tried using this declare var JQuery:any; on top of the component, but I get errors saying JQuery does not exists. For this approach I also imported the jquery files from the cdn on my index.html

Any ideas on how can I integrate this behaviors to each component so that when they load they always have the function available and not just on reload.

Thanks in advance

**Comment by anselmhou** [comment]
You need to both expose jquery and @type/jquery

**Comment by Andrey-Pavlov** [comment]
>You need to both expose jquery and @type/jquery
Can you share some code?

**Comment by lgarro** [comment]
@anselmhou do you have some sample code on the way to implement it.
