### ISSUE TITLE
Unit test error: Router outlet is not a known element

### ISSUE THREAD

**Issue by gaurav2887** [AngularClass/angular2-webpack-starter#1004]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[x ] bug report

I am getting following error when running a unit test: 

Error: **Template parse errors:
    'router-outlet' is not a known element:
    1. If 'router-outlet' is an Angular component, then verify that it is part of this module.**

**My unit test code:**

```

import {
    inject,
    TestBed
} from '@angular/core/testing';

// Load the implementations that should be tested
import { App } from './app.component';
import { AppState } from './app.service';
import { Renderer } from '@angular/core';
import { Router, RouterOutlet } from "@angular/router";

class MockRouter { public navigate() {}; }

describe('App', () => {
    
    // provide our implementations or mocks to the dependency injector
    beforeEach(() => TestBed.configureTestingModule({
        declarations: [ App ],
        providers: [
            AppState,
            Renderer,
            {provide: Router,  useClass: MockRouter },
            RouterOutlet
        ]}));

    it('should have a url', inject([ App ], (app: App) => {
        expect(app.name).toEqual('test');
    }));

});
```

**My app.html has router outlet:**

 <section class="page">

            <router-outlet></router-outlet>

 </section>

I tried removing RouterOutlet as well in unit test and it did not work. Has anyone experienced this issue and help me with the solution?

**Comment by gaurav2887** [comment]
I resolved this by importing RouterModule in spec file.

**Comment by eamell** [comment]
That didn't work for me (using 2.0.0).  What worked for me was importing RouterTestingModule instead.

**Comment by gaurav2887** [comment]
@eamell - I am still on rc6 and I changed my configuration to RouterTestingModule and it still works. Thanks for the help as this will not break my tests when I will move to 2.0.0

I am doing it this way now. Is that correct?

```
import {
    RouterTestingModule
} from '@angular/router/testing';

  beforeEach(() => {

        TestBed.configureTestingModule({
            providers: [
                App,
                AppState,
                Renderer,
                {provide: Router,  useClass: MockRouter }
            ],
            imports: [ RouterTestingModule ]
        });

    });
```

**Comment by randyangeles** [comment]
Hi @eamell,

I tried importing RouterTestModule in my spec file but just end up getting another error.

```
    beforeEach(async(() => {
        TestBed.configureTestingModule({
            declarations: [
                AppComponent
            ],
            providers: [
                // Other provides...
                { provide: Router, useClass: class { navigate = jasmine.createSpy("navigate"); } }
            ],
            imports: [
                // Other modules...
                RouterTestingModule
            ]
        });

    }));
```
Error message I got: Cannot read property 'root' of undefined.

It looks like it was trying to evaluate: router.RouterState.root. Am I missing something here?

Thanks!

**Comment by eamell** [comment]
Hi @randyangeles,

If you are trying to setup routes you need to provide the routes in your import and unless I am mistaken importing RouterTestingModule takes care of mocking Router for you.  You would need to do something like the following:

```
  beforeEach(() => {
    TestBed.configureTestingModule({
      declarations: [
        AppComponent
      ],
      imports: [
           RouterTestingModule.withRoutes({_route here_})
      ]
    });

    fixture = TestBed.createComponent(AppComponent);
    app = fixture.debugElement.componentInstance;
  });

```
You can then create routes to actual or mock components within your test.  In my case the routing is really simple (I really only use routing to make it easy to get info from the URL and for future support) so I actually removed the routing and only include the core import at the moment.

Take a look at the documentation (which unfortunately still appears to be a work in progress) for more information (https://angular.io/docs/ts/latest/api/router/testing/index/RouterTestingModule-class.html).

Hope this helps!

**Comment by eamell** [comment]
Hi @gaurav2887,

Just saw your post.  As I mentioned to @randyangeles, I don't think you should be mocking the router rather use the withRoutes function when importing RouterTestingModule.  That way you can route to either your actual components or to mock components.  My hope is that using this approach we will be less susceptible to framework changes going forward.

Hope that helps!

**Comment by randyangeles** [comment]
Hi @eamell,

Tried your approach and it worked! Going to leave what I did here to help someone down the road hopefully.

```
    @Component({
        template:''
    })
    class MockLoginComponent { }

    @NgModule({
        declarations: [MockLoginComponent],
        exports:      [MockLoginComponent]
    })
    class MockModule { }

    beforeEach(async(() => {
        TestBed.configureTestingModule({
            declarations: [
                AppComponent
            ],
            providers: [
                //...
            ],
            imports: [
                MockModule,
                RouterTestingModule.withRoutes([
                    {
                        path: 'login',
                        component: MockLoginComponent
                    }
                ]),
            ]
        });
    }));
    
    it(...
       spyOn(appComponent.router, 'navigate');
       expect(appComponent.router.navigate).toHaveBeenCalledWith(['/login']);
       expect(appComponent.router.navigate).toHaveBeenCalledTimes(1);
    );
```

Thanks for your help!

**Comment by gaurav2887** [comment]
@eamell - Thanks. 

One of my test case is breaking with RouterTestingModule as following code do not set router url property value to 'help'. 

  

> spyOn(app.router, 'navigate');
>   app.router.navigate(['/help']);


I have a function which is using "this.router.url.indexOf(route) > 0" logic and I want to test that by mocking the url.  router.navigate does not set the url property. How can mock router.url?

**Comment by boraita** [comment]
I tried make testing with different inject but the principal problem es that the router is not recognized.
somebody can I help with what I have that add into describe or in other site.

import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import { RouterModule } from '@angular/router';


import { AppComponent } from './app.component';
import { SearchComponent } from './search/search.component';

@NgModule({
  declarations: [
    AppComponent,
    SearchComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    RouterModule.forRoot([
      { path: '', component: SearchComponent },
    ])
  ],
  providers: [],
  bootstrap: [AppComponent]
})

export class AppModule { }

--------------------------

import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-search',
  templateUrl: './search.component.html',
  styleUrls: ['./search.component.css'],
})
export class SearchComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

-------------------------------

describe('Component: Search', () => {
  it('should create an instance de router', () => {
    beforeEach(() => {
    TestBed.configureTestingModule({
      declarations: [
        SearchComponent, RouterModule
      ]
    });
  });


---------------

Error:
'router-outlet' is not a known element:                                                                                                                     
        1. If 'router-outlet' is an Angular component, then verify that it is part of this module.                                                                  
        2. If 'router-outlet' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("        
        </nav>                                                                                                                                                      
        [ERROR ->]<router-outlet></router-outlet>"): AppComponent@6:0

**Comment by chenyingyin** [comment]
ugg outlet
cheap oakley sunglasses
adidas yeezy
true religion jeans
louis vuitton handbags
seahawks jerseys
air jordans
coach outlet online
michael kors bags
louis vuitton outlet
coach outlet
the north face outlet
sac louis vuitton
louis vuitton outlet
cheap oakley sunglasses
ugg slippers
gucci outlet
christian louboutin outlet
uggs outlet
coach outlet online
louis vuitton outlet online
replica rolex watches
doudoune moncler
ugg boots
ugg boots
louis vuitton
true religion outlet
chanel bags
louboutin outlet
beats by dre headphones
pandora jewelry outlet
toms outlet
hermes handbags
uggs sale
cheap oakley sunglasses
cheap uggs
louis vuitton outlet online
ugg outlet online
ray ban sunglasses outlet
kate spade handbags
the north face
ray ban sunglasses outlet
louboutin pas cher
ugg boots
ugg boots
ugg outlet
burberry scarf
michael kors
jordan retro
canada goose outlet
gucci handbags
ugg boots outlet
replica rolex watches
christian louboutin heels
canada goose jackets
roshe run 3
christian louboutin outlet
louis vuitton
nba jerseys
ugg boots
ray ban sunglasses sale
canada goose
ugg boots
ugg boots
true religion jeans
coach outlet
ralph lauren polo
canada goose outlet
canada goose jackets
nike roshe one
moncler outlet
nike air max
coach outlet
christian louboutin uk
cheap jordans
celtics jerseys
louis vuitton outlet online
wizards jerseys
louis vuitton outlet
polo ralph lauren
chaussures christian louboutin
polo ralph lauren
ray bans
coach outlet
fitflop sandals
moncler jacket
doudoune canada goose
cheap rolex watches
patriots jerseys
uggs on sale
timberland outlet
gucci outlet store
hollister jeans
uggs outlet
prada handbags
coach outlet store online
fitflop shoes
ugg slippers
nike trainers uk
celine bags
nfl jerseys
gucci outlet
cheap jordan shoes
louis vuitton handbags
bengals jerseys
ugg outlet
coach outlet
ugg canada
uggs outlet
adidas yeezy
coach outlet
hollister clothing store
ugg boots uk
adidas outlet
ugg boots outlet
louboutin pas cher
ugg outlet
hollister clothing store
abercrombie and fitch
canada goose outlet
ugg boots
cheap uggs
michael kors
cheap adidas shoes
kate spade outlet
ralph lauren uk
ugg boots
true religion jeans
coach outlet online
louis vuitton outlet online
gucci outlet online
louis vuitton
ugg boots
adidas originals shoes
uggs outlet
louis vuitton
mont blanc pens
cheap jordans
longchamp outlet store
jordan pas cher
michael kors outlet
uggs outlet
canada goose jackets
fitflop sandals
ugg outlet
air max pas cher
louis vuitton outlet online
michael kors outlet
cheap ugg boots
hollister clothing
tory burch handbags
ugg boots clearance
adidas nmd runner
louis vuitton handbags
gucci outlet
nike outlet
ugg pas cher
ray ban sunglasses outlet
christian louboutin heels
timberland boots
ed hardy shirts
canada goose jackets
cheap jordan shoes
pandora charms
hogan sito ufficiale
michael kors handbags
mbt shoes
tommy hilfiger outlet
jordans for sale
ugg australia
pandora jewelry
ray ban sunglasses
air jordans
mbt outlet
cheap nhl jerseys
heat jerseys
kate spade outlet
ugg australia
canada goose sale
coach factory outlet
prada outlet online
coach factory outlet
the north face jackets
rolex watches outlet
burberry outlet online
christian louboutin shoes
louis vuitton
louis vuitton borse
cheap ugg boots
louis vuitton
louis vuitton bags
polo ralph lauren outlet
michael kors outlet
canada goose
ralph lauren
ralph lauren
air max 90
nba jerseys cheap
longchamp outlet
canada goose clothing
burberry outlet
louis vuitton pas cher
coach factory outlet
moncler uk
louis vuitton handbags
michael kors outlet
chaussures ugg
louis vuitton
ugg uk
cheap jerseys
coach outlet online
adidas nmd r1
mlb jerseys
air max uk
cheap ugg boots
ugg outlet
moncler
louis vuitton discount
celine outlet
nike roshe run
michael kors outlet online
michael kors outlet clearance
moncler soldes
hockey jerseys
kate spade handbags outlet
uggs outlet
mulberry bags
louis vuitton
warriors jerseys
christian louboutin outlet
cheap uggs
ralph lauren outlet
tiffany and co
adidas superstar trainers
michael kors outlet
ugg boots outlet
tiffany and co jewelry
nike roshe run pas cher
oakley sunglasses
canada goose outlet
spurs jerseys
michael kors outlet clearance
coach factory outlet
ray ban glasses
cheap mlb jerseys
tommy hilfiger
michael kors outlet clearance
ray bans uk
oakley vault
toms wedges
ralph lauren polo
burberry scarf
tory burch outlet
ugg outlet
coach outlet store online clearances
canada goose uk
chanel outlet
ugg outlet
true religion outlet
mcm handbags
canada goose
canada goose
toms shoes uk
canada goose jackets
true religion jeans
louis vuitton outlet
louis vuitton purses
rolex watches outlet
retro jordan 12
christian louboutin outlet
cheap oakley sunglasses
tory burch outlet
broncos jerseys
gucci handbags
louis vuitton
chaussures jordan
louis vuitton outlet
canada goose jackets
oakley sunglasses
ugg canada
mont blanc pens cheap
toms outlet
cheap nfl jerseys
moncler uk
coach outlet online
timberland boots
coach outlet
kate spade
louboutin shoes
ray ban sunglasses
canada goose sale
fitflop sale
coach outlet
ray ban sunglasses
oakley sunglasses outlet
polo ralph lauren
oakley canada
true religion outlet
ray ban sunglasses outlet
nike tn 2016
adidas yeezy 350 boost
pandora rings
giuseppe zanotti shoes
chaussures ugg
adidas trainers uk
nike outlet store
abercrombie kids
mont blanc ballpoint pens
thunder jerseys
fitflop uk
coach outlet
ugg boots
toms shoes outlet
pandora charms
michael kors
oakley sunglasses
cheap rolex watches
mavericks jerseys
moncler jackets
pandora jewelry
ugg outlet
seahawks jerseys
montblanc pens
michael kors handbags
cheap ugg boots
ray ban sunglasses
polo outlet
ralph lauren polo uk
coach factory outlet
ray ban glasses
fitflops sale clearance
michael kors outlet
cheap jordan shoes
clippers jerseys
adidas nmd
coach outlet store online clearances
the north face
ray ban sunglasses
ugg boots
nike outlet store
ugg boots uk
uggs clearance
supra shoes
abercrombie oultet
timberland shoes
oakley sunglasses
canada goose jackets
vikings jerseys
ugg outlet
coach outlet online
louis vuitton handbags
moncler jackets
hermes bags
canada goose
uggs italia
ugg outlet
moncler jacket
steelers jerseys
coach outlet store online clearances
adidas yeezy boost
ray ban lunettes
fitflop shoes
cheap louis vuitton handbags
cheap oakley sunglasses
ugg boots
louis vuitton outlet stores
ugg boots sale
bulls jerseys
canada goose jackets
coach handbags new
louis vuitton outlet
prada outlet
ray ban glasses
ugg outlet online
rolex watches
nike air max uk
michael kors outlet clearance
michael kors outlet
canada goose jackets
christian louboutin uk
michael kors
north face outlet
adidas shoes
cheap ray ban sunglasses
toms outlet
cheap basketball shoes
jordan retro
stivali ugg
fitflop shoes
hollister jeans
louboutin shoes
cheap ray ban sunglasses
uggs uk
longchamp pas cher
uggs sale
ray ban outlet
jordans for sale
tory burch shoes
ugg boots
cheap toms shoes
coach outlet store online
toms outlet
ralph lauren
rolex watches
true religion jeans outlet
cavaliers jerseys
gucci outlet
michael kors outlet
coach factory outlet
michael kors outlet
tiffany and co
tod's shoes
ugg boots
ugg outlet
polo ralph lauren
ugg slippers on sale
knicks jerseys
red bottoms
uggs outlet
louis vuitton canada
polo ralph lauren
cheap oakley sunglasses
chenyingying20161201

**Comment by chenyingyin** [comment]
![default](https://cloud.githubusercontent.com/assets/24284270/20781345/18176ee6-b7bd-11e6-9b9e-2eac3db31a4e.png)
![default](https://cloud.githubusercontent.com/assets/24284270/20781350/1e8942e0-b7bd-11e6-890e-e165626527fe.png)
![Uploading 图片.png…]()

**Comment by chenyingyin** [comment]
![default](https://cloud.githubusercontent.com/assets/24284270/20781367/377e782e-b7bd-11e6-935c-fe46cb0e3e07.png)

**Comment by d3viant0ne** [comment]
Posts deleted & reported.

**Comment by ajithvallabai** [comment]
i resolved it by adding "routing " to imports: (Ngmodule)

**Comment by sharp-summit** [comment]
I try to add "RouterModule" to the @Ngmodule.  
It worked! Thanks! @ajithvallabai

**Comment by kam1515** [comment]
import {NgModule, Component} from '@angular/core';
import { ToasterService} from 'angular2-toaster';
import { ToastComponent } from 'angular2-toaster/angular2-toaster';
import { ToasterModule } from 'angular2-toaster';
import {BrowserAnimationsModule} from '@angular/platform-browser/animations';
import { RouterOutlet, RouterModule } from '@angular/router';

@NgModule({
  imports: [BrowserAnimationsModule, ToasterModule, RouterModule],
  declarations: [TestComponent],
  providers: [],
  bootstrap: [TestComponent]
})



@Component({
  selector: 'root',
  template: `
            <toaster-container></toaster-container>
            <button (click)="popToast()">pop toast</button>`,

  providers: [ToasterService]
})

export class TestComponent {
  private toasterService: ToasterService;

  constructor(toasterService: ToasterService) {
    this.toasterService = toasterService;
  }

  popToast() {
    this.toasterService.pop('success', 'Args Title', 'Args Body');
  }
}


Above is my code and I'm still getting the below error....

Uncaught Error: Template parse errors:
'toaster-container' is not a known element:
1. If 'toaster-container' is an Angular component, then verify that it is part of this module.
2. If 'toaster-container' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. (".....

Any help is appreciated.

Note: I have installed Angular 4 in m y machine.

**Comment by duluca** [comment]
It's easy to miss the correct solution in the thread. @eamell solution of adding `RouterTestingModule` is the correct one. More details can be found at https://github.com/mrholek/CoreUI-Free-Bootstrap-Admin-Template/issues/202#issuecomment-316686130
