### ISSUE TITLE
support for aot compilation?

### ISSUE THREAD

**Issue by born2net** [AngularClass/angular2-webpack-starter#1007]
Does this project support ahead of time compilation ?
 I didn't see any info in the readme,

tx

Sean

**Comment by yuanfeiz** [comment]
Check these issues:
#885 
#843

**Comment by IAMtheIAM** [comment]
Yes, however I'm having trouble getting it integrated even with those examples.

**Comment by smith64fx** [comment]
+1

**Comment by sbehun** [comment]
+1

**Comment by smith64fx** [comment]
Sorry guys, but this lasts definetely too long until you support AOT/Universal.

I switched to this starter here and it has everything included. AOT, Treeshaking, Universal and it's much easier to upgrade without having merge conflicts every time.

https://github.com/qdouble/angular-webpack2-starter

**Comment by katallaxie** [comment]
@smith64fx Yep, they have done many things right. We can learn many things. We should try to reduce some of the complexity and bring in more features. As for the AoT support, you can see https://github.com/AngularClass/angular2-webpack-starter/tree/aot

**Comment by katallaxie** [comment]
Duplicate #885
