### ISSUE TITLE
Can't load SASS and CSS

### ISSUE THREAD

**Issue by baonguyenyam** [AngularClass/angular2-webpack-starter#1016]
Hi all!
I can not using "ExtractTextPlugin" for css and sass in AngularClass

I set 
`webpack.common.js`

```
       {
          test: /\.sass$/,
          loaders: ExtractTextPlugin.extract(['style', 'css!sass'])
        },
        {
          test: /\.css$/,
          loaders: ExtractTextPlugin.extract({ fallbackLoader:'style', loader: 'css' })
        }
```

and 
`app.component.ts`

```
styles: [
        require('../../bower_components/animate.css/animate.min.css').toString(),
        require('../../bower_components/k-flex/dist/css/k-flex.css').toString(),
        require('../../bower_components/font-awesome/css/font-awesome.min.css').toString(),
        require('../styles/main.sass').toString()
    ]
```

and i run it still error 
Uncaught Error: Expected 'styles' to be an array of strings. zone.js:129

Help me, thank so much

**Comment by tobyforever** [comment]
'styles' is expected to be an array of strings.

try css-to-string loader:
```
        {
          test: /\.css$/,
          loader: 'css-to-string!css?sourceMap'
        },
        {
          test: /\.scss$/,
          exclude: [helpers.root('src/main.browser.scss')],
          loader: 'css-to-string!css?sourceMap!sass?sourceMap'
        },
```
in component:
```
@Component({
  selector: 'home-highlight',
  template: require('./highlight.html'),
  styles: [
    require('./highlight.scss')
  ]
})
```

**Comment by tomgeorge** [comment]
Is there a way to configure the setup to allow use of the `stylesUrl` option in your components?  It looks like with the configured loaders for .ts files you can use `templateUrl: './template.html'` now instead of doing `require('./template.html')`.  I also see in `home.component.ts` they use `stylesUrl`, but that's just for css files.

**Comment by erlopezh** [comment]
My webpack.common.js
`{
test: /\.scss$/,
exclude: /node_modules/,
loaders: ['raw-loader', 'sass-loader'] // sass-loader not scss-loader
        },`

and my component has

`@Component({
  templateUrl: 'suite.html',
  styleUrls: ['suite.scss']
})`

Hope this help.

**Comment by itslikegood** [comment]
@erlopezh your configuration worked for me (had the same problem as @baonguyenyam).  The result is that webpack now places the expected style rules (output from my less compiler) in a style tag in the head element of my document.
