### ISSUE TITLE
component vs module approach question

### ISSUE THREAD

**Issue by sdemurjian** [AngularClass/angular2-webpack-starter#1022]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [x ] question about the decisions made in the repository

The readme states "We use the component approach in our starter. This is the new standard for developing Angular apps and a great way to ensure maintainable code by encapsulation of our behavior logic."

However, RC6 removed @Component.directives (deprecated in a previous RC) which indicates to me that the angular team is supporting a module pattern. it doesn't really make sense to add a bunch of declarations in your `app.module.ts` that won't be used by the entire app, but only by specific components. this might be a weak example, but `home` uses the `x-large` directive but `about` may never need to have the ability to use that directive.

Does this make sense or am I misunderstanding the Angular team's intentions?

**Comment by eddedd88** [comment]
I think the README means as the overall architecture of a web app as explained here: http://developer.telerik.com/featured/front-end-application-frameworks-component-architectures/, instead of using NgModule to bundle parts of your application

**Comment by sdemurjian** [comment]
Well, regardless of what the README refers to, my question is about switching to a pattern that uses NgModule more heavily.

Instead of having app module declare home component and x-large directive, using a module pattern there would be an app module and a home module. The home module would have declarations for the home component and x-large directive.

**Comment by tenbits** [comment]
Hey @water42, have you find anywhere the explination as why a sub component should be registered via root or nearest module.  Absolutelly don't understand this decision.  Everything in the architecture is about the encapsulation, but suddenly if some functionallity of a component should be encapsulated by a child component, the subcomponent "leaks" up to the module where it now should be registered.
