### ISSUE TITLE
npm start give error after fresh installation on window

### ISSUE THREAD

**Issue by arifhussain353** [AngularClass/angular2-webpack-starter#1023]
Hi,
I just download and followed every step given on `AngularClass ` website and here also .I did install latest `npm` and `node`.After completing by procedure of installation i try to run this app by `npm start` but every time it give me this error.I search it in other issue open here but didn't find any solution so i decided to open and issue related this problem and sorry if anyother issue related this problem already open by other.Thank you.

D:\xampp\xampp\htdocs\angular2>npm start

> angular2-webpack-starter@5.0.5 start D:\xampp\xampp\htdocs\angular2
> npm run server:dev

> angular2-webpack-starter@5.0.5 server:dev D:\xampp\xampp\htdocs\angular2
> webpack-dev-server --config config/webpack.dev.js --progress --profile --watch --content-base src/

D:\xampp\xampp\htdocs\angular2\node_modules\webpack\lib\webpack.js:16
                throw new WebpackOptionsValidationError(webpackOptionsValidationErrors);
        ^
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'tslint'. These properties are valid:
   object { amd?, bail?, cache?, context?, devServer?, devtool?, entry, externals?, loader?, module?, name?, dependencies?, node?, output?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, res
olve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
 - configuration.module has an unknown property 'postLoaders'. These properties are valid:
   object { rules?, loaders?, noParse?, unknownContextRequest?, unknownContextRegExp?, unknownContextRecursive?, unknownContextCritical?, exprContextRequest?, exprContextRegExp?, exprContextRecursive?, exprContextCri
tical?, wrappedContextRegExp?, wrappedContextRecursive?, wrappedContextCritical? }
   Options affecting the normal modules (`NormalModuleFactory`).
 - configuration.node.global should be a boolean.
 - configuration.resolve has an unknown property 'modulesDirectories'. These properties are valid:
   object { modules?, descriptionFiles?, plugins?, mainFields?, aliasFields?, mainFiles?, extensions?, enforceExtension?, moduleExtensions?, enforceModuleExtension?, alias?, symlinks?, unsafeCache?, cachePredicate?,
fileSystem?, resolver? }
 - configuration.resolve.extensions[0] should not be empty.
    at webpack (D:\xampp\xampp\htdocs\angular2\node_modules\webpack\lib\webpack.js:16:9)
    at processOptions (D:\xampp\xampp\htdocs\angular2\node_modules\webpack-dev-server\bin\webpack-dev-server.js:263:13)
    at Object.<anonymous> (D:\xampp\xampp\htdocs\angular2\node_modules\webpack-dev-server\bin\webpack-dev-server.js:283:1)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "server:dev"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! angular2-webpack-starter@5.0.5 server:dev: `webpack-dev-server --config config/webpack.dev.js --progress --profile --watch --content-base src/`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-webpack-starter@5.0.5 server:dev script 'webpack-dev-server --config config/webpack.dev.js --progress --profile --watch --content-base src/'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-webpack-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --config config/webpack.dev.js --progress --profile --watch --content-base src/
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-webpack-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-webpack-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\xampp\xampp\htdocs\angular2\npm-debug.log

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! angular2-webpack-starter@5.0.5 start: `npm run server:dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-webpack-starter@5.0.5 start script 'npm run server:dev'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-webpack-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run server:dev
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-webpack-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-webpack-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\xampp\xampp\htdocs\angular2\npm-debug.log

**Comment by jwuliger** [comment]
I am getting this error also. Fresh git clone and the same problem. I think it has to do with the change in the latest Webpack 2.1 beta. It seems that Master is using beta.21, which should be fine. Beta 23 has the breaking changes. I am going to try Beta 22 as that has fixed some issues for me with some other apps.

**Comment by jwuliger** [comment]
@arifhussain353 I fixed the problem by removing my node_modules install, then changing the Webpack dependencies in package.json to:

`"webpack": "2.1.0-beta.22",`
`"webpack-dev-middleware": "^1.8.1",`
`"webpack-dev-server": "2.1.0-beta.4",`

Then `npm start` and everything works.

**Comment by arifhussain353** [comment]
@jwuliger  Hi, Thank you very much it solved my problem :) :+1:
