### ISSUE TITLE
How do you use multiple @NgModules with this seed?

### ISSUE THREAD

**Issue by jwuliger** [AngularClass/angular2-webpack-starter#1026]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)
- **I'm submitting a ...**
  [X ] bug report
  [ ] feature request
  [X ] question about the decisions made in the repository
- **Do you want to request a _feature_ or report a _bug_?**

Hello - I am not sure is this is a bug or not. I am new to Webpack HMR.
- **What is the current behavior?**

I am trying to add a Core module to the seed repo and import it into the main App Root Module. However I get an error when loading the app at `bootloader( main );` in `main.browser.ts` I know this must be related to HMR.
- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
  https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

I am following the Angular Style Guide and an app that John Papa has as an example of using a core module. The repo is here:

[https://github.com/johnpapa/event-view/tree/master/src/app/core](url)
- **What is the expected behavior?**

I was hoping for some direction on how to load more then one NgModule into the app.
- **What is the motivation / use case for changing the behavior?**

To separate my app out by feature, and only load components for modules that need them. 
- **Please tell us about your environment:**
- Angular version: 2.0.0 Final
- Browser: [ all ]
- Node: 6.6.0
- NPM: 3.10.8
- Windows 10
- **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Thank-you for any help!

**Comment by d3viant0ne** [comment]
I run a core, shared & multiple feature modules without issue. This is not a bug nor does it have anything to do with the starter.

https://angular.io/docs/ts/latest/guide/ngmodule.html has everything you need to implement what it is you want.
