### ISSUE TITLE
Is the default page a page without any CSS style ?

### ISSUE THREAD

**Issue by SonlyF5020** [AngularClass/angular2-webpack-starter#1028]
The home page in my local shows quite ugly without any styles inside, is this the expected one or there is something wrong with my local environment ?

Screenshot as below 
![2016-09-21 3 54 20](https://cloud.githubusercontent.com/assets/3728533/18699287/b45ba27c-8013-11e6-996e-64ef79d617d5.png)

**Comment by bartholomej** [comment]
That's correct. Starter kits are usually provided as minimal versions (without any useless styles and functions).
If you need version with shiny styles you can always use `material2` branch.
