### ISSUE TITLE
npm install fails on ubuntu 16.04.01

### ISSUE THREAD

**Issue by willypuzzle** [AngularClass/angular2-webpack-starter#1029]
When I do "npm install" on a fresh installation of angular2-webpack-starter on my ubuntu machine installation I receive this message:

> \> execSync@1.0.2 install /var/www/angular2-webpack-starter/node_modules/execSync
> \> node install.js
> 
> [execsync v1.0.2] Attempting to compile native extensions.
> [execSync v1.0.2]
>     Native code compile failed!!
> 

So if I do "npm run build:dev" it fails too.

I use node v6.6.0

NOTE:
I have found that [execSync](https://github.com/mgutz/execSync) is not maintained anymore and that nodejs has its own version of that command. I think it could be removed from dependencies.

**Comment by b4nt0** [comment]
If you have installed node from ubuntu package, it's executable is called "nodejs" instead of "node". Please do "sudo ln -s /usr/bin/nodejs /usr/bin/node", then kill node_modules and npm install again.

**Comment by katallaxie** [comment]
I highly recommend to use https://github.com/creationix/nvm and use an `.nvmrc`.

**Comment by willypuzzle** [comment]
I use node v6.6.0 so I had to install an appropriate ppa. However "npm run build:dev" failed for other reasons. I managed them and not it works. But execSync is however a broken dependence.

**Comment by katallaxie** [comment]
@willypuzzle 🍒
