### ISSUE TITLE
webpack run bug

### ISSUE THREAD

**Issue by charlieschen** [AngularClass/angular2-webpack-starter#1030]
[v ] bug report

I used node v6.6.0

npm start error:
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'tslint'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, loader?, module?, name?, node?, output?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
   For typos: please correct them.
   For loader options: webpack 2 no longer allows custom properties in configuration.
     Loaders should be updated to allow passing options via loader options in module.rules.
     Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the loader:
     plugins: {
       new webpack.LoaderOptionsPlugin({
         options: {
           tslint: ...
         }
       })
     }
 - configuration.module.rules[0].enforce should be one of these:
   "pre" | "post"
 - configuration.node['crypto'] should be one of these:
   false | true | "mock"
 - configuration.node.global should be a boolean.
 - configuration.resolve has an unknown property 'modulesDirectories'. These properties are valid:
   object { alias?, aliasFields?, cachePredicate?, descriptionFiles?, enforceExtension?, enforceModuleExtension?, extensions?, fileSystem?, mainFields?, mainFiles?, moduleExtensions?, modules?, plugins?, resolver?, symlinks?, unsafeCache? }
    at webpack (/Workspace/YongLin/VVIP/ng2-vvip/node_modules/webpack/lib/webpack.js:16:9)
    at processOptions (/Workspace/YongLin/VVIP/ng2-vvip/node_modules/webpack-dev-server/bin/webpack-dev-server.js:263:13)
    at Object.<anonymous> (/Workspace/YongLin/VVIP/ng2-vvip/node_modules/webpack-dev-server/bin/webpack-dev-server.js:283:1)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by 799956381** [comment]
@charlieschen 
I am encountering the same issue with npm start

**Comment by willypuzzle** [comment]
Me too but with npm run build:dev:

> Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
>  - configuration has an unknown property 'tslint'. These properties are valid:
>    object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, loader?, module?, name?, node?, output?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
>    For typos: please correct them.
>    For loader options: webpack 2 no longer allows custom properties in configuration.
>      Loaders should be updated to allow passing options via loader options in module.rules.
>      Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the loader:
>      plugins: {
>        new webpack.LoaderOptionsPlugin({
>          options: {
>            tslint: ...
>          }
>        })
>      }
>  - configuration.module has an unknown property 'postLoaders'. These properties are valid:
>    object { exprContextCritical?, exprContextRecursive?, exprContextRegExp?, exprContextRequest?, loaders?, noParse?, rules?, unknownContextCritical?, unknownContextRecursive?, unknownContextRegExp?, unknownContextRequest?, wrappedContextCritical?, wrappedContextRecursive?, wrappedContextRegExp? }
>    Options affecting the normal modules (`NormalModuleFactory`).
>  - configuration.node['crypto'] should be one of these:
>    false | true | "mock"
>  - configuration.node.global should be a boolean.
>  - configuration.resolve has an unknown property 'modulesDirectories'. These properties are valid:
>    object { alias?, aliasFields?, cachePredicate?, descriptionFiles?, enforceExtension?, enforceModuleExtension?, extensions?, fileSystem?, mainFields?, mainFiles?, moduleExtensions?, modules?, plugins?, resolver?, symlinks?, unsafeCache? }
>  - configuration.resolve.extensions[0] should not be empty.

**Comment by Anufriev** [comment]
https://github.com/AngularClass/angular2-webpack-starter/pull/1018#issuecomment-248544686
