### ISSUE TITLE
webpack npm run start

### ISSUE THREAD

**Issue by cheater001** [AngularClass/angular2-webpack-starter#1031]
[ ] bug report

[default] /Users/alexandermidtsev/Projects/stucco/goodwatch-website-mobile-front/node_modules/@types/protractor/index.d.ts:22:27 
    Module 'webdriver' has no exported member 'IButton'.
[default] /Users/alexandermidtsev/Projects/stucco/goodwatch-website-mobile-front/node_modules/@types/protractor/index.d.ts:25:24 
    Module 'webdriver' has no exported member 'IKey'.
[default] /Users/alexandermidtsev/Projects/stucco/goodwatch-website-mobile-front/node_modules/@types/protractor/index.d.ts:28:45 
    Property 'Error' does not exist on type 'typeof error'.
[default] /Users/alexandermidtsev/Projects/stucco/goodwatch-website-mobile-front/node_modules/@types/protractor/index.d.ts:29:40 
    Module 'webdriver.error' has no exported member 'IErrorCode'.
[default] /Users/alexandermidtsev/Projects/stucco/goodwatch-website-mobile-front/node_modules/@types/protractor/index.d.ts:36:37 
    Module 'webdriver.logging' has no exported member 'IType'.
[default] /Users/alexandermidtsev/Projects/stucco/goodwatch-website-mobile-front/node_modules/@types/protractor/index.d.ts:37:38 
    Module 'webdriver.logging' has no exported member 'ILevelValues'.
[default] /Users/alexandermidtsev/Projects/stucco/goodwatch-website-mobile-front/node_modules/@types/protractor/index.d.ts:39:67 
    Module 'webdriver.logging' has no exported member 'ILevel'.
[default] /Users/alexandermidtsev/Projects/stucco/goodwatch-website-mobile-front/node_modules/@types/protractor/index.d.ts:40:67 
    Module 'webdriver.logging' has no exported member 'ILevel'.
[default] /Users/alexandermidtsev/Projects/stucco/goodwatch-website-mobile-front/node_modules/@types/protractor/index.d.ts:287:39 
    Property 'stacktrace' does not exist on type 'typeof webdriver'.
[default] /Users/alexandermidtsev/Projects/stucco/goodwatch-website-mobile-front/node_modules/@types/protractor/index.d.ts:288:42 
    Property 'stacktrace' does not exist on type 'typeof webdriver'.
[default] /Users/alexandermidtsev/Projects/stucco/goodwatch-website-mobile-front/node_modules/@types/protractor/index.d.ts:303:35 
    Module 'webdriver' has no exported member 'stacktrace'.
[default] /Users/alexandermidtsev/Projects/stucco/goodwatch-website-mobile-front/node_modules/@types/protractor/index.d.ts:340:55 
    Module 'webdriver' has no exported member 'Locator'.
[default] /Users/alexandermidtsev/Projects/stucco/goodwatch-website-mobile-front/node_modules/@types/protractor/index.d.ts:414:52 
    Module 'webdriver' has no exported member 'Locator'.
[default] /Users/alexandermidtsev/Projects/stucco/goodwatch-website-mobile-front/node_modules/@types/protractor/index.d.ts:462:53 
    Module 'webdriver' has no exported member 'Locator'.
[default] /Users/alexandermidtsev/Projects/stucco/goodwatch-website-mobile-front/node_modules/@types/protractor/index.d.ts:664:29 
    Module 'webdriver' has no exported member 'Locator'.
[default] /Users/alexandermidtsev/Projects/stucco/goodwatch-website-mobile-front/node_modules/@types/protractor/index.d.ts:673:32 
    Module 'webdriver' has no exported member 'Locator'.
[default] /Users/alexandermidtsev/Projects/stucco/goodwatch-website-mobile-front/node_modules/@types/protractor/index.d.ts:704:39 
    Module 'webdriver' has no exported member 'Locator'.
[default] /Users/alexandermidtsev/Projects/stucco/goodwatch-website-mobile-front/node_modules/@types/protractor/index.d.ts:725:35 
    Module 'webdriver' has no exported member 'Locator'.
[default] /Users/alexandermidtsev/Projects/stucco/goodwatch-website-mobile-front/node_modules/@types/protractor/index.d.ts:801:48 
    Module 'webdriver' has no exported member 'Locator'.
[default] /Users/alexandermidtsev/Projects/stucco/goodwatch-website-mobile-front/node_modules/@types/protractor/index.d.ts:808:30 
    Module 'webdriver' has no exported member 'Locator'.
[default] /Users/alexandermidtsev/Projects/stucco/goodwatch-website-mobile-front/node_modules/@types/protractor/index.d.ts:1111:32 
    Module 'webdriver' has no exported member 'Locator'.
[default] /Users/alexandermidtsev/Projects/stucco/goodwatch-website-mobile-front/node_modules/@types/protractor/index.d.ts:1139:30 
    Module 'webdriver' has no exported member 'Locator'.
[default] /Users/alexandermidtsev/Projects/stucco/goodwatch-website-mobile-front/node_modules/@types/protractor/index.d.ts:1362:51 
    Module 'webdriver' has no exported member 'Locator'.
[default] /Users/alexandermidtsev/Projects/stucco/goodwatch-website-mobile-front/node_modules/@types/protractor/index.d.ts:1363:42 
    Module 'webdriver' has no exported member 'Locator'.
[default] /Users/alexandermidtsev/Projects/stucco/goodwatch-website-mobile-front/node_modules/@types/protractor/index.d.ts:1364:41 
    Module 'webdriver' has no exported member 'Locator'.
[default] /Users/alexandermidtsev/Projects/stucco/goodwatch-website-mobile-front/node_modules/@types/protractor/index.d.ts:1440:55 
    Module 'webdriver' has no exported member 'Locator'.
[default] /Users/alexandermidtsev/Projects/stucco/goodwatch-website-mobile-front/node_modules/@types/protractor/index.d.ts:1461:60 
    Module 'webdriver' has no exported member 'Locator'.
[default] /Users/alexandermidtsev/Projects/stucco/goodwatch-website-mobile-front/node_modules/@types/protractor/index.d.ts:1477:41 
    Module 'webdriver' has no exported member 'Locator'.
[default] /Users/alexandermidtsev/Projects/stucco/goodwatch-website-mobile-front/node_modules/@types/protractor/index.d.ts:1491:51 
    Module 'webdriver' has no exported member 'Locator'.
[default] /Users/alexandermidtsev/Projects/stucco/goodwatch-website-mobile-front/node_modules/@types/protractor/index.d.ts:1505:58 
    Module 'webdriver' has no exported member 'Locator'.
[default] /Users/alexandermidtsev/Projects/stucco/goodwatch-website-mobile-front/node_modules/@types/protractor/index.d.ts:1574:79 
    Module 'webdriver' has no exported member 'Locator'.
[default] /Users/alexandermidtsev/Projects/stucco/goodwatch-website-mobile-front/node_modules/@types/protractor/index.d.ts:1594:55 
    Module 'webdriver' has no exported member 'Locator'.
[default] /Users/alexandermidtsev/Projects/stucco/goodwatch-website-mobile-front/node_modules/@types/protractor/index.d.ts:1614:36 
    Module 'webdriver' has no exported member 'Locator'.
[default] Checking finished with 33 errors

**Comment by fmoessle** [comment]
+1

**Comment by vivekwisdom** [comment]
This issue is coming on latest codebase. Very annoying related to the protractor @types.

**Comment by kislovskij** [comment]
fixing the version of @types/selenium-webdriver resolves the issue

`"@types/selenium-webdriver": "2.44.26"`

**Comment by mshahin364** [comment]
@kislovskij Thanks, solved my problem.

**Comment by alex88** [comment]
Same here with `"@types/selenium-webdriver": "2.53.33"`

**Comment by Reiss-Cashmore** [comment]
Putting "@types/selenium-webdriver": "2.44.29" in your package.json is the latest version that does not display the error

Note: Make sure that you do not have a Caret "^" before the version number as that will cause npm to install Version the latest matching minor version which is: "2.53.33".  As described above will cause this error to occur.

Just some advice for anyone that comes across this post as these were stumbling blocks I fell on.
