### ISSUE TITLE
npm start issue

### ISSUE THREAD

**Issue by Chiholiu** [AngularClass/angular2-webpack-starter#1034]
Issue with running npm start..

$ npm run server:dev

> angular2-webpack-starter@5.0.5 server:dev C:\Users\chiho\Desktop\angular-youtube\Angularjs
> webpack-dev-server --config config/webpack.dev.js --progress --profile --watch --content-base src/

'webpack-dev-server' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "run" "server:dev"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! angular2-webpack-starter@5.0.5 server:dev: `webpack-dev-server --config config/webpack.dev.js --progress --profile --watch --content-base src/`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-webpack-starter@5.0.5 server:dev script 'webpack-dev-server --config config/webpack.dev.js --progress --profile --watch --content-base src/'.
npm ERR! This is most likely a problem with the angular2-webpack-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --config config/webpack.dev.js --progress --profile --watch --content-base src/
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-webpack-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls angular2-webpack-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\user\Desktop\angular-youtube\Angularjs\npm-debug.log

**Comment by gaurav2887** [comment]
@Chiholiu - I have normally faced this issue if I have messed up something with my webpack configuration file. If you have changed anything in there, It will be good idea to compare against this see config files.

**Comment by Chiholiu** [comment]
I have just run this command, but NPM start still gives the same error

**Comment by gaurav2887** [comment]
@Chiholiu - If you take a look at your logs you have older version of node :

npm ERR! node v4.5.0
npm ERR! npm v2.15.9

where as you need node > 5 and npm > 3 for this project.

**Comment by indiecore-fm** [comment]
I hate to reopen this but I have the exact same issue, but I have node 6.9.4 and npm 3.10.10

**Comment by crypto777** [comment]
Are you following the quick start instructions? Because you can't run: 

`npm start` and `npm run server` at the same time, that wasn't very clear in the instructions and I had the same issue on Windows, try running only one of those commands and then ctrl + c and try the other one.

**Comment by SherlockStd** [comment]
Please give a log for us to help you more easily
