### ISSUE TITLE
npm run build:prod error

### ISSUE THREAD

**Issue by 799956381** [AngularClass/angular2-webpack-starter#1035]
Issues with build:prod

> 94% asset optimizationError in bail mode: [default] master\node_modules\@types\protractor\index.d.ts:22 odule 'webdriver' has no exported member 'IButton'.

21 error Windows_NT 6.1.7601
22 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build:prod"
23 error node v4.5.0
24 error npm  v3.10.7
25 error code ELIFECYCLE
26 error angular2-webpack-starter@5.0.5 build:prod: `webpack --config config/webpack.prod.js  --progress --profile --bail`
26 error Exit status 1
27 error Failed at the angular2-webpack-starter@5.0.5 build:prod script 'webpack --config config/webpack.prod.js  --progress --profile --bail'.
27 error Make sure you have the latest version of node.js and npm installed.
27 error If you do, this is most likely a problem with the angular2-webpack-starter package,
27 error not with npm itself.
27 error Tell the author that this fails on your system:
27 error     webpack --config config/webpack.prod.js  --progress --profile --bail
27 error You can get information on how to open an issue for this project with:
27 error     npm bugs angular2-webpack-starter
27 error Or if that isn't available, you can get their info via:
27 error     npm owner ls angular2-webpack-starter
27 error There is likely additional logging output above.
28 verbose exit [ 1, true ]

**Comment by smith64fx** [comment]
Got the same error :(

**Comment by smith64fx** [comment]
@799956381 I got a solution.

```
npm i --save @types/selenium-webdriver@2.44.29
```

The problem is the new version of @types/selenium-webdriver (

I found it out using:
```
npm view @types/selenium-webdriver
```

Gives me this
```
    '2.44.29': '2016-09-19T18:11:04.054Z',
     '2.53.30': '2016-09-20T21:16:15.928Z'
```


Just downgrade to 2.44.29 and everything works fine :-)
