### ISSUE TITLE
i got some error in "npm run server" command

### ISSUE THREAD

**Issue by rahullsinha** [AngularClass/angular2-webpack-starter#1043]
![image](https://cloud.githubusercontent.com/assets/20947986/18776826/869fb72a-8189-11e6-9f8e-88e588ed7b9f.png)
![image](https://cloud.githubusercontent.com/assets/20947986/18776835/95c7bbbc-8189-11e6-9997-c65b36b18c28.png)
![image](https://cloud.githubusercontent.com/assets/20947986/18776845/a3a93c6a-8189-11e6-9cc4-678b736dab4a.png

**Comment by alsoicode** [comment]
I get the same error

**Comment by alsoicode** [comment]
However, updating to the latest version of this repository has me going again.

**Comment by rahullsinha** [comment]
i got the solution . run these commands

npm uninstall webpack --save-dev 
npm install webpack@2.1.0-beta.21 --save-dev
npm uninstall "@types/selenium-webdriver" --save-dev
npm install "@types/selenium-webdriver@2.44.26" --save-dev

**Comment by alsoicode** [comment]
Updating to the latest config(s) from the repo have me working again.
