### ISSUE TITLE
run build:prod error, Duplicate identifier 'sourceMap'.

### ISSUE THREAD

**Issue by 799956381** [AngularClass/angular2-webpack-starter#1048]
Issues with build:prod
node: v6.6.0
npm:  v3.10.7
webpack: 2.1.0-beta.22
@types/selenium-webdriver: 2.44.29

>  94% asset optimizationError in bail mode: [default] F:\Github\angular2-webpack-starter\node_modules.0.1.27@@types\source-map\index.d.ts:7:20 
>  Duplicate identifier 'sourceMap'.

21 error Windows_NT 6.1.7601
22 error argv "C:\Program Files\nodejs\node.exe" "C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "run" "build:prod"
23 error node v6.6.0
24 error npm  v3.10.7
25 error code ELIFECYCLE
26 error angular2-webpack-starter@5.0.5 build:prod: `webpack --config config/webpack.prod.js  --progress --profile --bail`
26 error Exit status 1
27 error Failed at the angular2-webpack-starter@5.0.5 build:prod script 'webpack --config config/webpack.prod.js  --progress --profile --bail'.
27 error Make sure you have the latest version of node.js and npm installed.
27 error If you do, this is most likely a problem with the angular2-webpack-starter package,
27 error not with npm itself.
27 error Tell the author that this fails on your system:
27 error     webpack --config config/webpack.prod.js  --progress --profile --bail
27 error You can get information on how to open an issue for this project with:
27 error     npm bugs angular2-webpack-starter
27 error Or if that isn't available, you can get their info via:
27 error     npm owner ls angular2-webpack-starter
27 error There is likely additional logging output above.
28 verbose exit [ 1, true ]

**Comment by raghavan85** [comment]
Pin it to 2.44.26 to make it work.

**Comment by ECHOyougf** [comment]
package.json
` "@types/selenium-webdriver": "2.44.26",`

node_modules\@types\source-map\index.d.ts
`//export as namespace sourceMap;`

**Comment by shoudaos** [comment]
Hi, can you tell how to fix this error, when it fails only on remote, when **cap staging deploy** is running.
in my local build:prod runs successfull, 

but on server it throws this errors:
ERROR in [default] /opt/bitnami/apps/nameProject/htdocs/releases/20160929125423/node_modules/@types/source-map/index.d.ts:7:20 
Duplicate identifier 'sourceMap'.

ERROR in [default] /opt/bitnami/apps/nameProject/htdocs/shared/node_modules/@types/source-map/index.d.ts:7:20 
Duplicate identifier 'sourceMap'.

**Comment by sustwater** [comment]
I've had the same issue.
Did you solve the issue?

**Comment by d3viant0ne** [comment]
Duplicate identifiers are exactly that, two libs both have the same types. Remove one or open an issue with the maintainers of the types in question.

i.e. Protractor & @types/selenium-webdriver will do this because protractor is now shipping with the same set of types.
