### ISSUE TITLE
Please update to minimatch 3.0.2   or higher to avoid a RegExp DoS issue

### ISSUE THREAD

**Issue by Chiholiu** [AngularClass/angular2-webpack-starter#1051]
Could you please update minimatch to 3.0.2 or higher to avoid a RegExp DoS issue

**Comment by Chiholiu** [comment]
Could you please update minimatch to 3.0.2  or higher to avoid a RegExp DoS issue

**Comment by d3viant0ne** [comment]
This is an issue with a dependency of a dependency and something that should be taken up with the maintainers of that package.
