### ISSUE TITLE
Add sonar for typescript

### ISSUE THREAD

**Issue by deacix** [AngularClass/angular2-webpack-starter#1053]
Hello every body! What about to add sonar:

https://github.com/Pablissimo/SonarTsPlugin

for typescript?

**Comment by d3viant0ne** [comment]
Not something that belongs in the starter as it's niche and many other options are available providing similar functionality.

That said, a wiki page on `how` to integrate https://github.com/Pablissimo/SonarTsPlugin into the starter would absolutely be welcome.
