### ISSUE TITLE
download zip, extract and run npm install installs angular rc6

### ISSUE THREAD

**Issue by aavelyn** [AngularClass/angular2-webpack-starter#1057]
- **I'm submitting a ...**
  [x ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
- **Do you want to request a _feature_ or report a _bug_?**

Bug
- **What is the current behavior?**

I use download zip, extract and run npm install, which installs angular rc6.

**Comment by DanielMcAssey** [comment]
Whats the contents of the package.json file?

**Comment by aavelyn** [comment]
{
  "name": "angular2-webpack-starter",
  "version": "5.0.5",
  "description": "An Angular 2 Webpack Starter kit featuring Angular 2 (Router, Http, Forms, Services, Tests, E2E, Coverage), Karma, Protractor, Jasmine, Istanbul, TypeScript, and Webpack by AngularClass",
  "keywords": [
    "angular2",
    "webpack",
    "typescript"
  ],
  "author": "Patrick Stapleton <patrick@angularclass.com>",
  "homepage": "https://github.com/angularclass/angular2-webpack-starter",
  "license": "MIT",
  "scripts": {
    "build:dev": "webpack --config config/webpack.dev.js --progress --profile",
    "build:docker": "npm run build:prod && docker build -t angular2-webpack-start:latest .",
    "build:prod": "webpack --config config/webpack.prod.js  --progress --profile --bail",
    "build": "npm run build:dev",
    "ci": "npm run lint && npm test && npm run e2e",
    "clean:dist": "npm run rimraf -- dist",
    "clean:install": "npm set progress=false && npm install",
    "clean:start": "npm start",
    "clean": "npm cache clean && npm run rimraf -- node_modules doc coverage dist",
    "docker": "docker",
    "docs": "npm run typedoc -- --options typedoc.json --exclude '**/*.spec.ts' ./src/",
    "e2e:live": "npm run e2e -- --elementExplorer",
    "e2e": "npm run protractor",
    "github-deploy:dev": "webpack --config config/webpack.github-deploy.js --progress --profile --github-dev",
    "github-deploy:prod": "webpack --config config/webpack.github-deploy.js --progress --profile --github-prod",
    "github-deploy": "npm run github-deploy:dev",
    "lint": "npm run tslint \"src/**/*.ts\"",
    "postversion": "git push && git push --tags",
    "prebuild:dev": "npm run clean:dist",
    "prebuild:prod": "npm run clean:dist",
    "preclean:install": "npm run clean",
    "preclean:start": "npm run clean",
    "pree2e": "npm run webdriver:update -- --standalone",
    "preversion": "npm test",
    "protractor": "protractor",
    "rimraf": "rimraf",
    "server:dev:hmr": "npm run server:dev -- --inline --hot",
    "server:dev": "webpack-dev-server --config config/webpack.dev.js --progress --profile --watch --content-base src/",
    "server:prod": "http-server dist --cors",
    "server": "npm run server:dev",
    "start:hmr": "npm run server:dev:hmr",
    "start": "npm run server:dev",
    "test": "karma start",
    "tslint": "tslint",
    "typedoc": "typedoc",
    "version": "npm run build",
    "watch:dev:hmr": "npm run watch:dev -- --hot",
    "watch:dev": "npm run build:dev -- --watch",
    "watch:prod": "npm run build:prod -- --watch",
    "watch:test": "npm run test -- --auto-watch --no-single-run",
    "watch": "npm run watch:dev",
    "webdriver-manager": "webdriver-manager",
    "webdriver:start": "npm run webdriver-manager start",
    "webdriver:update": "npm run webdriver-manager update",
    "webpack-dev-server": "webpack-dev-server",
    "webpack": "webpack"
  },
  "dependencies": {
    "@angular/common": "2.0.0",
    "@angular/compiler": "2.0.0",
    "@angular/core": "2.0.0",
    "@angular/forms": "^2.0.0",
    "@angular/http": "2.0.0",
    "@angular/platform-browser": "2.0.0",
    "@angular/platform-browser-dynamic": "2.0.0",
    "@angular/platform-server": "2.0.0",
    "@angular/router": "3.0.0",
    "@angularclass/conventions-loader": "^1.0.2",
    "@angularclass/hmr": "~1.2.0",
    "@angularclass/hmr-loader": "~3.0.2",
    "@angularclass/request-idle-callback": "^1.0.7",
    "@angularclass/webpack-toolkit": "^1.3.3",
    "assets-webpack-plugin": "^3.4.0",
    "core-js": "^2.4.1",
    "http-server": "^0.9.0",
    "ie-shim": "^0.1.0",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "~0.6.17"
  },
  "devDependencies": {
    "@types/hammerjs": "^2.0.33",
    "@types/jasmine": "^2.2.34",
    "@types/node": "^6.0.38",
    "@types/protractor": "^1.5.20",
    "@types/selenium-webdriver": "2.44.29",
    "@types/source-map": "^0.1.27",
    "@types/uglify-js": "^2.0.27",
    "@types/webpack": "^1.12.34",
    "angular2-template-loader": "^0.5.0",
    "awesome-typescript-loader": "^2.2.1",
    "codelyzer": "~0.0.28",
    "copy-webpack-plugin": "^3.0.1",
    "css-loader": "^0.25.0",
    "exports-loader": "^0.6.3",
    "expose-loader": "^0.7.1",
    "file-loader": "^0.9.0",
    "gh-pages": "^0.11.0",
    "html-webpack-plugin": "^2.21.0",
    "imports-loader": "^0.6.5",
    "istanbul-instrumenter-loader": "^0.2.0",
    "json-loader": "^0.5.4",
    "karma": "^1.2.0",
    "karma-chrome-launcher": "^2.0.0 ",
    "karma-coverage": "^1.1.1",
    "karma-jasmine": "^1.0.2",
    "karma-mocha-reporter": "^2.0.0",
    "karma-phantomjs-launcher": "^1.0.2",
    "karma-remap-coverage": "^0.1.1",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-webpack": "1.8.0",
    "parse5": "^1.3.2",
    "phantomjs": "^2.1.7",
    "protractor": "^3.2.2",
    "raw-loader": "0.5.1",
    "rimraf": "^2.5.2",
    "source-map-loader": "^0.1.5",
    "string-replace-loader": "1.0.5",
    "style-loader": "^0.13.1",
    "to-string-loader": "^1.1.4",
    "ts-helpers": "1.1.1",
    "ts-node": "^1.3.0",
    "tslint": "3.15.1",
    "tslint-loader": "^2.1.3",
    "typedoc": "^0.4.5",
    "typescript": "2.0.3",
    "url-loader": "^0.5.7",
    "webpack": "2.1.0-beta.22",
    "webpack-dev-middleware": "^1.6.1",
    "webpack-dev-server": "^2.1.0-beta.2",
    "webpack-md5-hash": "^0.0.5",
    "webpack-merge": "^0.14.1"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/angularclass/angular2-webpack-starter.git"
  },
  "bugs": {
    "url": "https://github.com/angularclass/angular2-webpack-starter/issues"
  },
  "engines": {
    "node": ">= 4.2.1",
    "npm": ">= 3"
  }
}

**Comment by andrewdacenko** [comment]
@aavelyn , @DanielMcAssey take a look at `npm-shrinkwrap.json` - rc6 is in there.

```
{
  "name": "angular2-webpack-starter",
  "version": "5.0.5",
  "dependencies": {
    "@angular/common": {
      "version": "2.0.0-rc.6",
      "from": "@angular/common@2.0.0-rc.6",
      "resolved": "https://registry.npmjs.org/@angular/common/-/common-2.0.0-rc.6.tgz"
    },
    "@angular/compiler": {
      "version": "2.0.0-rc.6",
      "from": "@angular/compiler@2.0.0-rc.6",
      "resolved": "https://registry.npmjs.org/@angular/compiler/-/compiler-2.0.0-rc.6.tgz"
    },
    "@angular/core": {
      "version": "2.0.0-rc.6",
      "from": "@angular/core@2.0.0-rc.6",
      "resolved": "https://registry.npmjs.org/@angular/core/-/core-2.0.0-rc.6.tgz"
    },
    "@angular/forms": {
      "version": "2.0.0-rc.6",
      "from": "@angular/forms@>=2.0.0-rc.6 <3.0.0",
      "resolved": "https://registry.npmjs.org/@angular/forms/-/forms-2.0.0-rc.6.tgz"
    },
    "@angular/http": {
      "version": "2.0.0-rc.6",
      "from": "@angular/http@2.0.0-rc.6",
      "resolved": "https://registry.npmjs.org/@angular/http/-/http-2.0.0-rc.6.tgz"
    },
    "@angular/platform-browser": {
      "version": "2.0.0-rc.6",
      "from": "@angular/platform-browser@2.0.0-rc.6",
      "resolved": "https://registry.npmjs.org/@angular/platform-browser/-/platform-browser-2.0.0-rc.6.tgz"
    },
    "@angular/platform-browser-dynamic": {
      "version": "2.0.0-rc.6",
      "from": "@angular/platform-browser-dynamic@2.0.0-rc.6",
      "resolved": "https://registry.npmjs.org/@angular/platform-browser-dynamic/-/platform-browser-dynamic-2.0.0-rc.6.tgz"
    },
    "@angular/platform-server": {
      "version": "2.0.0-rc.6",
      "from": "@angular/platform-server@2.0.0-rc.6",
      "resolved": "https://registry.npmjs.org/@angular/platform-server/-/platform-server-2.0.0-rc.6.tgz"
    },
    "@angular/router": {
      "version": "3.0.0-rc.2",
      "from": "@angular/router@3.0.0-rc.2",
      "resolved": "https://registry.npmjs.org/@angular/router/-/router-3.0.0-rc.2.tgz"
    },
    "@angularclass/conventions-loader": {
      "version": "1.0.12",
      "from": "@angularclass/conventions-loader@>=1.0.2 <2.0.0",
      "resolved": "https://registry.npmjs.org/@angularclass/conventions-loader/-/conventions-loader-1.0.12.tgz"
    },
    "@angularclass/request-idle-callback": {
      "version": "1.0.7",
      "from": "@angularclass/request-idle-callback@>=1.0.7 <2.0.0",
      "resolved": "https://registry.npmjs.org/@angularclass/request-idle-callback/-/request-idle-callback-1.0.7.tgz"
    },
    "@angularclass/webpack-toolkit": {
      "version": "1.3.3",
      "from": "@angularclass/webpack-toolkit@>=1.3.3 <2.0.0",
      "resolved": "https://registry.npmjs.org/@angularclass/webpack-toolkit/-/webpack-toolkit-1.3.3.tgz"
    },
    "async": {
      "version": "0.9.0",
      "from": "async@0.9.0",
      "resolved": "https://registry.npmjs.org/async/-/async-0.9.0.tgz"
    },
    "big.js": {
      "version": "3.1.3",
      "from": "big.js@>=3.1.3 <4.0.0",
      "resolved": "https://registry.npmjs.org/big.js/-/big.js-3.1.3.tgz"
    },
    "colors": {
      "version": "1.0.3",
      "from": "colors@1.0.3",
      "resolved": "https://registry.npmjs.org/colors/-/colors-1.0.3.tgz"
    },
    "core-js": {
      "version": "2.4.1",
      "from": "core-js@>=2.4.1 <3.0.0",
      "resolved": "https://registry.npmjs.org/core-js/-/core-js-2.4.1.tgz"
    },
    "corser": {
      "version": "2.0.1",
      "from": "corser@>=2.0.0 <2.1.0",
      "resolved": "https://registry.npmjs.org/corser/-/corser-2.0.1.tgz"
    },
    "ecstatic": {
      "version": "1.4.1",
      "from": "ecstatic@>=1.4.0 <2.0.0",
      "resolved": "https://registry.npmjs.org/ecstatic/-/ecstatic-1.4.1.tgz"
    },
    "emojis-list": {
      "version": "2.0.1",
      "from": "emojis-list@>=2.0.0 <3.0.0",
      "resolved": "https://registry.npmjs.org/emojis-list/-/emojis-list-2.0.1.tgz"
    },
    "eventemitter3": {
      "version": "1.2.0",
      "from": "eventemitter3@>=1.0.0 <2.0.0",
      "resolved": "https://registry.npmjs.org/eventemitter3/-/eventemitter3-1.2.0.tgz"
    },
    "he": {
      "version": "0.5.0",
      "from": "he@>=0.5.0 <0.6.0",
      "resolved": "https://registry.npmjs.org/he/-/he-0.5.0.tgz"
    },
    "http-proxy": {
      "version": "1.14.0",
      "from": "http-proxy@>=1.8.1 <2.0.0",
      "resolved": "https://registry.npmjs.org/http-proxy/-/http-proxy-1.14.0.tgz"
    },
    "http-server": {
      "version": "0.9.0",
      "from": "http-server@>=0.9.0 <0.10.0",
      "resolved": "https://registry.npmjs.org/http-server/-/http-server-0.9.0.tgz"
    },
    "ie-shim": {
      "version": "0.1.0",
      "from": "ie-shim@>=0.1.0 <0.2.0",
      "resolved": "https://registry.npmjs.org/ie-shim/-/ie-shim-0.1.0.tgz"
    },
    "json5": {
      "version": "0.5.0",
      "from": "json5@>=0.5.0 <0.6.0",
      "resolved": "https://registry.npmjs.org/json5/-/json5-0.5.0.tgz"
    },
    "loader-utils": {
      "version": "0.2.15",
      "from": "loader-utils@>=0.2.15 <0.3.0",
      "resolved": "https://registry.npmjs.org/loader-utils/-/loader-utils-0.2.15.tgz"
    },
    "mime": {
      "version": "1.3.4",
      "from": "mime@>=1.2.11 <2.0.0",
      "resolved": "https://registry.npmjs.org/mime/-/mime-1.3.4.tgz"
    },
    "minimist": {
      "version": "1.2.0",
      "from": "minimist@>=1.1.0 <2.0.0",
      "resolved": "https://registry.npmjs.org/minimist/-/minimist-1.2.0.tgz"
    },
    "mkdirp": {
      "version": "0.5.1",
      "from": "mkdirp@>=0.5.0 <0.6.0",
      "resolved": "https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.1.tgz",
      "dependencies": {
        "minimist": {
          "version": "0.0.8",
          "from": "minimist@0.0.8",
          "resolved": "https://registry.npmjs.org/minimist/-/minimist-0.0.8.tgz"
        }
      }
    },
    "object-assign": {
      "version": "4.1.0",
      "from": "object-assign@>=4.0.1 <5.0.0",
      "resolved": "https://registry.npmjs.org/object-assign/-/object-assign-4.1.0.tgz"
    },
    "opener": {
      "version": "1.4.1",
      "from": "opener@>=1.4.0 <1.5.0",
      "resolved": "https://registry.npmjs.org/opener/-/opener-1.4.1.tgz"
    },
    "optimist": {
      "version": "0.6.1",
      "from": "optimist@>=0.6.0 <0.7.0",
      "resolved": "https://registry.npmjs.org/optimist/-/optimist-0.6.1.tgz",
      "dependencies": {
        "minimist": {
          "version": "0.0.10",
          "from": "minimist@>=0.0.1 <0.1.0",
          "resolved": "https://registry.npmjs.org/minimist/-/minimist-0.0.10.tgz"
        }
      }
    },
    "parse5": {
      "version": "1.3.2",
      "from": "parse5@1.3.2",
      "resolved": "https://registry.npmjs.org/parse5/-/parse5-1.3.2.tgz"
    },
    "portfinder": {
      "version": "0.4.0",
      "from": "portfinder@>=0.4.0 <0.5.0",
      "resolved": "https://registry.npmjs.org/portfinder/-/portfinder-0.4.0.tgz"
    },
    "qs": {
      "version": "2.3.3",
      "from": "qs@>=2.3.3 <2.4.0",
      "resolved": "https://registry.npmjs.org/qs/-/qs-2.3.3.tgz"
    },
    "requires-port": {
      "version": "1.0.0",
      "from": "requires-port@>=1.0.0 <2.0.0",
      "resolved": "https://registry.npmjs.org/requires-port/-/requires-port-1.0.0.tgz"
    },
    "rxjs": {
      "version": "5.0.0-beta.11",
      "from": "rxjs@5.0.0-beta.11",
      "resolved": "https://registry.npmjs.org/rxjs/-/rxjs-5.0.0-beta.11.tgz"
    },
    "symbol-observable": {
      "version": "1.0.2",
      "from": "symbol-observable@>=1.0.1 <2.0.0",
      "resolved": "https://registry.npmjs.org/symbol-observable/-/symbol-observable-1.0.2.tgz"
    },
    "union": {
      "version": "0.4.4",
      "from": "union@>=0.4.3 <0.5.0",
      "resolved": "https://registry.npmjs.org/union/-/union-0.4.4.tgz"
    },
    "url-join": {
      "version": "1.1.0",
      "from": "url-join@>=1.0.0 <2.0.0",
      "resolved": "https://registry.npmjs.org/url-join/-/url-join-1.1.0.tgz"
    },
    "wordwrap": {
      "version": "0.0.3",
      "from": "wordwrap@>=0.0.2 <0.1.0",
      "resolved": "https://registry.npmjs.org/wordwrap/-/wordwrap-0.0.3.tgz"
    },
    "zone.js": {
      "version": "0.6.17",
      "from": "zone.js@>=0.6.17 <0.7.0",
      "resolved": "https://registry.npmjs.org/zone.js/-/zone.js-0.6.17.tgz"
    }
  }
}
```

**Comment by katallaxie** [comment]
😴

**Comment by d3viant0ne** [comment]
Shrinkwrap has been removed from the repo as it causes more confusion than it's worth. Resolving
