### ISSUE TITLE
dojo and arcgis javascript api

### ISSUE THREAD

**Issue by hassanqaiser** [AngularClass/angular2-webpack-starter#1058]
Feature Request:

Would you please advise how I can load arc-js-api and dojo modules which are amd modules in angular2-webpack-starter

**Comment by dyh333** [comment]
@hassanqaiser, have you solved this problem?

**Comment by hassanqaiser** [comment]
@dyh333 , not yet, you need this feature as well? tried hard but remained unlucky..... kind of giving up for now
