### ISSUE TITLE
PathLocationStrategy doesnot work.

### ISSUE THREAD

**Issue by Fresst10** [AngularClass/angular2-webpack-starter#1060]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[*] bug report
[ ] feature request
[ ] question about the decisions made in the repository

Hello, I changed 'useHash' to 'false'. When I click on the link it works (pic. 1), but when I load page it doesnt work(pic. 2). I changed LocationStrategy providers in the provides, it doesnt help. Can I set the wrong settings?

Pic. 1
![url_without_hash](https://cloud.githubusercontent.com/assets/20557044/18877165/060cabfa-84d5-11e6-818f-d649c4a573e9.jpg)

Pic. 2
![url_doesnt_work](https://cloud.githubusercontent.com/assets/20557044/18877223/32e52ee0-84d5-11e6-90db-9bf702ec9c57.jpg)

**Comment by wilfredmifsud** [comment]
Same thing happens to me. +1

**Comment by Fresst10** [comment]
Yes, it works. Thx.
