### ISSUE TITLE
Update starter to work with sass/scss files. 

### ISSUE THREAD

**Issue by ciasej** [AngularClass/angular2-webpack-starter#1062]
* **I'm submitting a ...**
[ ] bug report
[x ] feature request
[ ] question about the decisions made in the repository

* **What is the motivation / use case for changing the behavior?**
Been having lots of issues finding the right build configuration for pre-compiling sass/scss using this starter project. Anything that does work seems to have very slow performance.

Currently, the project I am working on, has a main.scss file that imports several others assets including other scss files, fonts from font-awesome, and since bootstrap-sass is in the project it also has to declare $icon-font-path: "~bootstrap-sass/assets/fonts/bootstrap/";

Seems like my implementation is very slow 90s + for a build or rebuild and I suspect it is because of the css and scss source maps. example:

`            {
                test: /\.scss$/,
                exclude: /node_modules/,
                loaders: ['style', 'css?sourceMap', 'resolve-url', 'sass?sourceMap']
            },`

I am sure other people are trying to include scss files in their projects based on this starter and so it would be nice if possible to see a performant example of how to do this with the starter.

* **Please tell us about your environment:**
- Angular version: 2.0.0
- ng2-bootstrap 1.1.1
- bootstrap-sass 3.3.7
- node-sass 3.9.0
- sass-loader 4.0.1
- resolve-url-loader 1.6.0
- font-awesome 4.6.3
- angular2-webpack-starter 5.0.5

**Comment by JulioC** [comment]
I've been using the following config for loading app wide styles from 'src/styles' and from `styles` entry on `ComponentMetadata`. As on your case, my build is pretty slow, but the project is already much bigger than starter.

```
        {
          test: /\.scss$/,
          exclude: [/node_modules/, helpers.root('src/style')],
          loader: 'exports-loader?module.exports.toString()!css?sourceMap!postcss!sass?sourceMap!sass-resources',
        },
        {
          test: /\.scss$/,
          exclude: [/node_modules/, helpers.root('src/app')],
          loader: ExtractTextPlugin.extract({
            fallbackLoader: 'style',
            loader: 'css?sourceMap!postcss!sass?sourceMap!sass-resources',
          }),
        },
```

Any suggestions of improvements would be welcome.

**Comment by RaphaelYan** [comment]
See in the wiki of this repo for how to include scss :
https://github.com/AngularClass/angular2-webpack-starter/wiki/How-to-include-SCSS-in-components

It works fine

**Comment by IAMtheIAM** [comment]
Here's my loader for SCSS - works fast and easy

```
         /**
          * SASS support for *.scss files
          */
         {
            test: /\.(scss)$/,
            loaders: DEBUG ?
               ['style', 'css?sourceMap', 'postcss', 'sass?sourceMap', 'sass-resources', '@epegzz/sass-vars-loader?' + sassVarsConfig] : // dev mode
               ExtractTextPlugin.extract({
                  fallbackLoader: "css-loader",
                  notExtractLoader: "css-loader",
                  loader: ['css?sourceMap', 'postcss', 'sass?sourceMap', 'sass-resources', '@epegzz/sass-vars-loader?' + sassVarsConfig],
                  publicPath: '/' // 'string' override the publicPath setting for this loader
               })
         },
```
`sass-vars-loader` allows you to load a JS file with exported variables, then import them into every scss file.
`sass-resources` loads up a specified array of .scss files, and prepends them before every .scss file is compiled. Useful for appwide variables and mixins.
`postcss` allows you to do lots of cool stuff, like autoprefix classes with vendor prefixes.

Here's how to specify the options for each of those loaders
```
   new webpack.LoaderOptionsPlugin({
      /** Append a new entry under the "options" property to pass addition custom properties to webpack loaders. They listen for the properties here. */
      options: {
         postcss: function () {
            return [AutoPrefixer];
         },
         sassResources: ['./src/assets/styles/variables.scss', './src/assets/styles/mixins.scss'],
         context: helpers.paths.root,
         // sassLoader: {  //Pass custom variables such as ENV variable to scss files.
         //    data: "$susyDebug: " + susyDebug + ";"
         // }
      }
   }),
```
This is where `sassVarsConfig` is defined:
```
   // Sets debug for Susy Grid to "hide" or "show" depending on environment variable
const susyDebug = DEBUG ? 'show' : 'hide';
const sassVarsConfig = querystring.stringify({
   files: [
      // path.resolve(__dirname, '/path/to/breakpoints.js'), // JS
      // path.resolve(__dirname, '/path/to/colors.json'), // JSON

      // set vars in external .js or .json file
      path.resolve(helpers.paths.appRoot + '/assets/styles/sass-js-variables.js')
   ],
});
```

**Comment by d3viant0ne** [comment]
Resolving - multiple resolutions to the question exist in the issue.
