### ISSUE TITLE
How make ngIf globally visible in all project? 

### ISSUE THREAD

**Issue by maxkarpovets** [AngularClass/angular2-webpack-starter#1064]
I have a code `<div class="flex-container" *ngIf="mail"> Some data </div>`

And i have a error `Can't bind to 'ngIf' since it isn't a known property of 'div'. `

How i can fix it?

**Comment by zigzag95** [comment]
Please give the solution while closing your own issue.
Other developer may get the same issue and your solution may help while googlizing.
