### ISSUE TITLE
Update Material2 branch

### ISSUE THREAD

**Issue by nekkon** [AngularClass/angular2-webpack-starter#1065]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[ ] bug report
[X] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**

I would like the material2 branch of this repo to be updated to the latest version (2.0.0-alpha.9). I tried it myself and had issues. Maybe I did something wrong, just need to verify that everything is ok if someone just updates it to the latest version.

* **What is the current behavior?**

Current version is 2.0.0-alpha.7-4

**Comment by dweitz43** [comment]
i can check this out

**Comment by dweitz43** [comment]
#1066

**Comment by nekkon** [comment]
Thanks! The mistake was from my side, there were changes with latest update of material2. Just in case someone else needs to check what has changed : https://github.com/angular/material2/blob/master/CHANGELOG.md
