### ISSUE TITLE
Navigating to routes when useHash=false 

### ISSUE THREAD

**Issue by tr11** [AngularClass/angular2-webpack-starter#1075]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[X ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**

Disabling hash navigation and navigating to any route that is not the root route renders the following

`<% if (webpackConfig.htmlElements.headTags) { %> <%= webpackConfig.htmlElements.headTags %> <% } %> Loading... <% if (webpackConfig.metadata.isDevServer && webpackConfig.metadata.HMR !== true) { %> <% } %>
`

This only happens using the dev server. Production builds work as expected.  This seems to be the same or very similar to issue #762, which was marked as closed.  

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

Change on src/app/app.module.ts:50:
`RouterModule.forRoot(ROUTES, { useHash: true })`
to
`RouterModule.forRoot(ROUTES, { useHash: false })`

* **What is the expected behavior?**

Expectation is that we navigate to the correct route (e.g. http://localhost:3000/home)

* **Please tell us about your environment:**

- Angular version: 2.0.0
- Browser: Chrome

**Comment by Kamalswami** [comment]
I am facing same issue....

**Comment by nekkon** [comment]
The solution to [#1056](https://github.com/AngularClass/angular2-webpack-starter/issues/1056) did not solve the problem either. Tried removing all ^ from package.json, didn't work either.

**Comment by tr11** [comment]
@nekkon, thanks for pointing out the other issue -- I'll close this one as the problem is exactly the same as described there. Using the suggestion on #1056 issue worked for me: `"webpack-dev-server": ">=2.1.0-beta.6"` seems to break the `useHash: false` option.
