### ISSUE TITLE
Github-deploy stopped working with webpack 2.x

### ISSUE THREAD

**Issue by JonnyBGod** [AngularClass/angular2-webpack-starter#1078]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
- **Do you want to request a _feature_ or report a _bug_?**

bug
- **What is the current behavior?**

```
npm run github-deploy
```

throws an error:

```
Unknown argument: github-dev
```
- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
  https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

```
npm run github-deploy
```
- **What is the expected behavior?**

Expected to deploy the app to github
- **Please tell us about your environment:**
- Webpack 2.x
- **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

https://github.com/webpack/webpack/issues/2254

**Comment by lukad03** [comment]
Any updates on this? This is now an issue beyond env parameters given the recent changes to the webpack configuration syntax (any references to `metadata`, `output`, etc. return undefined now).
