### ISSUE TITLE
Is it possible not to use typescript?

### ISSUE THREAD

**Issue by zh-wowtv** [AngularClass/angular2-webpack-starter#1086]
I'd like to ask if it's possible not to use typescript? Instead I'd like to use es6 Javascript? Thanks.

**Comment by fxck** [comment]
why would you ever want that?

**Comment by katallaxie** [comment]
@zh-wowtv You could do so. Have look at https://github.com/katallaxie/generator-angular2-ts You can use Babel for any of the JS features (ES6/7).
