### ISSUE TITLE
Who to navigating routes without useHash or useHash=false ???

### ISSUE THREAD

**Issue by AnatolyKovalenko** [AngularClass/angular2-webpack-starter#1088]
If i  change:
RouterModule.forRoot(ROUTES, {useHash: false}) or RouterModule.forRoot(ROUTES)
and start
http://localhost:3000 it works fine, but i start http://localhost:3000/about  or another.
I get this error:
<% if (webpackConfig.htmlElements.headTags) { %> <%= webpackConfig.htmlElements.headTags %> <% } %> Loading... <% if (webpackConfig.metadata.isDevServer && webpackConfig.metadata.HMR !== true) { %> <% } %>

Anyone know how to fix this!? 
Thanks!

My package version:
    "webpack": "2.1.0-beta.22",
    "webpack-dev-middleware": "^1.6.1",
    "webpack-dev-server": ">=2.1.0-beta.6"

**Comment by csailly** [comment]
You shoud use "webpack-dev-server": "2.1.0-beta.**5**"

**Comment by AnatolyKovalenko** [comment]
@csailly Thank you! That help me.
