### ISSUE TITLE
@angularclass/webpack-toolkit is not working.

### ISSUE THREAD

**Issue by bfwg** [AngularClass/angular2-webpack-starter#1092]
* **I'm submitting a ...**
[* ] bug report

* **What is the current behavior?**
I'm getting this error when importing @angularclass/webpack-toolkit in vendor.browser.ts.
[default] /Users/fan.jin/code/medeo-iris/node_modules/@angularclass/webpack-toolkit/dist/index.d.ts:1:10
    Module '"/Users/fan.jin/code/medeo-iris/node_modules/@angular/core/index"' has no exported member 'ComponentResolver'.

* **Please tell us about your environment:**
RC6
MacOS

**Comment by russelltrafford** [comment]
Same, I'm also getting this error. For me its when I can trying to update angular to 2.1.0. But looks like @bfwg is getting this even with angular RC6 from the post above.

Anyone have any thoughts on what might be causing this? Or how I can try to fix it on my end until a proper fix is in?

**Comment by katallaxie** [comment]
@russelltrafford https://github.com/AngularClass/angular2-webpack-starter/commit/899225d96caeb3aa666233b13aa2e0dc4f3f4abb should have fixed that

**Comment by russelltrafford** [comment]
@katallaxie thanks for the update, and removing shrinkwrap as per that commit you referenced should definitely fix the version change. But maybe a little too quick to close the issue. There seems to be nothing in that commit that fixes the issue described in the original post by @bfwg?
