### ISSUE TITLE
Flash of white when navigating between routes via URL (pathlocationstrategy)

### ISSUE THREAD

**Issue by rjlee7** [AngularClass/angular2-webpack-starter#1093]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

How should I remove the flash of white (aka "loading..." screen) when I navigate between routes via URL. I am using pathlocationstrategy now to avoid the hash in the url. Could anyone recommend a server side configuration that works with the starter, to use pathlocationstrategy and make the route navigation work like hashlocationstrategy?

**Comment by gdi2290** [comment]
the flash of white means you're making a request for a new page at that url so the client code is not running where it would take over the links and show client generated views
