### ISSUE TITLE
PathLocationStrategy does not work

### ISSUE THREAD

**Issue by rajagopal4890** [AngularClass/angular2-webpack-starter#1094]
Hi.
I was trying to convert the location strategy from hash to path. I did try a variety of stuff in my ngModule:
change `useHash: false`
`import {PathLocationStrategy} from '@angular/common';
RouterModule.forRoot(ROUTES, { useClass: PathLocationStrategy })`
`usePath: true`
removed the entire thing in import and just did an
`imports:` [ // import Angular's modules
    BrowserModule,
    FormsModule,
    HttpModule,
    RouterModule.forRoot(ROUTES)
  ]`
or

`imports:` [ // import Angular's modules
    BrowserModule,
    FormsModule,
    HttpModule,
    ROUTES
  ]`

`
'ROUTES' being my route configuration from app.routes, which is:
`import { Routes, RouterModule } from '@angular/router';
import { SearchEventCategoryComponent } from '../components/searchEventCategory';
import { About } from '../components/about';
import { NoContent } from '../components/no-content';

export const ROUTES: Routes = [
  { path: '', component: SearchEventCategoryComponent },
  { path: 'EventCategory',  component: SearchEventCategoryComponent },
  { path: 'about', component: About },
  { path: '**',    component: NoContent },
];
`
Nothing works and I keep getting the hash.

Any thoughts?

**Comment by RaphaelYan** [comment]
Use the same config as this repo and just change those :

## app.module.ts
`RouterModule.forRoot(ROUTES, { useHash: true })`
TO
`RouterModule.forRoot(ROUTES, { useHash: false })`


## package.json
```
"webpack-dev-middleware": "^1.6.1",
"webpack-dev-server": "^2.1.0-beta.2",
```

TO

```
"webpack-dev-middleware": "1.6.1",
"webpack-dev-server": "2.1.0-beta.2",
```

**Comment by rajagopal4890** [comment]
Hi. Thanks for the response. I tried this already.
`RouterModule.forRoot(ROUTES, { useHash: false })`

It was not working. I guess it was more of a caching issue. Once I cleared the cached and reloaded the project, it was working fine.

**Comment by akshaypatidar455** [comment]
RaphaelYan the problem is still remains the same if i'm not using # and refresh that than it show 404
