### ISSUE TITLE
Which hashing library to use with angular2 and webpack?

### ISSUE THREAD

**Issue by drag0** [AngularClass/angular2-webpack-starter#1096]
Hi guys, I'm pretty new to webpack and angular2 so it might be an easy question. What package do you recommend for hashing files? I've done it in regular javascript with crypto-js and now I tried using [ts-md5](https://www.npmjs.com/package/ts-md5) for angular2 but with no success. Can't even import it properly in my project. Anyone run into a similar problem?

**Comment by d3viant0ne** [comment]
@drag0 - That lib is tragically out of date with angular, hence the import issues. To the best of my knowledge, a good hashing lib doesn't exist.

If this were my issue, I would probably use ts-md5 as a starting point if portions of it are viable, include it in a shared module ( faster for developing ) and stick a comment at the top referencing the original repo. Once it's current & in good working order, PR it back to the original repo or publish a new package if the owner doesn't respond.

That said, it really has nothing to do with angular2 and if all else fails using crypto-js would take very little effort to wedge into an ng2 application.
