### ISSUE TITLE
Adding css from external package 

### ISSUE THREAD

**Issue by jbeckton** [AngularClass/angular2-webpack-starter#1097]
I have a library package (node_modules/mylib) that holds some css files among other things and I need to include them in the css processing so that they are bundled along with my local app styles.

How could I accomplish this?

**Comment by davidsielert** [comment]
I believe you can use the app/vendor.browser.ts to import the assets

**Comment by jbeckton** [comment]
That seems to be the place but it does not work as expected.

**Comment by jbeckton** [comment]
So I ended up adding the css file from my node module into the app.component.ts styleUrls array and it gets bundled along with the rest of my css. The problem with this set up though is that since the css is bundled along with the javascript files then I cannot have any styles while the app is loading, I just have a blank screen until the angular app is bootstrapped, not desirable.
