### ISSUE TITLE
Add directive

### ISSUE THREAD

**Issue by mymai91** [AngularClass/angular2-webpack-starter#1098]
I clone angular2-webpack-starter and use this structure to do practice. I have a problem when I apply directive. Hope you can help me slove it.

In this file `src/app/home/home.component.ts` 

I added code: 
```
@Component({
  selector: 'fancy-button',
  template: `<button>clickme</button>`
})
export class FancyButton {}
```

In the home component I added `directives: [FancyButton]` below  `templateUrl: './home.component.html',`
```
@Component({
  // The selector is what angular internally uses
  // for `document.querySelectorAll(selector)` in our index.html
  // where, in this case, selector is the string 'home'
  selector: 'home',  // <home></home>
  // We need to tell Angular's Dependency Injection which providers are in our app.
  providers: [
    Title
  ],
  // Our list of styles in our component. We may add more to compose many styles together
  styleUrls: [ './home.component.css' ],
  // Every Angular template is first compiled by the browser before Angular runs it's compiler
  templateUrl: './home.component.html',
  directives: [FancyButton],
})
```

And then at the file: `src/app/home/home.component.html`

I added 

```
<fancy-button></fancy-button>
```

In my mind `<fancy-button>` will be render `<button>clickme</button>`

but it show the error message `main.browser.ts:25Error: Template parse errors:(…)`

![shoping-mall_and_loanstreet_partners____development](https://cloud.githubusercontent.com/assets/6791942/19345942/7ef0a418-9173-11e6-8a0a-a933970679eb.png)

Can you help me solve it?

Thanks

**Comment by ranakrunal9** [comment]
From version [2.0.0-rc.6](https://github.com/angular/angular/blob/master/CHANGELOG.md#breaking-changes-1) `@Component.directives` and `@Component.pipes` support was removed so you have to add your `FancyButton` to your modules declaration part.

**Comment by mymai91** [comment]
@ranakrunal9 Thanks, I will find out about it. 
Thank you
