### ISSUE TITLE
error 404 in other server

### ISSUE THREAD

**Issue by hmuschett** [AngularClass/angular2-webpack-starter#1100]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)
- **I'm submitting a ...**
  [ ] bug report
  [x ] feature request
  [ ] question about the decisions made in the repository
- **Do you want to request a _feature_ or report a _bug_?**

yes

i use de script "build:prod" and be properly creates the dist folder and run the "server: prod" script works great, but if I take dist folder for an Apache server (xampp) does not work throws the following errors in the browser console

[Http / 1.1 not found404] GET http: //localhost/main.e1ee96f13a8865ff1429.bundle.js
[Http / 1.1 not found404] GET http: //localhost/polyfills.2bb9fd3f5f96d5d1d642.bundle.js
[Http / 1.1 not found404] GET http: //localhost/vendor.bbbccddf6238ea19922a.bundle.js
- **Please tell us about your environment:**
  i on win 7 
- Angular version: 2.0.0
- Browser: Chrome 48 | Firefox 47 

)

**Comment by d3viant0ne** [comment]
There is nothing wrong with the dist build. Live ops issues and or features are outside the scope of a client side starter project.
