### ISSUE TITLE
Background images included in css / scss do not load from the CDN 

### ISSUE THREAD

**Issue by raghavan85** [AngularClass/angular2-webpack-starter#1101]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [X] question about the decisions made in the repository
- **What is the current behavior?**

When I use a image as a background for a css class, i place the image in the assets folder and the image is displayed fine on the browser. The problem occurs with the images not showing when I generate the dist files, place the generated dist files on a CDN like Akamai and access the dist files from my JBoss application. 

If my application url is jboss.com and the dist files of all the js files and my images (assets) are placed in say akamai.com, the css being served well, but since the css is part of the main.bundle.js and loaded on the DOM, it is attempting to load the image from jboss.com instead of from akamai.com. 

Only if I load the css directly on the head without including it as a StyleUrl in the Angular2 component, it will actually look for the image in the CDN and render it on the application. 

P.S: I currently have the ViewEncapsulation set to NONE.
- **What is the expected behavior?**

Expected behavior should be the image should load from the CDN. 
- **What is the motivation / use case for changing the behavior?**

To not place static resources like the images in the application server and serve them from a CDN.
- **Please tell us about your environment:**
- Angular version: 2.0.0
- Browser: [all ]

**Comment by d3viant0ne** [comment]
This is a configuration issue based on a rather niche requirement outside the scope of a client side starter and not something that needs to be fixed
