### ISSUE TITLE
v5.0.5 says it is angular/*-2.0.0 but in fact it is still on angular RC6

### ISSUE THREAD

**Issue by russelltrafford** [AngularClass/angular2-webpack-starter#1103]
* **I'm submitting a ...** bug/question about the decisions made in the repository

The release notes for v5.0.5 are misleading. The release notes show:

>  v5.0.5 - 52b4d4e
> Title: Angular 2
> @katallaxie katallaxie released this on Sep 2 · 35 commits to master since this release
> 
> @angular/*-2.0.0

The above suggests that the latest version (5.0.5) is on Angular 2.0.0, but taking a look at the package.json file, angular is still only on RC6. A long away off 2.0.0.

Manually updating package.json to 2.0.0 or 2.1.0 has no effect due to npm shrinkwrap forcing it back down to RC6.

3 questions:

1. Can the release notes be updated to be clear that this is NOT 2.0.0, but it is RC6. Or if the chosen commit for that tag was incorrect, and it should be 2.0.0, can the tag be updated.

2. The code in master is on angular 2.0.0, but using latest master (039deb5) causes other dependancy warnings. What is the most stable 2.0.0 commit, if there is one. Is perhaps the 2.1.0 branch more stable/ready yet?

3. What are the pros/cons/reasons one would need/want to continue to use the angular class starter kit over doing webpack yourself. I like the starter kit, but having this dependancy in the middle preventing us from using the latest released version of angular is causing an issue for us. If someone could outline the pros and cons of not using the starter kit, that would be appreciated, to help decide the best course of action.

_Note: I took out all the other questions in the template bug report, as this does not apply to a specific environment, and is a question about the repo/code in general. Can provide the info if needed._

**Comment by katallaxie** [comment]
See https://github.com/AngularClass/angular2-webpack-starter/commit/899225d96caeb3aa666233b13aa2e0dc4f3f4abb. Should be fixed.
