### ISSUE TITLE
CSS served in <style> element!

### ISSUE THREAD

**Issue by trsh** [AngularClass/angular2-webpack-starter#1107]
- **I'm submitting a ...**
  [x] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
- **Do you want to request a _feature_ or report a _bug_?**

It's kind of a feature request, but more like a bug to me.
- **What is the current behavior?**

Compiled style-sheets are server in head `<style>` element. What is kind of bad style of forming HTML documents now-days. The DOM is bigger (can get huge), no-caching, etc. I can go.., but we all probably know.
- **What is the expected behavior?**

Style-sheets should be served by default in separate files like documented here https://webpack.github.io/docs/stylesheets.html.
- **What is the motivation / use case for changing the behavior?**

Making this start pack better. Also I cold not do it my-self. Got tons of errors working with that plugin.
- **Please tell us about your environment:**
- Angular version: 2.0.0
- Browser: Chrome (latest stable), Windows 10 64x

**Comment by trsh** [comment]
Read some docs online, seems like it's THE NEW WAY. And I can always insert my global styles in html. Right?

**Comment by ebeal** [comment]
You are correct. Ideally once browsers properly use the shadow dom the styles will be encapsulated within the component, but until then.... this is what we've got. I'm not a huge fan of it either.
