### ISSUE TITLE
I want to add rest api to this project using Express.js framework

### ISSUE THREAD

**Issue by itranga** [AngularClass/angular2-webpack-starter#1108]
I want to add rest api to this project using Express.js framework.
what is the best way to integrate it? I need to add nginx for my server .

**Comment by d3viant0ne** [comment]
This [wiki page](https://github.com/AngularClass/angular2-webpack-starter/wiki/How-to-pass-environment-variables%3F) covers passing in an API URL to make calls to an api.

Documentation on how to spin up a full MEAN stack application out of the starter is well outside the scope of this project. I'd suggest https://github.com/sindresorhus/awesome & google.
