### ISSUE TITLE
(bug): Can't use sass/scss in the latest version

### ISSUE THREAD

**Issue by rafaelss95** [AngularClass/angular2-webpack-starter#1110]
- **I'm submitting a ...**
  [X] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
- **Do you want to request a _feature_ or report a _bug_?**
  Bug.
- **What is the current behavior?**
  I cloned this project and it works. So I searched a way to use  `scss` instead of `css`, then I followed  this [tutorial](https://github.com/AngularClass/angular2-webpack-starter/wiki/How-to-include-SCSS-in-components) and modify the extension to `scss` and, of course, in styleUrls. however I'm still receiving a bug:

> ERROR in ./src/app/app.component.scss
> Module build failed: 
> html {
> ^
>       Invalid CSS after "... Get the styles": expected 1 selector or at-rule, was "var styles = requir"
>       in /home/rafael/work/angular/angular2-webpack-starter/src/app/app.component.scss (line 1, column 1)
>  @ ./src/app/app.component.ts 26:16-47
>  @ ./src/app/app.module.ts
>  @ ./src/app/index.ts
>  @ ./src/main.browser.ts
>  @ multi main

My `webpack.common.js` is configured as follows:

```
module: {

  rules: [

    /*
     * Typescript loader support for .ts and Angular 2 async routes via .async.ts
     * Replace templateUrl and stylesUrl with require()
     *
     * See: https://github.com/s-panferov/awesome-typescript-loader
     * See: https://github.com/TheLarkInn/angular2-template-loader
     */
    {
      test: /\.ts$/,
      loaders: [
        '@angularclass/hmr-loader?pretty=' + !isProd + '&prod=' + isProd,
        'awesome-typescript-loader',
        'angular2-template-loader'
      ],
      exclude: [/\.(spec|e2e)\.ts$/]
    },

    /*
     * Json loader support for *.json files.
     *
     * See: https://github.com/webpack/json-loader
     */
    {
      test: /\.json$/,
      loader: 'json-loader'
    },

    /*
     * to string and css loader support for *.css files
     * Returns file content as string
     *
     */
    {
      test: /\.css$/,
      loaders: ['to-string-loader', 'css-loader']
    },

    /* Raw loader support for *.html
     * Returns file content as string
     *
     * See: https://github.com/webpack/raw-loader
     */
    {
      test: /\.html$/,
      loader: 'raw-loader',
      exclude: [helpers.root('src/index.html')]
    },

    /* File loader for supporting images, for example, in CSS files.
     */
    {
      test: /\.(jpg|png|gif)$/,
      loader: 'file'
    },

    // Sass
    {
      test: /\.scss$/,
      exclude: /node_modules/,
      loaders: ['raw-loader', 'sass-loader'] // sass-loader not scss-loader
    },

    // ng2Bootstrap + Bootstrap 3

    {
      test: /\.(sass|scss)$/,
      loaders: ['css-to-string-loader', 'css-loader?sourceMap', 'resolve-url', 'sass-loader?sourceMap']
    },

    {
      test: /\.woff(2)?(\?v=.+)?$/,
      loader: "url?limit=10000&minetype=application/font-woff"
    },

    {
      test: /\.(ttf|eot|svg|woff)(\?v=.+)?$/,
      loader: "file"
    }
  ]
},
```
- **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

I did the same thing in the previous version and it works very well, the problem just happens in the **latest** version of this webpack.

**Comment by d3viant0ne** [comment]
```
        {
          test: /\.scss$/,
          loaders: ['raw-loader', 'sass-loader']
        },

        {
          test: /init\.scss$/,
          loader: ExtractTextPlugin.extract({ fallbackLoader: 'style-loader', loader: 'css-loader!sass-loader?sourceMap' })
        },
```

**Comment by samikha** [comment]
Hi, I'm having the same issue when trying to include the bootstrap and fontawesome scss....even with d3viant0ne''s proposition, the error is still there

**Comment by katallaxie** [comment]
@samikha remove `angular2-template-loader` and then just `require` your scss. `angular2-template-loader` transforms the `templateUrl` to a `template`.

**Comment by ebeal** [comment]
Closing this, if you're still having issues check the material2 branch, I have a working example there.
