### ISSUE TITLE
how to add NodeJS to the project? we use nodejs for backend. Someone can help?

### ISSUE THREAD

**Issue by abbymrs** [AngularClass/angular2-webpack-starter#1119]

**Comment by vesteraas** [comment]
You could add the `proxy` parameter to `devServer` in `webpack.dev.js`:

```
        devServer: {
            proxy: {
                '/api/*': 'http://<YOUR_BACKEND_HOST>:<YOUR_BACKEND_PORT>',
            },
            port: METADATA.port,
            host: METADATA.host,
            historyApiFallback: true,
            watchOptions: {
                aggregateTimeout: 300,
                poll: 1000
            },
            outputPath: helpers.root('dist')
        },
```

This way, all requests starting with '/api/' will be redirected to your backend server.

**Comment by abbymrs** [comment]
@vesteraas, thanks. 
I fixed it with your method.

**Comment by abbymrs** [comment]
Hi @vesteraas ,
i need your further help....
with the config as below, angular2.0.0 project works with node as backend, but it failed in angular1.5 project, may i know where it was wrong?

```
....
 devServer: {
        port: 5000,
        host: 'localhost',
        historyApiFallback: true,
        watchOptions: {
            aggregateTimeout: 300,
            poll: 1000
        },
        outputPath: '/',
        proxy: {
            '/api/*': 'http://localhost:8000'
        }
    },
....
```

**Comment by vesteraas** [comment]
@abbymrs I guess your question is off-topic here (as well as this answer) but have a look at http://stackoverflow.com/questions/35538472/webpack-dev-server-with-backend-api

**Comment by abbymrs** [comment]
thanks, i rechecked again, it was my mistake that forgot to add '/api/' in my front end codes when make requests from backend.
Thank you so much!
