### ISSUE TITLE
Feature Request: State Management

### ISSUE THREAD

**Issue by CharlieGreenman** [AngularClass/angular2-webpack-starter#1121]
* **I'm submitting a ...**
[ ] bug report
[X] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
App does not currently allow for state management out of the box. 

* **What is the expected behavior?**
Build system should have the ability to manage state, using either [ngrx](https://github.com/ngrx/store), or [ng2-redux](https://github.com/angular-redux/ng2-redux). 

* **What is the motivation / use case for changing the behavior?**
Ability to manage state using [ngrx](https://github.com/ngrx/store), or [ng2-redux](https://github.com/angular-redux/ng2-redux). (Ideally, ngrx.)

* **Please tell us about your environment:**
- Angular version: 2.0.0-beta.X
- Browser: all

**Comment by d3viant0ne** [comment]
@CharlieGreenman - This would be something that belongs on a fork of the `angular2-webpack-starter`. My suggestion would be to go the route that NathanWalker went with https://github.com/NathanWalker/angular-seed-advanced

Not everyone wants / needs something like ngrx.

As an aside, professionally I run a heavily modified version of the webpack-starter with ngrx / scss & a few other goodies. If you were interested in maintaining a feature fork for ngrx, i'd certainly be up for contributing to it.

**Comment by CharlieGreenman** [comment]
Ok. I was thinking of contributing to https://github.com/qdouble/angular-webpack2-starter. However, https://github.com/NathanWalker/angular-seed-advanced does seem to be better off for this stage in things. It's just that angular2-seed-advanced is too jammed pack, with Electron/Nativescript. I'll take my reservations over to [angular2-seed-advanced](https://github.com/NathanWalker/angular-seed-advanced) if need be.

**Comment by d3viant0ne** [comment]
@CharlieGreenman  I wasn't necessarily suggesting you contribute to a different repo. 

To be clear, I was suggesting you create a fork of this repo and modify it to run ngrx as an example / base seed for those that want to get into redux.

Nathan's advanced seed is great but it's based on SystemJS, if you want to use Webpack ( my personal choice ) that is going to be a big change. I've looked at the `angular-webpack2-starter` it's solid work but imho it's a bit cluttered for my taste.

In the end I personally forked this repo & added ngrx, scss & material2 and it's maintained independently at this point.

**Comment by CharlieGreenman** [comment]
Hey Joshua, I actually did realize that! I also realized after writing what
I did that I should mention that, but was caught up at the time :)
