### ISSUE TITLE
NPM install failed

### ISSUE THREAD

**Issue by vinothinivenkatesan** [AngularClass/angular2-webpack-starter#1125]
![capture](https://cloud.githubusercontent.com/assets/7835176/19643561/913b02c4-9a08-11e6-9b20-60a0360519b4.PNG)

Getting the error after cloned from github and tried npm install.
I am running cmd prompt as admin , Also tried

>  npm cache clean. 

Since i am behind proxy, 
I tried using

> npm config set proxy proxy-url:port
> npm config set https-proxy proxy-url:port

All my effort failed. Kindly help me in resolving the issue.

**Comment by d3viant0ne** [comment]
When looking at the dependency tree ..
<img width="352" alt="screen shot 2016-10-29 at 9 05 15 pm" src="https://cloud.githubusercontent.com/assets/8420490/19834020/e9927f48-9e1c-11e6-82ec-25b4a7dd0243.png">


Codecov is using an ancient lib which is where your checksum issues are coming from. That said, `angular2-template-loader` shouldn't be leaking devDeps in a package. Already spoke to Sean about it, I'll be adding a bit of packaging to the template loader lib to tighten up what is being pulled down when it's installed.

**Comment by d3viant0ne** [comment]
@vinothinivenkatesan - #1145 Resolves the issue with the `angular2-template-loader`
