### ISSUE TITLE
Webpack 2 Tree Shaking - Can't get Karma to work

### ISSUE THREAD

**Issue by rafiwardak2003** [AngularClass/angular2-webpack-starter#1128]
I got tree shaking to work with Angular 2.1/Webpack 2 beta. All seems to be good, except my test runner doesn't work anymore. As soon as I switched TypeScript module from commonjs to es6 (target has remained the same, es5) to get tree shaking working, Karma now blows up. I get a bunch of unexpected token (referring to the ES6 import, and a bunch of other errors, failed to parse file... something.ts. Has anyone had luck getting TypeScript/Tree Shaking working with Angular 2 yet?

**Comment by d3viant0ne** [comment]
@rafiwardak2003 - Tree shaking is broken, relevant issues to watch 

https://github.com/webpack/webpack/issues/2867
