### ISSUE TITLE
include yarn lock

### ISSUE THREAD

**Issue by gdi2290** [AngularClass/angular2-webpack-starter#1129]
add docs about yarn

**Comment by katallaxie** [comment]
@gdi2290 👍 is included. We should also use it in `.travis.yml` https://yarnpkg.com/en/docs/install-ci#travis-tab

**Comment by katallaxie** [comment]
@gdi2290 #1130

**Comment by d3viant0ne** [comment]
@gdi2290 @katallaxie - Can we close this one, looks like we are all yarned up :)
