### ISSUE TITLE
Url reload not rendering on production build

### ISSUE THREAD

**Issue by alan12111** [AngularClass/angular2-webpack-starter#1132]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)
- **I'm submitting a ...**
  [x ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
- **Do you want to request a _feature_ or report a _bug_?**
  bug report
- **What is the current behavior?**
  refreshing the page on a clicked component will render in local dev but will not refresh when i execute local prod
- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
  https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

npm run build:prod
npm run server:prod (i have a custom configured)

click on any link (about, etc)
refresh the page

page is blank
- **What is the expected behavior?**
  Page should reload fine
- **What is the motivation / use case for changing the behavior?**

To test on production
- **Please tell us about your environment:**
- Angular version: 2.1.1
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome, Mac,
- **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by phivo** [comment]
I have the same issue. I found it is ok if useHash is set to true, but not if false.

How to reproduce:

1. clone project and `npm install`
1. change `useHash` to `false` in the app.module.ts
1. `npm run build:prod`
1. `npm run server:prod`
1. `http://localhost:8080/about fails to load`

The server replies with:
`"GET /detail" Error (404): "Not found"`

**Comment by katallaxie** [comment]
@phivo you have to rewrite all urls to index.html, so to the Angular app.

**Comment by phivo** [comment]
I understand the issue is with the http-server not redirecting everything to index.html.
As testing the production is important part before uploading to server, this should be supported out of the box.

**Comment by katallaxie** [comment]
@phivo we could include a local config. However, this is something that depends on production requirements.

**Comment by chiranjeevitapal** [comment]
This issue is not only with http-server but also with Apache Tomcat. I guess URL Rewriting is one solution. Could any one suggest how to configure URL Rewriting on Express JS?

**Comment by zaikin-andrew** [comment]
Hi there! Any news here? I have the same issue.

**Comment by arrian0511** [comment]
Is there any fix for these? I got the same issue also.

**Comment by vivekdoshi2** [comment]
I got the same issue also.

**Comment by George02** [comment]
Guys, If you use apache you could create a .htaccess file in the root directory of your application and write those line into that file:

`RewriteEngine on
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule . index.html [L]`

More details here:
https://gist.github.com/RaVbaker/2254618

**Comment by gialang** [comment]
I got the same issue also with product enviroment.
