### ISSUE TITLE
Chunkhash of polyfills commons chunk is the same for different content

### ISSUE THREAD

**Issue by ilyahumbar** [AngularClass/angular2-webpack-starter#1133]
Hello guys, 
Thank you for the wonderful starter project! 

It would be really great if you could help me with the following issue, as it can cause a lot of troubles on a real production environment. 
The issue is with long-term caching of static assets and lazy loaded modules.
Reproducible on windows and Linux machines. Here are the steps:
1. clone the repository, run `npm install` and `npm run build:prod`
2. copy dist folder and save it somewhere to be able to compare old content with newly generated later
3. modify Lazy-loaded component (src\app+detail\detail.component.ts) somehow (change console.log statement for instance). 
4. run `npm run build:prod` again
5. compare folders with any diff tool. Here are my results

![image](https://cloud.githubusercontent.com/assets/13537012/19752979/f13e4638-9c09-11e6-899a-9cb8c6a6a3cc.png)

The only difference is in polyfills commons chunk:

![image](https://cloud.githubusercontent.com/assets/13537012/19753039/78170fdc-9c0a-11e6-8fd6-82ab954cdf0d.png)

For some reason, chunkhash for polyfills chunk is not changed although content is different. 

Appreciate any help.

**Comment by ilyahumbar** [comment]
BTW looks similar to  webpack/webpack#1155.

**Comment by katallaxie** [comment]
@ilyahumbar if you do not add anything different to the polyfills, which usually you don't. The hash will not be different, as the content did not vary.

**Comment by ilyahumbar** [comment]
@katallaxie, maybe I didn't explain the issue properly. Indeed, polyfills content isn't changed in this case. But reference map is changed. And this map happens to be stored inside polyfills file with current webpack configuration. 
Anyway, I don't expect this to be fixed as part of starter project. This is a webpack-related bug. To be precise it is webpack-md5-hash bug (erm0l0v/webpack-md5-hash#7). 
To overcome the issue I decided to use [hash] instead of [chunkhash] for webpack output. Obviously it will force clients to invalidate each module after application release/build. But it is better than not invalidating content at all and it is temporary solution while the bug isn't fixed.
