### ISSUE TITLE
npm install (npm v2) and npm shrinkwrap (npm v3) fail

### ISSUE THREAD

**Issue by aleksfes** [AngularClass/angular2-webpack-starter#1134]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
- **Do you want to request a _feature_ or report a _bug_?**
  bug
- **What is the current behavior?**
  Npm (v2) fails to install node modules. Npm (both v2 and v3) fails to shrinkwrap.
- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
  https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).
1. checkout latest master (currently d6c2afa440394)
2. run "npm install" (npm v2)

```
npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/aleksander.feoktistov/.nvm/versions/node/v4.4.7/bin/node" "/Users/aleksander.feoktistov/.nvm/versions/node/v4.4.7/bin/npm" "i"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package rxjs@5.0.0-rc.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer @angular/core@2.1.1 wants rxjs@5.0.0-beta.12
npm ERR! peerinvalid Peer @angular/http@2.1.1 wants rxjs@5.0.0-beta.12
npm ERR! peerinvalid Peer @angular/router@3.1.1 wants rxjs@5.0.0-beta.12
```

or
2. run "npm install" (npm v3) - you will get some warnings

```
npm WARN @angular/http@2.1.1 requires a peer of rxjs@5.0.0-beta.12 but none was installed.
npm WARN @angular/router@3.1.1 requires a peer of rxjs@5.0.0-beta.12 but none was installed.
npm WARN @angular/core@2.1.1 requires a peer of rxjs@5.0.0-beta.12 but none was installed.
npm WARN tslint-loader@2.1.5 requires a peer of tslint@^3.0.0 but none was installed.
npm WARN codelyzer@1.0.0-beta.3 requires a peer of tslint@^3.9.0 but none was installed.
```
1. run "npm shrinkwrap"

```
npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/aleksander.feoktistov/.nvm/versions/node/v6.5.0/bin/node" "/Users/aleksander.feoktistov/.nvm/versions/node/v6.5.0/bin/npm" "shrinkwrap"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3

npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! peer invalid: rxjs@5.0.0-beta.12, required by @angular/core@2.1.1
npm ERR! peer invalid: rxjs@5.0.0-beta.12, required by @angular/http@2.1.1
npm ERR! peer invalid: rxjs@5.0.0-beta.12, required by @angular/router@3.1.1
```
- **What is the expected behavior?**
  At least "npm shrinkwrap" should work for npm v3.
  It's desirable "npm install" should work for npm v2 too.
- **What is the motivation / use case for changing the behavior?**
  Unfortunately, I can't upgrade npm to the v3 version, and I want to stop saving node_modules to the my sources/git, so I need to make "npm install" works for the npm v2 version.
- **Please tell us about your environment:**
- Angular version: 2.0.0-beta.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  MacOS X (10.10.5), nvm (0.31.6), node/npm (v4.4.7/v2.15.8, v6.5.0/v3.10.3).
- **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by otjutt** [comment]
I'm also facing this problem.

**Comment by katallaxie** [comment]
@otjutt @aleksfes we require `npm@^3`, so `npm@^2` will not work. See `README`. You could also use the v6 branch for the most recent version of Angular.

**Comment by aleksfes** [comment]
@katallaxie thanks, but what about shrinkwrap? It does not work for npm@3.
