### ISSUE TITLE
Using with NG2-smart-table

### ISSUE THREAD

**Issue by alan12111** [AngularClass/angular2-webpack-starter#1136]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**

report a bug

* **What is the current behavior?**
trying to build dev with NG2-Smart table
ERROR in ./~/ng2-smart-table/build/src/ng2-smart-table/ng2-smart-table.scss
Module parse failed: /Users/developer/Desktop/2.1.1/angular2-webpack-starter-master/node_modules/ng2-smart-table/build/src/ng2-smart-table/ng2-smart-table.scss Unexpected token (1:0)
You may need an appropriate loader to handle this file type.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

npm install --save ng2-smart-table 
npm run build:dev

* **What is the expected behavior?**
does not build

* **What is the motivation / use case for changing the behavior?**

to use ng smart table

* **Please tell us about your environment:**

- Angular version: 2.1.1
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Mac, Chrome

Node 6.9.0
* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links s to have context, eg. stackoverflow, gitter, etc)

**Comment by michaeljota** [comment]
I'm sure this is not an issue with the starter. It just doesn't have any SASS loaders, you have to setup on your own. If you want to, you can google for the ng2-admin theme, it's partially based on this, and have SASS loaders configured. (I'm making a starter on my own with sass loader based on this, but I don't have any ETA)

**Comment by katallaxie** [comment]
@alan12111 and @michaeljota yep, the Starter really is a Starter. You then have to add to it Sass or anything else. We also will not add any of these, because not all people use Sass, and not all people use Bootstrap or else. It is that you can customize it to your needs and have something to go to be productive.
