### ISSUE TITLE
Why Bootstrap4 cannot show default Icon?

### ISSUE THREAD

**Issue by hllinc** [AngularClass/angular2-webpack-starter#1137]
According to the Wiki "How to use Bootstrap 4 and Sass (and jQuery)".
Most of the bootstrap layout style can work well.
But the Tags's background is blank.
The icon of the Collapsible content Navbar's toogle button don't show.
And so on.
Project starts well without any errors.
Why? God bless me.

**Comment by d3viant0ne** [comment]
Is there associated console output with this or does it just not do anything at all?

**Comment by hllinc** [comment]
There is nothing about this in console, project starts success without any error.
I used the navbar component of Bootstrap 4, the items of nav's menu display well, but when collapsible button appeared there is no icon in the button, there is only a button frame display in the collapsible area. When I clicked it can slide down the hidden menu.
And the navbar's 'float-lg-right' class not worked either.
Thanks. @d3viant0ne

**Comment by hllinc** [comment]
Oh, no!!!!
I used the wrong version of bootstrap 4.
The api document of bootstrap is v4-5, but the version I installed was v4-2. 
I can't find the api doc of v4-2 in bootstrap official website.
Finally I changed the version to v3.3.7 and solved it .
Thank to @d3viant0ne again.
