### ISSUE TITLE
Image Loader works for production but not tests

### ISSUE THREAD

**Issue by georgeedwards** [AngularClass/angular2-webpack-starter#1139]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
- **What is the current behavior?**

Components with images work great in dev/production mode, but when it comes to testing, they can't be bundled, e.g. 

> Error: Module parse failed: C:\myProj\client\assets\img\background.jpg Unexpected character '�' (1:0)
>  You may need an appropriate loader to handle this file type.
>   (Source code omitted for this binary file)
>   at config/spec-bundle.js:72122
- **What is the expected behavior?**

For the test webpack config to more closely reflect the dev configuration
- **What is the motivation / use case for changing the behavior?**

A more unified test/develop experience
- **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by d3viant0ne** [comment]
@georgeedwards - The test config isn't merged with the common config like dev or prod is.

You will need to copy the relevant loader configs into `webpack.test.js`

See this portion of `webpack.common.js` 
https://github.com/AngularClass/angular2-webpack-starter/blob/master/config/webpack.common.js#L140-L161

**Comment by georgeedwards** [comment]
@d3viant0ne Awesome - thanks, that has fixed it. Although not working for .svg? I tried changing to:

```
        /* File loader for supporting images, for example, in CSS files.
         */
        {
          test: /\.(jpg|png|gif|svg)$/,
          loader: 'file'
        },
```
but that didn't work. How shoudl I fix that?

**Comment by d3viant0ne** [comment]
@georgeedwards - Short version SVG != Image

For SVG's and also fonts, you would want to do something like this.

```
        {
          test: /\.(ttf|eot|svg)(\?v=.+)?$/, loader: 'file-loader'
        },
```

**Comment by d3viant0ne** [comment]
Resolution exists in issue, resolving.
