### ISSUE TITLE
Error with "webpack": "^2.1.0-beta.21" in the branch material2

### ISSUE THREAD

**Issue by jdavmo** [AngularClass/angular2-webpack-starter#1140]
I am getting an error with the version "webpack": "^2.1.0-beta.22" in the branch material2

angular2-webpack-starter@5.0.5 start /Users/...../Dev/al/projects/bucketmovies

> npm run server:dev
> 
> angular2-webpack-starter@5.0.5 server:dev /Users/..../Dev/al/projects/bucketmovies
> webpack-dev-server --config config/webpack.dev.js --progress --profile --watch --content-base src/

/Users/..../Dev/al/projects/bucketmovies/node_modules/webpack/lib/webpack.js:16
        throw new WebpackOptionsValidationError(webpackOptionsValidationErrors);
        ^
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
- configuration has an unknown property 'tslint'. These properties are valid:
  object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, loader?, module?, name?, node?, output?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
  For typos: please correct them.
  For loader options: webpack 2 no longer allows custom properties in configuration.
   Loaders should be updated to allow passing options via loader options in module.rules.
   Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the loader:
   plugins: {
     new webpack.LoaderOptionsPlugin({
       // test: /.xxx$/, // may apply this only for some modules
       options: {
         tslint: ...
       }
     })
   }
- configuration.module has an unknown property 'preLoaders'. These properties are valid:
  object { exprContextCritical?, exprContextRecursive?, exprContextRegExp?, exprContextRequest?, loaders?, noParse?, rules?, unknownContextCritical?, unknownContextRecursive?, unknownContextRegExp?, unknownContextRequest?, wrappedContextCritical?, wrappedContextRecursive?, wrappedContextRegExp? }
  Options affecting the normal modules (`NormalModuleFactory`).
- configuration.node.global should be a boolean.
- configuration.resolve has an unknown property 'modulesDirectories'. These properties are valid:
  object { alias?, aliasFields?, cachePredicate?, descriptionFiles?, enforceExtension?, enforceModuleExtension?, extensions?, fileSystem?, mainFields?, mainFiles?, moduleExtensions?, modules?, plugins?, resolver?, symlinks?, unsafeCache? }
- configuration.resolve.extensions[0] should not be empty.
  at webpack (/Users/..../Dev/al/projects/bucketmovies/node_modules/webpack/lib/webpack.js:16:9)
  at processOptions (/Users/..../Dev/al/projects/bucketmovies/node_modules/webpack-dev-server/bin/webpack-dev-server.js:310:17)
  at Object.<anonymous> (/Users/..../Dev/al/projects/bucketmovies/node_modules/webpack-dev-server/bin/webpack-dev-server.js:374:1)
  at Module._compile (module.js:413:34)
  at Object.Module._extensions..js (module.js:422:10)
  at Module.load (module.js:357:32)
  at Function.Module._load (module.js:314:12)
  at Function.Module.runMain (module.js:447:10)
  at startup (node.js:148:18)
  at node.js:405:3

**Comment by jdavmo** [comment]
I solved this with "webpack": "^2.1.0-beta.22",

**Comment by mmathys** [comment]
@jdavmo Can't get it to work, still. Could you provide a solution command...? --> #1151

**Comment by jdavmo** [comment]
@mmathys what node version are you using ? try with a minor version like v5.12.0

**Comment by ebeal** [comment]
Try it now, I've updated from master branch.
