### ISSUE TITLE
project does not work when it is opened in safari.

### ISSUE THREAD

**Issue by amanullahnxb** [AngularClass/angular2-webpack-starter#1146]
I installed safari 5.0 on linux machine (ubuntu 14) with the help of wine (PlayOnLinux). The app is failed to load in browser. It shows 4 errors in console all saying same: "SyntaxError: Parse error". as shown in figure attached.
![screenshot from 2016-10-31 17 07 14](https://cloud.githubusercontent.com/assets/22980215/19853690/9e65470a-9f8c-11e6-8d90-e43b5d88c46a.png)

**Comment by katallaxie** [comment]
@amanullahnxb see [Browser Support](https://angular.io/docs/ts/latest/guide/browser-support.html)
