### ISSUE TITLE
Yarn in favor of npm

### ISSUE THREAD

**Issue by laumair** [AngularClass/angular2-webpack-starter#1148]
Any plans for using `yarn` instead of `npm`? If this is to be implemented in near future I'd be happy to submit a PR for it with updated docs.

**Comment by hamzatrq** [comment]
Currently, I am using Yarn without any issue.

**Comment by d3viant0ne** [comment]
@laumair - the project is already setup for yarn #1130 should people want to use it for install. As for executing everything with yarn, that forces people to use yarn and it's still a little buggy.

**Comment by laumair** [comment]
@d3viant0ne Ah, I see. Thanks for the reply back. Awesome boilerplate btw
