### ISSUE TITLE
There is no need to include webpack-dev-server.js in index.html

### ISSUE THREAD

**Issue by Redigast13** [AngularClass/angular2-webpack-starter#1150]
Automatic page refresh works without `<script src="/webpack-dev-server.js"></script>` in `index.html`. So, it could be removed from `index.html`.

Steps to reproduce the problem:
1. remove  `<script src="/webpack-dev-server.js"></script>` from `index.html`.
2. npm start
3. open localhost:3000 in browser
4. change something in any file in `src` directory
5. page will be automatically reloaded

**Comment by ohadlahav** [comment]
same here

**Comment by katallaxie** [comment]
@Redigast13 yep, it is not always needed, but in case you want to use the Webpack API.
