### ISSUE TITLE
Branch material2 : not working !

### ISSUE THREAD

**Issue by mahmoudmahdi24** [AngularClass/angular2-webpack-starter#1151]
Hello,

I tried to start your project using the branch material2 but it's not working! any requests ?
"npm start" fails !

Thanks

**Comment by mahmoudmahdi24** [comment]
<img width="1406" alt="capture d ecran 2016-11-03 a 12 47 51" src="https://cloud.githubusercontent.com/assets/4971795/19964731/c9c6130a-a1c3-11e6-84ca-db1996b2ebb8.png">

**Comment by mahmoudmahdi24** [comment]
<img width="1229" alt="capture d ecran 2016-11-03 a 12 48 32" src="https://cloud.githubusercontent.com/assets/4971795/19964740/dfc8a8ca-a1c3-11e6-926e-2860d2b2dfaf.png">

**Comment by dissoupo** [comment]
I have the same issue. It looks like Material2 branch has outdated Webpack config files.
I tried to replace those from Master branch, then "npm start" works but there are other issues in produced code.

**Comment by codespicelabs** [comment]
[Surely] (https://github.com/AngularClass/angular2-webpack-starter/blob/material2/package.json#L60)

but there is nothing special in that branch, just add material 2 to your project in usual way

**Comment by mmathys** [comment]
Not working for me as well!

**Comment by ebeal** [comment]
Hey guys, my bad, haven't been keeping up. Just pushed a new version with limited examples of material components, links to resources and examples of theme modifications. I'll keep this open for anyone having issues with the new version.

**Comment by mahmoudmahdi24** [comment]
It's ok !
Thanks for updating the project ! I'll try it out later ;)

**Comment by jrab** [comment]
Hey Folks

Just wanted to bring up an issue when building the material2 branch -- seems like an NPM error:

![npm-error](https://cloud.githubusercontent.com/assets/694448/20282535/1a8f30ce-aa83-11e6-8117-46e03012ab79.PNG)

**Comment by ebeal** [comment]
ah yeah, was trying to get the e2e to work properly, forgot to check in.
Replace the @types/protractor version with "@types/protractor": "^1.5.20", in the package.json

I'll update this in the branch too

**Comment by ebeal** [comment]
should be good to go now
