### ISSUE TITLE
npm2 install fails

### ISSUE THREAD

**Issue by ihabZhaika** [AngularClass/angular2-webpack-starter#1153]
Hi,
i pulled the repo and did npm install
i got the following
`
npm ERR! Linux 4.8.0-26-generic
npm ERR! argv "/home/ihab/progs/node-v4.6.0/bin/node" "/home/ihab/progs/node-v4.6.0/bin/npm" "install"
npm ERR! node v4.6.0
npm ERR! npm  v2.15.9
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package @angular/common@2.1.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer @angular/forms@2.1.2 wants @angular/common@2.1.2
npm ERR! peerinvalid Peer @angular/platform-browser@2.1.1 wants @angular/common@2.1.1
npm ERR! peerinvalid Peer @angular/platform-browser-dynamic@2.1.1 wants @angular/common@2.1.1
npm ERR! peerinvalid Peer @angular/platform-server@2.1.1 wants @angular/common@2.1.1
npm ERR! peerinvalid Peer @angular/router@3.1.1 wants @angular/common@2.1.1

`
IS there any reason why this happen ?

**Comment by katallaxie** [comment]
@ihabZhaika no an `npm i npm@^3` before. Your npm is simply outdated. The `package.json` requires `npm` > 3.x
