### ISSUE TITLE
Details from "Template parse errors" not shown

### ISSUE THREAD

**Issue by baloodevil** [AngularClass/angular2-webpack-starter#1154]
Details from "Template parse errors" are not shown; only a generic message is shown.

To reproduce, in a new angular2-webpack-starter project in `app.component.html` add `<foo></foo>`.  When running you will get this error...
![image](https://cloud.githubusercontent.com/assets/11354890/20012999/ee35fb32-a287-11e6-9071-495e76b05a7a.png)

For comparison, in a new [quickstart](https://github.com/angular/quickstart) project do the same in the template field of `app.component.ts`.  When running you will get this more helpful error...
![image](https://cloud.githubusercontent.com/assets/11354890/20012972/dccad944-a287-11e6-9717-4c6bcedba73b.png)

Not sure if this is due to Webpack, or specifics of the starter project.  Without helpful error messages, troubleshooting and development is very slow.

**Comment by katallaxie** [comment]
@baloodevil Have a look at the bootstrap function in, it is slightly different. Or checkout `v6`branch.

**Comment by baloodevil** [comment]
@katallaxie Great tip.  Commenting out `.catch(err => console.error(err));` from `main.browser.ts` surfaced the original errors in their full glory.  I think this change should be included in v5 and v6.  Many people are using this starter project.  Unhelpful error messages make people think Angular 2 is to blame, which it is not.
