### ISSUE TITLE
this.http.get(...).map is not a function inside v6 branch

### ISSUE THREAD

**Issue by ranakrunal9** [AngularClass/angular2-webpack-starter#1155]
* **I'm submitting a ...**
[*] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
BUG

* **What is the current behavior?**
TypeError: this.http.get(...).map is not a function

* **Steps to reproduce**

  1. Clone the repository
  2. Checkout [v6](https://github.com/AngularClass/angular2-webpack-starter/tree/v6) branch
  3. add `import { Http } from '@angular/http';` in `app.component.ts` and call API inside `ngOnInit` as   below :
      `this.http.get('http://your.apiurl.com').map((res) => res.json()).subscribe((res) => { console.log(res); });`

  4. serve application with `npm start` and visit [http://localhost:3000/](http://localhost:3000/) in browser it will throw error TypeError: this.http.get(...).map is not a function in browser console

   Instead of serving with with `npm start` if i will first run `npm run build:aot` and then serve application with `npm run server:prod` then its running application and not throwing error `TypeError: this.http.get(...).map is not a function`

* **What is the expected behavior?**
It needs to run application without any error.

* **Please tell us about your environment:**

- Angular version: 2.1.2
- Browser: Chrome XX

**Comment by ericmartinezr** [comment]
You have to import the map operator. Anyway according to your description this is not an angular issue but that seed project's. Please re-open it in its repo https://github.com/AngularClass/angular2-webpack-starter

**Comment by katallaxie** [comment]
@ranakrunal9 I have added the `development` environment to `server:dev`. It is that the `dll`s are only build when dev is the env.

**Comment by ranakrunal9** [comment]
@katallaxie I have checked this again after your changes but error is still coming so i have made pull request #1158 to solve it.
