### ISSUE TITLE
RXJS Compilation error

### ISSUE THREAD

**Issue by jneveux** [AngularClass/angular2-webpack-starter#1168]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[ x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**

I'm seeing that error when building in dev mode (apparently it does not affect the application):

`webpack: bundle is now VALID.
[default] D:\Projects\Angular\angular2-webpack-starter\node_modules\rxjs\observable\PairsObservable.d.ts:1:1
    Cannot find type definition file for 'chai'.
[default] D:\Projects\Angular\angular2-webpack-starter\node_modules\rxjs\observable\dom\AjaxObservable.d.ts:1:1
    Cannot find type definition file for 'chai'.
[default] Checking finished with 2 errors
`

* **Please tell us about your environment:**

- Angular2-webpack-starter version: 5.1.1

**Comment by jneveux** [comment]
Switching to "rxjs": "5.0.0-beta.12", fixes the issue.

**Comment by katallaxie** [comment]
You could also use the V6 branch.
