### ISSUE TITLE
Question: What are the use cases of `AppState`?

### ISSUE THREAD

**Issue by cmckni3** [AngularClass/angular2-webpack-starter#1169]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[x] question about the decisions made in the repository

I don't understand the purpose behind `AppState` (app.service.ts). Is this intended to store additional state for `AppComponent` (in other words a sort of store what `AppComponent` may need to share) or is it more a generic store for all components of the application?

I am leaning more towards just a shared, non-reactive service to store & share state.

What are the use cases of `AppState`? Storing the currently authenticated user?

**Comment by d3viant0ne** [comment]
Rolling the state back up the tree to a `single source of truth` prevents you from mutating shared state which will have unintended / undesired side effects in your application that are extremely difficult to run down in a large application. In short, you want as many dumb components as is humanly possible.

What Patrick implemented is very similar to `ngrx` in a lot of ways. For instance if you look  [here](https://github.com/AngularClass/angular2-webpack-starter/blob/master/src/app/app.service.ts#L19-L22) this implementation attempts to prevent people from mutating state directly, leading to the issue described above.

Inevitably you will need to maintain state in your application and inevitably you will need your applications components to communicate. Angular2 is designed to flow data / state down and events up. Your lower level components simple take `@Input()` & `@Output()` which makes them reusable and easier to maintain / test. As your application grows, this approach also makes it much easier to reason about your application state given you always know the beginning and end of every state change.
 
As an aside, this implementation is also very simple to convert to use something like `ngrx` should you or your team decide you want to leverage that particular suite of tools.

**Comment by cmckni3** [comment]
Great answer! That's basically what I have been gathering from looking at ngrx.

Thanks!

**Comment by JimTheMan** [comment]
Sorry, but I am still confused. With a reactive store the components can do .subscribe() to update their own state automatically whenever the central state changes. Can you more info on how to do this with the current AppState?

**Comment by katallaxie** [comment]
@JimTheMan don't be confused. It is just a a demo. If you want to have a fully reactive store, and harvest actions, reducers, and effects, then you should use `ngrx`. Which I do in almost all of my projects. I guess some of the things in the current starter do not belong there, or are just really a starter. You could use the `v6` which doesn't include many of these things.

**Comment by JimTheMan** [comment]
Hi @katallaxie! Not sure what you mean about v6. The v6 branch has the same AppState in AppComponent as the master branch. So do you normally just make a new file for store to bring in ngrx/store and then a new file for actionCreators? Will this still work fine with the Hot Module Replacement? Thanks. :)

**Comment by cmckni3** [comment]
I ended up using ngrx in my application and removing `app.service.ts`. `AppState` became an interface for `Store`. Everything after that is typical ngrx usage, such as, `Store`, reducers, etc.

@JimTheMan I used the link [here](https://github.com/AngularClass/angular2-webpack-starter/issues/1003#issuecomment-247558708) to setup HRM with ngrx.

**Comment by JimTheMan** [comment]
Hey thanks @cmckni3 . It's inspiring to know that I can use HRM in Angular 2 with ngrx/store. :) 
However, the issue you linked to just has one answer with a broken link. :/

**Comment by cmckni3** [comment]
@JimTheMan Bummer that the link is broken. I snipped out some code from my application and put it below.

```typescript
import {
  Action,
  ActionReducer,
  combineReducers,
  Store,
  StoreModule
} from '@ngrx/store';
import { compose } from '@ngrx/core/compose';

// AppState is an interface custom to your application
type StoreType = {
  state: AppState,
  restoreInputValues: () => void,
  disposeOldHosts: () => void
};

// Reducer for setting the root STATE for HMR
const stateSetter: ActionReducer<any> = (reducer: ActionReducer<any>) => {
  return (state, action ) => {
    if (action.type === 'SET_ROOT_STATE') {
      return action.payload;
    }
    return reducer(state, action);
  };
};

const rootReducer = compose(stateSetter, combineReducers)({
  // Add your reducers here
});

// ...

export class AppModule {
  constructor(public appRef: ApplicationRef, private _store: Store<any>) {}

  hmrOnInit(store: StoreType) {
    if (!store || !store.state) return;
    console.log('HMR store', JSON.stringify(store, null, 2));

    // set state
    // restore state by dispatch a SET_ROOT_STATE action
    if (store.state) {
      this._store.dispatch(<Action>{ type: 'SET_ROOT_STATE', payload: store.state });
    }

    // set input values
    if ('restoreInputValues' in store) {
      let restoreInputValues = store.restoreInputValues;
      setTimeout(restoreInputValues);
    }

    this.appRef.tick();
    delete store.state;
    delete store.restoreInputValues;
  }

  hmrOnDestroy(store: StoreType) {
    const cmpLocation = this.appRef.components.map(cmp => cmp.location.nativeElement);
    // save state
    this._store.take(1).subscribe(s => store.state = s);

    // recreate root elements
    store.disposeOldHosts = createNewHosts(cmpLocation);

    // save input values
    store.restoreInputValues  = createInputTransfer();

    // remove styles
    removeNgStyles();
  }

  hmrAfterDestroy(store: StoreType) {
    // display new elements
    store.disposeOldHosts();
    delete store.disposeOldHosts;
  }

}
```

**Comment by dereklin** [comment]
@cmckni3 Did you delete app.service.ts? Can you share the code on AppState?

**Comment by cmckni3** [comment]
@dereklin yes, I deleted `app.service.ts` (formerly `app.state.ts`). My setup of @ngrx/store is pretty standard. See [this walkthrough](http://bodiddlie.github.io/ng-2-toh-with-ngrx-suite/)

**Comment by dereklin** [comment]
@cmckni3 Thanks for the walkthrough.  I am putting the ngrx example-app on top of the angular2-webpack-starter.  It looks like the AppState is the State in reducers/index.ts.

**Comment by dereklin** [comment]
It seems like another starter is using the same approach: https://github.com/qdouble/angular-webpack2-starter/blob/master/src/app/app.module.ts

**Comment by dereklin** [comment]
@cmckni3 I think I have set hmr up.  But hmr is not much faster than non-hmr.  What is your experience with hmr?  Here is my repo: https://github.com/dereklin/ng-ws-ngrx-hmr

**Comment by JimTheMan** [comment]
I also ended up going with Ngrx instead of the AppState here (actually, I added ngrx to an Angular CLI project). I haven't added hot module REPLACEMENT yet, still using the regular 'serve' command for hot module RELOADING. I think replacement will still take a second or two to realize you stopped typing and compile the code. It's not so much that you don't have to wait for the browser to flash but more that your state is preserved. The fact that you don't have to navigate through and set up your state again is probably what will save you the most time.

Question for you guys though- with hot module replacement does it only update changes to your state or will it also update changes to local component variables, services, and css?

**Comment by cmckni3** [comment]
@dereklin hmr happens faster than a full build for my large project. Sometimes styles don't work correctly with hmr.

**Comment by dereklin** [comment]
@JimTheMan I haven't fully tested hmr yet.  @cmckni3 I am retrofitting my larger project with hmr.  I am getting some injector error.  I am going to troubleshoot more, but was wondering if you guys know a thing or two about this problem.

![ngrx-hmr](https://cloud.githubusercontent.com/assets/2231799/23186013/58bf3ccc-f83a-11e6-9a90-aeaf64ba39f7.PNG)

**Comment by dereklin** [comment]
@JimTheMan At least on a small project like https://github.com/dereklin/ng-ws-ngrx-hmr, it's working great so far.  I can modify my component, service, css without page reload

**Comment by JimTheMan** [comment]
Thanks dereklin. I need to give it a try myself. So if it works for local components variables is it true that HMR has nothing to do with ngrx/store? I mean I see that the lib is in the "ngrx family", but can I use HMR in a project that doesn't use ngrx/store at all?

**Comment by cmckni3** [comment]
@JimTheMan yes hmr (Hot Module Replacement) reloads your components and styles without a full page reload. It also has some hooks so you can reload the state of the application before hmr was triggered.

Basically, you write your own logic ([example](https://gist.github.com/cmckni3/332627bc8b39d58c3014fda72d6f1c35#file-app-module-ts-L43), [example](https://github.com/AngularClass/angular2-webpack-starter/blob/master/src/app/app.module.ts#L83)) to save your application's state and restore the application's state using the hmr lifecycle methods.

**Comment by JimTheMan** [comment]
I've been searching for an hour, but I can't even find any documentation or how-to guide at all for using HMR... everything I come across seems to be outdated. How did you guys set this up with ngrx??

**Comment by IAMtheIAM** [comment]
Can anyone recommend a good high level overview of when and why and how to use ngRx vs a simple appState implementation such as in this repo? 

As well as a good "How To" use ngRx?
