### ISSUE TITLE
tutorial with api backend for mean stack

### ISSUE THREAD

**Issue by blubberbo** [AngularClass/angular2-webpack-starter#1171]
Hi,

Great tutorial. I was wondering - do you have a similar tutorial that those this type of angular 2, webpack app with an api backend for a MEAN stack app?

**Comment by sdemurjian** [comment]
What I'm currently doing is using a proxy to my server's localhost api endpoint for development and in production serving the minified dist files. I'm actually hoping to open-source my server soon but I need to clean up the code quite a bit and convert it to typescript (it's in ES6 with Babel/Flow).

For development, in `webpack.dev.js` add to the `devServer`:

```
      proxy: {
        '/api/*': 'http://localhost:SERVER_PORT'
      },
```

For production, run the builkd:prod task + start the server. and in production mode on server serve the files. Hope this helps.

**Comment by d3viant0ne** [comment]
@blubberbo - Check the last section of https://github.com/AngularClass/angular2-webpack-starter/wiki/How-to-pass-environment-variables%3F

That wiki page is proxying http calls to an API. All you need is a target for the XHR call & then feed that target into your http requests and if you want to make life easier, create a base class that handles your headers.


```
const API_URL = `${API_BASE_URL}/someRoute`;

@Injectable()
export class SomeService extends RequestBase {

  constructor(
    public http: Http,
  ) { super(http); }

  loadSomethings() {
    return this.http.get(API_URL)
      .map(res => res.json());
  }
}

```

Given a client side application doesn't have the luxury of `process.env.SOMECONST` you will need to define the target in your webpack config at build time per the wiki page above.
