### ISSUE TITLE
rxjs version conflit

### ISSUE THREAD

**Issue by mrsoto** [AngularClass/angular2-webpack-starter#1172]
* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**

The version version 5.1.1 npm install report rxjs version conflicts, angular require 5.0.0-beta.12 
but package reference 5.0.0-rc.2

* **What is the current behavior?**
```
$ npm install

angular2-webpack-starter@5.1.1 /home/mrsoto/Documents/workspace/ng2HelloWorld

├── UNMET PEER DEPENDENCY @angular/common@2.1.1
├── @angular/compiler@2.1.1 
├── UNMET PEER DEPENDENCY @angular/core@2.1.1
...
├── UNMET PEER DEPENDENCY rxjs@5.0.0-rc.1
├── script-ext-html-webpack-plugin@1.3.2 
```

* **What is the expected behavior?**

Clean initial install

**Comment by gdi2290** [comment]
the angular repo is still using the old version of rxjs. I reverted the dep here https://github.com/AngularClass/angular2-webpack-starter/commit/4ba07752e1e8f955a7725e0076425bfc7c65c53c so the warning will be removed
