### ISSUE TITLE
Explain NG symbol in index.html

### ISSUE THREAD

**Issue by Andrey-Pavlov** [AngularClass/angular2-webpack-starter#1173]
Why you changed lang="" to 🆖 in index.html file?

https://github.com/AngularClass/angular2-webpack-starter/commit/a017f882df530ed3e29832695fcba6ce8e8fcb51

**Comment by samvloeberghs** [comment]
it's obviously some kind of joke .. :) change it back to lang if you prefer

**Comment by Andrey-Pavlov** [comment]
Really? The joke in the most popular, complex and complicated Angular2 Starter project?
In my opinion, you should be more serious with this project and code reviews because the project already includes a lot of ambiguous parts, surprises and jokes, no joke.

**Comment by samvloeberghs** [comment]
If you are so serious in your whole life I feel sad for you. Please be grateful for this project instead and applaud the creators, maintainers and everything else around it.

**Comment by gdi2290** [comment]
sorry for the confusion. it's been removed via https://github.com/AngularClass/angular2-webpack-starter/commit/359b4375e40c9521e6bdc7f34d8d38c53a754fb9
