### ISSUE TITLE
webpack.validateSchema is not a function

### ISSUE THREAD

**Issue by cappelleMedia** [AngularClass/angular2-webpack-starter#1174]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[ X ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Report a Bug

* **What is the current behavior?**
'npm start' does not work -> throws a type error (see image)

![image](https://cloud.githubusercontent.com/assets/13681110/20270580/e67c8214-aa87-11e6-9c16-9c4a73ceb7c5.png)

worked fine before but I cleaned node modules and ran npm install agian, after every package was installed I tried to fire it up again but it failed, giving me the error

* **What is the expected behavior?**
Startup of the webpack server

* **What is the motivation / use case for changing the behavior?**

/

* **Please tell us about your environment:**
(just used all files from this repo to make sure it wasn't my code and had the same error)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by cappelleMedia** [comment]
I think it is related to the webpack beta version (i changed all webpack related versions in package.json to an exact version instead of a 'compatible with' and it worked again)

**Comment by AndrewKralovec** [comment]
I get the same thing

**Comment by gdi2290** [comment]
sorry about that. version locked via https://github.com/AngularClass/angular2-webpack-starter/commit/48e4755bed14b2a0fa6f93a416cab014fccf6c9e

**Comment by cappelleMedia** [comment]
@gdi2290 Thanks!
