### ISSUE TITLE
[Bug][V6][Prod] Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by Luchillo** [AngularClass/angular2-webpack-starter#1183]
* **I'm submitting a ...**
[x] bug report

* **Do you want to request a *feature* or report a *bug*?**
I'm reporting a bug that happens when bundling the V6 branch in production with: `npm run build:prod && npm run server:prod`

* **What is the current behavior?**
If i bundle with dev mode, all is ok, but when running with: `npm run build:prod && npm run server:prod` it shows the error: `Uncaught TypeError: Cannot convert undefined or null to object`.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 
1. Clone repo.
2. Switch to `V6` branch.
3. Run `npm i && npm run build:prod && npm run server:prod`.
4. Open `https://localhost:8080` and the error should be in browser console.

* **What is the expected behavior?**
I hope to see the page when open the prod url http://localhost:8080/#/, instead got that error in browser and webpack didn't complain by any errors.

* **Please tell us about your environment:**

  - Angular version: 2.2.0
  - Browser: [all | Chrome 54.0.2840.98 | Safari 10.0.1 ]

* **Other information** 
Chrome stack:
![image](https://cloud.githubusercontent.com/assets/9698639/20398815/dd8857e6-acbc-11e6-8b68-626399a9a350.png)
Safari stack:
![image](https://cloud.githubusercontent.com/assets/9698639/20399076/a2261ca0-acbd-11e6-86c0-fb9f458ce603.png)

**Comment by katallaxie** [comment]
@Luchillo Checkout 2aabdde

**Comment by Luchillo** [comment]
Merged, tested and all OK, thanks for fast solution.

**Comment by Luchillo** [comment]
Btw how long until V6 is ready?
