### ISSUE TITLE
Add more checks to travis build

### ISSUE THREAD

**Issue by Blakko** [AngularClass/angular2-webpack-starter#1192]
* **I'm submitting a ...**
[ ] bug report
[x ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
I think travis should check the following during a PR build:

  - npm run lint

  - npm run test

* **What is the current behavior?**
Apparently they're not executed at the moment

* **What is the motivation / use case for changing the behavior?**
Lately it happens quite a lot that PRs not passing linting/tests are merged into the master, causing lot of troubles

**Comment by ddolzan** [comment]
:+1:

**Comment by d3viant0ne** [comment]
I agree whole heartedly @Blakko - I'll pick this one up as soon as I can figure out what broke but didn't break sourcemaps running karma.
