### ISSUE TITLE
[Bug] [v6] Observable.interval(...).map is not a function

### ISSUE THREAD

**Issue by Luchillo** [AngularClass/angular2-webpack-starter#1196]
* **I'm submitting a ...**
[x] bug report

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
VSCode doesn't complain for the map operator, but browser does with error: `Observable.interval(...).map is not a function`, this is what i import:
```ts
import { Observable } from 'rxjs/Observable';
import "rxjs/add/observable/interval";
import "rxjs/add/operator/map";
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
Try and implement a real time clock with:
```ts
this.clock = Observable
   .interval(1000)
   .map((n: number) => new Date());
```
Which needs the imports above

* **What is the expected behavior?**
To just work without errors.

* **Please tell us about your environment:**

  - Angular version: 2.2.1
  - Browser: [all | Chrome 54]

* **Other information**
It seems it has to do with the DLL's related to Rxjs, as soon as i delete the generated ones and comment the map import in dll's array in `src/dll.ts` it works ok.

**Comment by ranakrunal9** [comment]
I think its related to issue #1155.

**Comment by Luchillo** [comment]
@ranakrunal9 Indeed, however they seem to think the error is in the lack of dll generation, while i see the error in dev builds, i've managed to fix this by commenting the map path in the dll's array and generating again the dlls.

It's like if the import collided because the dlls make them and i do so as well in my code.

**Comment by katallaxie** [comment]
🎱
