### ISSUE TITLE
Postcss In Webpack 2 beta 25

### ISSUE THREAD

**Issue by DanielYKPan** [AngularClass/angular2-webpack-starter#1198]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[X ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
The Wiki page suggestion about how to use postcss seems to not correct in current version webpack-starter( webpack beta 25 ).
So how do i configure postcss?

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by Spittal** [comment]
The recommended way now is to use the postcss common loader syntax. Which is to make a new file called `postcss.config.js` in the root of your project and put all postcss related plugins there.

You can find more info on the [postcss-loader](https://github.com/postcss/postcss-loader) github page.

There are a few caveats, I found this issue quite useful:
https://github.com/postcss/postcss-loader/issues/127

**Comment by DanielYKPan** [comment]
@Spittal I did check the  [postcss-loader](https://github.com/postcss/postcss-loader) github page before, but I put the **postcss.config.js** in the config folder. So that's why it didn't work.

**Comment by Spittal** [comment]
I've updated the Wiki and recommend this ticket to be closed.

**Comment by mikkeldamm** [comment]
I also got the issue, and tried the solution that was specified on the postcss github page, but that didn't work for me.
So did this, that works: 😃 (using strings instead of require, for the plugins)
```
module.exports = {
    plugins: {
        'postcss-cssnext': {
            browsers: ['ie >= 9', 'last 2 versions']
        },
        'postcss-nested': true,
        'postcss-mixins': true
    }
}
```
