### ISSUE TITLE
How to cope with the cross-domain request?

### ISSUE THREAD

**Issue by mlyknown** [AngularClass/angular2-webpack-starter#1203]
Is there any configuration of the place?

**Comment by tieppt** [comment]
i think this is problem of server-side, you need change server-side to allow request from some/all sites.

**Comment by d3viant0ne** [comment]
@mlyknown - Are you talking about `CORS` ?

If so, your question has more to do with how you are hosting and less about code. To give you any kind of semi-specific answer, I'd need to know how you are hosting / running your application.

**Comment by mlyknown** [comment]
@tieppt @d3viant0ne   Yes,it's CORS.I want to send a cross-domain request.Is there a place to configure the proxy?Like [this](https://vuejs-templates.github.io/webpack/proxy.html)

**Comment by mlyknown** [comment]
Running application just use "npm run server:dev:hmr".......................

**Comment by d3viant0ne** [comment]
@mlyknown - This [wiki article](https://github.com/AngularClass/angular2-webpack-starter/wiki/How-to-pass-environment-variables%3F) outlines how to pass an env. variable to enable calling an external api.

As for dealing with `cors errors` specifically, that would require the use of something like `nginx` proxying calls to a back end which as @tieppt stated requires proper configuration to accept calls from the origin of the client. In this case, your local environment.

**Comment by mlyknown** [comment]
thanks!!
