### ISSUE TITLE
Add autoprefixer for css and sass

### ISSUE THREAD

**Issue by aaronbalthaser** [AngularClass/angular2-webpack-starter#1204]
I tried to add autoprefixer but was not able to get it to work. When I initially installed the autoprefixer package I discovered it was depreciated and was instructed to use postcss instead. I followed the directions seen in the link below:

https://github.com/postcss/postcss-loader

In the webpack.common.js file I tried to add the loader to the arrays used for css and sass:

`loaders: ['raw-loader', 'postcss-loader', 'sass-loader']`
`loaders: ['to-string-loader', 'css-loader', 'postcss-loader']`

This unfortunately did not work. I am not sure if this was enough to get the package to work.

**Comment by mikkeldamm** [comment]
Can you provide the error you get?

**Comment by katallaxie** [comment]
Duplicate https://github.com/AngularClass/angular2-webpack-starter/issues/644. Have a look in the Wiki.
