### ISSUE TITLE
error running Quick start script results in error 

### ISSUE THREAD

**Issue by Geraldf** [AngularClass/angular2-webpack-starter#1211]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[X ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

Hi Running the script you have posted on github 

   ```
 # clone our repo
    # --depth 1 removes all but one .git commit history
    git clone --depth 1 https://github.com/angularclass/angular2-webpack-starter.git

   # change directory to our repo
   cd angular2-webpack-starter

   # install the repo with npm
   npm install

    # start the server
   npm start
```

results on

**ERROR in (webpack)-dev-server/client?http://localhost:3000
Module not found: Error: Can't resolve 'strip-ansi' in '/Users/geraldfuchs/CloudStation/Projects/l2/client/angular2-webpack-starter/node_modules/webpack-dev-server/client'
 @ (webpack)-dev-server/client?http://localhost:3000 3:16-37
 @ multi polyfills

ERROR in (webpack)-dev-server/client/socket.js
Module not found: Error: Can't resolve 'sockjs-client' in '/Users/geraldfuchs/CloudStation/Projects/l2/client/angular2-webpack-starter/node_modules/webpack-dev-server/client'
 @ (webpack)-dev-server/client/socket.js 1:13-37
 @ (webpack)-dev-server/client?http://localhost:3000
 @ multi polyfills
Child html-webpack-plugin for "index.html":**

**Comment by Geraldf** [comment]
Resolved by upgrading nom to version 4.0.2

**Comment by vance** [comment]
guessing you meant NPM...

**Comment by vance** [comment]
NM, had to remove all the deps and re-install.
