### ISSUE TITLE
Can't work according to the wiki.

### ISSUE THREAD

**Issue by mlyknown** [AngularClass/angular2-webpack-starter#1223]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[ ] bug report
* **What is the current behavior?**
The console error:
ERROR in ./~/.npminstall/css-loader/0.26.0/css-loader!./~/.npminstall/postcss-l
ader/1.1.1/postcss-loader!./~/.npminstall/resolve-url-loader/1.6.0/resolve-url-
oader!./~/.npminstall/sass-loader/4.0.2/sass-loader!./src/app/pages/indication/
ndication.scss
Module build failed: TypeError: Cannot read property 'path' of undefined
    at Object.resolveUrlLoader (D:\MyProject\mpj\mkitchen\node_modules\.npminst
ll\resolve-url-loader\1.6.0\resolve-url-loader\index.js:38:55)
 @ ./src/app/pages/indication/indication.scss 2:21-382
 @ ./src/app/pages/indication/bindDevice.ts
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.browser.ts
 @ multi main

* **Please tell us about your environment:**

system:windows10
npm:v3.9.5
node:v6.2.2

webpack.common.js
        {
          test: /\.css$/,
          loaders: ['to-string-loader', 'css-loader', 'postcss-loader']
        },
        {
          test: /\.(sass|scss)$/,
          loaders: ['to-string-loader', 'css-loader', 'postcss-loader', 'resolve-url-loader', 'sass-loader']
        },
        {
          test: /\.styl$/,
          loaders: ['to-string-loader', 'css-loader', 'postcss-loader', 'resolve-url-loader', 'stylus-loader']
        },

postcss.config.js
module.exports =  {
  plugins: [
    require('postcss-smart-import')(),
    require('postcss-cssnext')(),
    require('postcss-apply')(),
    require('postcss-responsive-type')(),
    require('autoprefixer')({ /* ...options */ })
  ]
};

**Comment by mlyknown** [comment]
[wiki](https://github.com/AngularClass/angular2-webpack-starter/wiki/How-to-include-PostCSS)

**Comment by katallaxie** [comment]
@mlyknown 🥇
