### ISSUE TITLE
How to deploy /dist folder to apache web server

### ISSUE THREAD

**Issue by baudo2048** [AngularClass/angular2-webpack-starter#1225]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[x] Need a How-To

* **What is the current behavior?**
I've cloned angular2-webpack-starter repository and runned the following commands:

`npm install`
`npm run build:prod`

Everything seems ok but when I copy generated /dist folder inside the root of my apache web server and open the app from my web browser at localhost (http://localhost/dist/index.html) nothing appear on the screen except

`Loading...`

In the browser console there is any message.
From debugger window of my web browser developer tool I can see files that are actually download (i.e. index.html + linked resources). Only two files are downloaded: index.html and analytics.js; that is a little bit strange.

Instead, if I run the following commands:

`npm run server`

and open my browser at http://0.0.0.0:3000 it works fine.

* **What is the expected behavior?**
To deploy app simply by copy and paste /dist folder to web server public/root folder.

* **Please tell us about your environment:**
- linux mint
- apache web server

**Comment by baudo2048** [comment]
ok I got it!!!
just to know, I've modified the port number at line 26 of https://github.com/AngularClass/angular2-webpack-starter/blob/master/config/webpack.prod.js 
from
` line26: const PORT = process.env.PORT || 8080;`
to
`line26: const PORT = process.env.PORT || 80;`

After that I've build with
`npm run build:prod`

and copied and paste /dist folder to the root of my apache web server.

It works.

**Comment by d3viant0ne** [comment]
If this question is not longer an issue, can you please close it @baudo2048
