### ISSUE TITLE
Error: ⨯ Unable to compile TypeScript

### ISSUE THREAD

**Issue by abhissha** [AngularClass/angular2-webpack-starter#1253]
I'm submitting a ...**
[x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
I just got fresh copy of "angular2-webpack-starter" and trying to "npm run e2e" and getting this error. I searched for the issue in the issues and found it was previously reported and there were changes made, but it still seems to be occuring.

* **What is the current behavior?**
Below is the error
[12:49:59] I/direct - Using ChromeDriver directly...
[12:49:59] I/launcher - Running 1 instances of WebDriver
[12:50:06] E/launcher - Error: ⨯ Unable to compile TypeScript
Cannot find type definition file for 'hammerjs'. (2688)
Cannot find type definition file for 'jasmine'. (2688)
Cannot find type definition file for 'node'. (2688)
Cannot find type definition file for 'selenium-webdriver'. (2688)
Cannot find type definition file for 'source-map'. (2688)
Cannot find type definition file for 'uglify-js'. (2688)
Cannot find type definition file for 'webpack'. (2688)
src\app\app.e2e.ts (3,1): Cannot find name 'describe'. (2304)
src\app\app.e2e.ts (5,3): Cannot find name 'beforeEach'. (2304)
src\app\app.e2e.ts (10,3): Cannot find name 'it'. (2304)
src\app\app.e2e.ts (13,5): Cannot find name 'expect'. (2304)
[12:50:06] E/launcher - Process exited with error code 100

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 
Download the latest angular2-webpack-starter and run the command "run npm e2e". I had the server running.

* **Please tell us about your environment:**
- Angular version: version defined in the package.json when I downloaded the webpack starter today.
- Browser: [Chrome ]

**Comment by karolmie1** [comment]
Hi!
Did you download node_modules packages first?
You can do it by issuing command: npm install, but I recommend instead to install yarn on your computer
npm install -g yarn, and then yarn (same thing as npm install but way faster).

Also please remember that to run e2e tests you have to have application running in another terminal, so you need 2 terminals for that.

**Comment by abhissha** [comment]
This issue can be closed. This issue was related with issue earlier reported #1249 . I had uncommented new ForkCheckerPlugin() in webpack.common.js, which was recommended by the user with previously same issue. After I used the resolution from issue #1249, this issue no longer appears.
