### ISSUE TITLE
How to add a new package after installing.

### ISSUE THREAD

**Issue by utd1878** [AngularClass/angular2-webpack-starter#1257]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
In the Wiki Page, it directs me here to submit a request for a new page.  Not sure which one this falls under.
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**

Request a new wiki page be written

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

I've started using the angular2-webpack-starter app.  After using a bit, I wanted to install another package.  I run the npm install -g <package> command and that's about as far as I get.  I'm not sure where I need to go to ensure my app recognizes this new package.  For the novices out there, it would be good to understand how to get webpack/angular2 to recognize any new packages that were install.

I've search high and low for an example on this but apparently I'm not asking the right question, or I'm just not understanding the differences in how webpack and native angular 2 are setup.  Having a writeup explaining the differences and examples on how to properly wire up a new package would be great.

not sure it matters, but the specific package was ng2-nouislider 

* **Please tell us about your environment:**
Latest Angular,
All browsers
Mac
node and npm
- Angular version: 2.0.0-beta.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by katallaxie** [comment]
`-g` on npm installs the deps in the global space. Your have to call it without, and decide to have it as dev `-D` or prod `-S` dependency.
