### ISSUE TITLE
why use arguments object?

### ISSUE THREAD

**Issue by keith-pinto** [AngularClass/angular2-webpack-starter#1259]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Requesting to raise a pull request.
It may be a minor patch; but wanted to confirm before doing so.

The following line uses [arguments](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Functions/arguments) object rather than using `args` variable passed to the respective function `root`. Is there a specific reason for doing so, or is this redundant?

https://github.com/AngularClass/angular2-webpack-starter/blob/master/config/helpers.js#L18

``` javascript
function root(args) {
  args = Array.prototype.slice.call(arguments, 0);
  return path.join.apply(path, [ROOT].concat(args));
}
```

P.S. Thanks for building this starter project!

**Comment by aluanhaddad** [comment]
I believe the reason was to facilitate compatibility with older versions of NodeJS, this matters because it isn't being transpiled by TypeScript.

That said, the code style is abysmal. Assigning to a parameter is a terrible practice and also completely unnecessary.

**Comment by colinskow** [comment]
It works, but not good coding. If somebody can re-write this in a better way that works with Node 5 then go for it!
