### ISSUE TITLE
Where's materials branch mentioned in readme file?

### ISSUE THREAD

**Issue by holms** [AngularClass/angular2-webpack-starter#1261]
I expect to see materials branch which is promised in readme file. Where is it..? I mean guys can you please insure that this would be a starter, not a confusion pack..? There's tons of stress to make this work. Also as your AngularClass contains completely different code from presented here. There's no way to learn Angular faster then just to go completely from scratch, because everything is messed up.

**Comment by romelgomez** [comment]
It was deleted https://github.com/AngularClass/angular2-webpack-starter/issues/1199 , To add material see this gist: https://gist.github.com/romelgomez/106625de08bbf68a2ca2b5c8aa93dcc8

**Comment by holms** [comment]
@romelgomez  thank you this is incredible nice development.. through gist.. :)

**Comment by holms** [comment]
@romelgomez 

And results i've got is this:

```
./src/app/app.module.ts
Module not found: Error: Can't resolve 'hammerjs' in '/frontend/src/app'
 @ ./src/app/app.module.ts 9:0-19
 @ ./src/app/index.ts
 @ ./src/main.browser.ts
 @ multi main webpack-dev-server.js:3:8855

./src/app/app.component.ts
Module not found: Error: Can't resolve './app.component.scss' in '/frontend/src/app'
 @ ./src/app/app.component.ts 26:16-47
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.browser.ts
 @ multi main
```

I have no idea what i'm doing in here anymore, this is not a starter, it's bullshit which complicates life more than anything else i've tried in my life.. I'm moving to react.js

**Comment by boldtrn** [comment]
@romelgomez Thanks, that worked. Could we add the gist to the wiki and link to the wiki entry instead of linking a branch that does not exist anymore? Would be convenient for new users.

**Comment by romelgomez** [comment]
@boldtrn sure, here is the wiki, https://github.com/AngularClass/angular2-webpack-starter/wiki/How-to-include-Material
