### ISSUE TITLE
Nitrous is no longer available as a service but referenced in the README

### ISSUE THREAD

**Issue by bdougie** [AngularClass/angular2-webpack-starter#1265]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[x] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
[Nitrous](https://www.nitrous.io/) is no longer available as a service but referenced in the README

* **What is the expected behavior?**
It should probably be removed from the README. Cloud9 is an alternative, I am not sure if there is a quickstart link similar to Nitrous though. 

```
// note on their website

We will be discontinuing the Nitrous Development Platform and Cloud IDE on November 14th, 2016. 

If you have an active workstation, we will email you a link that allows you to download a backup of your data. You will have 15 days to download your data before it is deleted. If you didn't receive this email, please send us an email at support@nitrous.io and we will do our best to help. Payments made after October 16, 2016 will be refunded in full.

In the coming weeks, we will be releasing a self-hosted & open-source version of the Nitrous IDE called Nitrous Solo that will be available for free. Nitrous Solo lets you host your own instance of the Nitrous IDE on your preferred cloud provider.

Your subscription on any Nitrous email list will expire on November 30, 2016. If you would like to receive updates after November 30 about any of our open source initiatives, please click on the following button:
```

**Comment by seiyria** [comment]
This can probably be closed now that #1266 has been merged.
