### ISSUE TITLE
Missing comments on the wiki topic "How to include jQuery"

### ISSUE THREAD

**Issue by zeitlupe** [AngularClass/angular2-webpack-starter#1267]
I´d like to add some missing sentences in the wiki topic "How to include jQuery":

1.) Use the following import to include JQuery: import * as jQuery from 'jquery';
2.) Put the ProvidePlugin into the file webpack.common.js

This is a generally thing in my opinion: The 2 sentences are understandable clear to everone who is "into it". But for me it took some "time`n google" to find it out.

**Comment by katallaxie** [comment]
Please, create a [PR](https://help.github.com/articles/creating-a-pull-request/) with your desired changes.
