### ISSUE TITLE
Loader process dead after upgrade to "typescript": "2.1.1"

### ISSUE THREAD

**Issue by vincent-cm** [AngularClass/angular2-webpack-starter#1272]
bug report
report a *bug* After typescript 2.0.6 the build process stuck at loading js. No debug error happens but seems infinite burning CPU.

Stuck point: 

Project is running at http://localhost:8888/
webpack output is served from /
Content not from webpack is served from xxxxxxxx
404s will fallback to /index.html                                                                                                67% building modules 1165/1226 modules 61 active ...

No debug log and nothing different to verbose mode.
I also switch between node from 7.2.1 to 6.9.2 nothing changed.
The stuck point is building a module that if I remove that module it stuck to another one. so something general must be wrong during the module js file loading.

Solution is to fix the typescript version to 2.0.6 instead of ^2.0.6

Here are the packages I used:

`{
  "name": "",
  "version": "0.0.25",
  "description": "",
  "keywords": [
    "angular2",
    "webpack",
    "typescript"
  ],
  "author": "",
  "homepage": "",
  "license": "MIT",
  "scripts": {
    "build:dev": "webpack --config config/webpack.dev.js --progress --profile",
    "build:docker": "npm run build:prod && docker build -t angular2-webpack-start:latest .",
    "build:prod": "webpack --config config/webpack.prod.js  --progress --profile --bail",
    "build": "npm run build:dev",
    "ci": "npm run lint && npm test && npm run e2e",
    "clean:dist": "npm run rimraf -- dist",
    "clean:install": "npm set progress=false && npm install",
    "clean:start": "npm start",
    "clean": "npm cache clean && npm run rimraf -- node_modules doc coverage dist",
    "docker": "docker",
    "docs": "npm run typedoc -- --options typedoc.json --exclude '**/*.spec.ts' ./src/",
    "e2e:live": "npm run e2e -- --elementExplorer",
    "e2e": "npm run protractor",
    "github-deploy:dev": "webpack --config config/webpack.github-deploy.js --progress --profile --env.githubDev",
    "github-deploy:prod": "webpack --config config/webpack.github-deploy.js --progress --profile --env.githubProd",
    "github-deploy": "npm run github-deploy:dev",
    "lint": "npm run tslint \"src/**/*.ts\"",
    "postversion": "git push && git push --tags",
    "prebuild:dev": "npm run clean:dist",
    "prebuild:prod": "npm run clean:dist",
    "preclean:install": "npm run clean",
    "preclean:start": "npm run clean",
    "pree2e": "npm run webdriver:update -- --standalone",
    "preversion": "npm test",
    "protractor": "protractor",
    "rimraf": "rimraf",
    "server:dev:hmr": "npm run server:dev -- --inline --hot",
    "server:dev": "webpack-dev-server --config config/webpack.dev.js --progress --profile --watch --content-base src/",
    "server:prod": "http-server dist --cors",
    "server:prod:ci": "http-server dist -p 3000 --cors",
    "server": "npm run server:dev",
    "start:hmr": "npm run server:dev:hmr",
    "start": "npm run server:dev",
    "test": "karma start",
    "tslint": "tslint",
    "typedoc": "typedoc",
    "version": "npm run build",
    "watch:dev:hmr": "npm run watch:dev -- --hot",
    "watch:dev": "npm run build:dev -- --watch",
    "watch:prod": "npm run build:prod -- --watch",
    "watch:test": "npm run test -- --auto-watch --no-single-run",
    "watch": "npm run watch:dev",
    "webdriver-manager": "webdriver-manager",
    "webdriver:start": "npm run webdriver-manager start",
    "webdriver:update": "npm run webdriver-manager update",
    "webpack-dev-server": "webpack-dev-server",
    "webpack": "webpack"
  },
  "dependencies": {
    "@angular/common": "2.2.1",
    "@angular/compiler": "2.2.1",
    "@angular/core": "2.2.1",
    "@angular/forms": "2.2.1",
    "@angular/http": "2.2.1",
    "@angular/platform-browser": "2.2.1",
    "@angular/platform-browser-dynamic": "2.2.1",
    "@angular/platform-server": "2.2.1",
    "@angular/router": "3.2.1",
    "@angularclass/conventions-loader": "^1.0.2",
    "@angularclass/hmr": "~1.2.2",
    "@angularclass/hmr-loader": "~3.0.2",
    "angular2-cookie": "^1.2.5",
    "angular2-ui-switch": "^1.2.0",
    "assets-webpack-plugin": "^3.4.0",
    "core-js": "^2.4.1",
    "http-server": "^0.9.0",
    "ie-shim": "^0.1.0",
    "jquery": "1.12.4",
    "lodash": "^4.17.2",
    "ng2-data-table": "^0.6.1",
    "ng2-dnd": "^2.0.1",
    "ng2-page-scroll": "^4.0.0-beta.1",
    "ng2-slimscroll": "^1.2.0",
    "ng2-translate": "^4.2.0",
    "primeng": "^1.0.1",
    "rxjs": "5.0.0-beta.12",
    "swagger-client": "^2.1.26",
    "underscore": "^1.8.3",
    "zone.js": "~0.6.26"
  },
  "devDependencies": {
    "@types/hammerjs": "^2.0.33",
    "@types/jasmine": "^2.2.34",
    "@types/node": "^6.0.38",
    "@types/selenium-webdriver": "2.53.33",
    "@types/source-map": "^0.1.27",
    "@types/uglify-js": "^2.0.27",
    "@types/webpack": "^1.12.34",
    "angular-router-loader": "^0.4.0",
    "angular2-template-loader": "^0.6.0",
    "awesome-typescript-loader": "^2.2.1",
    "codelyzer": "~1.0.0-beta.4",
    "copy-webpack-plugin": "^4.0.0",
    "css-loader": "^0.26.0",
    "exports-loader": "^0.6.3",
    "expose-loader": "^0.7.1",
    "file-loader": "^0.9.0",
    "gh-pages": "^0.12.0",
    "html-webpack-plugin": "^2.21.0",
    "imports-loader": "^0.6.5",
    "istanbul-instrumenter-loader": "0.2.0",
    "json-loader": "^0.5.4",
    "karma": "^1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-coverage": "^1.1.1",
    "karma-jasmine": "^1.0.2",
    "karma-mocha-reporter": "^2.0.0",
    "karma-remap-coverage": "^0.1.1",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-webpack": "1.8.0",
    "parse5": "^2.2.2",
    "protractor": "^4.0.10",
    "raw-loader": "0.5.1",
    "rimraf": "~2.5.4",
    "script-ext-html-webpack-plugin": "^1.3.2",
    "source-map-loader": "^0.1.5",
    "string-replace-loader": "1.0.5",
    "style-loader": "^0.13.1",
    "to-string-loader": "^1.1.4",
    "ts-helpers": "1.1.2",
    "ts-node": "^1.7.0",
    "tslint": "~3.15.1",
    "tslint-loader": "^2.1.5",
    "typedoc": "^0.5.0",
    "typescript": "2.0.6",
    "url-loader": "^0.5.7",
    "v8-lazy-parse-webpack-plugin": "^0.3.0",
    "webpack": "2.1.0-beta.27",
    "webpack-dev-middleware": "^1.6.1",
    "webpack-dev-server": "2.1.0-beta.11",
    "webpack-md5-hash": "^0.0.5",
    "webpack-merge": "~1.0.1",
    "sass-loader": "^4.0.2",
    "node-sass": "^3.4.2"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/angularclass/angular2-webpack-starter.git"
  },
  "bugs": {
    "url": "https://github.com/angularclass/angular2-webpack-starter/issues"
  },
  "engines": {
    "node": ">= 4.2.1",
    "npm": ">= 3"
  }
}
`

**Comment by gdi2290** [comment]
angular2 doesn't support typescript 2.1.x until angular4

**Comment by vincent-cm** [comment]
what angular4 mean? Since this project (#1252) has recently upgraded to typescript 2.1.1 so it seems support angular2 as well.

**Comment by aparraga** [comment]
lo has entendido! LOL
