### ISSUE TITLE
It confused me that "npm run test" didn't run the e2e tests.

### ISSUE THREAD

**Issue by dickon** [AngularClass/angular2-webpack-starter#1277]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**

You read through the README as far "Run tests", try it and then assume that's run all the tests. So I went to add a failing e2e test and then was briefly surprised and confused that the test code had all passed.

* **What is the expected behavior?**

It may be better to say "Run unit tests" so that people read on and see how to run the e2e tests. It may also be worth a few words on why the e2e/protractor tests are handled differently from the unit tests.

* **What is the motivation / use case for changing the behavior?**

Okay, this is trivial, but it would have saved me a few minutes confusion.

* **Please tell us about your environment:**

Windows 10, and I simply cloned angular2-webpack-starter and started experimenting.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

I can submit a pull request if you agree this is worth addressing (in a couple of weeks after the holiday season)

**Comment by d3viant0ne** [comment]
@dickon - `npm run test` is intended to just run the karma suite.

For the e2e tests, you need to run some sort of server for Protractor to execute against. In a CI environment, that requires additional commands prior to the execution of the e2e tests.

The same is applicable for running the test watcher during active development, where you normally don't want to be running an e2e suite which can involve other services to be running in most data driven applications.

The validations are split intentionally which is both the community standard way to handle testing and the most flexible as well as, imo having the best overall development experience.

If you want to change how the tests execute in your own application, you are of course free to do so but I am betting after some time working with it that way you will find it to be more cumbersome than beneficial.
