### ISSUE TITLE
Why # in the URL still? 

### ISSUE THREAD

**Issue by GenZodd** [AngularClass/angular2-webpack-starter#1287]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[X ] question about the decisions made in the repository

Still trying to wrap my head around some of this but this was the first start I have seen where the solution still uses # in the URL. Is there a reason that still has to be used? One of the nice things about Angular2 is that we no longer had to deal with # in the URL. Seems there are other features we can't use with this version like moduleId so just wondering if this is another one that can't be used.

**Comment by katallaxie** [comment]
Just change the `LocationStrategy` to [PathLocationStrategy](https://angular.io/docs/ts/latest/api/common/index/PathLocationStrategy-class.html). You can use `moduleId` see here: [Component Relative Paths](https://angular.io/docs/ts/latest/cookbook/component-relative-paths.html).

**Comment by GenZodd** [comment]
Cool. Thanks for the quick response. That helped educate me.
