### ISSUE TITLE
I m geting error on while making dist of the project

### ISSUE THREAD

**Issue by anandangular** [AngularClass/angular2-webpack-starter#1289]
npm ERR! Linux 4.4.0-53-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build:prod"
npm ERR! node v6.9.1
npm ERR! npm  v4.0.2

npm ERR! missing script: build:prod
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/lampp/htdocs/angular/angular2-webpack-master (copy)/npm-debug.

**Comment by glendaviesnz** [comment]
Did you run:

npm run build:prod

and does the following line appear in the scripts section of your package.json file?
 "build:prod": "npm run clean:dist && webpack --config config/webpack.prod.js  --progress --profile --bail",

**Comment by d3viant0ne** [comment]
No, he didn't
