### ISSUE TITLE
TypeScript 2.1 async / await throws reference error exception (es5 target)

### ISSUE THREAD

**Issue by WillooWisp** [AngularClass/angular2-webpack-starter#1294]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
Using async / await in current setup throws exception where __generator is not defined on  ZoneAwarePromise (polyfills.bundle.js).

* **What is the motivation / use case for changing the behavior?**
Being able to use async / await with latest TypeScript 2.1 and es5.

* **Please tell us about your environment:**

- Angular version: 2.2.1
- Browser: Chrome

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by d3viant0ne** [comment]
TypeScript isn't supported by Angular 2.x. You will have to wait until Angular 4.x

**Comment by WillooWisp** [comment]
Can you explain what you mean with "TypeScript isn't supported by Angular 2.x"? TypeScript is the preferred language when writing Angular 2 apps. Since the async / await is compiled to es5 JavaScript code with the use of a polyfill containing a correctly implemented Promise it should work, or at least I thought so.

Please explain why Angular 2 is a specific problem for this scenario, compared to Angular 4, since it feels like I am missing something here.

Thanks!

**Comment by d3viant0ne** [comment]
http://lmgtfy.com/?q=angular+with+typescript+2.1.4

**Comment by WillooWisp** [comment]
Can't see any real info about that it should not work, only some specific cases. I do use TypeScript 2.1.4 together with Angular 2.2.4 and it works great. The problem is the zone promise class being used and cannot be switched out. That promise does not work in conjunction with async / await.

**Comment by d3viant0ne** [comment]
There are other threads around that topic as well. The general consensus is it's not supported and won't be for a while. If you choose to push past what is in Angular's package.json you are in uncharted waters.

Async/Await is a cool feature and i'm sure i'll be leveraging it in another 6 months when it has robust support. You could create an issue over at Angular but i'm all but positive they are going to tell you the same thing.
