### ISSUE TITLE
AOT with @angular/material

### ISSUE THREAD

**Issue by shlomiassaf** [AngularClass/angular2-webpack-starter#1301]
Trying to use the new AOT I get a weird behaviour with `@angular/material`

The error says:
```
main.bundle.js:1139 Uncaught TypeError: Cannot read property 'forRoot' of undefined
```

Basically the `MaterialModule` is undefined so calling `MaterialModule.forRoot()` causes the error.

My imports are as usual:
```
import { NgModule, ApplicationRef } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { ReactiveFormsModule } from '@angular/forms';
import { HttpModule, Http } from '@angular/http';
import { RouterModule } from '@angular/router';
import { MaterialModule } from '@angular/material';
```

Looking at the generated code shows something interesting:
```
                __WEBPACK_IMPORTED_MODULE_1__angular_platform_browser__["c" /* BrowserModule */],
                __WEBPACK_IMPORTED_MODULE_2__angular_forms__["a" /* ReactiveFormsModule */],
                __WEBPACK_IMPORTED_MODULE_3__angular_http__["a" /* HttpModule */],
                __WEBPACK_IMPORTED_MODULE_4__angular_router__["a" /* RouterModule */].forRoot(__WEBPACK_IMPORTED_MODULE_17__app_root_routes__["a" /* ROUTES */], { useHash: true }),
                __WEBPACK_IMPORTED_MODULE_6__angular_material__["MaterialModule"].forRoot(),
```

Material is the only module that is left intact.

I'm not using AOT compilation, just running `npm run start`
Any ideas?

**Comment by shlomiassaf** [comment]
Looks like the Material got some of the objects set, some undefined.

![image](https://cloud.githubusercontent.com/assets/5377501/21501723/f80c2de4-cc52-11e6-8466-a5827b4cf5b4.png)

Has a strong tree shaking smell :)

Something cut the webpack process in the middle, maybe cyclic deps?

**Comment by shlomiassaf** [comment]
Update:
Removing the `CommonsChunkPlugin` for `vendor` didn't help, still same result...

**Comment by shlomiassaf** [comment]
Ok, getting closer...

`import { MaterialModule } from '@angular/material/module';`

Works...

the material exports?

**Comment by shlomiassaf** [comment]
Ok, more clues...

This is the material `index.js` file:
```
export * from './core';
export * from './module';
export * from './button/index';
export * from './button-toggle/index';
// ... more
```

this is the `@angular/core` index file:
```
export { NgLocalization, CommonModule, NgClass, NgFor, NgIf, NgPlural, NgPluralCase, NgStyle, NgSwitch, NgSwitchCase, NgSwitchDefault, NgTemplateOutlet, AsyncPipe, DatePipe, I18nPluralPipe, I18nSelectPipe, JsonPipe, LowerCasePipe, CurrencyPipe, DecimalPipe, PercentPipe, SlicePipe, UpperCasePipe, VERSION, Version, PlatformLocation, LocationStrategy, APP_BASE_HREF, HashLocationStrategy, PathLocationStrategy, Location } from './src/common';
```

It looks like the setup can't handle **wildcard exports**

Changing the `index.js` file of `@angular/material` to:
```
export { MaterialModule, MaterialRootModule } from './module';
```
(using only the module....)  

###Everything works! Property names minified as well.


Here's an interesting point:
Changing only the material module line to export specific:
```
export * from './core';
export { MaterialModule, MaterialRootModule } from './module';
export * from './button/index';
export * from './button-toggle/index';
/// ... more
```
Works (for MaterialModule only) but the property names are no minified!

**Comment by d3viant0ne** [comment]
This is a problem with the Material / Webpack, not the seed or configuration

https://github.com/angular/material2/issues/2401
