### ISSUE TITLE
Integrating lodash

### ISSUE THREAD

**Issue by brud** [AngularClass/angular2-webpack-starter#1302]
`npm i @types/lodash --save-dev`
`npm i lodash --save`

when i import lodash in my code
`import * as _ from "lodash";`

`_` is empty - what i'm doing wrong?

**Comment by jindalrohit** [comment]
I am also getting the same issue

**Comment by markpritchett** [comment]
This works for me.  The only thing I did differently was install them in the opposite order:

```
npm install lodash --save
```

then

```
npm install @types/lodash --save-dev
```

After that I just modified **src/app/home/home.component.ts** by adding:

``` typescript
import * as _ from 'lodash';
```

and use it:

``` typescript
ngOnInit() {
    console.log('hello `Home` component');
    console.log(_.uniq(['A', 'B', 'A']));
}
```

**Comment by katallaxie** [comment]
@brud make it explicit and include the @types in `tsconfig.json`. Also, try to delete caches e.g. `.awcache`. Are there any errors?! Which versions are you using?!

**Comment by jindalrohit** [comment]
@markpritchett  - Thank you. It's working now.

**Comment by katallaxie** [comment]
@markpritchett 🥇
