### ISSUE TITLE
Crippling const enum bug discovered in awesome-typescript-loader

### ISSUE THREAD

**Issue by ZenSoftware** [AngularClass/angular2-webpack-starter#1305]
* **I'm submitting a ...**
[X] bug report
[X] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
This is both a bug submission and a feature request as a solution.

* **What is the current behavior?**
awesome-typescript-loader incorrectly transpiles **const enum**

* **What is the expected behavior?**
awesome-typescript-loader should transpile **const enum** by replacing the variable name, with its respective representative integer.

* **What is the motivation / use case for changing the behavior?**
Please refer to the GitHub issue: [Const enum are preserved and not replaced with actual values #137](https://github.com/s-panferov/awesome-typescript-loader/issues/137)

We are concerned about how many projects in the wild that are being transpiled incorrectly because of this bug.  This issue has been standing in their repository for months without being addressed.  We are making a feature request to consider [ts-loader](https://github.com/TypeStrong/ts-loader) as the choice of loader for the starter kit, as it correctly transpiles **const enum**

[ts-loader](https://github.com/TypeStrong/ts-loader) loader seems to adhere to typescript standard better, and is more responsive to crippling bugs.  We should consider this seriously.

**Comment by katallaxie** [comment]
This cannot be replicated with the starter. Using examples from [Enums](https://www.typescriptlang.org/docs/handbook/enums.html) produces expected results.

**Comment by ZenSoftware** [comment]
It is fine that this is closed.  I thought you should be warned that this behavior does exist for some particular configurations.  Which configurations... who knows. ^_^  Cheers my friend @katallaxie

**Comment by gdi2290** [comment]
it would be great if someone can reproduce the error otherwise it's just an awesome-ts side-effect that we can't account for and ts-loader is too slow
