### ISSUE TITLE
AoT error: Calling function 'RouterModule', function calls are not supported

### ISSUE THREAD

**Issue by Phmager** [AngularClass/angular2-webpack-starter#1316]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**
Running npm run build:aot nothing is compiled. And this command throws an error:
"./node_modules/.bin/ngc" -p tsconfig.webpack.json
Error: Error encountered resolving symbol values statically. Calling function 'RouterModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol DetailModule in ./src/app/+detail/index.ts.

I don't understand, why the RouterModule is seen as a function. I copied and pasted it exactly like in the repository. I used yarn to lock the correct version of angular 2.4.1 and router 3.4.1, used TypeScript 2.0.10. When I remove the RouterModule.forChild(...) the compilation gets further.

When I just use the repository it works correctly.

**Comment by shlomiassaf** [comment]
@Phmager I don't understand your description.

The repository works but you make some changes that does not.

Please provide some code sample...

I think it's a support issue or something.

Note that you cant use lambda function (or non exported symbols) where a symbol is needed (by the compiler)

For example a factory provider can't use a lambda function, it must use a function that was **exported**

```ts
export function httpFactory(backend: XHRBackend, defaultOptions: RequestOptions, globalService: GlobalService) {
  return  new HttpLoading(backend, defaultOptions, globalService);
}

providers: [
        GlobalService,
        {
            provide: Http,
            useFactory:  httpFactory,
            deps: [XHRBackend, RequestOptions, GlobalService]
        }
    ],
```

**Comment by Phmager** [comment]
You are right, it is a support issue. When I clone the repository it is working. When I apply the AOT commit to my own repository I get that error:
Error: Error encountered resolving symbol values statically. Calling function 'RouterModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol DetailModule in ./src/app/+detail/index.ts.

index.ts:
``` JavaScript
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { NgModule } from '@angular/core';
import { RouterModule } from '@angular/router';

import { DetailComponent } from './detail.component';

console.log('Detail bundle loaded asynchronously');
// async components must be named routes for WebpackAsyncRoute
export const routes = [
  { path: '', component: DetailComponent, pathMatch: 'full' }
];

@NgModule({
  declarations: [
    // Components / Directives/ Pipes
    DetailComponent
  ],
  imports: [
    CommonModule,
    FormsModule,
    RouterModule.forChild(routes), // <-- This is the problematic line, when I remove it, it compiles further
  ]
})
export class DetailModule {
  static routes = routes;
}
```

detail.component.ts
``` JavaScript
import { Component } from '@angular/core';
/*
 * We're loading this component asynchronously
 * We are using some magic with es6-promise-loader that will wrap the module with a Promise
 * see https://github.com/gdi2290/es6-promise-loader for more info
 */

console.log('Detail component loaded asynchronously');

@Component({
  selector: 'detail',
  template: `
    <h1>Hello from Detail</h1>
    <router-outlet></router-outlet>
  `
})
export class DetailComponent {
  constructor() {

  }

  ngOnInit() {
    console.log('hello Detail component');
  }
}
```

I will try to reproduce the issue with the main repository

**Comment by colinskow** [comment]
The AoT compiler is very sensitive and there are code styles that won't work. See "AoT Don'ts" in the README.

These issues don't have anything to do with this Starter repo and belong under @angular/compiler-cli.

**Comment by colinskow** [comment]
@Phmager it may help you out to look at the changes I had to make to make this repository compatible with AoT. Basically you cannot have default exports, and you need to use the string version of `loadChildren` in the router definitions.
https://github.com/AngularClass/angular2-webpack-starter/commit/c597344107dfd81530106aaf8f072b9b9a26871f#diff-15e96909d26305ab86756a9d68100c27
