### ISSUE TITLE
Error in browser console on starting-up the unchanged, cloned repository

### ISSUE THREAD

**Issue by plug-n-play** [AngularClass/angular2-webpack-starter#1324]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
Getting error in console:

Uncaught TypeError: __WEBPACK_IMPORTED_MODULE_19_zone_js_dist_long_stack_trace_zone__ is not a function
    at Object.<anonymous> (polyfills.bundle.js:7284)
    at __webpack_require__ (polyfills.bundle.js:54)
    at Object.<anonymous> (polyfills.bundle.js:16958)
    at __webpack_require__ (polyfills.bundle.js:54)
    at polyfills.bundle.js:146
    at polyfills.bundle.js:149

* **If the current behavior is a bug, please provide the steps to reproduce
1. Clone master repository
2. npm i && npm start
3. Open localhost:3000 (is this supposed to get opened by its own? I had to open the page manually)
4. Open browser console and see the error:

Uncaught TypeError: __WEBPACK_IMPORTED_MODULE_19_zone_js_dist_long_stack_trace_zone__ is not a function
    at Object.<anonymous> (polyfills.bundle.js:7284)
    at __webpack_require__ (polyfills.bundle.js:54)
    at Object.<anonymous> (polyfills.bundle.js:16958)
    at __webpack_require__ (polyfills.bundle.js:54)
    at polyfills.bundle.js:146
    at polyfills.bundle.js:149

* **What is the expected behavior?**
There should be no error in browser console when the default page starts

* **Please tell us about your environment:**
Tried in both OS X and Windows 8.1

**Comment by plug-n-play** [comment]
Also getting the following warnings:

[WDS] Warnings while compiling.
polyfills.bundle.js:3667 asset size limit: The following asset(s) exceed the recommended size limit (250 kB). 
This can impact web performance.
Assets: 
  vendor.bundle.js (3.17 MB)
  polyfills.bundle.js (524 kB)
warnings @ polyfills.bundle.js:3667
polyfills.bundle.js:3667 entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (250 kB). This can impact web performance.
Entrypoints:
  polyfills (524 kB)
      polyfills.bundle.js

  main (3.72 MB)
      polyfills.bundle.js
      vendor.bundle.js
      main.bundle.js

warnings @ polyfills.bundle.js:3667
main.bundle.js:276 Initial App State Object
vendor.bundle.js:314 Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.
main.bundle.js:488 hello `Home` component
:3000/0.chunk.js:61 `Detail` component loaded asynchronously
:3000/0.chunk.js:20 `Detail` bundle loaded asynchronously
webpack-dev-server.js:3 [WDS] Warnings while compiling.
webpack-dev-server.js:3 asset size limit: The following asset(s) exceed the recommended size limit (250 kB). 
This can impact web performance.
Assets: 
  vendor.bundle.js (3.17 MB)
  polyfills.bundle.js (524 kB)
warnings @ webpack-dev-server.js:3
webpack-dev-server.js:3 entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (250 kB). This can impact web performance.
Entrypoints:
  polyfills (524 kB)
      polyfills.bundle.js

  main (3.72 MB)
      polyfills.bundle.js
      vendor.bundle.js
      main.bundle.js

**Comment by katallaxie** [comment]
Duplicate https://github.com/AngularClass/angular2-webpack-starter/issues/1327

**Comment by GenZodd** [comment]
So I looked at this post and the linked Duplicate issue. I am getting this error with all the warnings and I looked at the committed PR and my code and my polyfills.browers.ts is the exact same was what the PR is linked to but I still get all these warnings. So I am confused on how/why this is fixed/closed.
