### ISSUE TITLE
Tons of error in console after npm install and npm start

### ISSUE THREAD

**Issue by weijyewang** [AngularClass/angular2-webpack-starter#1327]
* **I'm submitting a ...**
[ ] bug report

* **Do you want to request a *feature* or report a *bug*?**
Report a bug

* **What is the current behavior?**
After npm install and npm start/ npm run server. I get tons of errors such as these:
![image](https://cloud.githubusercontent.com/assets/8890603/21587421/30779966-d117-11e6-959b-57ab2e4df35c.png)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
Please refer to the description above.

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.X
- Browser: Chrome Canary  version 57.0
- Node 6.0
- Npm 3.8.6

**Comment by katallaxie** [comment]
@weijyewang should fix that 35af1985c4ab9a9b4ed660bddbf9edad7eb3d74a

**Comment by lordgreg** [comment]
So is this a revert to previous version of file?

**Comment by katallaxie** [comment]
@lordgreg yep!

**Comment by weijyewang** [comment]
thanks!

**Comment by weijyewang** [comment]
Here's the error shown in the terminal after running npm start:
![image](https://cloud.githubusercontent.com/assets/8890603/21591791/3bb8ede0-d142-11e6-9c29-90d4cc2e15e2.png)
