### ISSUE TITLE
1. Webpack Unmet Peer Dependency, and 2. Size Warning of vendor.bundle.js (3.17 MB) and polyfills.bundle.js (524 kB)

### ISSUE THREAD

**Issue by plug-n-play** [AngularClass/angular2-webpack-starter#1329]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
1. Getting error on npm i which says, "UNMET PEER DEPENDENCY webpack@2.2.0-rc.3"
![image](https://cloud.githubusercontent.com/assets/6245927/21598088/e1edf424-d17b-11e6-8aa3-f980ada0e4cf.png)

2. Get warnings for size of vendor.bundle.js (3.17 MB) and polyfills.bundle.js (524 kB)
![image](https://cloud.githubusercontent.com/assets/6245927/21598095/1bf03588-d17c-11e6-9f3e-e54dd8d27878.png)

**Comment by katallaxie** [comment]
1. yep, some packages are not yet updated to the recent release candidate
2. this is a standard behavior of webpack 2
