### ISSUE TITLE
Using ES2015 import statements to load npm dependencies

### ISSUE THREAD

**Issue by superchris** [AngularClass/angular2-webpack-starter#133]
I'd like to be able to load dependent libraries by using the standard `import` statement of ES2015 as I can in jspm. So far I've only been able to load npm libraries by using `require`. Is there a way to do this. For example, I added the phoenix_js npm to my project and tried:

```javascript
import { Socket } from "phoenix_js";
```

This gave me an error about finding the module, but when I changed it to:

```
var Socket = require("phoenix_js").Socket;
```

it worked. Having to mix the two syntaxes in my app code seems gross. I'd really like to just use `import` as it's the official standard for bringing modules going forward. Is there a way to do this? Not sure if this is webpack's issue or this repos, I found webpacks docs not as clear as I hoped.

**Comment by gdi2290** [comment]
the error you encountered was a typescript one. You need to make a type definition for the module for example
`phoenix_js.d.ts`
```typescript
// phoenix_js.d.ts example
define module "phoenix_js" {
  class Socket {
    constructor(endPoint: any, opts: any) 
    connect(): void;
    disconnect(callback: any, code: any, reason: any): void;
  }
}
```
The types are decoupled so users can write types for modules that aren't written in typescript. So this is a feature of typescript

**Comment by superchris** [comment]
So I'm pretty much a typescript newb. I tried dropping a `phoenix_js.d.ts` file into the `typings` directory and then added a reference line to `_custom.d.ts` but this didn't seem to work. First it didn't seem to like `define` so I changed it to `declare` per other examples I'd seen, but it still gives me the error about `Cannot find module 'phoenix_js'`. I've been unsuccessful finding any typescript docs thus far that clearly illuminate how this whole thing works, anything you could do to point me in the right direction is appreciated. Thanks for your prompt response.

**Comment by gdi2290** [comment]
@superchris I sent you a tweet. I can jump on hangout to quickly show you the solution

**Comment by gdi2290** [comment]
here's the repo for [phoenix_js](https://github.com/jerel/phoenix_js) so you can make a pull-request for the finished type definition you created
