### ISSUE TITLE
Meet error with build:aot:prod when update typescript from 2.0.10 to 2.1.4

### ISSUE THREAD

**Issue by nickppa** [AngularClass/angular2-webpack-starter#1332]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**

Feature

* **What is the current behavior?**

When I update typescript from 2.0.10 to 2.1.4, and run "npm run build:aot:prod", I met the error, see the error log as below:

> .tsModuleNotFoundError: Module not found: Error: Can't resolve '../compiled/src/
app/app.module.ngfactory' in 'E:\jsLib\angular2-webpack-starter-master\src'
    at factoryCallback (E:\jsLib\angular2-webpack-starter-master\node_modules\we
bpack\lib\Compilation.js:234:38)
    at E:\jsLib\angular2-webpack-starter-master\node_modules\webpack\lib\NormalM
oduleFactory.js:235:19
    at onDoneResolving (E:\jsLib\angular2-webpack-starter-master\node_modules\we
bpack\lib\NormalModuleFactory.js:60:20)
    at E:\jsLib\angular2-webpack-starter-master\node_modules\webpack\lib\NormalM
oduleFactory.js:127:20
    at E:\jsLib\angular2-webpack-starter-master\node_modules\webpack\node_module
s\async\dist\async.js:3694:9
    at E:\jsLib\angular2-webpack-starter-master\node_modules\webpack\node_module
s\async\dist\async.js:356:16
    at iteratorCallback (E:\jsLib\angular2-webpack-starter-master\node_modules\w
ebpack\node_modules\async\dist\async.js:934:13)
    at E:\jsLib\angular2-webpack-starter-master\node_modules\webpack\node_module
s\async\dist\async.js:840:16
    at E:\jsLib\angular2-webpack-starter-master\node_modules\webpack\node_module
s\async\dist\async.js:3691:13
    at apply (E:\jsLib\angular2-webpack-starter-master\node_modules\webpack\node
_modules\async\dist\async.js:21:25)
    at E:\jsLib\angular2-webpack-starter-master\node_modules\webpack\node_module
s\async\dist\async.js:56:12
    at E:\jsLib\angular2-webpack-starter-master\node_modules\webpack\lib\NormalM
oduleFactory.js:122:22
    at onResolved (E:\jsLib\angular2-webpack-starter-master\node_modules\webpack
\node_modules\enhanced-resolve\lib\Resolver.js:70:11)
    at loggingCallbackWrapper (E:\jsLib\angular2-webpack-starter-master\node_mod
ules\webpack\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at afterInnerCallback (E:\jsLib\angular2-webpack-starter-master\node_modules
\webpack\node_modules\enhanced-resolve\lib\Resolver.js:138:10)
    at loggingCallbackWrapper (E:\jsLib\angular2-webpack-starter-master\node_mod
ules\webpack\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at Resolver.applyPluginsAsyncSeriesBailResult1 (E:\jsLib\angular2-webpack-st
arter-master\node_modules\tapable\lib\Tapable.js:145:46)
    at innerCallback (E:\jsLib\angular2-webpack-starter-master\node_modules\webp
ack\node_modules\enhanced-resolve\lib\Resolver.js:125:19)
    at loggingCallbackWrapper (E:\jsLib\angular2-webpack-starter-master\node_mod
ules\webpack\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at E:\jsLib\angular2-webpack-starter-master\node_modules\tapable\lib\Tapable
.js:247:15
    at E:\jsLib\angular2-webpack-starter-master\node_modules\webpack\node_module
s\enhanced-resolve\lib\UnsafeCachePlugin.js:39:4
    at loggingCallbackWrapper (E:\jsLib\angular2-webpack-starter-master\node_mod
ules\webpack\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at afterInnerCallback (E:\jsLib\angular2-webpack-starter-master\node_modules
\webpack\node_modules\enhanced-resolve\lib\Resolver.js:138:10)
    at loggingCallbackWrapper (E:\jsLib\angular2-webpack-starter-master\node_mod
ules\webpack\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at Resolver.applyPluginsAsyncSeriesBailResult1 (E:\jsLib\angular2-webpack-st
arter-master\node_modules\tapable\lib\Tapable.js:145:46)
    at innerCallback (E:\jsLib\angular2-webpack-starter-master\node_modules\webp
ack\node_modules\enhanced-resolve\lib\Resolver.js:125:19)
    at loggingCallbackWrapper (E:\jsLib\angular2-webpack-starter-master\node_mod
ules\webpack\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at E:\jsLib\angular2-webpack-starter-master\node_modules\tapable\lib\Tapable
.js:247:15
    at innerCallback (E:\jsLib\angular2-webpack-starter-master\node_modules\webp
ack\node_modules\enhanced-resolve\lib\Resolver.js:123:11)
    at loggingCallbackWrapper (E:\jsLib\angular2-webpack-starter-master\node_mod
ules\webpack\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
resolve '../compiled/src/app/app.module.ngfactory' in 'E:\jsLib\angular2-webpack
-starter-master\src'
  using description file: E:\jsLib\angular2-webpack-starter-master\package.json
(relative path: ./src)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: E:\jsLib\angular2-webpack-starter-master\package
.json (relative path: ./src)
    using description file: E:\jsLib\angular2-webpack-starter-master\package.jso
n (relative path: ./compiled/src/app/app.module.ngfactory)
      as directory
        E:\jsLib\angular2-webpack-starter-master\compiled\src\app\app.module.ngf
actory doesn't exist
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        E:\jsLib\angular2-webpack-starter-master\compiled\src\app\app.module.ngf
actory doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        E:\jsLib\angular2-webpack-starter-master\compiled\src\app\app.module.ngf
actory.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        E:\jsLib\angular2-webpack-starter-master\compiled\src\app\app.module.ngf
actory.js doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        E:\jsLib\angular2-webpack-starter-master\compiled\src\app\app.module.ngf
actory.json doesn't exist

> 
It seems app.module.ngfactory.ts didn't been generated.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

1st step: update typescript from 2.0.10 to 2.1.4;
2nd step: npm run build:aot:prod

* **What is the expected behavior?**

The aot build success.

* **What is the motivation / use case for changing the behavior?**

I want to use async/await, which is supported with typescript 2.1.4 when set the tsconfig's target to es5.
Although I can use babel + typescript to supported it, I still don't want to import other packages.

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by d3viant0ne** [comment]
Angular doesn't support TypeScript 2.1.4 and won't until Angular 4.x
