### ISSUE TITLE
Where to import vendor js after adding A. O. T support

### ISSUE THREAD

**Issue by vincent-cm** [AngularClass/angular2-webpack-starter#1334]
I have some of the vendor library to be imported before the vendor.browser.ts removed:
...
// RxJS
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/mergeMap';
// NPM Modules
import 'underscore';
import 'jquery';
import 'primeng/primeng';
import 'rxjs/Rx';

Now this file is removed from loader entry could you please help?

**Comment by vincent-cm** [comment]
no need any more

**Comment by hankaibo** [comment]
@vincent-cm How to fix it?

**Comment by govi2010** [comment]
@vincent-cm  and @hankaibo  how to fix this ?
 where should i add my vendor js ?

**Comment by hankaibo** [comment]
you don't need the vendor.js file.
Tomorrow I show my code.

**Comment by evgd** [comment]
@hankaibo @govi2010 did you find solution?

**Comment by hankaibo** [comment]
I'm sorry.tomorrow tee you.


发自坚果手机

evgd <notifications@github.com> 于 2017年1月24日，18:48写道：


@hankaibo<https://github.com/hankaibo> @govi2010<https://github.com/govi2010> did you find solution?

―

**Comment by hankaibo** [comment]
You can wirte it in webpack.dev.js.
![default](https://cloud.githubusercontent.com/assets/5361465/22413133/09187c48-e6f0-11e6-878c-d298648f5bbc.png)

**Comment by maciejsobala** [comment]
@hankaibo What do you have on your mind saying that we don't need vendor in our built? I can remove it from index.html file without any concerns?
