### ISSUE TITLE
Support for Hybrid Angular 1 & Angular 2+ Applications

### ISSUE THREAD

**Issue by abhishekisnot** [AngularClass/angular2-webpack-starter#1335]
* **I'm submitting a ...**
[ ] bug report
[x ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
*feature*

* **What is the current behavior?**
Currently the starter supports only Angular 2+ applications.

* **What is the expected behavior?**
Support bootstraping Angular 1 & Angular 2+ hybrid applications.

* **What is the motivation / use case for changing the behavior?**
Many of enterprise applications are still on Angular 1 and potentially most (or many?) of them would want to migrate to Angular 2. Assuming ngUpgrade is a de-facto solution for such an upgrade, it would be great if this starter supported bootstraping hybrid application as outlined here https://angular.io/docs/ts/latest/guide/upgrade.html#!#bootstrapping-hybrid-angular-1-2-applications

* **Other information**
* This feature I suppose should be an opt in/out.. But currently we do not have any strategy for opt in/out.
* We are raising this request in an attempt to explore possibility of such a support and also to gather feedback if this needs to be done in a fork

**Comment by d3viant0ne** [comment]
The requirements to support any number of angular 1.x versions is a rabbit hole filled with stylistically & architecturally different upgrade applications.

- This is beyond the scope of what this was built for.
- It would add a bunch of bloat for the remainder of the community who won't ever use it.
- Too many ngUpgrade quirks to not purpose build a solution.

In short, there is no good way to take the one size fits all approach to upgrading existing 1.x applications. It's certainly possible to modify the starter to support an upgrade path, it is not on the other hand something I see as beneficial for this repo or it's consumers.

//cc @katallaxie @colinskow @gdi2290

**Comment by katallaxie** [comment]
@d3viant0ne 👍 Upgrade is seriously beyond what this starter wants to achieve. Also, it seems that in most cases it would be more beneficial if we would provide something like `angular2-recipes` in which we provide some patterns and examples.

**Comment by abhishekisnot** [comment]
> any number of angular 1.x versions is a rabbit hole...

@d3viant0ne On same page here, maybe we can pick latest version and just keep it limited to that.

> It would add a bunch of bloat for the remainder of the community who won't ever use it.

I guess this is where opt in/out can be considered? If still complicated, maybe we can resort to `angular2-recipes` as @katallaxie said.

> Too many ngUpgrade quirks to not purpose build a solution.

Agreed. Easy or Hard, I guess we would still need a support of some sort in form of build solution or receipes considering ngUpgrade is a de-facto solution for upgrading. 

Also, it's fine if we agree that it's something out of the scope for this starter. 

What I was wondering is, we have [NG6-starter](https://github.com/AngularClass/NG6-starter) for NG1.x apps and this starter for NG2+ apps, it would be great if we have a build solution (or even receipes) that connects these 2 starters.

**Comment by d3viant0ne** [comment]
That was kind of my point, they shouldn't be connected. This starter exists to facilitate the development of an Angular version 2.x or newer application. It doesn't support ngupgrade and shouldn't as you are adding a a bunch of functionality / complexity / bloat for a niche requirement outside the scope of this repo.

Adding things into master means we are making a technology choice for thousands of people, those choices need to be made with the best interests of the users & the library in mind. 

Adding opt in / out support for ngupgrade, regardless of limiting version is not in the best interest of either the majority of the consumers or the repo nor would we want to assume the maintenance costs of the validations and issues that would come along with it.

Furthermore in my personal opinion this is not something that I would ever choose to undertake professionally using a generic boilerplate. If you have requirements that necessitate the use of ngupgrade and all it's quirks, I would strongly encourage you to purpose build the base of that project using whatever starting point you deem appropriate for you and your team.
