### ISSUE TITLE
Compression having issue

### ISSUE THREAD

**Issue by dheeraja00** [AngularClass/angular2-webpack-starter#1337]
I am trying to use `CompressionPlugin`, but when I install `compression-webpack-plugin` it gives me this error: `UNMET PEER DEPENDENCY webpack@2.2.0-rc.3`. Do I need to install some other version of compression?

**Comment by colinskow** [comment]
Does the build work, or is it broken? If it works you can safely ignore the message.

**Comment by katallaxie** [comment]
@dheeraja00 You can ignore this. The `compression-webpack-plugin` works as is with webpack@^2.x.x`. Btw. it is not the plugin itself, which does not require webpack, but it is some other dep down the chain.
