### ISSUE TITLE
Linting for Typescript

### ISSUE THREAD

**Issue by matthewdenobrega** [AngularClass/angular2-webpack-starter#134]
This is relatively easy to add but it will be time-consuming to get all the existing code to lint, and there will be some disagreement on the best rules to use for the linter. Is this something that there is interest in, or is it too opinionated for this sort of starter?

**Comment by dotcs** [comment]
I think it's best to guide programmers along their way. +1 for code linting.

**Comment by gdi2290** [comment]
pull-request? :)

**Comment by gdi2290** [comment]
done via https://github.com/AngularClass/angular2-webpack-starter/commit/9e3211121ec51b3799577dedd950fe930d90c93b
