### ISSUE TITLE
[Bug] Webpack command breaks when no npm scripts is used

### ISSUE THREAD

**Issue by Luchillo** [AngularClass/angular2-webpack-starter#1340]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
I've been testing and whenever i use `cross-env NODE_ENV=development webpack --progress --profile` alone i get this error:

```sh
/usr/local/lib/node_modules/ts-node/src/index.ts:312
          throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset))
                ^
TSError: ⨯ Unable to compile TypeScript
webpack.config.ts (28,5): Subsequent variable declarations must have the same type.  Variable 'ENV' must be of type 'string', but here has type 'any'. (2403)
webpack.config.ts (48,12): Property 'module' does not exist on type '{}'. (2339)
webpack.config.ts (88,12): Property 'plugins' does not exist on type '{}'. (2339)
webpack.config.ts (101,12): Property 'node' does not exist on type '{}'. (2339)
webpack.config.ts (117,12): Property 'devtool' does not exist on type '{}'. (2339)
webpack.config.ts (118,12): Property 'resolve' does not exist on type '{}'. (2339)
```
Along with 20 more of those lines with almost the same error but different problem

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

Just try to run `cross-env NODE_ENV=development webpack --progress --profile` in the V6 branch will break the app like that.

* **What is the expected behavior?**

That it worked the same way the npm script containig such statement is, working ok.

* **What is the motivation / use case for changing the behavior?**

Fix the build pipeline.

* **Please tell us about your environment:**

- Angular version: 2.1.2
- Browser: Chrome  55.0.2883.95

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

No idea why would it work with npm scripts, but not with the normal terminal with webpack command, neither with the `cross-env` packaje.

**Comment by d3viant0ne** [comment]
The `v6` branch isn't intended for public consumption and there is no expectation that any / all of the functionality is working. If you are using it in an attempt to utilize the DLL support, don't.

**Comment by Luchillo** [comment]
Actually i was going for the AoT support (in the side of testing to try and make it work), it works flawlessly when using the npm scripts, i was just wondering why using webpack directly won't work.

**Comment by d3viant0ne** [comment]
FYI there is AoT support in current Master.

**Comment by Luchillo** [comment]
Yes but not with `@ngtools/webpack` plugin, i was really wanting to make the plugin work.
