### ISSUE TITLE
do starter not lazily load bundles?

### ISSUE THREAD

**Issue by pleerock** [AngularClass/angular2-webpack-starter#1351]
I just cloned this repo, made `npm i` and run `npm run build:prod` then `npm run server:prod`. When I open it in browser, console shows me following logs:

```
Initial App State Object {}
main.5bf4ea0….bundle.js:1 hello `Home` component
0.993da87….chunk.js:1 `Detail` component loaded asynchronously
0.993da87….chunk.js:1 `Detail` bundle loaded asynchronously
1.2f878f0….chunk.js:1 `Barrel` component loaded asynchronously
1.2f878f0….chunk.js:1 `Barrel` bundle loaded asynchronously
5.fe560f6….chunk.js:1 `ChildDetail` component loaded asynchronously
5.fe560f6….chunk.js:1 `Detail` bundle loaded asynchronously
6.aab8402….chunk.js:1 `Barrel` component loaded asynchronously
6.aab8402….chunk.js:1 `ChildBarrel` bundle loaded asynchronously
```

However I didnt navigate throw the different tabs. So, the question is, does lazy load works correctly right now?

**Comment by pleerock** [comment]
or probably its just a false alarm and routing preloading does this thing....

**Comment by gdi2290** [comment]
it's preloading

**Comment by colinskow** [comment]
This seems to be caused by the change from `angular-router-loader` to `ng-router-loader`. Is it bad that it is preloading?

**Comment by pleerock** [comment]
if its preloading then it is expecting behaviour

**Comment by minhnguyenwp** [comment]
**angular2-router-loader TO ng-router-loader for preloading.**

At the first page the site call many chunk files. so is it Good?
in version 2.2 i saw first page just has 1 chunk and go to sub page site will call new chunk. 

*version 2.4: A site maybe up to 6.2MB (without Gzip) - AoT Mode
*version 2.2 : A site is about 2.7MB (without Gzip) - Prod Mode

**I have a little bit confusing in this problem. Could u tell me which one is better?**

**Comment by minhnguyenwp** [comment]
@pleerock 
```
export const ROUTES: Routes = [
  { path: 'detail', loadChildren: () => '../my-ng-modules/details#DetailModule?loader=sync' },
];
```
if you want to make lazy load Module,  pls check this https://github.com/shlomiassaf/ng-router-loader#synchronous-loading
