### ISSUE TITLE
Any way to make main.js or vendor.js is smaller [QUESTION]

### ISSUE THREAD

**Issue by minhnguyenwp** [AngularClass/angular2-webpack-starter#1356]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[x ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
- I cloned this source. 
- run build prod . i've not developed yet. just using your original source
i got main.js (prod mode) -> main.js is vendor + main  , right? 810kb. 

if i develop product, code real product , i will get main or vendor is over than 1.1 MB. it's too heavy. 

i'm using angular2-webpack-starter v5.1.1 but i'm finding the way to make bundle lighter. 

**is there any way to make main.js or vendor.js (prod mode) is lower than 500kb**

**Comment by fxck** [comment]
are you sure you are looking at gzipped values? also there was `npm run build:aot` added recently which should reduce the size further

**Comment by d3viant0ne** [comment]
No, I am pretty sure he is not looking at gzipped size as it's well under a MB. As per the `dependencies` it's just angular and it's supporting libraries and the compiled output is under 500kb.

I'm not entirely sure what it is you are looking at but it isn't the production build output for #master 

![screen shot 2017-01-10 at 12 13 14 pm](https://cloud.githubusercontent.com/assets/8420490/21818692/6af2e858-d72e-11e6-8268-1c64f6c8fb6e.png)

As to you question, you have two options for reducing payload ... Split or Remove

**Comment by minhnguyenwp** [comment]
Thank you man, i knew AOT and now i know how to gzip .

**Comment by euprogramador** [comment]
@minhnguyenwp share it.
