### ISSUE TITLE
CLI or generator to create pages, components..., etc

### ISSUE THREAD

**Issue by aalshaikh** [AngularClass/angular2-webpack-starter#1357]
I can't find in documentation if there is CLI or generator for create components, directives, pages..? and what about if i can use angular CLI?

**Comment by d3viant0ne** [comment]
No there isn't and no you can 't.

If you want to generate content, use the CLI for your projects & not someone's starter it's not in bad shape as of beta.24.

Alternatively, if the intent is to just speed up velocity during development, you can accomplish the same thing with a few properly configured @code plugins.
