### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined when running AOT

### ISSUE THREAD

**Issue by GenZodd** [AngularClass/angular2-webpack-starter#1361]
* **I'm submitting a ...**
[X ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**
when I run npm run build:aot I get this error. 

Starting compilation using the angular compiler.
Angular compilation done, starting webpack bundling.
TypeError: Cannot read property 'length' of undefined
    at StaticSymbolResolver.resolveSymbol (D:\project\node_modules\@angular\compiler\bundles\compiler.umd.js:25950:35)

* **What is the expected behavior?**
no error

* **Please tell us about your environment:**

- Angular version: 2.4.2
- npm 3.10.8
- Browser: [Chrome ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by shlomiassaf** [comment]
What is the TS version?

Did it work with 2.4.1?

**Comment by d3viant0ne** [comment]
This is an issue in your repository, there is no AOT compilation issue with either Angular 2.4.1 or 2.4.2.

![screen shot 2017-01-10 at 3 29 38 pm](https://cloud.githubusercontent.com/assets/8420490/21825533/bbe00f78-d749-11e6-8500-fc91583a34dc.png)

**Comment by klihelp** [comment]
@GenZodd Did you had any success with the build?

**Comment by GenZodd** [comment]
yes, thanks for asking. I had to back a couple other packages out and then I got this working. I had a toastr and a loggly npm package that I had to remove and then it worked. Then I update those other packages and it is still working.
