### ISSUE TITLE
Should compiled/ directory be excluded by at-loader

### ISSUE THREAD

**Issue by glendaviesnz** [AngularClass/angular2-webpack-starter#1366]
* **I'm submitting a ...**
[ x] bug report
[] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
bug  - but maybe a feature :-)

* **What is the current behavior?**

Currently if you have run an aot build and have a compiled/ folder, and then run the dev server, then at-loader runs across the compiled directory also, which increases compile time by a couple of seconds, but also shows errors if constructor injections in src folder change. 

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 

With a fresh copy of repo run the start:hmr and check at-loader completion times, then run build:aot, and then start:hmr again - at-loader times possible increased by several seconds.

If you delete compiled folder or change excludes in tsconfig.webpack.json to the following then at-loader completion times go down again.

  "exclude": [
    "node_modules",
    "dist",
    "compiled",
    "src/**/*.spec.ts",
    "src/**/*.e2e.ts"
  ]

The above change does not appear to affect the AoT build process at all.
Maybe cleaning the compiled folder at the start of the dev server task is a better option?

* **What is the expected behavior?**

Existence of the compiled folder shouldn't affect dev build at all?

* **What is the motivation / use case for changing the behavior?**

The extra at-loader completion time is not such a big issue, but getting at-loader errors about code in the compiled folder when running dev task is annoying.

* **Please tell us about your environment:**
- Angular version: 2.4.1
Windows

**Comment by colinskow** [comment]
Currently the at-loader is using the same configuration file for AoT and JiT builds. `node_modules` is necessary to include since `@angular` and other dependencies live there. Excluding `*.spec.ts` and `*.e2e.ts` could possibly shave a few dozen milliseconds off each build.

We could also try specifying `"rootDir": "./src"` in `tsconfig.webpack.json` and see if that prevents unnecessary files from being scanned.

As far as `compiled` I usually run `npm run clean:aot` to remove this folder before doing a non-AoT build.

**Comment by glendaviesnz** [comment]
@colinskow  had another look at this and even with "compiled" excluded in tsconfig.webpack.json at-loader still reports errors in the compiled folder when running dev server. This is because main.browser.aot.ts is still being included from src dir. Modifying tsconfig.webpack.json to the following seems to fix the issue, and AoT still works fine as main.browser.aot.ts explicitly listed as entry point in webpack config
```
  "exclude": [
    "node_modules",
    "dist",
    "compiled",
    "src/**/*.spec.ts",
    "src/**/*.e2e.ts",
    "src/main.browser.aot.ts"
  ]
```
Is it worth putting in a pull request for this? I am happy to just make this change locally and you can close this issue if not.

**Comment by colinskow** [comment]
Excluding files is like putting a bandaid over a deeper problem. I'm working on a PR that will cause TypeScript to compile only dependent files and ignore everything else. This will make builds run more efficiently.

**Comment by glendaviesnz** [comment]
Ok  - thanks - no need to keep this one open then.

**Comment by colinskow** [comment]
@glendaviesnz by the way if you are getting compiler errors from compiled while running other scripts, then you are probably running older versions of dependencies. Try upgrading everything to the same versions in master. I don't get errors.
