### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by chriscurnow** [AngularClass/angular2-webpack-starter#137]
Hey, how come you deleted all the examples?
I just re-synced to get the latest with ng47 and all the examples disappeared!!

**Comment by SekibOmazic** [comment]
@chriscurnow You can get them here: https://github.com/AngularClass/angular2-examples

**Comment by chriscurnow** [comment]
Thanks. I have had head down developing some ideas for several weeks and I haven't kept up with what's happening here. This makes sense – it means the starter is just that.

**Comment by gdi2290** [comment]
for example https://github.com/AngularClass/angular2-webpack-starter/pull/127 requires bootstrap to be a dependency in the repo. I would either need to include another script to install it's dependency (bootstrap) like we did for express or just refactor everything out into another repo

**Comment by gdi2290** [comment]
thanks for asking :+1:
