### ISSUE TITLE
[at-loader] cannot find name 'require'.

### ISSUE THREAD

**Issue by ajeeshbaygrape** [AngularClass/angular2-webpack-starter#1371]
Followed the instructions in readme and executed npm start and I am getting below errors.

[at-loader] Checking finished with 6 errors
[at-loader] Cannot find type definition file for 'hammerjs'.

[at-loader] Cannot find type definition file for 'node'.

[at-loader] src\app\app.component.ts:19:5
    Cannot find name 'require'.

[at-loader] src\app\home\home.component.ts:20:13
    Cannot find name 'require'.

[at-loader] src\app\home\home.component.ts:22:13
    Cannot find name 'require'.

[at-loader] src\polyfills.browser.ts:44:3
    Cannot find name 'require'.

**Comment by PeymanGhadiri** [comment]
+1

**Comment by hankaibo** [comment]
me too.

**Comment by matb** [comment]
I was able to solve the problem by changing line 106 of webpack.common.js from 

`'awesome-typescript-loader?{configFileName: "tsconfig.webpack.json"}',`

to 

`'awesome-typescript-loader?{tsconfig: "tsconfig.webpack.json"}',`

**Comment by ajeeshbaygrape** [comment]
Awesome! Thank you All.

**Comment by d3viant0ne** [comment]
So something odd going on here that needs to be figured out.

`'awesome-typescript-loader?{configFileName: "tsconfig.webpack.json"}',` is as it should be per the `awesome-typescript-loader` api docs.

The three of you that were having issues with this.

Are these fresh clones of the repo?
What is your NodeJS Version?
What OS are you running on?

That "workaround" should be causing the loader to use it's default which means it's targeting `tsconfig.json` not `tsconfig.webpack.json`

//cc @colinskow

**Comment by ajeeshbaygrape** [comment]
Fresh clones, node v7.4.0, windows 10;

**Comment by DBosley** [comment]
I just had this happen to me as well. My package.json has
`"awesome-typescript-loader": "~3.0.0-beta.17"`
for my atl dependency. I'm building a project based off the AOT release download. I've modified quite a bit, but I haven't changed how atl is configured. Yesterday it built fine, no errors, today I got these. Changed the param name from `configFileName` to `tsconfig` and we're working good again.

**Comment by d3viant0ne** [comment]
@DBosley - I assume you are running on Windows as well?

**Comment by scallacs** [comment]
#1372

**Comment by DBosley** [comment]
Yes I am.

**Comment by colinskow** [comment]
Could this be a breaking change in ATL?

**Comment by d3viant0ne** [comment]
No, everything works fine for me. We have two looming issues on Windows that need to be worked out.

**Comment by colinskow** [comment]
`configFileName` is the correct option for `awesome-typescript-loader`. Changing this option will load `tsconfig.json` instead of `tsconfig.webpack.json` and disable tree shaking.

**Comment by DBosley** [comment]
So what caused these errors to start today?

**Comment by colinskow** [comment]
This appears to be a bug affecting just Windows with TypeScript 2.1.5. It goes away when downgrading to TypeScript 2.0.10.

But I found a better solution:
Just above `"types:"` in both `tsconfig.json` files add the following:

```json
"typeRoots": [
      "node_modules/@types"
    ],
```

TypeScript should [automatically look there](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#types-typeroots-and-types), but it appears this is failing on Windows.

**Comment by colinskow** [comment]
Filed an issue with TypeScript
https://github.com/Microsoft/TypeScript/issues/13486

**Comment by d3viant0ne** [comment]
I've got some work to do so I won't be watching github issues. If anyone still has an issue with this after picking up the changes from @colinskow - Ping me directly in the AngularClass slack channel.

**Comment by DBosley** [comment]
@colinskow I added "node_modules/@types" but I'm still getting the issue. It doesn't seem to be able to find any type files inside of node_modules. My tsconfig:
`{
    "compilerOptions": {
        "target": "es5",
        "module": "es2015",
        "moduleResolution": "node",
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "allowSyntheticDefaultImports": true,
        "sourceMap": true,
        "noEmit": true,
        "noEmitHelpers": true,
        "strictNullChecks": false,
        "baseUrl": ".",
        "paths": {
        },
        "lib": [
            "es2015",
            "dom"
        ],
        "types": [
            "node_modules/@types",
            "hammerjs",
            "node",
            "source-map",
            "uglify-js",
            "webpack"
        ]
    },
    "exclude": [
        "node_modules",
        "pkg",
        "Client/angular/**/*.spec.ts",
        "Client/angular/**/*.e2e.ts",
    ],
    "awesomeTypescriptLoaderOptions": {
        "forkChecker": true,
        "useWebpackText": true
    },
    "angularCompilerOptions": {
        "genDir": "./pkg/compiled",
        "skipMetadataEmit": true
    },
    "compileOnSave": false,
    "buildOnSave": false,
    "atom": { "rewriteTsconfig": false }
}
`

**Comment by pauldcollins** [comment]
Just to update, I've just downloaded the latest clone and getting the same error as mentioned here and in #1372  

The change from @colinskow is already merged in and I've already tried the fix from @matb - but neither seem to make the difference.

I'm on OS X 10.12.2, running: Node Version 5.0.0 and NPM 3.3.6

@d3viant0ne - I'll ping you at Slack, as requested. Thanks for any help.

**Comment by pauldcollins** [comment]
I upgraded my Node Version to 6.9.0 and that seems to have solved the problem. 

Not sure what the minimum Node Version required is now, but on the README it still says 5.0.0. 

Thanks all.

**Comment by GrushinEgor** [comment]
Solution: 
If you have your separated tsconfig in NON-root folder (e.g. config folder), you have to set `typeRoots` prop of this config to be relative (e.g. `"../node_modules/@types"`)
