### ISSUE TITLE
How to add vendor libraries (e.g. jquery, font awesome, kendo ui) after commit c597344

### ISSUE THREAD

**Issue by feng-xiao** [AngularClass/angular2-webpack-starter#1380]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[x] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
We need a guide

Please provide a simple guide for how to add new vendor libraries (e.g. font awesome, kendo ui, bootstrap 4, etc.). I'm very confused why vendor.browser.ts has been removed in commit [c597344]

**Comment by d3viant0ne** [comment]
![screen shot 2017-01-16 at 8 17 05 am](https://cloud.githubusercontent.com/assets/8420490/21986216/3231e2e0-dbc4-11e6-9114-f6af319c4123.png)

**Comment by govi2010** [comment]
@what is solution ?

**Comment by Ovidiu-S** [comment]
+1
