### ISSUE TITLE
Camel cased filenames seem to cause issues with TypeScript

### ISSUE THREAD

**Issue by juristr** [AngularClass/angular2-webpack-starter#139]
When I have a camel-cased filename like `dateTime.ts` I get errors in VSCode

![image](https://cloud.githubusercontent.com/assets/542458/11610207/d135371c-9b9b-11e5-978c-48774cae91cb.png)

...on the other side when I change the filename casing, everything works just fine

![image](https://cloud.githubusercontent.com/assets/542458/11610215/09def44a-9b9c-11e5-812d-c2b677978d19.png)

**Comment by gdi2290** [comment]
that's odd

**Comment by juristr** [comment]
Ya 😁

**Comment by gdi2290** [comment]
I'm not too sure what to do here :/ it might be an issue with the editor

**Comment by juristr** [comment]
Which one are u using? VSCode?

**Comment by gdi2290** [comment]
I'm using sublime and sometimes atom

**Comment by juristr** [comment]
Sublime user as well. Since a couple of weeks I'm using VSCode now for better TypeScript support. It's a difficult relationship currently, but it's not that bad as well.
Kinda complicated :smile:
