### ISSUE TITLE
Feature request: Minify index.html

### ISSUE THREAD

**Issue by AKlaus** [AngularClass/angular2-webpack-starter#1396]
Currently, the `index.html` file gets into the production destination folder "as is" (`npm run build:prod`).
I'd like to see it minified with removed comments, spaces, etc.

Usually, the `index.html` file is quite concise, but with some comments though. So removing the comments for the production version would be very useful.

**Comment by nidilong** [comment]
and also need merge some extra js in html

**Comment by katallaxie** [comment]
We have [html-webpack-plugin](https://www.npmjs.com/package/html-webpack-plugin) in place.

```
minify: {
removeComments: true,
removeTagWhitespace: true
}
```

should to the trick.
