### ISSUE TITLE
Angular2 +Electron + Webpack

### ISSUE THREAD

**Issue by disshishkov** [AngularClass/angular2-webpack-starter#140]
May be you can help we to understand how to configure angular2 and webpack on electron? 
I'd prefer leave angular2.js file and just have an app.js (which will be a enter point for an electron) but CommonsChunkPlugin moves webpack specific methods to angular2.js  and electron can not handle app.js without them.

**Comment by jgodi** [comment]
I have a playground [here](https://github.com/jgodi/angular2-electron-playground) that does Electron+NG2, modeled off this starter/ionic2-conference-app.

**Comment by disshishkov** [comment]
Thank you @jgodi but you separated webpack+angular2 and electron. I want to write `index` file in typescript as well and build app to index.js with webpack

**Comment by kilmister** [comment]
Not exactly sure what you're looking for, but check [this out](https://github.com/kilmister/Electron-Angular2).

**Comment by gdi2290** [comment]
I need to write a wiki page for the repo. closing for now since there are other repos atm
