### ISSUE TITLE
Question - Bundle size

### ISSUE THREAD

**Issue by olaf89** [AngularClass/angular2-webpack-starter#1400]
Hello, im currently investigating my bundle size using aot and prod build version. I noticed that for example using one module from ng2-bootstrap causes all modules from that library to be bundled. I would like to have in my bundle only those modules which im using. Is this expected ? Is that something ng2-bootstrap library should improve on? or should i investigate more advanced tools for tree shaking?

**Comment by d3viant0ne** [comment]
It's not quite that simple but you have two options, split or shake.

For tree shaking, anything that isn't commonjs will benefit from the tree shaking that's in master currently. I don't use bootstrap, first thing I would check is that what you are trying to shake out is a ES2015 module and not commonjs. If it's commonjs, you would have to take it up with them or use another component framework.

If it's ES2015 and not being properly shaken, we will have to look at your setup.

**Comment by olaf89** [comment]
I used clean clone of latest version of this starter and just added alert module from ng2-bootstrap.
As a result whole liblary was added to bundle.
![image](https://cloud.githubusercontent.com/assets/11535118/22186065/3435ccc4-e0f0-11e6-8942-ef235183a95c.png)
I think this is their config: ("module": "commonjs")
https://github.com/valor-software/ng2-bootstrap/blob/development/src/tsconfig.json
Anyway now I understand that is not related to any configuration in starter, Thanks so much for help! Please close.

**Comment by evgd** [comment]
will it "shake" correctly with the latest changes?
https://github.com/valor-software/ng2-bootstrap/commit/2d74fc39aa99a4c31ab3d3a226022c6974bb28d9
-    "module": "commonjs",
+    "module": "es2015",

**Comment by olaf89** [comment]
It does not,
issue: 
https://github.com/valor-software/ng2-bootstrap/issues/1538
