### ISSUE TITLE
How to support bower?

### ISSUE THREAD

**Issue by cbyniiaii** [AngularClass/angular2-webpack-starter#1401]
To supprot bower, I find in https://webpack.github.io/docs/usage-with-bower.html .

but not work;

and then I find other in https://github.com/lpiepiora/bower-webpack-plugin  

but also not work;

I want to use vaadin UI components that It's build bower. 

Am I missing something?

**Comment by d3viant0ne** [comment]
The starter doesn't support bower, most won't anymore.

For reference, the vast majority of the JavaScript community has moved away from Bower, the reasons are too numerous to bother mentioning.

Point being, as opposed to trying to wedge Bower in anyone of the current starters I highly suggest you simply stop using it.
