### ISSUE TITLE
Provide angular4 branch

### ISSUE THREAD

**Issue by karolmie1** [AngularClass/angular2-webpack-starter#1402]
* **I'm submitting a ...**
[ ] bug report
[ x ] feature request
[ ] question about the decisions made in the repository

* **What is the motivation / use case for changing the behavior?**

Angular4-beta releases are more bleeding edge (https://github.com/angular/angular/blob/master/CHANGELOG.md), that would also prepare people for imminent confusion when angular4 will be released.

I've personally switched to angular4, and I've not experienced any issues for now.

**Comment by d3viant0ne** [comment]
The starter will be upgraded to 4.x when it's stable enough to be usable
