### ISSUE TITLE
Using template in app.component.ts like template: require('app.html') gives error on aot

### ISSUE THREAD

**Issue by MangeshPimpalkar** [AngularClass/angular2-webpack-starter#1408]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
In the app.component.ts using the template: require('app.html') syntax intead gives a error on running "build:aot:prod".

```
Error: Error encountered resolving symbol values statically. Calling function 'require', 
function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, 
resolving symbol AppComponent in /angular2-webpack-starter/angular2-webpack-starter/src/app/app.component.ts, resolving symbol AppComponent in /angular2-webpack-starter/angular2-webpack-starter/src/app/app.component.ts

```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by d3viant0ne** [comment]
This isn't a bug, you can't use `require()` in angular templates and compile with AOT

**Comment by MangeshPimpalkar** [comment]
@d3viant0ne  Thanks So to use aot we have to put all our templates in the ts file and also the styles.

**Comment by d3viant0ne** [comment]
You can inline them or use `templateUrl: ''` you just can't use `templateUrl: require('')`

**Comment by d3viant0ne** [comment]
And do yourself the favor of getting of the Angular beta versions, far too many major changes between beta and `2.4.3` to make any of the work you are doing right now worth your time.

**Comment by MangeshPimpalkar** [comment]
@d3viant0ne Sorry the version i am using is 2.4.3.I updated the ticket.
