### ISSUE TITLE
ES6 target, vendor.dll.js small fix

### ISSUE THREAD

**Issue by Neur0mante** [AngularClass/angular2-webpack-starter#1409]
* **I'm submitting a ...**
[*] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**
When targeting ES6 with the typescript complier you get 

> Uncaught TypeError: Cannot convert undefined or null to object
>     at Function.getPrototypeOf (<anonymous>)
>     at getParentCtor (http://localhost:3100/vendor.dll.js:62720:39)
> ...

* **Other information** 
Simply changing the getParentCtor function in the dll/vendor.dll.js file by adding a check for the prototype (` if (ctor.prototype)` ):
```
 function getParentCtor(ctor) {
                var /** @type {?} */ parentProto;
                if (ctor.prototype) parentProto = Object.getPrototypeOf(ctor.prototype);
                var /** @type {?} */ parentCtor = parentProto ? parentProto.constructor : null;
                // Note: We always use `Object` as the null value
                // to simplify checking later on.
                return parentCtor || Object;
            }
```
seems to fix the issue.

**Comment by shlomiassaf** [comment]
@Neur0mante I didn't get this error with es6 target.

Anyway, the `vendor.dll.js` file is auto generated so I don't think changing it will help.
If there is an issue (and I don't think there is), it's with `@angular/core` where this piece of code is taken from.
