### ISSUE TITLE
TypeScript doesn't recognize external moment.js module

### ISSUE THREAD

**Issue by juristr** [AngularClass/angular2-webpack-starter#141]
Hi,

maybe someone here can help me. I created a simple component with an external dependency to moment.js.

The src can be downloaded here: https://github.com/juristr/angular2-webpack-starter/blob/simple-component/src/app/datetime.ts

The problem is that I get a TypeScript error as it does not recognize the moment module:

![image](https://cloud.githubusercontent.com/assets/542458/11631966/fcdd67bc-9d04-11e5-82fe-61f8e4857993.png)

The app runs without issues, it's just a typings issue and I wonder how I can fix this.

**Comment by valorkin** [comment]
1. moment is not in typescript, so
2. import from `moment`
3. install typings via tsd

**Comment by juristr** [comment]
Hmm..I did step 3. If you look at the src branch I linked above, then you should see typings have been downloaded with TSD. I just don't know whether they are in the right location for this starter project.

Could u detail step 2? What do you mean "import from moment"?

**Comment by sasha7** [comment]
Maybe my solution will help. I installed moment with ```npm install moment``` and imported it in component like this ```const moment = require('moment');```

**Comment by valorkin** [comment]
@juristr ```import * as moment from 'moment'```

**Comment by juristr** [comment]
Got it to work.

@valorkin I had already installed `moment` via tsd.

What I had to do was the following.

**1. Reference the `tsd.d.ts` generated by `tsd` in `src/typings/_custom.d.ts`.**
```
/*
 * Our custom types
 */
/// <reference path="browser.d.ts" />
/// <reference path="webpack.d.ts" />
/// <reference path="./tsd/tsd.d.ts" />
``` 

Not sure that's the right place, but it definitely worked and looks clean to me.

**2. Moving the tsd typings to `src/typings` for more consistency**

Obviously this is not needed, but I found it more intuitive to have a single app-wide `typings` folder. For doing so I added a `tsd.json` ([src here](https://github.com/juristr/angular2-webpack-starter/blob/simple-component/tsd.json)). Maybe we should include this in this starter by default? What's your view on this @gdi2290 ? or does it interfere with your plans from issue #122 ?

**3. Change the `moment` import as suggested by @valorkin**

It now looks like this:

```javascript
import { Component } from 'angular2/angular2';
import * as moment from 'moment';

@Component({
	...
})
export class DateTimeCmp {
	...
}
```

TypeScript autocompletion now works as expected
![image](https://cloud.githubusercontent.com/assets/542458/11655886/7bf6381a-9db1-11e5-819f-bb25612da277.png)

Someone still has to explain me why I don't need any "path" in the import for moment while I need it for angular2. Is it 'cause `moment` is somehow "global"?? Otherwise I'll find it out :wink:

**Comment by valorkin** [comment]
check `moment` package.json `main` property
it routes to commonjs file with all required exports
angular2 doesn't have common entry point (nor main property, nor index.js)
so you have to declare entry point like `angular2/angular2` or `angular2/testing`
if issue is solved to you, I will close it

**Comment by juristr** [comment]
oh I see, thx a lot @valorkin.

What do u think of including by default the `tsd.json` and reference the `tsd.d.ts` directly from the `_custom.d.ts` in this seed project? Would help newbies to get started easier, don't you think?

**Comment by valorkin** [comment]
this kind of decisions is more up to @gdi2290 :)

**Comment by gdi2290** [comment]
we're planning on switching to `typings` rather than `tsd` since `typings` a superior typing manager. Thanks @valorkin for answering and closing the issue :+1:

**Comment by juristr** [comment]
@gdi2290 Cool, ya, that's what I was already guessing when I saw #122 . Thx for answering
