### ISSUE TITLE
cache problem

### ISSUE THREAD

**Issue by Viktor-Bredihin** [AngularClass/angular2-webpack-starter#1416]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**
npm run build:prod doesn't update hash of polyfills.bundle.js sometimes.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
For example I have added console.log() in one of my components, run build:prod, it updated 5.chunk.js hash but didn't update polyfills.bundle.js, so new 5.chunk.js ignored and old one used from cache.

* **What is the expected behavior?**
polyfils.bundle.js should be updated after any change in code, but it doesn't work so.

* **Please tell us about your environment:**

- Angular version: 2.4.4

**Comment by katallaxie** [comment]
@Viktor-Bredihin the hash is only changed, as the content changes. This is necessary for caching. So, the behavior is as expected, as `polyfills` has not changed, and doesn't needed to be invalidated.

**Comment by Viktor-Bredihin** [comment]
but I have cache issue, polyfills loading old chunk js with old logic

**Comment by Viktor-Bredihin** [comment]
![screenshot from 2017-01-25 19-11-02](https://cloud.githubusercontent.com/assets/2298048/22298593/1875f074-e332-11e6-8872-6255e4a4e0d2.png)

**Comment by Viktor-Bredihin** [comment]
here you can see that it's loading old chunk js file from cache instead of new one

**Comment by gdi2290** [comment]
click on `[ ] Disable Cache` in your screenshot

**Comment by Viktor-Bredihin** [comment]
yea, works fine for development, but what's about production? Should I ask all my users to click this checkbox? I thought that what for build:prod needs, to add hash and clear cache

**Comment by Viktor-Bredihin** [comment]
since it's not updating polyfills, and polyfills loading old chunks, I don't understand what's the point of build:prod and hash updating

**Comment by Viktor-Bredihin** [comment]
@katallaxie "the hash is only changed, as the content changes" - what content? I have changed html + component's logic, but polyfills still has the same hash

**Comment by katallaxie** [comment]
@Viktor-Bredihin because you have not added any new polyfills. Only if you add some polyfills the content of the underlying polylfilly bundle is changed. Then the hash of this file will change. Try it...add something to polyfills (e.g. the ie-shim).

**Comment by Viktor-Bredihin** [comment]
@katallaxie ok, but it's not solving my problem. The problem is that I have cache issues, chunk hash updates, but polyfills loads old versions

**Comment by katallaxie** [comment]
@Viktor-Bredihin Go it. Could you use https://github.com/webpack/webpack/blob/master/lib/HashedModuleIdsPlugin.js and test?!

**Comment by Viktor-Bredihin** [comment]
@katallaxie It works! Thank you, very appreciate your help. But you just removed this plugin and it works too, so what's better?

**Comment by katallaxie** [comment]
@Viktor-Bredihin the plugin has some various issues. So, I think it is best to just have it removed.

**Comment by Viktor-Bredihin** [comment]
@katallaxie cool thanks man!

**Comment by makdv** [comment]
@katallaxie, @Viktor-Bredihin, as I understand we should use md5-hash plugin  with webpack-inline-manifest plugin to exclude runtime info about mapping into separate script and inject it into html via html-webpack-plugin. What problems md5-hash plugin has?
