### ISSUE TITLE
Tests result in "Module not found: Error: Cannot resolve module 'angular2/test' "

### ISSUE THREAD

**Issue by yaroslavya** [AngularClass/angular2-webpack-starter#142]
Here are the steps I did:
`git clone https://github.com/AngularClass/angular2-webpack-starter.git`
`npm install `
after everything was installed( ofc made sure I installed the webpack globally ) I typed `npm test` in the console and I have the following error:
`ERROR in ./spec.bundle.js`
`Module not found: Error: Cannot resolve module 'angular2/test' in`

Do I need any other modules globally? Any help is appreciated.

**Comment by gdi2290** [comment]
thanks for reporting the error.
fixed via https://github.com/AngularClass/angular2-webpack-starter/commit/378ba30a16c12cf7db4b596e82786a06f1435dd5
