### ISSUE TITLE
Material Design

### ISSUE THREAD

**Issue by Antonystefano** [AngularClass/angular2-webpack-starter#1421]
How can I use Material Design with this project - "angular2-webpack-starter" ?

**Comment by d3viant0ne** [comment]
https://github.com/angular/material2

**Comment by Antonystefano** [comment]
Thank you for touch. But I've tried so many times without any success.
In the WebPack, there is no System.config.js. So that I can't load the material module.
Thank you.

**Comment by d3viant0ne** [comment]
It's webpack, System.config.js is a systemjs thing.

I would suggest starting here: https://webpack.js.org/

**Comment by Antonystefano** [comment]
1. npm install --save @angular/material
2. src/app/app.module.ts -> 
import { MaterialModule } from '@angular/material';
@NgModule({
  imports: [MaterialModule.forRoot()]
})
3. src/app/home/home.component.ts ->
import { MdCheckboxModule } from '@angular/material/checkbox/checkbox';
4. src/app/home/home.component.html ->
<button md-raised-button color="primary">PRIMARY</button>

Of course, the button was appeared, but primary is not working.
Please help me if you have time. I wanna you to save me from this issue.
Thank you.

**Comment by d3viant0ne** [comment]
https://github.com/jelbourn/material2-app
