### ISSUE TITLE
AOT: Images aren't emitted for html and css (Linux only)

### ISSUE THREAD

**Issue by Andrey-Pavlov** [AngularClass/angular2-webpack-starter#1428]
Because of https://github.com/shlomiassaf/ngc-webpack - overrideResource

See my issue: https://github.com/shlomiassaf/ngc-webpack/issues/4

**Comment by shlomiassaf** [comment]
Please check version 1.2.0 of `ngc-webpack`, should solve your issue.

I'd appreciate if you can replay with the results.

**Comment by shlomiassaf** [comment]
See #1451

**Comment by bmayen** [comment]
Can close this one, yes?
