### ISSUE TITLE
support question: refer html dom element in external library

### ISSUE THREAD

**Issue by shaikhspear16** [AngularClass/angular2-webpack-starter#1436]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

The above channels dont seem to be available currently, so posting a support question here.

* **I'm submitting a ...**
[ ] support question

I have a component that has html as follows:

      <div id="partners-slider" class="partners">
            <div class="partners__slider js-slick-slider">
              <a class="partners__item"><img src="assets/logo-company-1.png" alt="">Elite Construction Group, LLC</a>
              <a class="partners__item"><img src="assets/logo-company-2.png" alt="">Pro Era Limited</a>
             </div></div>

Its basically a slider.
I have a library that I use in a lot of projects, for animations and stuffs. 

Theres a function as follows that initiates a slider:

    function initPartnersSlider(container) {
    var $partnersSlider = $(container) ;
    if (!$partnersSlider.length) return;

    $partnersSlider
      .find('.js-slick-slider')
      .slick({
        dots: false,
        infinite: true,
        speed: 300,
        slidesToShow: 5,
        autoplay: true,
        accessibility: false,
        prevArrow: $partnersSlider.find('.js-partners-prev'),
        nextArrow: $partnersSlider.find('.js-partners-next'),
        responsive: [
          {
            breakpoint: 1100,
            settings: {
              slidesToShow: 4
            }
          },
          {
            breakpoint: 1000,
            settings: {
              slidesToShow: 3
            }
          },
          {
            breakpoint: 768,
            settings: {
              slidesToShow: 1
            }
          }
        ]
      });}

Function Call:
`initPartnersSlider('#partners-slider');`

Problem here is 

    $partnersSlider.length

is always 0.

As per my understanding, the html element is placed inside a minified file by webpack (prod)

> main.bundle.js

 I am referring my external javascript file inside index.html as a script tag. It doesnt seem to recognise the dom element with `id="properties-slider"` as the element is inside main.bundle.js?. I am able to debug and see it in my library code.

Has anyone done that before?
Thanks for any help!

**Comment by IvanBisultanov** [comment]
What do you have inside `container` variable?
```
var $partnersSlider = $(container) ;
```

**Comment by shaikhspear16** [comment]
Updated the question, basically initPartnersSlider method is called with id ref '#partners-slider'

`initPartnersSlider('#partners-slider');`

so 
`$(container) = $('#partners-slider');`

**Comment by IvanBisultanov** [comment]
We had same problem and we just wrap run slick code in setTimeout, not good solution but it works for us
```
setTimeout(() => {
      $(this.el.nativeElement.children).slick(this.local.options);
    }, 0);
```

**Comment by shaikhspear16** [comment]
It worked like a charm. Thank you, spent a lot of time over this, you saved me some more!!
