### ISSUE TITLE
Angular 2 Webpack for updating.

### ISSUE THREAD

**Issue by Antonystefano** [AngularClass/angular2-webpack-starter#1445]
Hi. Angular 2 Web Pack Team.
First I am gonna say thank you for WebPack developers.
I am so interesting for Webpack and cli.
Please help me some problems.
Thank you.

**Comment by bmayen** [comment]
Hi @Antonystefano. Stackoverflow is a more appropriate forum for general questions. Try to make your questions there more specific so people are better able to help you.
