### ISSUE TITLE
seperate main.js and vendor.js files in webpack:prod

### ISSUE THREAD

**Issue by shaikhspear16** [AngularClass/angular2-webpack-starter#1455]
* **I'm submitting a ...**
[ ] feature request

* **feature request** *
seperate files for main.js and vendor.js in webpack:prod build

* **current behavior**
main.js and vendor.js in webpack:prod build are compiled in same file

* **What is the expected behavior?**
seperate files for main.js and vendor.js in webpack:prod build

* **What is the motivation / use case for changing the behavior?**
User should not be forced to download new vendor.js file on each deployment as it hardly changes.

* **Please tell us about your environment:**

- Angular version: ~2.4.3
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by shlomiassaf** [comment]
@shaikhspear16 that's not what happens in my build....
![image](https://cloud.githubusercontent.com/assets/5377501/22584109/4f1d06ee-e9f9-11e6-81b2-8d40b38de608.png)

**Comment by shlomiassaf** [comment]
Also, it's not a feature request but a bug, if any...

Try to clone a fresh copy of the repo and see

**Comment by shaikhspear16** [comment]
I worked with a fresh copy.
