### ISSUE TITLE
Plus sign in front of component's name

### ISSUE THREAD

**Issue by jakub2** [AngularClass/angular2-webpack-starter#1456]
* **I'm submitting a ...**
[x] question about the decisions made in the repository

Hi, I'm new to this. Why are some components named with a plus sign? For example, +barrel, or +detail? What's the difference between a component without a '+' sign and the one that has it, please?

Thanks.

**Comment by katallaxie** [comment]
the `+` should indicate that this component is lazy loaded.

**Comment by maxkuzmin** [comment]
@katallaxie plus sign is not mentioned in official docs and it is not recommended to use according to https://github.com/angular/angular.io/issues/2944 answer.
