### ISSUE TITLE
undefined ViewChild in dynamic component with AOT

### ISSUE THREAD

**Issue by KhanaevRoman** [AngularClass/angular2-webpack-starter#1459]
**I'm submitting a ...**
**[ x ] bug report**
[ ] feature request
[ ] question about the decisions made in the repository

* **Bug report:**

When we try to insert AOT component to dynamic (JIT) component ViewChild in AOT is undefined. 

![image](https://cloud.githubusercontent.com/assets/20964736/22543682/ba9faf82-e942-11e6-9809-81c4e8b787e3.png)

* **Example:** 

Dynamic component: 
```
interface IDynamicComponent {
}

@Component({
  selector: 'dynamic',
  templateUrl: './dynamic.component.html'
})
export class MainDynamicComponent implements AfterViewInit {

  private template: string = `<p>Dynamic</p><aot-component>AOT component</aot-component>`;

  @ViewChild('container', {read: ViewContainerRef})
  container: ViewContainerRef;

  private componentRef: ComponentRef<IDynamicComponent>;

  ngAfterViewInit(){
    let factory = this.createComponentFactory(this.template);
    this.componentRef = this.container.createComponent(factory);
  }

  private createComponentFactory(template: string): ComponentFactory<IDynamicComponent> {

    @Component({template: template})
    class DynamicComponent implements IDynamicComponent {
    }

    @NgModule({
      declarations: [DynamicComponent],
      imports: [
        CommonModule,
        FormsModule,
        RouterModule,
        AOTModule
      ]
    })
    class DynamicModule {
    }

    let compiler = new JitCompilerFactory([{useDebug: true, useJit: true}]).createCompiler();
    return compiler.compileModuleAndAllComponentsSync(DynamicModule)
      .componentFactories.find(factory => factory.componentType === DynamicComponent);

  }
}
```
dynamic.component.html: 
```
<div #container></div>
```

AOT component: 
```
@Component({
  selector: 'aot-component',
  templateUrl: './aot.component.html'
})

export class AOTComponent implements AfterViewInit {

  @ViewChild('container', {read: ElementRef})
  public container: ElementRef;

  ngAfterViewInit() {
    console.log(this.container); //<- undefined here!
  }
}
```

aot.component.html:
```
<div #container>
  <ng-content></ng-content>
</div>
```

GitHub demo: https://github.com/KhanaevRoman/Dynamic-components-with-AOT
Reproduce: 
  npm install
  npm run-script build:aot:prod
  npm run-script server:prod

* **Expected behavior:**

ViewChild shall contains ElementRef with nativeElement for DOM manipulation.

* **Motivation / use case for changing the behavior:**

Need possibility to use AOT components with dynamic (JIT) components.

* **Environment:**

- angular version: 2.4.3-2.4.5
- webpack version: 2.2.0
- ngc-webpack version (Windows x64): 1.1.1-1.1.4, 1.2.0 (1.1.0 works)
- ngc-webpack version (Mac OS, Linux): 1.1.0-1.2.0
- node version: 4.2.1
- npm version: 3
- Browser: Chrome

**Comment by shlomiassaf** [comment]
The JIT compiler is not present when you compile AOT, that's what compiling AOT means otherwise it was JIT, right?

JIT compiler is not included in the bundle when you AOT compile, in your case you included it since you created a hard reference but it was not properly set, you can't just use it you need to hook it up with angular, when you AOT compile its not hooked, when you JIT compile it is automatically hooked by angular.

if you want to do JIT compilation with AOT you need to instantiate the JIT compiler through DI (providers) 

This is how to do it with lazy loading the JIT compiler in a different lazy-loaded NgModule.
https://github.com/shlomiassaf/lazy-jit

The JIT compiler is quite big so this is why you will want it to lazy load.
On of the main reasons for AOT is not bundling the JIT compiler, its 60% of angular.

Everything you need is in the referenced repository, other then that it's a support issue which we kindly ask to forward to the relevant forums.

**Comment by KhanaevRoman** [comment]
@shlomiassaf 
Thanks for your fast answer and your good job.
Problem was with NgcWebpackPlugin in default webpack.common.js:
```
new ngcWebpack.NgcWebpackPlugin({
        disabled: !AOT,
        tsConfig: helpers.root('tsconfig.webpack.json'),
        resourceOverride: helpers.root('config/resource-override.js')
      }),
```
After removing 'resourceOverride' dynamic creating work good with AOT compiling even with JitCompilerFactory.

As we understood this option do not remove from components source of HTML templates and JIT compiler can read and compile these templates.

So repeat. How is actually it works:
1. If components was compiled by AOT.
2. Some dynamic component wants to use one or more AOT components.
3. Shall JIT compiler recompile all component (templates, styles) used by dynamic component?
It means that we shall save all source html and styles after AOT compilation for JIT compiler.
Also we shall include JIT compiler to our project.
As result we will have: additional size of JIT compiler + all sources of components. 

Thanks a lot.
