### ISSUE TITLE
Add pagination feature

### ISSUE THREAD

**Issue by klihelp** [AngularClass/angular2-webpack-starter#1462]
Add pagination as starter feature.
eg:
https://github.com/michaelbromley/ng2-pagination

**Comment by shlomiassaf** [comment]
@klihelp Thank you for the suggestion.

We are not adding features that are not core or build related.

If we do, this repo will not help developers but confuse them. 
Think about the time it will take for a developer to remove those it does not need.

There are thousands of little feature, datatable, toaster, modals etc... we can't add them all.
