### ISSUE TITLE
showdown is not defined

### ISSUE THREAD

**Issue by Alezhka** [AngularClass/angular2-webpack-starter#1471]
I want add [Covalent](https://github.com/Teradata/covalent) in my project.

* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[x] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**

When i added td-markdown, i have a error:

![error](http://i.imgur.com/N4TYsOh.png)

I added `"@types/showdown": "^1.4.31"` in package.json, added showdown in tsconfig.json

```
"types": [
      "hammerjs",
      "jasmine",
      "node",
      "source-map",
      "uglify-js",
      "showdown",
      "webpack"
    ]
```
Also i added showdown in 'vendor', file: config/webpack.dev.js

```
vendor: [
            '@angular/platform-browser',
            '@angular/platform-browser-dynamic',
            '@angular/core',
            '@angular/common',
            '@angular/forms',
            '@angular/http',
            '@angular/router',
            '@angularclass/hmr',
            'rxjs',
            'showdown'
          ]
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

I created simple project:
[https://github.com/Alezhka/angular2-webpack-starter-covalent](https://github.com/Alezhka/angular2-webpack-starter-covalent)

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- OSX
- Angular version: 2.4.6
- Browser: [all]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by katallaxie** [comment]
it seems you just added the types for `showdown`. You also have to add the package itself.
