### ISSUE TITLE
Please add stylus support

### ISSUE THREAD

**Issue by dereklin** [AngularClass/angular2-webpack-starter#1475]
It's easy to add by the users.  Just do
```
npm install stylus-loader stylus --save-dev
```
But It will be nice to have it out of the box

It would be easier for people migrating from existing projects using stylus

I was thinking creating pull request for this but i don't have rights to create/commit to a branch

**Comment by MarkPieszak** [comment]
You need to Fork the project, then make your changes in a branch there, and then you can send pull requests :)

Also I believe the goal is to keep it simple (more unopiniated), there is information in the Wiki about adding SASS for example. Stylus would be almost identical.
https://github.com/AngularClass/angular2-webpack-starter/wiki/How-to-include-SCSS-in-components

**Comment by dereklin** [comment]
@MarkPieszak Thanks for the info on creating pull requests.

sass (.scss) is supported out of the box.  But stylus is not.   I just think it will be nicer for me and others to upgrade the build tool without having to reinstall other popular tools.
