### ISSUE TITLE
loadChildren broken

### ISSUE THREAD

**Issue by nmahefa** [AngularClass/angular2-webpack-starter#1485]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Report a bug 

* **What is the current behavior?**
loadChildren from Router seems to be broken with the new version of angular

* **Please tell us about your environment:**
- Angular version: 2.4.6
- Browser: [chrome]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
(dunno if a bug from angular to from angular class ) The loadChildren doesn't work as well, the following code : 
`const clickRoutes: Routes = [
  { path : '', redirectTo: 'login', pathMatch: 'full' },
  { path: 'login' ,    component    : LoginComponent },  
  { path: 'home'      , loadChildren : './home/home.component#homeModule'  },
  { path: '**'    ,    component    : NoContentComponent },
]`

they gave me an error:

> 'app' is not a known element

the other routes seems to be working.

**Comment by nmahefa** [comment]
Ok, i find why it didn't work :

the component don't like :

`templateUrl: ' `
    `<h1>Hello</h1>`
` '`

changed it to :
`templateUrl : '<h1>hello</h1>'`

**Comment by d3viant0ne** [comment]
fyi that should be 

```
template: `
    <h1>Hello</h1>
`
```

`templateUrl:` requires a path to an external template i.e. `some.component.html` and you need to use back ticks in ```template: ` ` ```
