### ISSUE TITLE
autoprefixer not works for imported scss files

### ISSUE THREAD

**Issue by Mentor-kh** [AngularClass/angular2-webpack-starter#1493]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
I'm not sure whether that means a bug or feature, but when I'm trying to brush my code with prefixes, its behavior seemed be wrong, or I'm doing wrong. 

* **What is the current behavior?**
While I import scss file directly at app.component.ts '../styles/styles.scss';  they were not added with prefixes. But using another your example with adding scss file directly at App Component with 
styleUrls: [ './app.component.scss' ], it become prefixable

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
here part of my app.component.ts:
```
import '../styles/styles.scss';
@Component({
  selector: 'app',
  encapsulation: ViewEncapsulation.None,
  styleUrls: [
    './app.component.scss'
],

```
here webpack.common.js:
```
{
    test: /\.scss$/,
    use: ['to-string-loader', 'css-loader', 'postcss-loader', 'sass-loader'],
    exclude: [helpers.root('src', 'styles')]
},
{
    test: /\.css$/,
    use: ['to-string-loader', 'css-loader', 'postcss-loader'],
    exclude: [helpers.root('src', 'styles')]
},
```

* **What is the expected behavior?**
I'm using your example with bootstrap 4 and expected to see not only vanilla css styling, I prefer use it with autoprefixer, which configured with postcss.config.js file and it works correct.

* **What is the motivation / use case for changing the behavior?**
compatibility of old versioned browsers

* **Please tell us about your environment:**

"@angular/common": "~2.4.3",
"webpack": "2.2.0",
"autoprefixer": "^6.7.2",
"postcss-loader": "^1.2.2",
"css-loader": "^0.26.1",
"sass-loader": "^4.1.1",
"to-string-loader": "^1.1.4",

please advise...

**Comment by derdiggn** [comment]
@Mentor-kh i hat the same problem. 

i fix this with the following steps 

1. follow the steps from https://github.com/postcss/autoprefixer
2. add postcss-loader to the scss settings in webpack.common.js and webpack.dev.js
3. add autoprefixer browser setting in postcss.config.js

here is my postcss.config.js
`module.exports = {
  plugins: [
    require('postcss-smart-import')({ }),
    require('precss')({ }),
    require('postcss-flexbugs-fixes'),
    require('autoprefixer')({
      browsers: '> 1%, last 2 versions, IE 11'
    })
  ]
}`

**Comment by Mentor-kh** [comment]
derdiggn, thanks! The reason was adding postcss at webpack.dev.js

**Comment by bobrosoft** [comment]
Just found: every config i.e. webpack.dev.js, webpack.prod.js, webpack.test.js overrides (s)css rules from webpack.common.js so 'postcss-loader' SHOULD BE ADDED INTO EVERY CONFIG.
