### ISSUE TITLE
Failed to load home.component.html

### ISSUE THREAD

**Issue by maxisam** [AngularClass/angular2-webpack-starter#1496]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[ X] bug report

* **What is the current behavior?**

I just download the whole project clean and run yarn from the beginning.

After npm start, the site can't start correctly. 

the error I got was
```
Failed to load home.component.html.
```
Apparently it trys to load the page from root but fail.

http://localhost:3000/home.component.html

My best guess is webpack's issue ?

* **Please tell us about your environment:**

I tried it on 2 machines. None of them works. Same error message.

npm 6.9.5 , npm 7.2 | Chrome

**Comment by szzProject** [comment]
same error

**Comment by maxx0r** [comment]
Related issue 
https://github.com/AngularClass/angular2-webpack-starter/issues/1484

can be fixed by fixing angular2-template-loader to 0.6.0 (0.6.1 is installed currently, which apperently breaks the build)
https://github.com/AngularClass/angular2-webpack-starter/issues/1484#issuecomment-277725743
