### ISSUE TITLE
Run Spring4MVC with Angular 2 application on a single server

### ISSUE THREAD

**Issue by rakshitshah94** [AngularClass/angular2-webpack-starter#1511]
I am new to angular2, I want to know what is the possible file structure for SpringMVC4 with angular 2?
![spring4mvcangularjscrudexample_img0](https://cloud.githubusercontent.com/assets/8470762/22795674/8a04df60-ef1d-11e6-94f8-7f8fc375bd4d.png)

As shown in image, it will work for Angular 1.x but file structure of Angular 2 is quite different and its component driven, and I am using angular 2 file structure as given below 

![exl8b](https://cloud.githubusercontent.com/assets/8470762/22795694/998ce298-ef1d-11e6-9fa8-4fad747d4a6b.jpg)

I searched a lot and I found that we can use Front end(using angular2) and back end(server- using spring/springboot) separately, but we need 2 server to run application. For example, Frontend : 192.168.100.1:4200 And Backend : 192.168.100.1:8080

So is there any way or general file structure to run both angular2 and spring4MVC on same server (like 192.168.100.1:8080)?

Thanks in advance. Answers will be appreciated!

**Comment by shlomiassaf** [comment]
Hi,

The issues section is for bugs and feature requests.

We would like to use the issues section for issues only, this will allow us to maintain a clean list of issues and be able to track and manage them efficiently.

for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

Thank you
