### ISSUE TITLE
Material md-progress-bar not visible when importing angular 2 material in Setup

### ISSUE THREAD

**Issue by rahulrsingh09** [AngularClass/angular2-webpack-starter#1514]
component file

<div class="loading-overlay" *ngIf="loading">
  Here
  <md-progress-bar mode="indeterminate"></md-progress-bar> // This Component dosent show up at all
</div>

ngModule

import { MaterialModule } from '@angular/material';
@NgModule({
  bootstrap: [ AppComponent],
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    RouterModule,
    routing,
    [MaterialModule.forRoot()]
  ],

})

**Comment by shlomiassaf** [comment]
Hi,

The issues section is for bugs and feature requests.

We would like to use the issues section for issues only, this will allow us to maintain a clean list of issues and be able to track and manage them efficiently.

for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

Thank you
