### ISSUE TITLE
Can I load custom javascript into my angular2 webpack component

### ISSUE THREAD

**Issue by mohan1304** [AngularClass/angular2-webpack-starter#1517]
I have a component "a.component.ts" and a java script file "b.js" with createGraph() as function. My requirement is to call createGraph() from "b.js" in "a.component.ts" Using systemJs approach I used to include "b.js" in index.html file and declare its function as "declare function createGraph():void;" in "a.component.ts". Now I converted my project to angular2 webpack and not sure how to call createGraph() from "b.js" in "a.component.ts" Please let me know if you have any suggestions.

**Comment by shlomiassaf** [comment]
Hi,

The issues section is for bugs and feature requests.

We would like to use the issues section for issues only, this will allow us to maintain a clean list of issues and be able to track and manage them efficiently.

for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

Thank you
