### ISSUE TITLE
How to place Bootstrap js and Jquery Js on vendor.bundle.js

### ISSUE THREAD

**Issue by jayapalt** [AngularClass/angular2-webpack-starter#1521]
Hi,

How to load Bootstrap.js, Jquery Js and other js from Vendor.bundle.js rather than loading from main app file. Because i want to keep all external lib away from angular Main code. I'm not able to keep it like angular core and other angular codes. And there is no **vendor.browser.ts** file to hold all the files separately. Could please let me know if there is a way

**Comment by shlomiassaf** [comment]
Hi,

The issues section is for bugs and feature requests.

We would like to use the issues section for issues only, this will allow us to maintain a clean list of issues and be able to track and manage them efficiently.

for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

Thank you
