### ISSUE TITLE
Lazy Loading a Module - problem

### ISSUE THREAD

**Issue by rKiest** [AngularClass/angular2-webpack-starter#1531]
Hi,

I use the latest angular2-webpack-starter
(https://github.com/AngularClass/angular2-webpack-starter)

angular: 2.4.6
webpack: 2.2.0
ng-router-loader: ^2.1.0

nodejs: 7.5
npm: 4.1.2

DetailModule, BarrelModule modules will be lazy loaded when the user clicks on the Detail/Barrel link.
Meanwhile, they are loaded at once together with other components.

I thought that the Modules that are lazily loaded will only be loaded when the user navigates to their routes.

Anyone know why this is happening ?

Thanks

**Comment by skriems** [comment]
afaik they are not loaded _lazily_ in a pure angular2 fashion. see [this comment](https://github.com/AngularClass/angular2-webpack-starter/blob/master/src/app/%2Bdetail/detail.component.ts#L5-L9)
and the _preloadingStrategy_ option the RouterModule receives in the AppModule.

**Comment by rKiest** [comment]
I see, thanks for the answer.

**Comment by shlomiassaf** [comment]
Look at the
