### ISSUE TITLE
Built files are much larger than angular-cli

### ISSUE THREAD

**Issue by antriver** [AngularClass/angular2-webpack-starter#1536]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**

The size of the files produced by this project are much larger than those produced by a "stock" angular project. The vendor file shows the most significant difference - 805KB vs 352KB.
Is there some flag or configuration I am missing?

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

```
git clone https://github.com/AngularClass/angular2-webpack-starter.git angular-app-webpack
npm install
npm run build:prod
ls -lh dist
total 1920
-rw-r--r--   1 Anthony  staff   1.2K 15 Feb 16:54 0.e7be5d0a075560dca796.chunk.js
-rw-r--r--   1 Anthony  staff   1.2K 15 Feb 16:54 1.f26a107876a0ce88298f.chunk.js
-rw-r--r--   1 Anthony  staff    64B 15 Feb 16:54 2.18c43ab534a82a55977e.chunk.js
-rw-r--r--   1 Anthony  staff   996B 15 Feb 16:54 5.da1abb86e9d037bbbeb6.chunk.js
-rw-r--r--   1 Anthony  staff   996B 15 Feb 16:54 6.aaf9720ec6c10efac8ca.chunk.js
drwxr-xr-x  11 Anthony  staff   374B 15 Feb 16:54 assets
-rw-r--r--   1 Anthony  staff   251B 15 Feb 16:54 humans.txt
-rw-r--r--   1 Anthony  staff   2.7K 15 Feb 16:54 index.html
-rw-r--r--   1 Anthony  staff   8.8K 15 Feb 16:54 main.5b8355c1fdf3f2713310.bundle.js
-rw-r--r--   1 Anthony  staff   118B 15 Feb 16:54 main.5b8355c1fdf3f2713310.bundle.map
-rw-r--r--   1 Anthony  staff   263B 15 Feb 16:54 main.d799841e5ce53c2fb9389a7567f94401.css
-rw-r--r--   1 Anthony  staff    94K 15 Feb 16:54 polyfills.b81dbe2dd41f8a21c703.bundle.js
-rw-r--r--   1 Anthony  staff    31B 15 Feb 16:54 robots.txt
-rw-r--r--   1 Anthony  staff   805K 15 Feb 16:54 vendor.ac01af4c312a36a0517c.bundle.js
-rw-r--r--   1 Anthony  staff   267B 15 Feb 16:54 webpack-assets.json
```

* **What is the expected behavior?**
File sizes closer to this:
```
ng new angular-app
cd angular-app/
ng build --prod
ls -lh dist
total 1064
-rw-r--r--  1 Anthony  staff   5.3K 15 Feb 16:49 favicon.ico
-rw-r--r--  1 Anthony  staff   704B 15 Feb 16:49 index.html
-rw-r--r--  1 Anthony  staff   1.4K 15 Feb 16:49 inline.ed8fc5e2b0a89cde7a89.bundle.js
-rw-r--r--  1 Anthony  staff    12K 15 Feb 16:49 main.6950728dcb37264ac7e8.bundle.js
-rw-r--r--  1 Anthony  staff   2.8K 15 Feb 16:49 main.6950728dcb37264ac7e8.bundle.js.gz
-rw-r--r--  1 Anthony  staff    54K 15 Feb 16:49 polyfills.763f03aa943676dfbdaa.bundle.js
-rw-r--r--  1 Anthony  staff    17K 15 Feb 16:49 polyfills.763f03aa943676dfbdaa.bundle.js.gz
-rw-r--r--  1 Anthony  staff     0B 15 Feb 16:49 styles.d41d8cd98f00b204e980.bundle.css
-rw-r--r--  1 Anthony  staff   352K 15 Feb 16:49 vendor.c40e1400846b72a7f2f2.bundle.js
-rw-r--r--  1 Anthony  staff    71K 15 Feb 16:49 vendor.c40e1400846b72a7f2f2.bundle.js.gz
```

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

```
ng --version

                             _                           _  _
  __ _  _ __    __ _  _   _ | |  __ _  _ __         ___ | |(_)
 / _` || '_ \  / _` || | | || | / _` || '__|_____  / __|| || |
| (_| || | | || (_| || |_| || || (_| || |  |_____|| (__ | || |
 \__,_||_| |_| \__, | \__,_||_| \__,_||_|          \___||_||_|
               |___/
@angular/cli: 1.0.0-beta.31
node: 6.9.1
os: darwin x64
@angular/common: 2.4.6
@angular/compiler: 2.4.6
@angular/core: 2.4.6
@angular/forms: 2.4.6
@angular/http: 2.4.6
@angular/platform-browser: 2.4.6
@angular/platform-browser-dynamic: 2.4.6
@angular/platform-server: 2.4.6
@angular/router: 3.4.6
@angular/compiler-cli: 2.4.6
```

```
webpack --version
2.2.1
node --version
v6.9.1
npm --version
4.0.5
```

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by shlomiassaf** [comment]
I don't know the cli very well but I think it might do an AOT build by default.

While you do a JIT build with the starter (`npm run build:prod`)

So you get the compiler in the vendor file, try `npm run build:aot:prod`

**Comment by antriver** [comment]
Thanks @shlomiassaf 
I just found this out today in a post on StackOverflow:

> Note: As of Angular CLI 1.0.0-beta.28 (released February 1st, 2017), --aot is on by default if --prod is specified.

Using `npm run build:aot:prod`, and stripping out some stuff from this starter project to make it comparable to a normal clean angular project, actually produced a smaller vendor file: 312KB with this vs 352KB

**Comment by shlomiassaf** [comment]
@antriver The underlaying compiler is the same (angular/compiler), the bundler is the same (webpack)

So it should be roughly the same
