### ISSUE TITLE
npm run server -> "ERROR in ./src/vendor.ts"  and "ERROR in ./src/bootstrap.ts"

### ISSUE THREAD

**Issue by Marco-exports** [AngularClass/angular2-webpack-starter#154]
ERROR in ./src/vendor.ts
Module build failed: Error: ENOENT: no such file or directory, open '/Users/Marco/Sites/exports-webpack/typings/main.d.ts'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at /Users/Marco/Sites/exports-webpack/node_modules/ts-loader/index.js:193:22
    at Array.forEach (native)
    at ensureTypeScriptInstance (/Users/Marco/Sites/exports-webpack/node_modules/ts-loader/index.js:190:17)
    at Object.loader (/Users/Marco/Sites/exports-webpack/node_modules/ts-loader/index.js:375:14)
 @ multi vendor

ERROR in ./src/bootstrap.ts
Module build failed: TypeError: Cannot read property 'getEmitOutput' of null
    at Object.loader (/Users/Marco/Sites/exports-webpack/node_modules/ts-loader/index.js:410:33)
 @ multi app

webpack: bundle is now VALID.

**Comment by blakeembrey** [comment]
Same issue mentioned in https://github.com/AngularClass/angular2-webpack-starter/issues/153

**Comment by Marco-exports** [comment]
**Thanks for your help...  followed your recommendation**

blakeembrey commented an hour ago
@mastertinner Try npm install tslint.
@Emnalyeriar @MischaZed Do a typings install.

**One error went away, and this remains**

ERROR in ./src/vendor.ts
(3,8): error TS2656: Exported external package typings file '/node_modules/reflect-metadata/reflect-metadata.d.ts' is not a module. Please contact the package author to update the package definition.

**Comment by blakeembrey** [comment]
What version is `reflect-metadata`? Looks like it was fixed in `0.1.2` - https://github.com/rbuckton/ReflectDecorators/commit/07dcd99c807a402b255065979d9485fbdc69924b.

**Comment by Marco-exports** [comment]
According to package.json

  "_from": "reflect-metadata@0.1.2",
  "_id": "reflect-metadata@0.1.2",

**Comment by blakeembrey** [comment]
Oh, I see now, missed it before. It's from https://github.com/AngularClass/angular2-webpack-starter/blob/master/src/vendor.ts#L3. Add `node_modules/reflect-metadata/reflect-metadata.d.ts` to your `tsconfig.json` file.

**Comment by Marco-exports** [comment]
Not sure what I must do.
Do I add a line inside the tsconfig.json file ?
Which tsconfig.json ?

**Comment by monokrome** [comment]
I think that the recommendation is to add `"node_modules/reflect-metadata/reflect-metadata.d.ts"` as a file in the **files** key of *tsconfig.json*. That doesn't seem to work here, however. Here's my config:

```json
{
  "compilerOptions": {
    "target": "ES5",
    "module": "commonjs",
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "sourceMap": true
  },
  "files": [
    "node_modules/reflect-metadata/reflect-metadata.d.ts",
    "typings/main.d.ts",
    "test/injector.spec.ts",
    "test/sanity-test.spec.ts",
    "src/app/app.spec.ts",
    "src/app/app.ts",
    "src/app/directives/x-large.ts",
    "src/app/directives/x-large.spec.ts",
    "src/app/providers/title.spec.ts",
    "src/app/providers/title.ts",
    "src/app/home/home.ts",
    "src/bootstrap.ts",
    "src/vendor.ts"
  ],
  "compileOnSave": false
}
```

**Comment by monokrome** [comment]
It looks like this works for the issue with **bootstrap.ts**, but doesn't solve for **vendor.ts**:

```json
{
  "compilerOptions": {
    "target": "ES5",
    "module": "commonjs",
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "sourceMap": true
  },
  "definitions": [
    "node_modules/reflect-metadata/reflect-metadata.d.ts"
  ],
  "files": [
    "typings/main.d.ts",
    "test/injector.spec.ts",
    "test/sanity-test.spec.ts",
    "src/app/app.spec.ts",
    "src/app/app.ts",
    "src/app/directives/x-large.ts",
    "src/app/directives/x-large.spec.ts",
    "src/app/providers/title.spec.ts",
    "src/app/providers/title.ts",
    "src/app/home/home.ts",
    "src/bootstrap.ts",
    "src/vendor.ts"
  ],
  "compileOnSave": false
}
```

**Comment by gdi2290** [comment]
thanks for opening an issue :+1: 
fix via https://github.com/AngularClass/angular2-webpack-starter/commit/c8f85ed0d9547c48fb598b36ab020229578623c6 and https://github.com/AngularClass/angular2-webpack-starter/commit/614e8d707b35155d642fd05c130e09ed208f29b1

**Comment by monokrome** [comment]
Thanks, @gdi2290! :)

**Comment by dewwwald** [comment]
@monokrome why does adding the files vendor, polyfills and app (in my case) to files resolve the issue?

**Comment by monokrome** [comment]
@dewwwald I have no idea :)
