### ISSUE TITLE
AoT build fail with ngx-perfect-scrollbar module

### ISSUE THREAD

**Issue by daominhsangvn** [AngularClass/angular2-webpack-starter#1541]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
I want to report a bug

* **What is the current behavior?**
I'm trying to install module [ngx-perfect-scrollbar](https://github.com/zefoy/ngx-perfect-scrollbar) and make AoT build. I got this error:
```
Error: Child compilation failed:
Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
    at Object.module.exports.pitch (...angular2-webpack-starter\node_modules\extract-text-webpack-plugin\loader.js:27:9):
Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
1. Clone the repository
2. install ngx-perfect-scrollbar via npm `npm install --save angular2-perfect-scrollbar`
3. Add ngx-pefect-scrollbar to `app.module.ts`

```

...

import {PerfectScrollbarModule} from 'angular2-perfect-scrollbar';
import {PerfectScrollbarConfigInterface} from 'angular2-perfect-scrollbar';
const PERFECT_SCROLLBAR_CONFIG: PerfectScrollbarConfigInterface = {
  suppressScrollX: true
};

...

@NgModule({
  ...
  imports: [ // import Angular's modules
    BrowserModule,
    FormsModule,
    HttpModule,
    RouterModule.forRoot(ROUTES, { useHash: true, preloadingStrategy: PreloadAllModules }),
    PerfectScrollbarModule.forRoot(PERFECT_SCROLLBAR_CONFIG),
  ],
  ...
})

...

```

* **What is the expected behavior?**
Build AoT without errors

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 2.4.6
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by derdiggn** [comment]
i use perfect-scrollbar to, have no problems.

**Comment by daominhsangvn** [comment]
Yeah, Good to know. But I'm using `ngx-perfect-scrollbar`, it's angular 2 module

**Comment by shlomiassaf** [comment]
@daominhsangvn The extract text plugin is trying to load (and extract) the css from that package, which is defined at the component level.

My suggestion is to block the extract plugin from running when styles are coming from node_modules

**Comment by derdiggn** [comment]
@daominhsangvn you use angular2-perfect-scrollbar this is the same that i use. 

When i check out the lastest starter and add this module it works without errors.

**Comment by daominhsangvn** [comment]
@derdiggn : I'm using that Plugin btw, did you try build AoT yet?

**Comment by daominhsangvn** [comment]
@shlomiassaf Thanks, that's a good point to start with.

**Comment by daominhsangvn** [comment]
ok Thanks @shlomiassaf for the point. I resolved this issue by exclude the angular2-perfect-scrollbar from ExtractTextPlugin and use css-loader combine with to-string-loader for angular2-perfect-scrollbar.

I'm not sure why the ExtractTextPlugin cannot find the css file of angular2-perfect-scrollbar but this is just work around.

Anyway, problem solved. Closed!

**Comment by qtruongbk** [comment]
@daominhsangvn 
Chào anh, em đang gặp vấn đề tương tự, anh có thể chỉ cho em cách được không? vietsub trên github cho máu
