### ISSUE TITLE
Hot module reload/hmr is not much faster than without

### ISSUE THREAD

**Issue by dereklin** [AngularClass/angular2-webpack-starter#1553]
I have just done a not so scientific comparison between npm run start:hmr and npm start.  I am just changing some html.  hmr takes 3 to 4 seconds to reload.  non-hmr, takes maybe 4.5 seconds.  Is 3 to 4 seconds the fastest speed hmr can go? (I have a pretty fast and modern laptop)

**Comment by Torqode** [comment]
You won't notice an appreciable difference with HMR until you work with a larger project.

I have an app with 50+ components split into several lazy loaded modules.  A regular build takes 90 seconds, while an HMR compile/reload takes around 10 seconds.

**Comment by dereklin** [comment]
OK. hopefully the fastest speed can be improved in the future.
