### ISSUE TITLE
Sizes of app.js and vendor.js

### ISSUE THREAD

**Issue by jamesthurley** [AngularClass/angular2-webpack-starter#158]
Thanks for this repo, it's very helpful!  I was surprised after cloning and building unoptimised (npm run build) that the `app.js` file is 4.8MB, `vendor.js` is 5.45MB while `common.js` is only 4.65kB.  Even with the `--optimize-minimize` switch the `app.js` file is still 577kB.

Looking inside `app.js` there seems to be a lot of Angular in there, when I was expecting that to be in `vendor.js`.

I'm fairly new to WebPack, so I was wondering if someone could help me understand what is happening here.  If vendor modules required by the application are being bundled into `app.js` then what is the purpose of `vendor.js`?  Or if they should not be, then why is `app.js` so large?

**Comment by jamesthurley** [comment]
Ok, I think I've worked out the problem....

Starting with everything fresh again, the `webpack.config.js` contains these lines:

```
  plugins: [
    new CommonsChunkPlugin({ name: 'vendor', filename: 'vendor.js', minChunks: Infinity }),
    new CommonsChunkPlugin({ name: 'common', filename: 'common.js', minChunks: 2, chunks: ['app'] })
  ],
```
And I get this output:
```
     Asset     Size  Chunks             Chunk Names
    app.js   4.8 MB    0, 2  [emitted]  app
 vendor.js  5.45 MB    1, 2  [emitted]  vendor
 common.js  3.65 kB       2  [emitted]  common
   app.map  5.11 MB    0, 2  [emitted]  app
vendor.map  5.91 MB    1, 2  [emitted]  vendor
common.map  3.68 kB       2  [emitted]  common
```

Removing the `chunks` property from the common chunk:
```
  plugins: [
    new CommonsChunkPlugin({ name: 'vendor', filename: 'vendor.js', minChunks: Infinity }),
    new CommonsChunkPlugin({ name: 'common', filename: 'common.js', minChunks: 2 })
  ],
```
Give this:
```
     Asset     Size  Chunks             Chunk Names
    app.js  7.31 kB    0, 2  [emitted]  app
 vendor.js  5.45 MB    1, 2  [emitted]  vendor
 common.js  3.65 kB       2  [emitted]  common
   app.map  8.14 kB    0, 2  [emitted]  app
vendor.map   5.9 MB    1, 2  [emitted]  vendor
common.map  3.67 kB       2  [emitted]  common
```
And finally putting both entries into the chunks property:
```
  plugins: [
    new CommonsChunkPlugin({ name: 'vendor', filename: 'vendor.js', minChunks: Infinity }),
    new CommonsChunkPlugin({ name: 'common', filename: 'common.js', minChunks: 2, chunks: ['app', 'vendor'] })
  ],
```
Gives this:
```
     Asset     Size  Chunks             Chunk Names
    app.js  7.31 kB       0  [emitted]  app
 vendor.js   652 kB       1  [emitted]  vendor
 common.js   4.8 MB       2  [emitted]  common
   app.map  8.14 kB       0  [emitted]  app
vendor.map   800 kB       1  [emitted]  vendor
common.map  5.11 MB       2  [emitted]  common
```

Which appears to be using the files correctly.

**Comment by gdi2290** [comment]
fixed by your pr https://github.com/AngularClass/angular2-webpack-starter/pull/159, thanks again

**Comment by zainul-realtime** [comment]
why common js is big size ? its downloaded to client side, its probably make slow  ?
