### ISSUE TITLE
Fresh clone | Getting "ERROR in Assigning to rvalue" when "npm run build:prod"

### ISSUE THREAD

**Issue by gabrielgodoy** [AngularClass/angular2-webpack-starter#1583]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Report a bug

* **What is the current behavior?**
First I run `npm install`
When I run `npm run build:prod` I get the error **ERROR in Assigning to rvalue (1:4291)**

* **What is the expected behavior?**

Build the project for production

**Comment by bartholomej** [comment]
After a quick look, the problem is here: https://github.com/AngularClass/angular2-webpack-starter/blob/master/config/webpack.prod.js#L134

**Comment by marcel-goedhart** [comment]
we've had the same problem yesterday suddenly, but it disappeared in our nightly build, it looked like some dependency was updated that caused the problem.

**Comment by gabrielgodoy** [comment]
I did a fresh install today and the problems seems to be resolved. Maybe was some dependency problem that was resolved. Closing this issue for now.
