### ISSUE TITLE
Upgrade abnormal

### ISSUE THREAD

**Issue by 392475992** [AngularClass/angular2-webpack-starter#1596]
I has a lot on the frame after upgraded warning。

[WDS] Warnings while compiling.
webpack-dev-server.js:3 ./src/app/environment.ts
[11, 26]: non-arrow functions are forbidden
[29, 21]: missing whitespace
[31, 11]: missing whitespace
[32, 11]: missing whitespace。

These warnings are not I need, could you tell me how to block it

**Comment by bmayen** [comment]
These are tslint warnings. You could disable tslint entirely if you don't want warnings of any kind, or you could adjust the tslint.json config to your liking.

**Comment by 392475992** [comment]
Thank you, done
