### ISSUE TITLE
cannot seem to get bootstrap 3 to work

### ISSUE THREAD

**Issue by adowning** [AngularClass/angular2-webpack-starter#16]
Have tried loading bs3 w/ webpack, from the index file and even from the home css. Never can get it to play nice with jquery.

Any suggestions?

**Comment by gdi2290** [comment]
@adowning do you have a link to your repo? I want to see how you're adding it and to see if I can provide better instructions. Including bootstrap is a great idea, ideally I wanted to include Material Design components when they're available

**Comment by lightswitch05** [comment]
A big :+1: to Material Design, but having an example for bootstrap would be nice too

**Comment by valorkin** [comment]
no problem, I can add one :)

**Comment by gdi2290** [comment]
this will be solved via @valorkin's ng2-bootstrap module which supports bootstrap versions 3 and 4
