### ISSUE TITLE
Critical dependencies ./~/zone.js/dist/zone-microtask.js

### ISSUE THREAD

**Issue by leshin** [AngularClass/angular2-webpack-starter#161]
./~/zone.js/dist/zone-microtask.js
Critical dependencies:
1:113-120 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/zone.js/dist/zone-microtask.js 1:113-120

**Comment by gdi2290** [comment]
you might have downloaded a version of the repo without this change
https://github.com/AngularClass/angular2-webpack-starter/blob/master/webpack.config.js#L66

**Comment by gdi2290** [comment]
also related https://github.com/AngularClass/angular2-webpack-starter/issues/160 I'm going to close this unless you hit this problem again
