### ISSUE TITLE
Can't change the folder name "angular2-webpack-starter"

### ISSUE THREAD

**Issue by lhc069** [AngularClass/angular2-webpack-starter#1613]
i tried to rename the folder name but it didn't work, is there any way that i can use my customized name instead of angular2-webpack-starter when setting up the starter?

Thanks!
Clark

**Comment by vaudy** [comment]
how did you clone this project?
you can do `git clone https://github.com/AngularClass/angular2-webpack-starter your-custom-folder`

**Comment by gdi2290** [comment]
it looks like the issue was solved by the comment above

Thank you for the issue. Please follow issue https://github.com/AngularClass/angular2-webpack-starter/issues/1686 for updates into Angular version 4+
