### ISSUE TITLE
Zone is not defined with Angular 2 beta 0

### ISSUE THREAD

**Issue by jamesthurley** [AngularClass/angular2-webpack-starter#162]
If I clone `https://github.com/AngularClass/angular2-webpack-starter.git` and then update the `package.json` to Angular 2 beta 0 by updating dependencies like so:

```
    "angular2": "2.0.0-beta.0",
    "rxjs": "5.0.0-beta.0",
    "zone.js": "0.5.10"
```

Then test the website with `npm start` and navigating to `http://localhost:3000/`, angular fails to load and I get an error in the console of:

```
Uncaught ReferenceError: Zone is not defined 
NgZone._createInnerZone @ ng_zone.js:325NgZone @ ng_zone.js:117createNgZone @ application_ref.js:52PlatformRef_.application @ application_ref.js:153bootstrap @ browser.js:101main @ bootstrap.ts:20run @ core.js:96zoneBoundFn @ core.js:69
```

Any ideas?

**Comment by gdi2290** [comment]
can you download the latest changes to the starter repo? I pushed a fix to this any a few others last night

**Comment by jamesthurley** [comment]
Sorry @gdi2290, you're absolutely right - the latest runs perfectly, thank you!

Incidentally, doing a fresh clone and `npm install` gave me this:

```
npm ERR! peerinvalid The package es6-shim@0.34.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer angular2@2.0.0-beta.0 wants es6-shim@^0.33.3
```

I downgraded to 0.33.3 thought and it's fine... is that the correct thing to do?

**Comment by gdi2290** [comment]
Angular2 needs to update their repo to accept anything higher than 0.33.3 tbh. Can you make a pull request to lower the version so we won't see the warning

**Comment by jamesthurley** [comment]
Done.

One more thing, I noticed in Angular's angular2-seed project they do `import 'angular2/bundles/angular2-polyfills';` to handle their polyfills:

https://github.com/angular/angular2-seed/blob/master/src/vendor.ts#L1

I tried changing your `vendor.cs` polyfills section to use that and it seems to work fine, so might be a nice simplification.  I can do a PR if you agree.

**Comment by gdi2290** [comment]
I did the PR for the one in that repo :p there is more benefit if we manually do it (sourcemaps)

**Comment by jamesthurley** [comment]
Ha, ok, makes sense!
