### ISSUE TITLE
Common.js - why?

### ISSUE THREAD

**Issue by jbazinga** [AngularClass/angular2-webpack-starter#164]
Dear Angularclass!

Thanks for the project, I love it, but I would like to ask why is common.js used? What is the benefit of it? Because If we can not define a common chunk, and do not include it in index.html, then the app works well.

Thanks

**Comment by gdi2290** [comment]
common.js is included in our [index.html#L42](https://github.com/AngularClass/angular2-webpack-starter/blob/2baa3b087c1e286b8a8298b5600bdbd4ccce81df/src/public/index.html#L42) I added the file so it's much easier for developer to do code splitting if they need to lazy load sections of their app

**Comment by jbazinga** [comment]
I see, thanks
