### ISSUE TITLE
Angular 4  server side rendering support

### ISSUE THREAD

**Issue by jbeckton** [AngularClass/angular2-webpack-starter#1641]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[ ] bug report
[ x] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**

no Universal or Angular 4 server side rendering

* **What is the motivation / use case for changing the behavior?**

would like to use this starter project for a nodejs site that utilized server side rendering or Angular Universal

**Comment by gdi2290** [comment]
Thank you for the issue. Please follow issue https://github.com/AngularClass/angular2-webpack-starter/issues/1686 for updates into Angular version 4+ with server rendering
