### ISSUE TITLE
No diff between AoT and JIT

### ISSUE THREAD

**Issue by albandaft** [AngularClass/angular2-webpack-starter#1642]
Is AoT the default build or JIT?
I see no difference in the build commands.

How to enable one or the other?

**Comment by Torqode** [comment]
The default (using`npm build`) is a dev build, which is JIT.  For AoT, use `npm run build:aot`

From [README.MD](https://github.com/AngularClass/angular2-webpack-starter#build-files):

# development
npm run build:dev
# production (jit)
npm run build:prod
# AoT
npm run build:aot

**Comment by albandaft** [comment]
@Torqode please have a look at the package.json
```
  "build:aot:prod": "npm run clean:dist && npm run clean:aot && webpack --config config/webpack.prod.js  --progress --profile --bail",
    "build:aot": "npm run build:aot:prod",
    "build:dev": "npm run clean:dist && webpack --config config/webpack.dev.js --progress --profile",
    "build:docker": "npm run build:prod && docker build -t angular2-webpack-start:latest .",
    "build:prod": "npm run clean:dist && webpack --config config/webpack.prod.js  --progress --profile --bail",
```

As you can see the `build:aot` is just running `build:aot:prod` which at the end just runs ` webpack --config config/webpack.prod.js  --progress --profile --bail` which is the same as `build:prod`.

**Comment by Torqode** [comment]
Yes, in that regard they are the same.  The difference is that the :aot flag is parsed out in [webpack.common.js](https://github.com/AngularClass/angular2-webpack-starter/blob/master/config/webpack.common.js#L28) to determine if AoT should be performed or not.

**Comment by albandaft** [comment]
Nice spot. What about the tsconfig.json?

**Comment by Torqode** [comment]
It will always use `tsconfig.webpack.json`.  I'm guessing the repo includes a normal tsconfig so that IDEs like Visual Studio can compile the Typescript without affecting the Webpack build process.

**Comment by albandaft** [comment]
Closing as the AOT identification is actually in the parameters detection
