### ISSUE TITLE
IE 11 error when use *ngFor for array of objects

### ISSUE THREAD

**Issue by Viktor-Bredihin** [AngularClass/angular2-webpack-starter#1668]
* **I'm submitting a ...**
[ x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**
Error in IE11 when I try to use *ngFor for array of objects

* **Please tell us about your environment:**

- Angular version: 2.4.3
- Browser: [IE11 ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
http://stackoverflow.com/questions/43206736/angular2-ngfor-array-of-objects-ie11-error

**Comment by Viktor-Bredihin** [comment]
I had to add core-js to index.html to repair that, I don't know why, considering that it should be loaded by webpack (it's in polyffils.browser.ts)

**Comment by gdi2290** [comment]
it looks like the issue was solved by the comment above

Thank you for the issue. Please follow issue https://github.com/AngularClass/angular2-webpack-starter/issues/1686 for updates into Angular version 4+
