### ISSUE TITLE
webpack-dev-server over https error

### ISSUE THREAD

**Issue by jbazinga** [AngularClass/angular2-webpack-starter#167]
Hi,

I am using my sample application in c9.io, and it is uses https. The problem is: webpack-dev-server uses sockjs-node, and try to download it from http -not https. How can I solve it?

I try to run the webpack-dev-server with --https , or add the https:true to devServer, but it is not solve my problem.

Thanks

**Comment by gdi2290** [comment]
this is a `webpack-dev-server` question.
I think you need to use `--https` rather than `--http`
https://webpack.github.io/docs/webpack-dev-server.html

**Comment by jbazinga** [comment]
Yes, that is what I tried....

**Comment by gdi2290** [comment]
with https you have to give it self-signed certificate files to run https locally

**Comment by gdi2290** [comment]
you probably have to remove Inline mode via `--inline` from package and manually include it with the correct protocol
