### ISSUE TITLE
Unable to run tests after upgrade to Angular 4

### ISSUE THREAD

**Issue by jakub2** [AngularClass/angular2-webpack-starter#1678]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
After upgrading to Angular 4, when I run `npm run test`, I get the following error:
```
λ npm run test

> kpi-se-ang@1.0.0 test c:\web-my\kpi-se-ang
> npm run lint && karma start


> kpi-se-ang@1.0.0 lint c:\web-my\kpi-se-ang
> npm run tslint "src/**/*.ts"


> kpi-se-ang@1.0.0 tslint c:\web-my\kpi-se-ang
> tslint "src/**/*.ts"


START:

[at-loader] Using typescript@2.2.2 from typescript and "tsconfig.json" from c:\web-my\kpi-se-ang/tsconfig.json.


[at-loader] Checking started in a separate process...

[at-loader] Ok, 0.971 sec.
Hash: 0d07aa6d695a7aacd7b6
Version: webpack 2.3.1
Time: 20057ms
                Asset       Size  Chunks                    Chunk Names
          0.bundle.js  690 bytes       0  [emitted]
config/spec-bundle.js    8.39 MB       1  [emitted]  [big]  config/spec-bundle.js

WARNING in ./~/@angular/core/@angular/core.es5.js
5870:15-36 Critical dependency: the request of a dependency is an expression

WARNING in ./~/@angular/core/@angular/core.es5.js
5886:15-102 Critical dependency: the request of a dependency is an expression

ERROR in ./src/app/home/x-large/x-large.directive.spec.ts
Module not found: Error: Can't resolve '@angular/platform-browser/src/dom/debug/by' in 'c:\web-my\kpi-se-ang\src\app\home\x-large'
 @ ./src/app/home/x-large/x-large.directive.spec.ts 6:11-64
 @ ./src \.spec\.ts
 @ ./config/spec-bundle.js
Chrome 57.0.2987 (Windows 7 0.0.0) ERROR
  Uncaught Error: Cannot find module "@angular/platform-browser/src/dom/debug/by"
  at webpack:///src/app/home/x-large/x-large.directive.spec.ts:6:0 <- config/spec-bundle.js:72251
Chrome 57.0.2987 (Windows 7 0.0.0) ERROR
  Uncaught Error: Cannot find module "@angular/platform-browser/src/dom/debug/by"
  at webpack:///src/app/home/x-large/x-large.directive.spec.ts:6:0 <- config/spec-bundle.js:72251

Finished in 2.691 secs / 0 secs @ 17:22:17 GMT+0200 (W. Europe Daylight Time)

SUMMARY:
√ 0 tests completed
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kpi-se-ang@1.0.0 test: `npm run lint && karma start`
npm ERR! Exit status 1](url)
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).
N/A

* **What is the expected behavior?**
Run the tests.

* **What is the motivation / use case for changing the behavior?**
Upgrade to Angular 4, then run the tests (`npm run test`).
N/A

* **Please tell us about your environment:**

- Angular version: 4.0.1
- Webpack 2.3.1
- Browser: [all]
- Windows 7
- npm 4.4.4
- node 6.10.2

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
N/A

**Comment by jakub2** [comment]
I fixed it by modifying the x-large.directive.spec.ts file. This is the correct import:
`import { By } from '@angular/platform-browser';`

**Comment by gdi2290** [comment]
Thank you for the issue it seems like it was solved via comment above. Please follow issue https://github.com/AngularClass/angular2-webpack-starter/issues/1686 for updates into Angular version 4+
