### ISSUE TITLE
Continuing support for this project?

### ISSUE THREAD

**Issue by bmayen** [AngularClass/angular2-webpack-starter#1684]
I see this question being asked in the comments of a few other issues, so perhaps it's useful to track it separately.

What is the status of this project? Are there plans to continue supporting it? There are quite a few PRs and issues which are not receiving attention and it seems like the project is falling behind. Is there intention to maintain this more actively in the future?

The work done here has been immensely valuable to us, and it is greatly appreciated, but it would be helpful to know where it's headed. I have a build system and a few projects based off of this. As Angular and Webpack quickly move forward, I think a lot of people in the same boat are getting to the point where we need to decide to continue using and contributing to this project or move to something more active.

Any feedback you could provide to help us understand the future state of things would be appreciated.

**Comment by wvesteraas** [comment]
It should be called angular-webpack-starter

**Comment by admosity** [comment]
I am looking to fork/maintain this repo, but haven't quite gotten a response.

I've posted my concerns and updates I've done to the stack over here awhile back:
https://github.com/AngularClass/angular2-webpack-starter/issues/968#issuecomment-290095324

**Comment by bmayen** [comment]
@admosity, yours was one of the comments which inspired this issue :)

**Comment by gdi2290** [comment]
I will update this repo this weekend

**Comment by gdi2290** [comment]
I'm redoing everything and changing the repo name

**Comment by gdi2290** [comment]
Thank you for the issue. Please follow issue https://github.com/AngularClass/angular2-webpack-starter/issues/1686 for updates
