### ISSUE TITLE
ng2-bootstrap + bootstrap 4.0 implementation

### ISSUE THREAD

**Issue by louisscruz** [AngularClass/angular2-webpack-starter#169]
How should I go about installing Bootstrap 4.0 and ng2-bootstrap? I've attempted adding code from the PRs at https://github.com/AngularClass/angular2-webpack-starter/pull/127, but I get an error: `Module parse failed [...] Unexpected token You may need an appropriate loader to handle this file type.`

I am new to Webpack, which I'm guessing is my shortcoming here.

**Comment by valorkin** [comment]
Yeap, remove node_modules from ignore

**Comment by lanocturne** [comment]
At ts loader for exclude property, use this code
`
exclude: [ /\.spec\.ts$/, /\.e2e\.ts$/,
					/node_modules\/(?!(ng2-bootstrap))/
`

**Comment by louisscruz** [comment]
Fantastic. That does it. Thanks!

**Comment by gdi2290** [comment]
this update should fix this problem for future developers https://github.com/AngularClass/angular2-webpack-starter/commit/cac643d3ad6b07d05c58ccb8e319bf852d572245

**Comment by manavsehgal** [comment]
Opened #199 to consolidate these issues.
