### ISSUE TITLE
preloading of lazy loaded modules not working  with  aot 

### ISSUE THREAD

**Issue by gomesNazareth** [AngularClass/angular2-webpack-starter#1692]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by gdi2290** [comment]
can you reopen with more info

**Comment by gomesNazareth** [comment]
I am using aot build with lazy loading. 

The app.routes are defined as 
```
{ path: 'home',children:[...PublicPageRoutes] ,canLoad: [CanLoadGuard] },
{ path: 'jobseeker', loadChildren: './jobseekers#JobseekerModule',,canLoad[CanLoadGuard] }

```
In the AppModule I activated preloading as below

```
@NgModule({
  bootstrap: [ AppComponent ],
  declarations: [
    AppComponent,
    InvalidPageComponent,
    UnAuthPageComponent,
    SwitchPageComponent,
    AboutComponent,
    RedirectComponent,
    HomeComponent,
    NoContentComponent,
    XLargeDirective
  ],
  imports: [ // import Angular's modules
    BrowserModule,
    PublicPageModule,
    DisplayBlockModule,
    FormsModule,
    HttpModule,
    RouterModule.forRoot(ROUTES, { useHash: false, preloadingStrategy: PreloadAllModules })
  ],
  providers: [ // expose our Services and Providers into Angular's dependency injection
    ENV_PROVIDERS,
    APP_PROVIDERS
  ]
})
export class AppModule {}

```
The jobseeker routes  are as followers


export const JobSeekerRoutes = RouterModule.forChild([

```
    { path: 'about', component: AboutComponent},
    { path: 'contactus', component: ContactusComponent},
    { path: 'terms', component: TermsComponent},
    { path: 'policy', component: PolicyComponent},
    { path: 'settings', loadChildren: '../core/account/account.module#AccountModule',data: {preload: true} },
    // { path: 'blog', loadChildren: './app/core/blog/blog.module#BlogModule' },
    { path: 'blog', loadChildren: './blog/listBlog.module#ListBlogModule',data: {preload: true} },
    { path: 'companies', loadChildren: './company/company.module#CompanyModule',data: {preload: true} },
    { path: 'jobs', loadChildren: './job/job.module#JobModule' ,data: {preload: true}},
    { path: 'dashboard', loadChildren: './dashboard/dashboard.module#DashboardModule',data: {preload: true} },
    { path: 'profile', loadChildren: './profile#ProfileModule',data: {preload: true} },
]);
```

Now when i open a link such as /jobseeker/jobs .The page takes about 4 to 5 seconds to open for the first time. This is because the jobseeker module did not pre load. This is my Issue.

Is there any way i can fix this issue?
