### ISSUE TITLE
dist is notworking 

### ISSUE THREAD

**Issue by gmchaturvedi1** [AngularClass/angular2-webpack-starter#174]
hello friend
i am new to webpack and angular2
can someone help for production
because when i run command
npm run build and copy index.html and those file in one folde is notworing
but my js file is not working

**Comment by OverclockedTim** [comment]
I'm sure there are a million ways to fix this.  I got it working by changing the webpack config to output the build files into /src/public/ instead of /public/ and then deploying out of /src/public

**Comment by gdi2290** [comment]
I'm working on a new build config to make this more clear

**Comment by manavsehgal** [comment]
I tried copying ```__build__``` folder and contents of ```/src/public/``` into a separate folder for production run from a single folder. Most PaaS/Cloud deploy CLI require single folder as source for deploy. This needs to be part of ```build:prod``` within the starter, rather than an external hack (smiles).

**Comment by gdi2290** [comment]
done via https://github.com/AngularClass/angular2-webpack-starter/compare/cf4b3f2bf4fc74de37aa6af05a891d29c7c2d0a8...master
