### ISSUE TITLE
comon and vendor bundle are almost empty

### ISSUE THREAD

**Issue by kampdomoj** [AngularClass/angular2-webpack-starter#177]
Hi,

I am trying to implement webpack in my own Angular2 project, using your project as an example. 
For some reason the common and vendor bundles stay very short, only calling System.register with all the required modules. Why would webpack use System.register in my case, and concatenate all required files in your case...?? I am trying to find out why.... Any hint?

**Comment by gdi2290** [comment]
System.register shouldn't be used so I need to see how you set up your build

**Comment by kampdomoj** [comment]
See https://github.com/kampdomoj/Test2

**Comment by kampdomoj** [comment]
I added the __build files, so you can see the result

**Comment by kampdomoj** [comment]
Solved!!!  :-)

I had other tsconfig parameters (system instead of commonjs) and another moduleResolution

Now the compiler has the same behavior as in your sample.

By the way: why do you have your own polyfills.ts? 
Isn't it enough to include the angular2-polyfills file?

**Comment by gdi2290** [comment]
I used my own polyfill for source maps and better universal module support. I'm going to close this since I'm also in the middle of changing the process for dist/ and production
