### ISSUE TITLE
can not access url in vagrant-based linux from host

### ISSUE THREAD

**Issue by davidxiao** [AngularClass/angular2-webpack-starter#179]
Hi, 
  I am using angular2-webpack-starter from vagrant-based linux, while can not access the url from host, not explicit error message from terminal.
  Vagrant version: 1.7.2

**Comment by davidxiao** [comment]
after doing some research, fixed the issue by reseting the default host to : 0.0.0.0, instead of localhost in package.json in root directory,
do we need to update in the template repo?

**Comment by datatypevoid** [comment]
@davidxiao What exactly did you do to alleviate this issue?
