### ISSUE TITLE
How to deploy?

### ISSUE THREAD

**Issue by louisscruz** [AngularClass/angular2-webpack-starter#180]
I'm new to Webpack. There is a copy of my project on my server. When I run `npm run build` on the server, I get a `__build__` folder. However, when I run `node app.js` within this folder, I get the following error: ReferenceError: webpackJsonp is not defined. Being that I've never deployed a TS project before, I assume that there is some fundamental error in my understanding of Webpack deployment. What should I do?

**Comment by louisscruz** [comment]
I should add that I've read https://github.com/AngularClass/angular2-webpack-starter/issues/174, but the actual deployment process is still unclear to me.

**Comment by gdi2290** [comment]
I included dist folder so now you would build the repo into a dist/ with production mode. see changes https://github.com/AngularClass/angular2-webpack-starter/compare/cf4b3f2bf4fc74de37aa6af05a891d29c7c2d0a8...master
