### ISSUE TITLE
Separate dev/prod configs

### ISSUE THREAD

**Issue by manavsehgal** [AngularClass/angular2-webpack-starter#182]
Can we add separate dev/prod config settings which apply depending on context? 

Currently production settings need to be commented out (debug:true) or changed (devtool: 'eval') in webpack.config between dev/prod scenarios. This is not ideal.

There are two prevalent solutions for separate webpack dev/prod configs. 
(1) Using npm webpack-merge  and environment variables to TARGET dev/prod in same config file. [SurviveJS implementation](http://survivejs.com/webpack_react/developing_with_webpack/)
(2) Using two separate webpack.config files for dev/prod. This is more common solution on most projects I have studied.

**Comment by gdi2290** [comment]
I have this and https://github.com/AngularClass/angular2-webpack-starter/issues/174 done locally. I'm trying to make it easier and I may end up making 3 webpack configs `development`, `production`, and `test`

**Comment by manavsehgal** [comment]
@gdi2290 Many thanks for your prompt response and action! Looking forward to pulling this change.

**Comment by gdi2290** [comment]
done via https://github.com/AngularClass/angular2-webpack-starter/compare/cf4b3f2bf4fc74de37aa6af05a891d29c7c2d0a8...master
