### ISSUE TITLE
npm WARN prefer global marked@0.3.5 should be installed with -g

### ISSUE THREAD

**Issue by manavsehgal** [AngularClass/angular2-webpack-starter#183]
Thanks for "almost perfect" ```npm install``` on Mac El Capitan. Markdown seems to be the only dependency generating a warning that it wants global install.

```
npm WARN prefer global marked@0.3.5 should be installed with -g
```

**Comment by gdi2290** [comment]
this is due to `typedoc` and I can't really do anything about it other than creating an issue in their repo
