### ISSUE TITLE
npm run build:prod WARNING in vendor.js from UglifyJs

### ISSUE THREAD

**Issue by manavsehgal** [AngularClass/angular2-webpack-starter#184]
I get this warning most of the times I run build:prod, sometimes when I run build.

https://gist.github.com/manavsehgal/188a559ad5904d4db7a8

**Comment by gdi2290** [comment]
that's normal, the warnings are from dead-code elimination

**Comment by manavsehgal** [comment]
ok. thanks. you may want to close this issue then.
