### ISSUE TITLE
Naming conventions + style guide and best practices

### ISSUE THREAD

**Issue by manavsehgal** [AngularClass/angular2-webpack-starter#185]
In the spirit of following best practices for this starter. Any thoughts on naming conventions and style guide for Angular2, that this starter can follow? 

Kind of like Angular2 version of the famous [johnpapa angular 1 style guide](https://github.com/johnpapa/angular-styleguide). I am sure many of the recommendations can be reused for Angular 2 with few changes.

Currently I notice following issue with component naming:

Angular 2 official docs seem to suggest using `app.component.ts` and `AppComponent` naming convention. More verbose. 

PS: I have not looked up the design docs of Angular2 if there are "official" docs that can kickstart such a style guide.

**Comment by gdi2290** [comment]
yeah good idea I can start one

**Comment by manavsehgal** [comment]
Great! I will be happy to contribute.

**Comment by martinoppitz** [comment]
@gdi2290 assign this ticket to me.

**Comment by dsebastien** [comment]
At work we've just started investing in AngularJS (time pressure), but since Angular 2 is just around the corner, we're trying hard to make things easier when we decide to upgrade/migrate.

As far as I can see for now, I think that AngularJS 1.5 apps written in TypeScript can share a (partly) common style guide (e.g., folder structure, folder-per-feature idea, focus on componentization, usage of classes, ...

If you're interested, I'll document here the things that we come up with along our project.

**Comment by gdi2290** [comment]
@dsebastien I'm interested if you can that would help everyone in the Angular community

**Comment by manavsehgal** [comment]
@dsebastien @gdi2290 Let us start a wiki page for documenting the naming conventions. We can use this thread to report issues or debate alternatives. 

Agree with @dsebastien that we can reference existing conventions so it is easy for folks migrating over from Angular1. 

Where missing, we can also lookup other best practices - like [API naming conventions from Apigee](https://pages.apigee.com/rs/apigee/images/api-design-ebook-2012-03.pdf) could possibly help navigation / router related naming conventions.

**Comment by gdi2290** [comment]
I created a wiki page here https://github.com/AngularClass/angular2-webpack-starter/wiki/Best-Practices I'll update next week so if you guys can update it before then it would be awesome to see everyone opinion first

**Comment by choopage** [comment]
I added my opinion to the wiki page you created @gdi2290

**Comment by manavsehgal** [comment]
Updated best practices.

**Comment by MrLehiste** [comment]
There is angular 2 style guide based on johnpapa guid: [mgechev's Angular 2 Style Guide](https://github.com/mgechev/angular2-style-guide)

**Comment by d3viant0ne** [comment]
All of which have been rolled into a single Angular architecture & style guide. This is covered in the wiki as well.
