### ISSUE TITLE
Webpack Configuration on virtual machine - vagrant

### ISSUE THREAD

**Issue by blackpr** [AngularClass/angular2-webpack-starter#186]
So i have a dev-test server running on a vagrant machine and i had two problems

I can access the server from my host computer through an ip like ```http://192.168.33.10/```

When i run ```npm start``` i cannot connect from my host computer to 
```
http://192.168.33.10:3000
```
To fix this i added to ```webpack.config.js``` to devServer this option
```host: "0.0.0.0",```

The second problem is that when i change a file from the host computer through a shared folder the webpack-dev-server doesn't restarts. To fix that i added the next option as you can see http://webpack.github.io/docs/webpack-dev-server.html

```
watchOptions: {
      aggregateTimeout: 300,
      poll: 1000
    }
```

So the finished devServer options in ```webpack.config.js``` are

```
  // our Webpack Development Server config
  devServer: {
    historyApiFallback: true,
    host: "0.0.0.0",
    watchOptions: {
      aggregateTimeout: 300,
      poll: 1000
    },
    contentBase: 'src/public',
    publicPath: '/__build__'
  }
};
```

I am writing this for anyone else who have similar issues

**Comment by gdi2290** [comment]
changing the host is a good idea. What are the defaults for watchOptions?

**Comment by blackpr** [comment]
I think the polling option is disabled by default

**Comment by gdi2290** [comment]
I added `aggregateTimeout: 300` and `poll: 1000` via https://github.com/AngularClass/angular2-webpack-starter/compare/cf4b3f2bf4fc74de37aa6af05a891d29c7c2d0a8...master
Can you see if latest changes work and open this issue again id it doesn't
