### ISSUE TITLE
Production Build Routes Require 2 Clicks To Render Parent-Child Components

### ISSUE THREAD

**Issue by manavsehgal** [AngularClass/angular2-webpack-starter#190]
This is a weird issue. I have added another set of parent-child components with routes configured as prescribed in starter. Works fine when I am running dev server (npm start). 

However when I build:prod and serve:prod, the routes seem to require 2 clicks to show up content beyond first parent component referred to in the route. The first click seems to render only parent component until ```@Input()``` is triggered to get child components on second click!

Anyone else facing this issue?

**Comment by gdi2290** [comment]
that's normal see https://github.com/angular/angular/issues/6160

**Comment by manavsehgal** [comment]
Thanks for linking the issue with main angular repo. I am reading more issues of similar nature to get grips on this one. There needs to be a workaround, otherwise we cannot have a situation where nested components are not allowed using routes to parent. Will keep this thread updated with my findings.

**Comment by gdi2290** [comment]
can you push the repo to github so I can see what you're doing?

**Comment by manavsehgal** [comment]
My main repo has a lot of unrelated code. I will setup something with simple parent-child components so we can focus on the problem. It will also help us test and isolate the issue.

**Comment by gdi2290** [comment]
yeah that would be awesome :+1:

**Comment by manavsehgal** [comment]
Ok. Hope I have done this correctly. I have created a fork of your repo and pushed a new branch with sample code. https://github.com/manavsehgal/angular2-webpack-starter/tree/nestedcomp

I can replicate the above mentioned issue in this simple example.

**Comment by gdi2290** [comment]
I'm installing it now

**Comment by gdi2290** [comment]
@manavsehgal can you remove the `CommonsChunkPlugin` for `common` then it should work

**Comment by manavsehgal** [comment]
Yes it works now. Many thanks.

**Comment by gdi2290** [comment]
the problem was how `CommonsChunkPlugin` and the order the polyfills were loaded from what I can see
