### ISSUE TITLE
Adding a UI framework

### ISSUE THREAD

**Issue by manavsehgal** [AngularClass/angular2-webpack-starter#199]
This issue combines several prior issues around Scss/jQuery/Bootstrap integration.

Angular community has a choice of UI frameworks to consider. Bootstrap, Semantic UI, Ionic, Material UI... among others. Can we showcase (with sample components, webpack integration...) integration of one UI framework using best practices followed by the starter...
- Using Scss in modular way - selective UI framework components for minimal payload.
- Integrating UI framework JS modules honoring Angular and Webpack requirements.

We need to vote on one such framework for integration, before considering the implementation.
- Bootstrap, Material will most likely be implemented in a project similar to Angular Bootstrap or Angular Material...
- Ionic is self-contained and already implementing Angular 2 + Ionic 2 integration on their own...
- Among the UI frameworks I find Semantic UI to be most comprehensive and flexible in terms of integration and customization surface...

+1 Semantic UI

**Comment by leshin** [comment]
+1 Angular Material

**Comment by gdi2290** [comment]
I have a version of the repo with ng2-material working.  I ended up not merging it since there was a lot of overhead. I probably need to write a how to extend wiki

**Comment by manavsehgal** [comment]
Writing a wiki to explain integration with various UI frameworks seems a good idea as well.

**Comment by RemKolomna** [comment]
I vote for Material Design. Also It would very helpful to add authentication with UI. IMHO it is very useful in starter kits.

**Comment by manavsehgal** [comment]
@RemKolomna Thanks for voting. Auth seems to be a separate thread, I agree an important one.

**Comment by fesor** [comment]
I agree, there is not so many examples of how to implement it with angular. At least some strategies should be described in wiki.

**Comment by manavsehgal** [comment]
Official Angular guidance doc for ng-material 2. https://drive.google.com/open?id=1GGKUuyTayOjuF_58e3PqPINkKmnwqUNoCrCLbyxR_-A

**Comment by MurhafSousli** [comment]
I vote for angular2 material

**Comment by manavsehgal** [comment]
Thanks for adding Wiki on [Bootstrap 4 integration](https://github.com/AngularClass/angular2-webpack-starter/wiki/How-to-use-Bootstrap-4-and-Sass-(and-jQuery))

**Comment by manavsehgal** [comment]
Just started coding a sample app forking this starter. Demo use of sass/scss at app level and component level (see [landing](https://github.com/manavsehgal/AngularPages/tree/master/src/app/landing) component). Simple example introducing theming and flexbox layouts using scss. https://github.com/manavsehgal/AngularPages

**Comment by dsebastien** [comment]
+1 for Angular material :)

**Comment by manavsehgal** [comment]
Quick count on votes, wiki and issues:

**Angular Material** = 5 votes > **Bootstrap 4** = 1 wiki, 2 issues > **Semantic UI** = 1 vote
**Sass/Scss** = 5 issues > **Less** = 1 issue

**Comment by gdi2290** [comment]
I rather include instructions on how to install either one than force developers to start off with one

**Comment by ollwenjones** [comment]
+1 for instructions / example to add either one. A good starter project shouldn't be saddled with too many dependencies a dev may or may not need for his/her next project.

**Comment by phil-lgr** [comment]
+1  for instructions / example to add either one, I think it is better to
show example on how to install sass css, fonts (as new to Webpack, it was
not so easy to load fonts) and let devs decide :)

On Fri, Jan 22, 2016 at 9:23 AM, Sam Jones <notifications@github.com> wrote:

> +1 for instructions / example to add either one. A good starter project
> shouldn't be saddled with too many dependencies a dev may or may not need
> for his/her next project.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AngularClass/angular2-webpack-starter/issues/199#issuecomment-173933175>
> .
>



-- 
Philippe Léger
-
Programmer (front-end) |  [image: LinkedIn]
<https://ca.linkedin.com/pub/philippe-l%C3%A9ger/29/57/14b>|
pleger2@gmail.com | 514-799-8461

**Comment by phil-lgr** [comment]
@manavsehgal thank you for https://github.com/manavsehgal/AngularPages, really helped me figure out how to generate style for components! Potentially a great addition to the boilerplate..

**Comment by manavsehgal** [comment]
@phil-lgr cheers for the note. I will discuss with @gdi2290 for inclusion into core (smiles).

**Comment by gruenebe** [comment]
regarding boostrap 4. I think there is a little mistake in the doc:
https://github.com/AngularClass/angular2-webpack-starter/wiki/How-to-use-Bootstrap-4-and-Sass-(and-jQuery)

You should not use bootstrap-sass package since it is bootstrap 3. And use config file to tell bootstrap-loader that it is bootstrap v4 (which already contains scss files): https://github.com/shakacode/bootstrap-loader/blob/master/.bootstraprc-4-default

I will try to figure it out myself but it will take some time.

**Comment by NickClark** [comment]
My biggest issue right now with styles, is keeping the source maps. Otherwise, I've been opting for the following config: 

```
{ test: /\.scss$/,  loaders: ['to-string', 'css?sourceMap', 'sass?sourceMap'] },
```

This allows me to keep using the `css-loader` to resolve `url()`s.

**Comment by cagataycivici** [comment]
How about PrimeNG? 

http://www.primefaces.org/primeng/

**Comment by alvipeo** [comment]
Let's add every UI lib to the project! ;)

**Comment by fesor** [comment]
@alvipeo this is actually good idea, it just means that we should make yoman generator.

**Comment by alvipeo** [comment]
Exactly. Let's leave the project alone and not make it fat.

**Comment by d3viant0ne** [comment]
Having done quite a bit of this lately and I would suggest going the route @gdi2290 suggested.

Fork it and create a walkthrough on how to add, material2/ng2-bootstrap/sass/whatever
Open a PR for the readme and have the repo added to a list of projects that have been extended.

It simplifies pulling in updates from the upstream repository ( this one ) and still provides value to the community using it without bloating upstream.

**Comment by MurhafSousli** [comment]
@cagataycivici did you find a way to integrate it? I can't get it to work

**Comment by msegers** [comment]
Sooo where did Material2 go It's gone from the project?

**Comment by gdi2290** [comment]
there's a material2 branch that is always up-to-date
https://github.com/AngularClass/angular2-webpack-starter/tree/material2

**Comment by vivekwisdom** [comment]
So Just to confirm we need to clone the material2 branch to use the material UI?

**Comment by d3viant0ne** [comment]
@vivekwisdom - You need to checkout the material2 branch. The modifications you need to use `@angular-material2` exist there.

**Comment by holms** [comment]
Anyone PLEASE can tell me where the hell is material2 branch???

**Comment by vivekwisdom** [comment]
Looks to me that material 2 is integrated in default branch :)

**Comment by romelgomez** [comment]
@holms it was deleted https://github.com/AngularClass/angular2-webpack-starter/issues/1199 , To add material see this gist: https://gist.github.com/romelgomez/106625de08bbf68a2ca2b5c8aa93dcc8
