### ISSUE TITLE
npm run build:dev getting errors on windows 7

### ISSUE THREAD

**Issue by shawnrmoss** [AngularClass/angular2-webpack-starter#201]
Ive cloned the repo and run npm install.  npm start does its magic and hosts a site for me at lh:3000, but when I try to build the app I get a bunch of errors.  Any help you can offer would be much appreciated.

λ npm run build:dev

> angular2-webpack-starter@0.0.0 build:dev C:\ProjectCode\SummitSolutions.Denali
> npm run clean:dist && ./node_modules/.bin/webpack --progress --profile --colors --display-error-details --display-cached

> angular2-webpack-starter@0.0.0 clean:dist C:\ProjectCode\SummitSolutions.Denali
> rimraf dist

'.' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\S343\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build:dev"
npm ERR! node v5.3.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! angular2-webpack-starter@0.0.0 build:dev: `npm run clean:dist && ./node_modules/.bin/webpack --progress --profile --colors --display-error-details --display-cached`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-webpack-starter@0.0.0 build:dev script 'npm run clean:dist && ./node_modules/.bin/webpack --progress --profile --colors --display-error-details --display-cached'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-webpack-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run clean:dist && ./node_modules/.bin/webpack --progress --profile --colors --display-error-details --display-cached
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-webpack-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-webpack-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\ProjectCode\SummitSolutions.Denali\npm-debug.log

**Comment by gdi2290** [comment]
@shawnrmoss can you download latest and try again

**Comment by shawnrmoss** [comment]
I will try that for sure.  Thanks

**Comment by shawnrmoss** [comment]
That fix it for me!  Great response time.  Thank you so much.

**Comment by gdi2290** [comment]
no problem thanks for opening an issue. open another one if you have any questions or problems
