### ISSUE TITLE
run webdriver:update/start automatically on e2e

### ISSUE THREAD

**Issue by samvloeberghs** [AngularClass/angular2-webpack-starter#206]
Hi,

Is it an idea to run webdriver:update/start automatically when running the e2e tests?
It is an dependency to it so it would be a good idea, right?

So:
npm run e2e
   -> ./node_modules/.bin/webdriver-manager update
   -> ./node_modules/.bin/webdriver-manager start
   -> ./node_modules/.bin/protractor

I also had the impression that protractor should automatically start and/or update webdriver?

Grtz

**Comment by gdi2290** [comment]
I can probably refactor the setup to also start the server and webdriver in one command

**Comment by samvloeberghs** [comment]
One thing that is still on my mind is to automatically stop the webdriver after the e2e tests. I remember having troubles with that in the past. If I can help out with anything just shout out.

**Comment by samvloeberghs** [comment]
adding it to the protractor config seems to start & stop it automatically

  seleniumServerJar: "node_modules/protractor/selenium/selenium-server-standalone-2.48.2.jar"

I shall do some testing / modification and create a PR if I succeed

**Comment by gdi2290** [comment]
they removed seleniumServerJar from protractor but if you can get it running I would definitly merge it

**Comment by gdi2290** [comment]
@samvloeberghs  nvm I got it working

**Comment by gdi2290** [comment]
done via https://github.com/AngularClass/angular2-webpack-starter/commit/06dbdfd6d62e2972ce11f1ae48ff304349e56f0c

**Comment by samvloeberghs** [comment]
nice one. I've checked the commit and that's basically what I've also done to make it work.

**Comment by samvloeberghs** [comment]
But we still need like a "pre step". Can we not create a bash script or something to check if the standalone version is installed? Or is this creating to much overhead in some way?
