### ISSUE TITLE
Dev workflow

### ISSUE THREAD

**Issue by maku** [AngularClass/angular2-webpack-starter#207]
I am curious how to achieve my preferred development workflow with angular2-webpack-starter... 
On every code change the whole linting, testing, server updating etc. should be done.
How do I run this things?  When I use the "server:dev" script, no testing is done....
(I am new with webpack, maybe this is the problem...)

**Comment by xyNNN** [comment]
You only have to start the build tool with ```npm start```and the magic will follow :)

**Comment by maku** [comment]
@xyNNN when you run ```npm start```not a single test is executed. What I want to achieve is that the karma tests should be executed (also on every code change) ...

**Comment by gdi2290** [comment]
I see what you mean. At the moment the tests are only run once but I should also include a watch version of tests

**Comment by maku** [comment]
@gdi2290 I investigated a little bit and oddly enough I don't found out how do run the tests in course of the webpack watch mode (or build in general). Thought in times were everybody in the javascript world talks about the importance of testing, it is "best practice" to run the tests on every code change...

**Comment by gdi2290** [comment]
I think you might be looking for
https://github.com/AngularClass/angular2-webpack-starter/blob/master/karma.conf.js#L56
and
https://github.com/AngularClass/angular2-webpack-starter/blob/master/karma.conf.js#L64

**Comment by maku** [comment]
I am aware of this. But would it not be right in the other way around... Maybe I am wrong but I thought it should work like linting (with a preloader or so)....

**Comment by gdi2290** [comment]
test auto-watch done https://github.com/AngularClass/angular2-webpack-starter/commit/5f7438fe64133bc6ea98e74abac32e863a226c7a
