### ISSUE TITLE
integrating angular2 translate fails

### ISSUE THREAD

**Issue by samvloeberghs** [AngularClass/angular2-webpack-starter#208]
Hi guys,

I'm trying to integrate angular2 translate as an addon to the starter kit but I'm facing some difficulties. 
Check the issue here: https://github.com/ocombe/ng2-translate/issues/11

It's basically the assets/i18n folder not serving apparently?

Just asking if you guys have  a quick thought and answer to it before I dig into code.

Grtz

**Comment by gdi2290** [comment]
fixed via https://github.com/ocombe/ng2-translate/issues/11
