### ISSUE TITLE
Include external dependencies

### ISSUE THREAD

**Issue by xyNNN** [AngularClass/angular2-webpack-starter#210]
Hey folks,

How I can include external typescript dependencies? For example i want to use the libxmljs library in a Angular 2 component (https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/libxmljs/libxmljs.d.ts). How I can reach this?

Thanks in advance.

**Comment by gdi2290** [comment]
`typings install libxmljs`

**Comment by xyNNN** [comment]
Thanks for your quick reply! And afterwards? How I can use this in my component? For example How can I add this as dependency to my component?

These are my first steps with TypeScript :)

Thanks in advance!

**Comment by gdi2290** [comment]
include in vendor.ts and import it in your component file or create a service that will wrap it

**Comment by xyNNN** [comment]
When I install the dependency via typings I get the following error, what does it mean?
```
→ typings install libxmljs
? Found typings for libxmljs in DefinitelyTyped. Ok? Yes
Installing libxmljs@0.14.2 (DefinitelyTyped)...

typings ERR! message Attempted to compile "libxmljs" as a dependency, but it contains ambient modules ("libxmljs"). Did you want to specify "--ambient" instead?
```

**Comment by gdi2290** [comment]
if you read the error it's saying you need `--ambient` flag

**Comment by xyNNN** [comment]
I have installed the libxmljs library with the --ambient option - Afterwards I included the libxmljs library in my ```vendor.ts```like the following.
```
import 'libxmljs';
```

After that I ran again the npm start command and get the following error
```
WARNING in ./~/libxmljs/~/bindings/bindings.js
Critical dependencies:
76:22-40 the request of a dependency is an expression
76:43-53 the request of a dependency is an expression
 @ ./~/libxmljs/~/bindings/bindings.js 76:22-40 76:43-53

WARNING in ./~/libxmljs/~/bindings/README.md
Module parse failed: /Users/philippbraeutigam/Development/private/morpheus/node_modules/libxmljs/node_modules/bindings/README.md Line 2: Unexpected token ===
You may need an appropriate loader to handle this file type.
| node-bindings
| =============
| ### Helper module for loading your native module's .node file
|
 @ ./~/libxmljs/~/bindings ^\.\/.*$

ERROR in ./~/libxmljs/~/bindings/bindings.js
Module not found: Error: Cannot resolve module 'fs' in /Users/philippbraeutigam/Development/private/morpheus/node_modules/libxmljs/node_modules/bindings
 @ ./~/libxmljs/~/bindings/bindings.js 6:9-22
```

**Comment by gdi2290** [comment]
if I"m not mistaken the module in question has node bindings written in c++ and this repo is bundle for the browser

**Comment by xyNNN** [comment]
That means that I can't use this library in the browser context?! I'm very new to typescript, especially handling their dependencies - Thank you very much for your help :)

**Comment by gdi2290** [comment]
I think `libxmljs` was only ment to be used on the server (node.js)

**Comment by xyNNN** [comment]
Okay, It make sense. In the repository from the Typescript package manager I can only find two libraries to solve my problem (libxmljs and xml2js) - But no one of these works for me ... any other possibilities? :)

**Comment by gdi2290** [comment]
if you're looking for an xml parser make sure it's written in javascript or if the bindings also provides javascript only support

**Comment by xyNNN** [comment]
Thank you very much so far! I think that now I know what I've to do ;)

**Comment by gdi2290** [comment]
alright, feel free to open another issue if you have a question or problem :+1:
