### ISSUE TITLE
How can I integrate jquery in the project?

### ISSUE THREAD

**Issue by MurhafSousli** [AngularClass/angular2-webpack-starter#212]
I'm new to webpack, I want to add **materlizecss** script which is dependent on **jquery**, I searched  *webpack.config* file to see how you added *angular* and *rxjs* and do the same for **materlizecss** and **jquery**, but I couldn't figure it out.
Where did you give their paths to webpack? and how can I add my desired scripts?

Thank you.

**Comment by manavsehgal** [comment]
Opened #199 consolidating UI/style related issues.

**Comment by manavsehgal** [comment]
Can be closed based on instructions in [wiki](https://github.com/AngularClass/angular2-webpack-starter/wiki/How-to-use-Bootstrap-4-and-Sass-(and-jQuery))
