### ISSUE TITLE
Using Bootstrap 3 - jQuery not defined

### ISSUE THREAD

**Issue by alvipeo** [AngularClass/angular2-webpack-starter#214]
I'm pretty new to webpack and I'd like to use Bootstrap 3. So I added bootstrap and jquery typings to the project but when I add
    
    import 'bootstrap';
    
and then npm start server I get

**'jQuery' is undefined (in console)**

Could anyone help?

**Comment by gdi2290** [comment]
you can also install and include jQuery

**Comment by alvipeo** [comment]
ok, found out. Just changed plugins section in webpack.config.js (added ProvidePlugin):

    plugins: [
        new CommonsChunkPlugin({ name: 'vendor', filename: 'vendor.bundle.js', minChunks: Infinity }),
        // static assets
        new CopyWebpackPlugin([{ from: 'src/assets', to: 'assets' }]),
        // generating html
        new HtmlWebpackPlugin({ template: 'src/index.html', inject: false }),
        // replace
        new DefinePlugin({
            'process.env': {
                'ENV': JSON.stringify(metadata.ENV),
                'NODE_ENV': JSON.stringify(metadata.ENV)
            }
        }),
        new ProvidePlugin({    // <added>
            jQuery: 'jquery',
            $: 'jquery',
            jquery: 'jquery'   // </added>
        })
    ],

That resolved the issue. As far as I understand now when Bootstrap imported webpack knows where jQuery should come from. Correct?

**Comment by gdi2290** [comment]
ya that shouls work

**Comment by xueyuman2** [comment]
初学angular2比较难，有什么比较易学angular2的推荐吗？学习angular2怎么样比较容易?
