### ISSUE TITLE
Build and deploy

### ISSUE THREAD

**Issue by talmog** [AngularClass/angular2-webpack-starter#216]
First of all, thank you so much for this repo, it is great!

I have run npm run build:prod, and I am seeing index.html, main.version.bundle.js, vendor.version.bundle.js and assets.

I have uploaded all of it to AWS S3, but when I load the file in the browser I am getting errors for missing views (templateUrl: './src/app/module/module.component.html') for example.
Should I upload the html files? shouldn't it be in the bundle file? 
Is the path for the html the problem?

Thank you!

**Comment by gdi2290** [comment]
can you use require for templateUrl, for example.
```es6
template: require('module.component.html')
```

**Comment by talmog** [comment]
Thank you, 
I am not ignoring the answer, just trying to make it work... it breaks the regular serve right now so I will comment here if I figure it out or if it fails.

**Comment by talmog** [comment]
ok, that worked to a certain point. originally I used 
    templateUrl: require('module.component.html')
but noticed you wrote
    template: require('module.component.html')

So it runs on dev, but now I get this error when I upload it to S3:

EXCEPTION: RangeError: Maximum call stack size exceeded
browser_adapter.js:76 EXCEPTION: RangeError: Maximum call stack size exceedede.logError @ browser_adapter.js:76e.logGroup @ browser_adapter.js:86t.call @ exception_handler.js:56(anonymous function) @ application_ref.js:183t._notifyOnError @ ng_zone.js:430e.onError @ ng_zone.js:328r.run @ core.js:99(anonymous function) @ ng_zone.js:343(anonymous function) @ core.js:69j @ es6-promise.js:326N @ es6-promise.js:338I @ es6-promise.js:309(anonymous function) @ microtask.js:37n @ ng_zone.js:383r.run @ core.js:96(anonymous function) @ ng_zone.js:343(anonymous function) @ core.js:69v @ es6-promise.js:120
browser_adapter.js:76 STACKTRACE:e.logError @ browser_adapter.js:76t.call @ exception_handler.js:58(anonymous function) @ application_ref.js:183t._notifyOnError @ ng_zone.js:430e.onError @ ng_zone.js:328r.run @ core.js:99(anonymous function) @ ng_zone.js:343(anonymous function) @ core.js:69j @ es6-promise.js:326N @ es6-promise.js:338I @ es6-promise.js:309(anonymous function) @ microtask.js:37n @ ng_zone.js:383r.run @ core.js:96(anonymous function) @ ng_zone.js:343(anonymous function) @ core.js:69v @ es6-promise.js:120
browser_adapter.js:76 RangeError: Maximum call stack size exceeded
    at Function.t.instance (element.js:35)
    at t.getDependency (element.js:341)
    at t._getByDependency (injector.js:823)
    at t._instantiate (injector.js:721)
    at t._instantiateProvider (injector.js:712)
    at t._new (injector.js:701)
    at t.instantiateProvider (injector.js:201)
    at t.init (element.js:553)
    at new t (element.js:235)
    at viewFactory_t0 (viewFactory_t:904)

**Comment by talmog** [comment]
looking at this similar issue: https://github.com/angular/angular/issues/5964 I am wondering if we need to remove zone.js from vendor.ts

**Comment by gdi2290** [comment]
I refactored the repo a lot in the past few months. you can pull latest and open another issue if you have anymore problems thanks

**Comment by LeanderG** [comment]
My dev build runs fine, but my prod build produces this error: "EXCEPTION: RangeError: Maximum call stack size exceeded".
I'm using the latest version of angular2-webpack-starter and angular 2.0.0-beta.9.

Here is part of the stack trace:

browser_adapter.ts:73 EXCEPTION: RangeError: Maximum call stack size exceededt.logError @ browser_adapter.ts:73t.logGroup @ browser_adapter.ts:84e.call @ exception_handler.ts:49(anonymous function) @ application_ref.ts:257e._notifyOnError @ ng_zone.ts:454t.onError @ ng_zone.ts:355e.run @ polyfills.bundle.js:6958(anonymous function) @ ng_zone.ts:371(anonymous function) @ polyfills.bundle.js:6931C @ polyfills.bundle.js:6179A @ polyfills.bundle.js:6191x @ polyfills.bundle.js:6162(anonymous function) @ polyfills.bundle.js:5834n @ ng_zone.ts:410e.run @ polyfills.bundle.js:6954(anonymous function) @ ng_zone.ts:371(anonymous function) @ polyfills.bundle.js:6931v @ polyfills.bundle.js:5973
browser_adapter.ts:73 STACKTRACE:t.logError @ browser_adapter.ts:73e.call @ exception_handler.ts:52(anonymous function) @ application_ref.ts:257e._notifyOnError @ ng_zone.ts:454t.onError @ ng_zone.ts:355e.run @ polyfills.bundle.js:6958(anonymous function) @ ng_zone.ts:371(anonymous function) @ polyfills.bundle.js:6931C @ polyfills.bundle.js:6179A @ polyfills.bundle.js:6191x @ polyfills.bundle.js:6162(anonymous function) @ polyfills.bundle.js:5834n @ ng_zone.ts:410e.run @ polyfills.bundle.js:6954(anonymous function) @ ng_zone.ts:371(anonymous function) @ polyfills.bundle.js:6931v @ polyfills.bundle.js:5973
