### ISSUE TITLE
Requiring SASS in Angular 2 components with webpack

### ISSUE THREAD

**Issue by mark-norgate** [AngularClass/angular2-webpack-starter#219]
I am trying to require my SASS in my components, like this:
```
@Component({
    selector: 'signup',
    directives: [RouterOutlet, RouterLink],
    styles: [require('../sass/signup.scss')],
    template: require('./signup.component.html')
})
```

but my browser is complaining: `EXCEPTION: TypeError: s.replace is not a function`

I previously had the require outside of the component definition and it worked fine; but now I have another component I have to put the styles inside the components.

I have the correct loaders going on for SASS:
```
{
    test: /\.scss$/,
    loaders: ['style', 'css?sourceMap', 'sass?sourceMap']
}
```
What am I doing wrong?

**Comment by davidarnarsson** [comment]
Have you tried calling .toString()? As in, `styles: [ require('../sass/signup.scss').toString() ]` ? 

I did something similar for stylus, using the css-loader.

**Comment by abdulhaq-e** [comment]
Change the `loaders` to:

```
{
    test: /\.scss$/,
    loaders: ['raw-loader', 'sass-loader?sourceMap']
}
```

**Comment by mark-norgate** [comment]
Thank you @davidarnarsson , that works. And @abdulhaq-e I tried implementing your suggested change but it ruined my layout unfortunately. The problem now remains that both styles are being loaded on both pages.

The main problem is the background colour, which is different for both components. I have this:
```
html, body {
    height:100%;
    background-color: #eaeaea;
    display: flex;
    align-items: center;
    justify-content: center;
    display: -webkit-flex;
    -webkit-align-items: center;
    -webkit-justify-content: center;
}
```
but the `background-color` for each component is the same, even though I am specifying a different colour in each scss file. This is more of an issue with Angular 2 so I will go elsewhere for the answer.

Unless you know.

Thanks for your help. Mark

**Comment by manavsehgal** [comment]
Opened #199 consolidating UI/style related issues.

**Comment by gdi2290** [comment]
closing for https://github.com/AngularClass/angular2-webpack-starter/issues/199

**Comment by ilio** [comment]
try

`require('../sass/signup.scss');

@Component({
       selector: 'signup',
       directives: [RouterOutlet, RouterLink],
       template: require('./signup.component.html')
})`

**Comment by bitterloa** [comment]
YASS!  @davidarnarsson, using require('./file.scss').toString() helped. Thanks

**Comment by smithad15** [comment]
If you don't want to have to write `.toString()` everywhere, you could use this loader instead: [https://www.npmjs.com/package/css-to-string-loader](https://www.npmjs.com/package/css-to-string-loader)

**Comment by lpalli** [comment]
Anyone was able to run the test after adding scss files?

**Comment by alvipeo** [comment]
I gave up. I use Bootstrap 3 now, so everything works.

**Comment by lpalli** [comment]
I founded the solution to run the test (karma) after adding scss files, I added the loader also in the `config/webpack.test.js` file, not only in the `config/webpack.common.js` file.

**Comment by alvipeo** [comment]
Can we have a separate branch for Bootstrap 4? I think it might be useful...
