### ISSUE TITLE
How to include socket.io-client

### ISSUE THREAD

**Issue by mastertinner** [AngularClass/angular2-webpack-starter#221]
I tried to include `socket-io.client` by adding `import 'socket.io-client';` to the end of `vendor.ts` and running `npm install --save socket.io-client` but that didn't do the trick... Can you give me a hint on what else I have to do to use it in my app?

**Comment by gdi2290** [comment]
you also need to install typings `typings install socket.io-client --save --ambient`

**Comment by mastertinner** [comment]
Thanks for your reply, @gdi2290! Unfortunately that didn't help... I'm still getting `ORIGINAL EXCEPTION: TypeError: this.connection[method] is not a function` when opening the app in the browser...

**Comment by gdi2290** [comment]
where these the steps?
```bash
npm install socket.io-client --save
typings install socket.io-client --save --ambient
# DefinitelyTyped type Y then enter
# select 1.4.4 then enter
```
```es6
import * as io from 'socket.io-client';
var socket = io('yourserverlocation');
socket.on('connect', function(){
  console.log('connect')
});
```

**Comment by mastertinner** [comment]
I did install it like you said but I'm not consuming it directly but use a library which consumes it: https://github.com/feathersjs/feathers-client

Currently I'm including these two libraries as follows directly from `index.html`:
```html
<script src="https://cdn.socket.io/socket.io-1.4.4.js"></script>
<script src="/assets/lib/feathers.js"></script>
```
I copied the contents of their `dist/feathers.js` to my `assets/lib/feathers.js`. Currently this implementation works well by using `declare const feathers;` at the top of the files where I need to use feathers. However, I think it's not a very pretty solution. That's why I'm looking for alternatives using `import` but so far haven't found any which worked...

**Comment by mastertinner** [comment]
I just now solved the problem using `ProvidePlugin` of `webpack`:
```javascript
new ProvidePlugin({
  io: 'socket.io-client',
  feathers: 'feathers-client'
})
```

which allowed me to declare
```typescript
declare const io;
declare const feathers;
```

and therefore use `io` and `feathers` in my code. I hope that's the right way to do it.

**Comment by gdi2290** [comment]
can you create a wiki page https://github.com/AngularClass/angular2-webpack-starter/wiki
I'm going to close this issue and thanks for helping out with the repo

**Comment by mastertinner** [comment]
Done: https://github.com/AngularClass/angular2-webpack-starter/wiki/How-to-use-with-FeathersJS

It's quite complex but I hope that I wrote it in an understandable way.

**Comment by gdi2290** [comment]
thanks!

**Comment by patrickpereira** [comment]
Is it possible to update the wiki to the Angular 2 final version?

Thanks in advance!!

**Comment by mastertinner** [comment]
I just did. Thanks for the hint, @patrickpereira!

**Comment by AMashoshyna** [comment]
thanks @mastertinner!
