### ISSUE TITLE
Super slow after update to latest version

### ISSUE THREAD

**Issue by panKt** [AngularClass/angular2-webpack-starter#222]
I just updated to latest version of angular2-webpack-starter and it is super slow comparing to much older version that used ts-loader@0.5.x. Is there a way to make it as fast as it was?

**Comment by gdi2290** [comment]
there might be an issue about it on ts-loader can you make it there? the other problem might be tslint running
https://github.com/AngularClass/angular2-webpack-starter/blob/4ac54d4e986a7073c95bb32a20394374fd85e900/webpack.config.js#L51

**Comment by panKt** [comment]
@gdi2290, that line I commented once I first time ran a project :) 
Actual problem is here and there is no solution yet even from author of loader https://github.com/TypeStrong/ts-loader/issues/78#issuecomment-171078918

in older version of ts-loader 0.5.2 it took <1 sec to rebuild, in new version it takes ~5sec :(

**Comment by gdi2290** [comment]
updating to awesome-typescript-loader allowed the build process to speed up. you can open another issue if you have anymore problems thanks
