### ISSUE TITLE
Error in phpStorm

### ISSUE THREAD

**Issue by piernik** [AngularClass/angular2-webpack-starter#223]
After making all in Quickstart in phpStorm I have marked one error
In `main.ts` file in line `import {App} from './app/app';` I have `App` marked with info `Coresponding file is not included in tsconfig.json`

What's that?

**Comment by gdi2290** [comment]
PhpStorm wanted you to list the file in tsconfig.json

**Comment by gdi2290** [comment]
you may need to manually specify each `.ts` file inside of `tsconfig.json` `files: []`. I'm going to close this for now unless it's not working please comment or reopen the issue

**Comment by piernik** [comment]
Got it working and I think You could make a change in tsconfig file.
Your file has:
```
"files": [
    "typings/main.d.ts",
    "test/injector.spec.ts",
    "test/sanity-test.spec.ts",
    "src/app/app.spec.ts",
    "src/app/home/home.spec.ts",
    "src/app/home/directives/x-large.spec.ts",
    "src/app/home/providers/title.spec.ts",
    "src/main.ts",
    "src/vendor.ts"
  ],
  "filesGlob": [
    "./src/**/*.ts",
    "./test/**/*.ts",
    "!./node_modules/**/*.ts"
  ],
```

When I deleted theese lines:
```
    "test/injector.spec.ts",
    "test/sanity-test.spec.ts",
    "src/app/app.spec.ts",
    "src/app/home/home.spec.ts",
    "src/app/home/directives/x-large.spec.ts",
    "src/app/home/providers/title.spec.ts",
    "src/main.ts",
    "src/vendor.ts"
```

IDE was working good.
I think You should delete them also from seed.
Those files are mentioned in `fliesGlob`.
Another point is that when I deleted those files from project (they are example files) I got error running npm tasks.
