### ISSUE TITLE
Testing - imported module - not exists

### ISSUE THREAD

**Issue by piernik** [AngularClass/angular2-webpack-starter#224]
I'm new to webpack, karma, tslint and so on, but find Your seed great and want to use it in designing my angular modules.
So I have questions. Here is first:
In my project I've installed `angular2-jwt` module (using npm so it's in `node_modules` folder).
In `localhost:3000` everything works but when I hit `npm test` I have error ` Error: Cannot find module "angular2-jwt/angular2-jwt"`
I suppose I have to include it in spec-boundle.js but have no idea how.

**Comment by gdi2290** [comment]
you might need to update the test files if you're using the angular2-jwt within your application. I'm going to close this for now but feel free to comment more or reopen the issue

**Comment by piernik** [comment]
But update how and which file?

**Comment by piernik** [comment]
But update how? Which file? Give me some clues

**Comment by gdi2290** [comment]
see https://github.com/AngularClass/angular2-webpack-starter/blob/master/src/custom_typings.d.ts I'm going to ask `angular2-jwt` to include type definitions
