### ISSUE TITLE
Big size vendor js 

### ISSUE THREAD

**Issue by zainul-realtime** [AngularClass/angular2-webpack-starter#230]
I have clone the repo and then follow the instruction, well done the app run. But i see something is too big too load is vendor js when i npm start and run vendor js have 5 MB size, i have read the issue #158 and i follow it but unfortunately the size still big  ? have any idea to make small size ? 

please help , i am run angular2 in new project

Thanks

**Comment by zainul-realtime** [comment]
Solve with follow #158 i think before it i miss typo , sorry . but i have one question why output common js is big ? and then common js downloaded at the begining, in another angular2 starter is minimalist to load , why this starter not use minimum content to load?

**Comment by gdi2290** [comment]
the problem is due to the vendor file which is importing all file paths. you can simply comment them out to ensure only what is used will be packaged

**Comment by zainul-realtime** [comment]
which packaged use for basic or minimalist feature ?

**Comment by gdi2290** [comment]
comment everything other than
```typescript
import 'es6-shim';
// (these modules are what are in 'angular2/bundles/angular2-polyfills' so don't use that here)
import 'es6-promise';
import 'zone.js/lib/browser/zone-microtask';

if ('production' !== process.env.ENV) {
  // Reflect Polyfill
  require('es7-reflect-metadata/src/global/browser');
  Error['stackTraceLimit'] = Infinity;
  Zone['longStackTraceZone'] = require('zone.js/lib/zones/long-stack-trace.js');
}

if ('production' === process.env.ENV) {
  // Reflect with es7-reflect-metadata/reflect-metadata is added
  // by webpack.prod.config ProvidePlugin
  let ngCore = require('angular2/core');
  ngCore.enableProdMode();
}
```

**Comment by zainul-realtime** [comment]
woke , thanks mate solved

**Comment by manavsehgal** [comment]
Does reduce generated vendor.js, however shifts dependencies to main.js. Are there any performance considerations in doing so? Like first time app load?

**Comment by gdi2290** [comment]
I removed vendor until I create a better solution that easier to grasp.
