### ISSUE TITLE
How to include jquery with typings

### ISSUE THREAD

**Issue by RemKolomna** [AngularClass/angular2-webpack-starter#231]
I added jquery to this starter using instructions from this link https://github.com/AngularClass/angular2-webpack-starter/issues/215
But I have TypeScript errors like this:
TS2339: Property 'ajax' does not exist on type 'cssSelectorHelper'. or
TS2339: Property 'mousedown' does not exist on type 'ElementFinder'.
In all places where I access $ variable

I have tried adding jquery.d.ts to files section of tsconfig.json (just after line "typings/main.d.ts"), but the problem persist. How to fix it?

**Comment by gdi2290** [comment]
`typings install jquery --save`

**Comment by RemKolomna** [comment]
I got an error:
typings ERR! message Unable to find "jquery" in the registry. Maybe you want to install ambient definitions using "--ambient"? Alternatively, if you can contribute this typing, please help us out: https://github.com/typings/registry

PS: I downloaded jquery.d.ts manually from DefinetlyTyped and put this files to typings folder

**Comment by RemKolomna** [comment]
Should I use an ambient option? I have read in blakeembrey blog, that he advises against using ambient modules http://blakeembrey.com/articles/2015/11/state-of-typescript-packaging/

**Comment by abdulhaq-e** [comment]
Look at the end of `jquery.d.ts`, change the exported var from `$` to `jQuery`, that should solve your problem.

**Comment by blakeembrey** [comment]
@RemKolomna can you share what you're doing right now. To install from DefinitelyTyped, you can do `typings install jquery --ambient --save` - it's better to use non-ambient modules where available, but jQuery has already been typed so you might as well make use of it :smile: 

As for the additional issues, I know Angular has some binding so the global `$` so you might have to do something there. If you can provide a link I can quickly review what you've done, that'll make it easier.

**Comment by abdulhaq-e** [comment]
@blakeembrey 

>
As for the additional issues, I know Angular has some binding so the global $ so you might have to do something there. If you can provide a link I can quickly review what you've done, that'll make it easier.

Indeed it does, I solved it by changing [L3200](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/jquery/jquery.d.ts#L3200) from:

```
export = $;
```

to

```
export = jQuery;
```

The problem with this solution is, if `jQuery` is included as a requirements in the `typings` file then `typings install` will reset the file.

**Comment by blakeembrey** [comment]
Awesome, makes sense. What we can do in Typings is turn jQuery into an external module and allow installation, just need someone to maintain that :+1: As for the reset, you don't **have** to use Typings to install it. I usually make a `custom_typings/` directory and put stuff in there, which I then include in `tsconfig.json`. Typings itself follows this: https://github.com/typings/typings/blob/master/tsconfig.json. If you do want to use Typings, you can do `typings install file:custom_typings/jquery.d.ts --ambient --save` for now.

**Comment by RemKolomna** [comment]
Thanks! I added jquery to custom_typings, change to export = jQuery; and everything is ok now!

**Comment by qSoft** [comment]
Use typings install dt~jquery --global

**Comment by trsh** [comment]
@qSoft I got:

[default] C:\Projects\xx\yy\typings\globals\jquery\index.d.ts:3227:13
    Subsequent variable declarations must have the same type.  Variable '$' must be of type 'cssSelectorHelper', but here has type 'JQueryStatic'.
[default] Checking finished with 2 errors

**Comment by Neur0mante** [comment]
I'm not using typings anymore, just including` "@types/jquery": "^2.0.34"` in my package.json file.

**Comment by d3viant0ne** [comment]
Did you add the jquery types to your tsconfig as well?

i.e - https://github.com/AngularClass/angular2-webpack-starter/blob/master/tsconfig.json#L19-L26

**Comment by Neur0mante** [comment]
Yes, sorry, forgot about that.

**Comment by DeanVanGreunen** [comment]
@d3viant0ne I cant get the typing working, followed all instructions.
 installed jquery, types/jquery
added to tsconfig as fig1
but still get this error as fig 2

![fig 1](https://user-images.githubusercontent.com/22296075/54074761-f689c200-429e-11e9-9fe0-645b1cdfb77c.png)

![fig 2](https://user-images.githubusercontent.com/22296075/54074766-0c978280-429f-11e9-9c08-36c46690768d.png)
