### ISSUE TITLE
problem with current route name from Router.hostComponent.name

### ISSUE THREAD

**Issue by arozwalak** [AngularClass/angular2-webpack-starter#233]
No matter if I'm using HashLocationStrategy or PathLocationStrategy once I build production version using `npm run build:prod` when I get route name from `this.router.hostComponent.name` all names are changed to 'n'

**Comment by gdi2290** [comment]
that's probably due to minification. `hostComponent` is a refernce to the class and when it's minified the `.name` is converted to the minified name
