### ISSUE TITLE
Add CompressionPlugin

### ISSUE THREAD

**Issue by antonmoiseev** [AngularClass/angular2-webpack-starter#234]
What do you think about adding [CompressionPlugin](https://github.com/webpack/compression-webpack-plugin)? I usually statically compress the build assets during the build rather than dynamically on a Web server, it has a couple of advantages:

1. Saves computation resources on the server
2. Simplifies a bit the Web server configuration - no need to configure threshold, ratio, buffers (nginx-specific varies on the platform), the file types that should be compressed.
3. Allows to calculate the real application payload size after the build and report/draw charts on CI.

**Comment by gdi2290** [comment]
good idea! can you make a pull-request for the prod webpack.config?

**Comment by antonmoiseev** [comment]
Sure, will do. The plugin doesn't allow configuring the compression level, the default one I believe is 6. To enable level 9 it requires a [tiny wrapper function](https://github.com/antonmoiseev/ng2-dart-vs-ts/blob/master/ts/webpack.config.js#L56-L58) around zlib which _slightly_ complicates the build script. Which level you would prefer?

**Comment by crh225** [comment]
@antonmoiseev does angular need any configuration to serve the gzipped files?
