### ISSUE TITLE
refactoring of webpack config files

### ISSUE THREAD

**Issue by maku** [AngularClass/angular2-webpack-starter#235]
Currently there are many redundant definitions in the webpack config files....

From my point of view it would be a good idea to refactor it and to abstract this redundant definitions

**Comment by antonmoiseev** [comment]
As a part of this issue could we also consider sharing the common configuration among the Webpack config files?

**Comment by manavsehgal** [comment]
I like this implementation for sharing common definition and reducing redundant code. http://survivejs.com/webpack_react/building_kanban/ uses https://github.com/survivejs/webpack-merge

**Comment by gdi2290** [comment]
the redundant definitions for config files are there as it's the easiest way for new developers to webpack to understand the differents ways to config the bundle without overwhelming them
