### ISSUE TITLE
When I run 'build:prod',there were some WARNING about UglifyJs

### ISSUE THREAD

**Issue by ibufu** [AngularClass/angular2-webpack-starter#241]
WARNING in vendor.b9e9e21a697cd23b53fc.bundle.js from UglifyJs
Condition always false [./~/tslint-loader!./src/vendor.ts:7,4]
Dropping unreachable code [./~/tslint-loader!./src/vendor.ts:9,2]
Condition always true [./~/tslint-loader!./src/vendor.ts:14,4]
Condition always true [./~/es7-reflect-metadata/dist/browser.js:2,0]
Dropping unreachable code [./~/es7-reflect-metadata/dist/browser.js:4,0]
Side effects in initialization of unused variable RequestMethod [./~/angular2/src/http/enums.js:13,0]
Side effects in initialization of unused variable ReadyState [./~/angular2/src/http/enums.js:27,0]
Side effects in initialization of unused variable ResponseType [./~/angular2/src/http/enums.js:39,0]
Side effects in initialization of unused variable PropertyBindingType [./~/angular2/src/compiler/template_ast.js:228,0]
Side effects in initialization of unused variable freeExports [./~/rxjs/util/root.js:11,0]
Side effects in initialization of unused variable freeModule [./~/rxjs/util/root.js:12,0]
Non-strict equality against boolean: != true [./~/angular2/src/compiler/html_tags.js:294,0]
Side effects in initialization of unused variable ViewType [./~/angular2/src/core/linker/view_type.js:12,0]
Non-strict equality against boolean: == false [./~/angular2/src/router/router.js:481,0]
Non-strict equality against boolean: == false [./~/angular2/src/router/router.js:278,0]
Dropping unused variable r [./~/es6-promise/dist/es6-promise.js:131,0]
Condition left of && always true [./~/es6-promise/dist/es6-promise.js:957,0]
Side effects in initialization of unused variable lib$es6$promise$asap$$toString [./~/es6-promise/dist/es6-promise.js:34,0]
Non-strict equality against boolean: == true [./~/angular2/src/router/url_parser.js:200,0]
Dropping unused variable $FF [./~/angular2/src/compiler/html_lexer.js:61,0]
Dropping unused variable $$ [./~/angular2/src/compiler/html_lexer.js:67,0]
Dropping unused variable $QUESTION [./~/angular2/src/compiler/html_lexer.js:79,0]
Dropping unused variable _CONTEXT_ACCESSOR [./~/angular2/src/core/change_detection/codegen_name_util.js:6,0]
Condition always true [./~/es6-shim/es6-shim.js:15,0]
Dropping unreachable code [./~/es6-shim/es6-shim.js:18,3]
Side effects in initialization of unused variable replaceFn [./~/es6-shim/es6-shim.js:3336,0]
Side effects in initialization of unused variable webSocketPatch [./~/zone.js/lib/patch/browser.js:8,0]

WARNING in main.f4592aa472d28dd44e0d.bundle.js from UglifyJs
Condition always true [./~/tslint-loader!./src/main.ts:21,7]
Side effects in initialization of unused variable common_dom_1 [./~/tslint-loader!./src/main.ts:8,0]
Side effects in initialization of unused variable Status [./~/tslint-loader!./src/models/CampApply.ts:4,12]

**Comment by gdi2290** [comment]
That's normal. It's dead code elimination
