### ISSUE TITLE
how to remove testing files dependency

### ISSUE THREAD

**Issue by MurhafSousli** [AngularClass/angular2-webpack-starter#243]
Hi, I get errors after I removed "Home" folder
```
ERROR in ./src/vendor.ts
Module build failed: Error: ENOENT: no such file or directory, 
open '...\GitHub\angular2-webpack-starter\src\app\home\directives\x-large.spec.ts'
```
I want to remove the dependency on testing files, From which file?

**Comment by gdi2290** [comment]
the error is in tsconfig. you need to remove the spec files in `"files": []`

**Comment by MurhafSousli** [comment]
@gdi2290 Got it, thank you so much.

**Comment by gdi2290** [comment]
np, thanks for opening an issue
