### ISSUE TITLE
Images in templates

### ISSUE THREAD

**Issue by alvipeo** [AngularClass/angular2-webpack-starter#245]
I tried to use images in component templates (.html) and I can't get those images to show up in the browser. Gives me 404 whatever url I type in. Am I missing something?

Shouldn't we add at least 1 image tag to the project? Just for other people to know.

**Comment by gdi2290** [comment]
Yeah I'll add an image

**Comment by alvipeo** [comment]
Could you tell how to do it? I really don't get why it returns 404 even if an image in the assets folder.

**Comment by RemKolomna** [comment]
Looks like it is the duplicate issue of https://github.com/AngularClass/angular2-webpack-starter/issues/232 ?

**Comment by gdi2290** [comment]
done via https://github.com/AngularClass/angular2-webpack-starter/commit/d9ea3fb4b57a6d7c320900b83a76e388546b56c6
