### ISSUE TITLE
Duplicate typings errors on fresh install

### ISSUE THREAD

**Issue by Snejk47** [AngularClass/angular2-webpack-starter#250]
Hi, few days ago I looked at this seed project and it was working ok. I've got it running just fine (npm start).
Today on fresh nodejs (other computer) I cloned this repo and it doesn't run anymore. I get tons of typings errors like
```
angular2-webpack-starter\node_modules\angular2\typings\node\node.d.ts
(45,5): error TS2300: Duplicate identifier 'extensions'.

[...]

angular2-webpack-starter\typings\main\ambient\angular-protractor\angular-protractor.d.ts
(12,11): error TS2300: Duplicate identifier 'ActionSequence'.

[...]

angular2-webpack-starter\typings\main\ambient\angular-protractor\angular-protractor.d.ts
(1848,5): error TS2300: Duplicate identifier 'export='.
```
There is like 4000 lines of them.

I can't find any solution. Other seed using typings is fine.

node -v : v4.2.6
npm -v : 2.14.12

I'm on Win8 64bit.

**Comment by gdi2290** [comment]
@Snejk47 can you download and install again? I pushed up a quick update

**Comment by gdi2290** [comment]
nvm I still need to fix it

**Comment by gdi2290** [comment]
if you run `npm run clean:ng2` then that will fix your problem. I'm trying to make sure people won't have to

**Comment by Snejk47** [comment]
Thank you, running clean:ng2 indeed fixed that (even without your last commit). Awesome!

**Comment by gdi2290** [comment]
thanks for posting an issue. if you have anymore problems feel free to open another one or submit a pull-request
