### ISSUE TITLE
test watch - possible?

### ISSUE THREAD

**Issue by alvipeo** [AngularClass/angular2-webpack-starter#251]
Basically, this repo is a great learning source so thanks for that!

I've started writing tests and for a real production scenario the repo missing continuous testing (test watch). Could it be done with webpack in some way?

I mean when working on a project and writing new code I'd like to have tests running all the time so if I break something I'd see it the same moment.

**Comment by gdi2290** [comment]
done via https://github.com/AngularClass/angular2-webpack-starter/commit/5f7438fe64133bc6ea98e74abac32e863a226c7a

**Comment by alvipeo** [comment]
Thanks! (you know a ton!)
