### ISSUE TITLE
Issue in es7-reflect-metadata

### ISSUE THREAD

**Issue by sasidhar** [AngularClass/angular2-webpack-starter#252]
When I run `npm start` I am getting following error.

```
ERROR in ./~/es7-reflect-metadata/src/helper/gen-randombytes.browser.ts
(2,31): error TS2307: Cannot find module './fill-randomBytes'.

ERROR in ./~/es7-reflect-metadata/src/helper/gen-randombytes.browser.ts
Module not found: Error: Cannot resolve 'file' or 'directory' ./fill-randomBytes in /home/sasidhar/projects/angular2-webpack-starter/node_modules/es7-reflect-metadata/src/helper
 @ ./~/es7-reflect-metadata/src/helper/gen-randombytes.browser.ts 1:25-54
```

I am on
* Node.js v4.2.4
* NPM 3.5.3
* Ubuntu 15.10

When i updated the file path from `./fill-randomBytes` to `./fill-randombytes` (uppercase B to lowercase b), it worked fine.

Might be issue with es7-reflect-metadata package.

**Comment by gdi2290** [comment]
thanks! I fixed it so if you run `npm update` it should be fixed
