### ISSUE TITLE
template_compiler.js, __decorate is not defined

### ISSUE THREAD

**Issue by Snejk47** [AngularClass/angular2-webpack-starter#257]
When run, Chrome logs 
```
Uncaught ReferenceError: __decorate is not defined template_compiler.js:205
```
```
(anonymous function)	@	template_compiler.js:205
(anonymous function)	@	template_compiler.js:210
__webpack_require__	@	bootstrap ddec45ec191e3dad7a0d:50
(anonymous function)	@	runtime_compiler.ts:3
__webpack_require__	@	bootstrap ddec45ec191e3dad7a0d:50
(anonymous function)	@	compiler.ts:1
__webpack_require__	@	bootstrap ddec45ec191e3dad7a0d:50
(anonymous function)	@	compiler.ts:8
__webpack_require__	@	bootstrap ddec45ec191e3dad7a0d:50
(anonymous function)	@	browser.ts:21
__webpack_require__	@	bootstrap ddec45ec191e3dad7a0d:50
(anonymous function)	@	main.ts:5
__webpack_require__	@	bootstrap ddec45ec191e3dad7a0d:50
webpackJsonpCallback	@	bootstrap ddec45ec191e3dad7a0d:21
(anonymous function)	@	main.bundle.js:1
```

**Comment by amilajack** [comment]
I'm also getting this error
<img width="449" alt="screen shot 2016-01-26 at 1 47 27 am" src="https://cloud.githubusercontent.com/assets/6374832/12577381/caa60088-c3ce-11e5-895c-de5f4fc153db.png">

**Comment by choopage** [comment]
I am also getting these 2 errors. I spent an hour trying to debug. My page just stuck with `Loading...`

**Comment by eslotwinski** [comment]
I'm also getting those errors, + additonal bunch of warring like in this issue https://github.com/AngularClass/angular2-webpack-starter/issues/256

**Comment by myccy8** [comment]
I'm also getting those errors

**Comment by myccy8** [comment]
![image](https://cloud.githubusercontent.com/assets/7892226/12584828/59b6e728-c484-11e5-8e6e-2ff2172ec174.png)

**Comment by mshamma** [comment]
Just tried the quickstart on a fresh clone of the repo.  I am also getting this error.

**Comment by mshamma** [comment]
Got it working by rolling back this commit: https://github.com/AngularClass/angular2-webpack-starter/commit/82c44112d2a499332816fc9cc8d91eccba27aa80

**Comment by gdi2290** [comment]
yeah, fixed via https://github.com/AngularClass/angular2-webpack-starter/commit/fa910ad94cff83f938bb24b44df52c55e4692bbc

**Comment by juristr** [comment]
:+1: just ran into this. Awesome. Works now :smile:

**Comment by gdi2290** [comment]
sorry about that. the recent changes fixes the minified problem that's in beta.1 right now. there's another problem with routerLink that still needs to be addressed
