### ISSUE TITLE
fix:ng fails on Windows

### ISSUE THREAD

**Issue by TomGillen** [AngularClass/angular2-webpack-starter#258]
In one of the scripts in package.json:

```
rimraf node_modules/angular2/manual_typings node_modules/angular2/typings node_modules/angular2/bundles/typings && cp -R src/.ng2-patch/. node_modules/angular2
```

This does not work; "cp" is not a recognized command on Windows.

**Comment by TomGillen** [comment]
On further testing, if I replace the cp with a similar xcopy command, everything installs fine, but while running I get errors complaining about "__decorate" not being recognized in template_compiler.js:205 and the page fails to load properly.

Removing the copy entirely, and running with the original template_compiler, the example seems to load fine.

**Comment by Snejk47** [comment]
That "__decorate" thing is fixed #257.

**Comment by gdi2290** [comment]
I pushed an update to fix this
https://github.com/AngularClass/angular2-webpack-starter/commit/ac7d641d28946d41d9771e9705c45e23c905a929
please run
```
npm run clean:install
```

**Comment by TomGillen** [comment]
I just did a clean copy of the project and ran `mpn install`:

```
> rimraf node_modules/angular2/manual_typings node_modules/angular2/typings node_modules/angular2/bundles/typings && ncp
 src/.ng2-patch node_modules && replace '"rxjs": "5.0.0-beta.0"' '"rxjs": "5.0.0-beta.1"' node_modules/* -r

fs.js:887
  return binding.lstat(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, lstat 'D:\Projects\angular2-webpack-starter-master\'rxjs:'
```

**Comment by gdi2290** [comment]
@TomGillen I pushed another update if you can give it another try

**Comment by TomGillen** [comment]
Yup, working now.

**Comment by gdi2290** [comment]
thanks again for for making the issue and commenting again :+1:
