### ISSUE TITLE
Why modules not found in VS Code?

### ISSUE THREAD

**Issue by alvipeo** [AngularClass/angular2-webpack-starter#263]
In **some of my files** *VS Code* can't find modules but the project compiles with 'npm run server'. For example:

![Image]
(http://inus.blob.core.windows.net/pub/unknown.png)

But other files are all ok. Could you please tell me why is that?

**Comment by gdi2290** [comment]
@alvipeo doy ou have the latest changes?
https://github.com/AngularClass/angular2-webpack-starter/blob/master/tsconfig.json

**Comment by alvipeo** [comment]
Thanks! Can't keep up with it! :)
