### ISSUE TITLE
Can jade template engine include in starter

### ISSUE THREAD

**Issue by zainul-realtime** [AngularClass/angular2-webpack-starter#267]
Hello my previous project i am create views in expressjs using jade, can the angular2 webpack starter included jade file to the project ?
how to include this ? :dancer: 

thanks

**Comment by zainul-realtime** [comment]
yeah finally i can do this. yes this project can do with jade template engine with following step:
1. install jade -> npm install jade
2. modify webpack config with adding jade extension

`resolve: {
    // ensure loader extensions match
    extensions: ['','.ts','.js','.json','.css','.html','.jade']
  },`

3. adding jade to loader

`
{ test: /\.jade$/,  loader: 'jade' }
`

for implementation just call by require like this

`
@Component({
    template: require('!jade!./your_file.jade')(),
`
work for me :)

thanks 

CMIIW :dancers:

**Comment by manavsehgal** [comment]
Thanks for sharing this. Any way to avoid !jade! and () in require?

**Comment by zainul-realtime** [comment]
!Jade! Syntax use for to handle detect a module by typescript, because whitout !jade! typescript detect this is a module , ..
And in the end require () use to compile jade to be html ..
If not use it will be show a jade function ..
Problably you have suggestions for more better again ?
Thanks hehe :)

**Comment by gdi2290** [comment]
add jade to extensions 
https://github.com/AngularClass/angular2-webpack-starter/blob/master/webpack.config.js#L69

see comment
https://github.com/AngularClass/angular2-webpack-starter/blob/master/webpack.config.js#L44

then `require('./your_file')`

and if you update my wiki page that would be awesome :)
https://github.com/AngularClass/angular2-webpack-starter/wiki/How-to-add-.jade-support
