### ISSUE TITLE
'this.http.get(...).map is not a function' when built for prod 

### ISSUE THREAD

**Issue by jmiazga** [AngularClass/angular2-webpack-starter#268]
I am getting the error:

```
this.http.get(...).map is not a function in [null]
```

when building and running in prod. There is no issue running in dev.

**Comment by gdi2290** [comment]
see 
https://github.com/AngularClass/angular2-webpack-starter/blob/master/src/polyfills.ts#L17
make an `else` that requires `require('rxjs/add/operator/map');`

**Comment by jmiazga** [comment]
Any reason they are all pulled in for dev? I will add the require in the file that needs it.

**Comment by lanocturne** [comment]
No luck, still get same error.

**Comment by gdi2290** [comment]
I moved rxjs to vendor.ts if you have anymore problems please open another issue thanks
