### ISSUE TITLE
Upgrade to typescript@^1.8.0

### ISSUE THREAD

**Issue by martinoppitz** [AngularClass/angular2-webpack-starter#270]
If we try, we get there (npm start) an error ...

`ERROR in ...\angular2-webpack-starter\node_modules\angular2\src\facade\promise.d.ts
(1,10): error TS2661: Cannot re-export name that is not defined in the module.`

**Comment by ollwenjones** [comment]
I ran into the same thing. Not sure if this is a compatibility issue with this project as much as with TS 1.8 and Angular 2. The way some of the imports/exports are done in the angular2 codebase don't seem to be allowed anymore?

**Comment by gdi2290** [comment]
It's a problem with Angular2 types again. They fixed it so next release won't have it. I can including a quick fix in the meantime so thanks for reporting

**Comment by alvipeo** [comment]
Until Angular2 team switch to 1.8 I wouldn't too.

**Comment by gdi2290** [comment]
this has been done thanks for the issue
