### ISSUE TITLE
RxJs Dependency Problems

### ISSUE THREAD

**Issue by datatypevoid** [AngularClass/angular2-webpack-starter#276]
Fresh clone of repo (Windows 10 64-bit, latest NPM, lastest Node) is getting the following after running `npm install` (note that I have run `npm install` once already at this point):

![Error](https://i.gyazo.com/f6493151b2d1b10deb7b7ff519d2204a.png)

**Comment by datatypevoid** [comment]
Additionally I get a ton a errors when running `npm start`:

![Errors galore](https://i.gyazo.com/89bf5967f6e3526800d72209e738f409.gif)

**Comment by datatypevoid** [comment]
This is what I get when attempting to view the app on `localhost:3000`:

![moar errors](https://i.gyazo.com/493519d3655996bb60df5236c2b67219.png)

**Comment by gdi2290** [comment]
the location you downloaded the repo at doesn't allow you to remove files. if you download the repo again I pushed the changes to revert the rxjs update hack

**Comment by datatypevoid** [comment]
Thanks for your swift reply ^^ I will give it a try.

**Comment by datatypevoid** [comment]
The compilation errors have gone away, thank you again for all your work.

**Comment by datatypevoid** [comment]
I am still getting a few errors after running `npm run server`:

![Errors](https://i.gyazo.com/0e08d7362619a9c13356241750779e5a.png)

![Moar errors](https://i.gyazo.com/244df5adf9d755210fdfc0881a2c4b86.png)

**Comment by gdi2290** [comment]
@datatypevoid  can you update this file or pull latest changes again
https://raw.githubusercontent.com/AngularClass/angular2-webpack-starter/master/src/polyfills.ts

**Comment by datatypevoid** [comment]
All cleared up. Thank again. This is the best resource I have found for Angular 2 with Webpack.

**Comment by gdi2290** [comment]
awesome thanks for opening an issue :+1: feel free to oen another one if you run into another problem
