### ISSUE TITLE
proposal - split vendor from code

### ISSUE THREAD

**Issue by daniele-zurico** [AngularClass/angular2-webpack-starter#277]
Hi guys,
what do you think if in webpack when we build the application we create 2 files:
1) contain our code
2)contain the vendor: like angular, rx, etc

In this way the vendor build don't increase in size and we can manage our code (src) in a separate file.
 I've done something like that in my webpack project:
https://github.com/daniele-zurico/angular2-webpack/blob/master/webpack.config.js

**Comment by gdi2290** [comment]
I had a vendor file and but removed it because everyone kept complaining about the vendor size. I will add it back after angular2 supports precompilation

**Comment by idiotstrike** [comment]
Have you looked into split-by-name-webpack-plugin? It allows you to separate modules from app code by matching an expression against the module's path.
