### ISSUE TITLE
How to add an css to src/assets/css/?

### ISSUE THREAD

**Issue by devcube** [AngularClass/angular2-webpack-starter#281]
Hey, I'm testing some scenarios with this repo and the webpack.config.js loads css files with a raw-loader instead of css!style. I assume this is useful since a angular2 component can have "styles: [ require('./home.css') ]" and then that file will be required and load on demand rather than bundled in the .js bundle.

This repo also have a src/assets/css folder and I've added an app.css file to that folder. That folder is copied using this webpack plugin:
```
new CopyWebpackPlugin([{ from: 'src/assets', to: 'assets' }])
```
The index.html is injected with webpack stuff using this plugin:
```
new HtmlWebpackPlugin({
      template: 'src/index.html',
      inject: false
    }),
```
and in the index.html there's this magic:
```
{% for (var css in o.htmlWebpackPlugin.files.css) { %}
  <link href="{%= o.htmlWebpackPlugin.files.css[css] %}" rel="stylesheet">
  {% } %}
```
But the o.htmlWebpackPlugin.files.css does not seem to include any files at all. How do I populate this array correctly?
I've tried extending the HtmlWebpackPlugin like this:
```
new HtmlWebpackPlugin({
      files: {
        css: [ 'assets/css/app.css' ]
      },
      template: 'src/index.html',
      inject: false
    }),
```
Still no go. Do I have to use ExtractTextPlugin? Or should I use the css!style loaders on this specific directory?

**Comment by devcube** [comment]
I'm really new to all of I ended up with these changes:
First, I changed so that I have different loaders for different css. The css in the angular2 app structure are nice to include with a raw-loader and the require() on the css files. The other css files, such as bootstrap3 are nice to bundle into a styles.css so that it can load in parallell to the javascript, thus minimizing FOUC.
First I add extract-text-webpack-plugin so that it can be used to bundle css files. This is then used in the loaders section of the webpack.config.js:
```
// Support for CSS as raw text (this is useful for angular2 components that can lazy load the css files)
{ test: /\.css$/, loader: 'raw-loader', include: [ root('src/app') ] },

// Support for CSS as loaded/bundled files (this is useful to cover all css files that aren't included otherwise, such as bootstrap.css)
{ test: /\.css$/, loader: ExtractTextPlugin.extract("style-loader", "css-loader"), exclude: [ root('src/app') ] },
```
Notice the include/exclude statements.
Second, I output the bundled css files into styles.css using this code:
```
new ExtractTextPlugin("styles.css")
```

With the current structure, my assets/css/app.css is still copied to the dist with the copy-webpack-plugin with this line:
```
new CopyWebpackPlugin([{ from: 'src/assets', to: 'assets' }])
```
I'm not entirely sure on how to handle that yet, so far it isn't a problem but I could either move the css folder out of assets, somehow exclude it from copy-webpack-plugin or just ignore it. Currently I'm just ignoring it.

Last but not least I import the css files that I want to include in the bundle. I'm doing this in polyfills.ts like this:
```
import 'bootstrap/dist/css/bootstrap.css';
import './assets/css/app.css';
```

Hope this helps someone and keep up the great work with this repo!

**Comment by siready** [comment]
You could exclude css files being copied from assets folder with ignore option statement for copy-webpack-plugin. Example:
`new CopyWebpackPlugin([
        {
          from: 'src/assets',
          to: 'assets'
        }
      ],
      {
        ignore: [ 'css/**' ]
      }
    )`

Thank you for the rest :+1:
