### ISSUE TITLE
Bootstrap 4 + angular 2 webpack starter

### ISSUE THREAD

**Issue by dvh91** [AngularClass/angular2-webpack-starter#284]
I've followed https://github.com/AngularClass/angular2-webpack-starter/wiki/How-to-use-Bootstrap-4-and-Sass-(and-jQuery) to load bootstrap 4 and it's working just fine but when I want to override variables using my own scss file, it just not working.

anyone encountered that problem as well? 

`styles: [
    require('../assets/css/sass/main.scss').toString()
  ],
  encapsulation: ViewEncapsulation.None,`

main.scss contain some overrides to bootstrap 4 variables.

**Comment by mbalex99** [comment]
Are you supposed to have the "toString()"? I thought it would just resolve it with a simple require.

**Comment by dvh91** [comment]
.toString() solved another bug that the app is not starting and throwing an error.
Found it in another ticket.

**Comment by dvh91** [comment]
For next people having that problem:
webpack config:
{ test: /\.scss$/, loaders: ['raw-loader','sass-loader'] },

component:
styles: [require('./component.scss')],

.scss file:
@import "./node_modules/bootstrap-sass/assets/stylesheets/bootstrap/variables";

**Comment by alvipeo** [comment]
Added to Wiki here https://github.com/AngularClass/angular2-webpack-starter/wiki/How-to-use-Bootstrap-4-and-Sass-(and-jQuery)
