### ISSUE TITLE
Serving generated assets

### ISSUE THREAD

**Issue by quanterion** [AngularClass/angular2-webpack-starter#288]
In this starter we have assets serving from _/src_ folder. However I need to copy some assets from different locations and generate on the fly some images in build step.

This way folders _/src/assets_ and _dist/assets_ have different content and I can't serve _"src/assets"_ as is.

What is the best way to deal this such situation?

PS: I tried to serve from /dist, but webpack dev server loads _index.html _ and js files from_ /dist _ folder, instead of from memory auto updated content. May be I should generate_ /src/assets_ folder using some gulp task?!

**Comment by spock123** [comment]
I would use npm scripts or pure bash/cp command in your package.json for those file-movings.
