### ISSUE TITLE
TSLint not working with `npm run lint`

### ISSUE THREAD

**Issue by sasidhar** [AngularClass/angular2-webpack-starter#289]
When I run in Dev mode, everything is working fine.
`npm start`

When I build for production, there are some TSLint errors. But these errors are not full and when I fix the issues shown and run the build command once again some more TSLint issues are shown.
`npm run build:prod`

I also tried linting using `lint` script. But It is not able to find any files. So, 0 files found and No issues found.
`npm run lint`

How can I update the script to lint all the files with watch using some script like `npm run lint` and once all issues are resolved do the build for production?

For reference I removed ending new line in `main.ts` and do the build for production. It failed. But when I ran `npm run lint` - no files found.

**Comment by jmiazga** [comment]
+1 ```npm run build:prod``` shows TSLint errors, but ```npm run lint``` does not.

**Comment by sasidhar** [comment]
When I add `-u` or `--use-glob` in `package.json`'s `lint` script, I am able to Lint for TypeScript errors.

But after first run, `tsconfig.json` file is updated with all the TypeScript files list. We might not want this.

**Comment by sasidhar** [comment]
Same Issue : #378
