### ISSUE TITLE
UNMET PEER DEPENDENCY phantomjs-prebuilt

### ISSUE THREAD

**Issue by Somiks** [AngularClass/angular2-webpack-starter#294]
hi,
I can't get this project. 
├── UNMET PEER DEPENDENCY phantomjs-prebuilt@>=1.9
└─┬ protractor@3.0.0
  └─┬ selenium-webdriver@2.48.2
    └─┬ ws@0.8.1
      └─┬ utf-8-validate@1.2.1
        ├── bindings@1.2.1
        └── nan@2.2.0

**Comment by gdi2290** [comment]
can you update to latest changes

**Comment by gdi2290** [comment]
oops nvm I meant that comment for another repo.

**Comment by Somiks** [comment]
how can it do it? should I do it throug npm command or i need to download again this package?

**Comment by gdi2290** [comment]
you can make sure to install it https://github.com/AngularClass/angular2-webpack-starter/blob/efb248c31219dd2ecaf1262b2136acde5a73e7fa/package.json#L74

you can also look at your project and the version here and update depending on the difference in the build system

**Comment by gdi2290** [comment]
I'm going to close this but if you still have a problem please open another issue
