### ISSUE TITLE
Sass file cannot be found in the Production environment

### ISSUE THREAD

**Issue by mattma** [AngularClass/angular2-webpack-starter#295]
Based on your [solution](https://github.com/AngularClass/angular2-webpack-starter/wiki/How-to-use-Bootstrap-4-and-Sass-(and-jQuery)), and following your [example](https://github.com/AngularClass/angular2-webpack-starter/wiki/How-to-include-SCSS-in-components), I implemented `sass` style [by forking your repo today](https://github.com/mattma/angular2-webpack-starter/commit/0bd9c255594aff096e4ae60f4f744a5a04443168)

It will work great in the development environment, But it failed to find the *stylesheet* in the `production` environment. 

If you pull down my test [repo](https://github.com/mattma/angular2-webpack-starter). And if you run `npm start`, it works great. but after you run `npm run build:prod`, `npm run server:prod`. and then you open in the browser, you will see the error below:

<img width="884" alt="screen shot 2016-02-03 at 3 32 46 pm" src="https://cloud.githubusercontent.com/assets/1148428/12800649/7883e054-ca8b-11e5-9a59-8780296d0151.png">

I have tried to filter the error and it is coming from [sass import statement](https://github.com/mattma/angular2-webpack-starter/blob/master/src/app/home/home.ts#L25). Tried with `styles` instead of `styleUrls`. I got other errors. even tried with exact your suggestion, I still get errors. 

Another common error I encountered is 

<img width="886" alt="screen shot 2016-02-03 at 3 31 54 pm" src="https://cloud.githubusercontent.com/assets/1148428/12800678/becadcb6-ca8b-11e5-9239-ef76b9dfd40e.png">

I am sure that it could be fixed by a couple of configurations of webpack. All we need here, is embedded stylesheet inline in the javascript file, at the same time, avoid the Typescript error `2374 -> Duplicate number index signature`. Any idea?

**Comment by gdi2290** [comment]
for what you're doing you also need to include sass https://github.com/mattma/angular2-webpack-starter/blob/master/webpack.config.js#L45 and don't use `styles` or `styleUrls` since you're opting into webpack's way of managing the styles rather than angular2

**Comment by mattma** [comment]
I tried with `import './path/to/style.sass'` before I submit the issue (more like a question) instead of `styleUrls: [...]`, it works. 

Can I ask you questions? 

Is there any drawback on opt-out **angular2** styles? What about `ViewEncapsulation.None `, `ViewEncapsulation.Emulated`,`ViewEncapsulation.Native `, do I still get the benefit what Angular2 offers?

When I opt-in webpack way, what did webpack do for the style? does webpack concat all component styles into one giant stylesheet? or does it still stay individual pack and embedded as string into component javascript?

thanks a lot.

**Comment by samvloeberghs** [comment]
I believe webpack will only parse the sass files and give back css, which is than required (in your component). What I do is just something like:

```
@Component({
    selector: 'iw-estate',  // <iw-property></iw-property>
    directives: [ROUTER_DIRECTIVES, NgIf],
    providers: [EstatesService],
    styles: [require('./iwEstate.scss')],
    template: require('./iwEstate.html'),
    encapsulation: ViewEncapsulation.None
})
```
I believe that will still let you benefit from angular handling the css.

**Comment by mattma** [comment]
@samvloeberghs I do not need a sass file in prod environment. Since I am coming from world of Gulp, still new to webpack, I am not too familiar with this use case. 

What I really want, compile `scss` into `css`, that is it, no debugging needed in prod. 

In my component source file, I have `styles: [require('./myComponent.scss')],`, in that case, in the production build, I need to compile `scss` to `css`, but component file still referencing `myComponent.scss`, that is part that I do not understand completely. 

Your approach works 100% fine in development environment, could you show me really quick on how to make it work in prod environment? Use [this test repo](https://github.com/mattma/angular2-webpack-starter)

**Comment by mattma** [comment]
@samvloeberghs I tried with your solution, it did not work as expected. Some styles works like `h1[_ngcontent-hkn-3]` selector, most of them did not. I am not sure how to make it work.

@gdi2290 solutions works fine. I just want to know the details what is behind the scene. [See my previous questions](https://github.com/AngularClass/angular2-webpack-starter/issues/295#issuecomment-179642614)
