### ISSUE TITLE
Tried to use beta.3 released today

### ISSUE THREAD

**Issue by alvipeo** [AngularClass/angular2-webpack-starter#296]
And got a bunch of errors regarding zone like:

>ERROR in ./~/zone.js/lib/patch/geolocation.ts
(4,14): error TS2339: Property 'navigator' does not exist on type 'Global'.

Used these as dependencies:

```
    "angular2": "2.0.0-beta.3",
    "es6-promise": "^3.0.2",
    "es6-shim": "^0.33.3",
    "es7-reflect-metadata": "^1.5.5",
    "rxjs": "^5.0.0-beta.0",
    "zone.js": "^0.5.11"
```
So, again, webpack is black hole...

**Comment by gdi2290** [comment]
this is a problem with the recent release that uses an old version of  `zone.js`. I can update the repo

**Comment by alvipeo** [comment]
yes, please. btw, I cloned the whole repo (as of now) and build it, got lots of errors. Just FYI

**Comment by gdi2290** [comment]
@alvipeo everything should be fixed it the latest release (a couple of minutes ago) feel free to open again if you run into a problem
