### ISSUE TITLE
How to debug tests? (VS Code)

### ISSUE THREAD

**Issue by alvipeo** [AngularClass/angular2-webpack-starter#297]
Writing tests without being able to debug code is difficult. Can we debug tests somehow in VS Code?

Thanks!

**Comment by yaroslavya** [comment]
:+1:

**Comment by alvipeo** [comment]
I tried it. But that's not what I'm talking about. I'd like to be able to use debugger in VS Code while running tests. So I could set a breakpoint inside test code.

**Comment by sumigoma** [comment]
https://github.com/AngularClass/angular2-webpack-starter/issues/144

This extension is usable and allows you to set breakpoints in VS Code, but configuring it correctly is still a pain. Webpack-dev-server puts the transpiled .js files in a virtual filesystem so the sourcemaps can't map the lines correctly to your typescript without some work. Still experimenting.

**Comment by alvipeo** [comment]
Please share your findings when you're done.

**Comment by sumigoma** [comment]
You can get it working by installing the vscode chrome debug extension in vscode (https://github.com/Microsoft/vscode-chrome-debug), and then changing the output in module.exports within webpack.config.js to get webpack to change the sourcemaps to point to the local filesystem.

      // Config for our build files
      output: {
        path: root('dist'),
        filename: '[name].bundle.js',
        sourceMapFilename: '[name].map',
        chunkFilename: '[id].chunk.js',
        devtoolModuleFilenameTemplate: function(info) {
          return "file:///"+info.absoluteResourcePath;
        }
      },

You'll need to change launch.json in vscode to the following
    {
      "version": "0.1.0",
      // List of configurations. Add new configurations or edit existing ones.
      // ONLY "node" and "mono" are supported, change "type" to switch.
      "configurations": [
        {
          "name": "Attach",
          "type": "chrome",
          "request": "attach",
          "port": 9222,
          "webRoot": "dist",
          "sourceMaps": true
        }
      ]
    }

And finally, you can run npm run build:dev, followed by npm run server:prod to output the build files to dist and get http-server to load from that. Note that you won't be using webpack-dev-server, so you lose the auto-refresh capabilities. You'll have to manually build:dev again whenever you make a code change.

**Comment by siready** [comment]
You could this this plugin: https://github.com/gajus/write-file-webpack-plugin, so you wouldn't need to run two separate scripts to create build files.

**Comment by sumigoma** [comment]
I tried this back when write-file-webpack-plugin had webpack 1.x as a dependency, but I couldn't get it to work. The project now uses webpack 2.x, but things may have improved since the last time I tried. Still requires investigation.

**Comment by siready** [comment]
How far did you get? Did debugging work for you? Attaching to chrome process did work for me and I could see console output, but I didn't see any success setting any breakpoint in the code. They just wouldn't get hit.

**Comment by tan9** [comment]
@siready the write-file-webpack-plugin works smoothly for me as described in https://github.com/AngularClass/angular2-webpack-starter/issues/144#issuecomment-198265242
