### ISSUE TITLE
Problem when trying to install typings

### ISSUE THREAD

**Issue by dbarke** [AngularClass/angular2-webpack-starter#302]
Hi!

When trying to install the application according to the [guide](https://github.com/AngularClass/angular2-webpack-starter#getting-started), on the step "typings install", I run in to trouble and get this error:

>typings install
typings ERR! message Unable to read typings for "zone". You should check the path is correct
typings ERR! caused by https://raw.githubusercontent.com/angular/DefinitelyTyped/b923a5aaf013ac84c566f27ba6b5843211981c7a/zone/zone.js.d.ts responded with 404, expected it to equal 200

>typings ERR! cwd C:\angular2\angular2-webpack-starter
typings ERR! system Windows_NT 10.0.10586
typings ERR! command "C:\\nodejs\\node.exe" "C:\\Users\\daniel.barke\\AppData\\Roaming\\npm\\node_modules\\typings\\dist\\bin\\typings-install.js"
typings ERR! node -v v4.1.2
typings ERR! typings -v 0.6.6

>typings ERR! If you need help, you may report this error at:
typings ERR!   <https://github.com/typings/typings/issues>

Any suggestions on what goes wrong here?

/Daniel

**Comment by mastertinner** [comment]
this should be fixed with #301

**Comment by dbarke** [comment]
Ah, thanks!
