### ISSUE TITLE
duplicate declarations

### ISSUE THREAD

**Issue by idiotstrike** [AngularClass/angular2-webpack-starter#303]
On a fresh install after running npm install and typings install, the typescript compiler throws about a million duplicate identifier errors (I'm running the compiler using webpack):

> ERROR in /var/www/dev/starter/typings/browser/ambient/ng2/ng2.d.ts
> (21,3): error TS2300: Duplicate identifier 'clearTimeout'.
> 
> ERROR in /var/www/dev/starter/typings/browser/ambient/ng2/ng2.d.ts
> (22,3): error TS2300: Duplicate identifier 'setInterval'.
> 
> ERROR in /var/www/dev/starter/typings/browser/ambient/ng2/ng2.d.ts
> (23,3): error TS2300: Duplicate identifier 'clearInterval'.
> 
> ERROR in /var/www/dev/starter/typings/browser/ambient/hammerjs/hammerjs.d.ts
> (18,3): error TS2300: Duplicate identifier 'defaults'.
> 
> ERROR in /var/www/dev/starter/typings/browser/ambient/hammerjs/hammerjs.d.ts
> (20,3): error TS2300: Duplicate identifier 'VERSION'.
> 
> ERROR in /var/www/dev/starter/typings/browser/ambient/hammerjs/hammerjs.d.ts
> (22,3): error TS2300: Duplicate identifier 'INPUT_START'.
> 
> ERROR in /var/www/dev/starter/typings/browser/ambient/hammerjs/hammerjs.d.ts
> (23,3): error TS2300: Duplicate identifier 'INPUT_MOVE'.
> 
> ERROR in /var/www/dev/starter/typings/browser/ambient/hammerjs/hammerjs.d.ts
> (24,3): error TS2300: Duplicate identifier 'INPUT_END'.
> 
> ERROR in /var/www/dev/starter/typings/browser/ambient/hammerjs/hammerjs.d.ts
> (25,3): error TS2300: Duplicate identifier 'INPUT_CANCEL'.
> 
> ERROR in /var/www/dev/starter/typings/browser/ambient/hammerjs/hammerjs.d.ts
> (27,3): error TS2300: Duplicate identifier 'STATE_POSSIBLE'.
> 
> ERROR in /var/www/dev/starter/typings/browser/ambient/hammerjs/hammerjs.d.ts
> (28,3): error TS2300: Duplicate identifier 'STATE_BEGAN'.
> 
> ERROR in /var/www/dev/starter/typings/browser/ambient/hammerjs/hammerjs.d.ts
> (29,3): error TS2300: Duplicate identifier 'STATE_CHANGED'.
> 
> ERROR in /var/www/dev/starter/typings/browser/ambient/hammerjs/hammerjs.d.ts
> (30,3): error TS2300: Duplicate identifier 'STATE_ENDED'.
> 
> ERROR in /var/www/dev/starter/typings/browser/ambient/hammerjs/hammerjs.d.ts
> (31,3): error TS2300: Duplicate identifier 'STATE_RECOGNIZED'.
> 
> ERROR in /var/www/dev/starter/typings/browser/ambient/hammerjs/hammerjs.d.ts
> (32,3): error TS2300: Duplicate identifier 'STATE_CANCELLED'.
> 
> ERROR in /var/www/dev/starter/typings/browser/ambient/hammerjs/hammerjs.d.ts
> (33,3): error TS2300: Duplicate identifier 'STATE_FAILED'.
> 
> ERROR in /var/www/dev/starter/typings/browser/ambient/hammerjs/hammerjs.d.ts
> (35,3): error TS2300: Duplicate identifier 'DIRECTION_NONE'.
> 
> ERROR in /var/www/dev/starter/typings/browser/ambient/hammerjs/hammerjs.d.ts
> (36,3): error TS2300: Duplicate identifier 'DIRECTION_LEFT'.
> 
> ERROR in /var/www/dev/starter/typings/browser/ambient/hammerjs/hammerjs.d.ts
> (37,3): error TS2300: Duplicate identifier 'DIRECTION_RIGHT'.
> 
> ERROR in /var/www/dev/starter/typings/browser/ambient/hammerjs/hammerjs.d.ts
> (38,3): error TS2300: Duplicate identifier 'DIRECTION_UP'.
> 
> ERROR in /var/www/dev/starter/typings/browser/ambient/hammerjs/hammerjs.d.ts
> (39,3): error TS2300: Duplicate identifier 'DIRECTION_DOWN'.
> 
> ERROR in /var/www/dev/starter/typings/browser/ambient/hammerjs/hammerjs.d.ts
> (40,3): error TS2300: Duplicate identifier 'DIRECTION_HORIZONTAL'.
> 
> ERROR in /var/www/dev/starter/typings/browser/ambient/hammerjs/hammerjs.d.ts
> (41,3): error TS2300: Duplicate identifier 'DIRECTION_VERTICAL'.
> 
> ERROR in /var/www/dev/starter/typings/browser/ambient/hammerjs/hammerjs.d.ts
> (42,3): error TS2300: Duplicate identifier 'DIRECTION_ALL'.
> 
> ERROR in /var/www/dev/starter/typings/browser/ambient/hammerjs/hammerjs.d.ts
> (44,3): error TS2300: Duplicate identifier 'Manager'.
> 
> ERROR in /var/www/dev/starter/typings/browser/ambient/hammerjs/hammerjs.d.ts
> (45,3): error TS2300: Duplicate identifier 'Input'.
> 
> ERROR in /var/www/dev/starter/typings/browser/ambient/hammerjs/hammerjs.d.ts
> (46,3): error TS2300: Duplicate identifier 'TouchAction'.
> 
> ERROR in /var/www/dev/starter/typings/browser/ambient/hammerjs/hammerjs.d.ts
> (48,3): error TS2300: Duplicate identifier 'TouchInput'.
> 
> ERROR in /var/www/dev/starter/typings/browser/ambient/hammerjs/hammerjs.d.ts
> (49,3): error TS2300: Duplicate identifier 'MouseInput'.
> 
> ERROR in /var/www/dev/starter/typings/browser/ambient/hammerjs/hammerjs.d.ts
> (50,3): error TS2300: Duplicate identifier 'PointerEventInput'.
> 
> ERROR in /var/www/dev/starter/typings/browser/ambient/hammerjs/hammerjs.d.ts
> (51,3): error TS2300: Duplicate identifier 'TouchMouseInput'.
> 
> ERROR in /var/www/dev/starter/typings/browser/ambient/hammerjs/hammerjs.d.ts
> (52,3): error TS2300: Duplicate identifier 'SingleTouchInput'.
> 
> ERROR in /var/www/dev/starter/typings/browser/ambient/hammerjs/hammerjs.d.ts
> (54,3): error TS2300: Duplicate identifier 'Recognizer'.
> 
> ERROR in /var/www/dev/starter/typings/browser/ambient/hammerjs/hammerjs.d.ts
> (55,3): error TS2300: Duplicate identifier 'AttrRecognizer'.
> 
> ERROR in /var/www/dev/starter/typings/browser/ambient/hammerjs/hammerjs.d.ts
> (56,3): error TS2300: Duplicate identifier 'Tap'.
> 
> ERROR in /var/www/dev/starter/typings/browser/ambient/hammerjs/hammerjs.d.ts
> (57,3): error TS2300: Duplicate identifier 'Pan'.
> 
> ERROR in /var/www/dev/starter/typings/browser/ambient/hammerjs/hammerjs.d.ts
> (58,3): error TS2300: Duplicate identifier 'Swipe'.
> 
> ERROR in /var/www/dev/starter/typings/browser/ambient/hammerjs/hammerjs.d.ts
> (59,3): error TS2300: Duplicate identifier 'Pinch'.
> 
> ERROR in /var/www/dev/starter/typings/browser/ambient/hammerjs/hammerjs.d.ts
> (60,3): error TS2300: Duplicate identifier 'Rotate'.
> 
> ERROR in /var/www/dev/starter/typings/browser/ambient/hammerjs/hammerjs.d.ts
> (61,3): error TS2300: Duplicate identifier 'Press'.
> 
> ERROR in /var/www/dev/starter/typings/browser/ambient/hammerjs/hammerjs.d.ts
> (75,3): error TS2300: Duplicate identifier 'domEvents'.
> 
> ERROR in /var/www/dev/starter/typings/browser/ambient/hammerjs/hammerjs.d.ts
> (76,3): error TS2300: Duplicate identifier 'enable'.
> 

Any ideas?

**Comment by gdi2290** [comment]
can you run `npm run fix:ng2`

**Comment by idiotstrike** [comment]
Thanks, that fixed it.

**Comment by ciobamike** [comment]
I've the exact same problem, but the fix:ng2 does not work :(  (I take the script from a older version, since I just clone the repo recently.)

**Comment by louisscruz** [comment]
I have the same issue. I've trying to update my clone of an older version, and I'm receiving about 20 duplicate messages.

**Comment by louisscruz** [comment]
`npm run fix:ng2` no longer exists in the package.json

**Comment by louisscruz** [comment]
Ok, no more duplicates. I was attempting to update an old clone of the project. After I deleted the `test` folder, the duplicate errors vanished. Hope this can help someone else.
