### ISSUE TITLE
404 on zone.d.ts on npm install

### ISSUE THREAD

**Issue by Migrain** [AngularClass/angular2-webpack-starter#304]
I'am Getting 404 on zone.d.ts on npm install. Is it the correct adress and it is just down or is something wrong with my setup?

Full trace:
typings ERR! message Unable to read typings for "zone". You should check the path is correct
typings ERR! caused by https://raw.githubusercontent.com/angular/DefinitelyTyped/31e7317c9a0793857109236ef7c7f223305a8aa9/zone/zone.d.ts responded with 404, expected it to equal 200

typings ERR! cwd /home/daniel/projects/angular2-webpack-starter
typings ERR! system Linux 3.2.0-4-amd64
typings ERR! command "/usr/local/bin/node" "/home/daniel/projects/angular2-webpack-starter/node_modules/typings/dist/bin/typings-install.js"
typings ERR! node -v v5.4.1
typings ERR! typings -v 0.6.6

typings ERR! If you need help, you may report this error at:
typings ERR!   <https://github.com/typings/typings/issues>

npm ERR! Linux 3.2.0-4-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "typings-install"
npm ERR! node v5.4.1
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! angular2-webpack-starter@2.0.0 typings-install: `typings install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular2-webpack-starter@2.0.0 typings-install script 'typings install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-webpack-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     typings install
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular2-webpack-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/daniel/projects/angular2-webpack-starter/npm-debug.log

npm ERR! Linux 3.2.0-4-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.4.1
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! angular2-webpack-starter@2.0.0 postinstall: `npm run typings-install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular2-webpack-starter@2.0.0 postinstall script 'npm run typings-install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-webpack-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run typings-install
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular2-webpack-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/daniel/projects/angular2-webpack-starter/npm-debug.log

**Comment by abdulhaq-e** [comment]
I believe https://github.com/AngularClass/angular2-webpack-starter/pull/301 fixes the url.

**Comment by Migrain** [comment]
Great! thnx!

**Comment by gdi2290** [comment]
thanks for creating the issue :+1:  fixed via https://github.com/AngularClass/angular2-webpack-starter/pull/301
