### ISSUE TITLE
Not really on topic but still - can't use fromArray on Observable

### ISSUE THREAD

**Issue by alvipeo** [AngularClass/angular2-webpack-starter#305]
I use this great repo as a source for my ng2 project and in my tests I need to use Observable.fromArray. But this simple code fails:
```
                const f = Observable.fromArray([1, 3, 5]);
                f.subscribe(d => console.log(d));
```
Here's an error:
>Failed: undefined is not a constructor (evaluating 'Observable_1.Observable.fromArray([1, 3, 5])')

Could anyone have an idea what would cause that? I'm stuck with this.

**Comment by abdulhaq-e** [comment]
1- Show how `Observable` is imported.
2- Try `from` rather than `fromArray`, according to rxjs 4 docs, `fromArray` has been deprecated. I'm not sure if it was reimplemented in rxjs 5.

**Comment by alvipeo** [comment]
Here are all Rx related imports:
```
import {Observable} from "rxjs/Observable";
import { ArrayObservable } from 'rxjs/observable/fromArray';
import {Subject} from 'rxjs/Subject';
import {BehaviorSubject} from "rxjs/subject/BehaviorSubject";
```

I tried *from*, *of* - all the same.

**Comment by alvipeo** [comment]
Could anyone please put these 2 lines of code in their angular2 project just to check if it's my local issue please?
```
const f = Observable.fromArray([1, 3, 5]);
f.subscribe(d => console.log(d));
```

**Comment by valorkin** [comment]
@alvipeo ng2 use rxjs v5 not 4
this could help https://github.com/ReactiveX/RxJS/blob/master/MIGRATION.md
and `fromArray` deprecated, use `from` instead
there are better place for this kind of questions
https://gitter.im/Reactive-Extensions/RxJS

**Comment by alvipeo** [comment]
ok, I found out this results in an error when running these 2 lines of code in a test method. If I run prj in a browser, no problem, values are in console log. But yeah, probably is an issue with angular test framework.
