### ISSUE TITLE
globalize a variable from **polypills**

### ISSUE THREAD

**Issue by MurhafSousli** [AngularClass/angular2-webpack-starter#306]
I added a third party library in **polyfills.ts** 
```
var WP = require( 'wordpress-rest-api' );
var wp = new WP({ endpoint: 'http://localhost/wptest/wp-json' });
```
I want to be able to call `wp` from any component.
```
wp.posts().then(function( data ) {
            console.log(data);
        }).catch(function( err ) {
            // handle error
        });
```
I want to avoid requiring the library in each component page, how can I globalize a variable from **polypills.ts**

**Comment by gdi2290** [comment]
the same way you include jQuery https://github.com/AngularClass/angular2-webpack-starter/wiki/How-to-include-jQuery

**Comment by gdi2290** [comment]
thanks for opening an issue and please review the provide plugin method of injecting global modules. if you have any more issues feel free to open another one thanks

**Comment by MurhafSousli** [comment]
@gdi2290 Thank you
