### ISSUE TITLE
Update Quick Start section

### ISSUE THREAD

**Issue by rjmreis** [AngularClass/angular2-webpack-starter#309]
Please remove this step from the Quick Start section
```bash
# install TypeScript typings
npm run typings-install
```
There is already a postinstall script in package.json that will install the typings.

**Comment by gdi2290** [comment]
@rjmreis can you make a pull-request?

**Comment by rjmreis** [comment]
Done.
https://github.com/AngularClass/angular2-webpack-starter/pull/330
