### ISSUE TITLE
jasmine.d.ts not available

### ISSUE THREAD

**Issue by mburger81** [AngularClass/angular2-webpack-starter#311]
Hello,

I'm using your angular2-webpack-starter and on npm install I get this error

> typings install
typings ERR! message Unable to read typings for "jasmine". You should check the path is correct
typings ERR! caused by https://raw.githubusercontent.com/angular/DefinitelyTyped/4b36b94d5910aa8a4d20bdcd5bd1f9ae6ad18d3c/jasmine/jasmine.d.ts responded with 404, expected it to equal 200

thx
  Michael

**Comment by gdi2290** [comment]
can you update your typings.json to the latest changes https://github.com/AngularClass/angular2-webpack-starter/blob/master/typings.json

**Comment by mburger81** [comment]
I cloned your master and there anything works fine. I fink i will upgrade my project to your last master!

Some hours before I tried to update typings.json to your last one but it didn't work, maybe I did something wrong.

thx
  Michael
