### ISSUE TITLE
Does not find icons

### ISSUE THREAD

**Issue by mburger81** [AngularClass/angular2-webpack-starter#313]
After run npm start on an empty project in my browser console I see this errors
GET http://localhost:3000/icon/favicon-16x16.png 404 (Not Found)
GET http://localhost:3000/icon/favicon-96x96.png 404 (Not Found)
GET http://localhost:3000/icon/favicon-32x32.png 404 (Not Found)
GET http://localhost:3000/icon/android-icon-192x192.png 404 (Not Found)

in your index.html you referenced it so
....href="/icon/favicon-16x16.png">

but the icons are in assets

Michael

**Comment by gdi2290** [comment]
they are all under `assets/`
