### ISSUE TITLE
how to use app.html template url instead of multi-line template string?

### ISSUE THREAD

**Issue by hoff** [AngularClass/angular2-webpack-starter#314]
(probably a question instead of an issue)

When I move the multi-line template string in app.ts to a file (app.html, next to app.ts) and specify templateUrl: './app.html', I get an error: Failed to load app.html (main.ts:35).

What do I need to do to use a template file instead of multi-line string in app.ts?

**Comment by samvloeberghs** [comment]
try `template: require('./app.html')` instead of `templateUrl: './app.html';`

**Comment by valorkin** [comment]
one way as @samvloeberghs said
or use copy webpack loader

**Comment by uglow** [comment]
@samvloeberghs - that works for me, but I'm using `html-loader?minimise=true` to load HTML files in `webpack.config.js`, instead of `raw-loader`. This strips the HTML of unnecessary characters (good!) but then Angular2's TemplateNormalizer thinks my HTML is invalid (which is incorrect).

HTML:  `<div><img src=path/to/img.png> <a href=#/page1>Link</a></div>`

Is that why you are using `raw-loader`, because of Angular2's buggy HTML parser?

**Comment by samvloeberghs** [comment]
No, I'm not yet at the stage where I want to minify my HTML.
Will definitely look into that in the near future, so if you find a good solution please post your findings here? :+1:

**Comment by samvloeberghs** [comment]
@uglow did you try other configurations? Like for example not to strip single and/or double quotes? As far as I can tell that might be one of the most obvious reasons it's not working, but indeed it should not be as it is valid HTML5.

Angular2 might have other requirements than the way a browser handles HTML5.

@gdi2290 what do you think? :)

**Comment by uglow** [comment]
@samvloeberghs - The following strings **work**:
```
<div><img src="/assets/demoModule/img/blank-logo.d71838b1.png"> <a class="btn" href="#/page2">Link</a></div>

<div><img src="/assets/demoModule/img/blank-logo.d71838b1.png"> <a class=btn href="#/page2">Link</a></div>
```

These strings do **not work**:
```
<div><img src="/assets/demoModule/img/blank-logo.d71838b1.png"> <a class=btn href=#/page2>Link</a></div>

<div><img src=/assets/demoModule/img/blank-logo.d71838b1.png> <a class=btn href="#/page2">Link</a></div>
```

So it appears that the template parser may be looking for `">` to determine the end of the start-tag of a HTML element. Notice that `<a class=btn href="...">` works, even though there are no quotes for the `class` attribute.

I've raised this question on the [Angular repo](https://github.com/angular/angular/issues/6099#issuecomment-188771286), and they suggested I raise a new issue. So I'll do that now.

**Comment by uglow** [comment]
Raised issue [7225](https://github.com/angular/angular/issues/7295) on Angular2

**Comment by uglow** [comment]
I've [documented a Webpack html-loader configuration](https://github.com/angular/angular/issues/7295#issuecomment-189063411) that seems to work with Angular2.0.0-beta6
