### ISSUE TITLE
Symlink directory can't import from node_modules

### ISSUE THREAD

**Issue by panKt** [AngularClass/angular2-webpack-starter#315]
I'm symlinking directory to my project and all the ```.ts``` works fine except those who have any imports from ```node_modules``` dir, for example 
```javascript
import { URLSearchParams, Response } from 'angular2/http'
```
will throw error
```
(1,43): error TS2307: Cannot find module 'angular2/http'.
```

I tried to set ```fallback```, ```root```, ```modulesDirectories``` in **webpack.config.js** but with no luck :(

```javascript
  resolve: {
    fallback: [path.join(__dirname, 'node_modules')],
    root:     [path.join(__dirname, 'node_modules')],
    modulesDirectories: [path.join(__dirname, 'node_modules')],
    ...
  },

  resolveLoader: {
    fallback: [path.join(__dirname, 'node_modules')]
  },
```

**Comment by gdi2290** [comment]
I updated the repo a bit so pull latest changes and open another issue if you still have the problem thanks
