### ISSUE TITLE
Using PostCSS with the "styles" meta property

### ISSUE THREAD

**Issue by Spittal** [AngularClass/angular2-webpack-starter#316]
Hey,

I'm looking to make a component that scopes styles that are processed using PostCSS
```typescript
@Component({
  selector: 'hny-header',
  template: require('./header-template.html'),
  styles: [
    require('./header-styles.css')
  ]
})
export class HnyHeader {

}
```

I'm using the raw approach so that my styles return as strings, here's my configuration
```javascript
//...
{ test: /\.css$/,   loader: 'raw-loader!css-loader!postcss-loader'},
//...
postcss: [
    require("postcss-import")({ addDependencyTo: webpack }),
    require('postcss-cssnext')({
			browsers: ['ie >= 9', 'last 2 versions']
		}),
    require("postcss-reporter")()
  ],
```

It looks like my styles are scoping but they don't seem to be loading as a raw string. They look like this
```
exports[_ngcontent-vwu-4] =[_ngcontent-vwu-4] module.exports[_ngcontent-vwu-4] =[_ngcontent-vwu-4] require("./../../../../node_modules/css-loader/lib/css-base.js")()[_ngcontent-vwu-4];
//[_ngcontent-vwu-4] imports


//[_ngcontent-vwu-4] module
exports.push([module.id[_ngcontent-vwu-4], ".hny-header[_ngcontent-vwu-4] {\n  color: yellow;\n}\n"[_ngcontent-vwu-4], ""])[_ngcontent-vwu-4];

// exports
```

Is this because the `postcss-loader` doesn't return a string? And if so is there a workaround for that?

Thanks

**Comment by Spittal** [comment]
If it means anything I found a really great NPM package for this exact purpose called `to-string`

https://www.npmjs.com/package/to-string-loader

Now I can load whatever I want with the css-loader and cast it to a string. Works great with Angular 2 emulated encapsulation.

**Comment by gdi2290** [comment]
@Spittal can you update this wiki page https://github.com/AngularClass/angular2-webpack-starter/wiki/How-to-include-PostCSS on how to include PostCSS (or at least what you have already). I can try it out and see what the fix is

**Comment by Spittal** [comment]
I added a pretty detail explanation now.

https://github.com/AngularClass/angular2-webpack-starter/wiki/How-to-include-PostCSS

As for my problem before, I wasn't targeting `:host` in my css file, I was targeting the actual selector. Which messed up scoping.

I've change my css file to be
```
:host {
  color: red;
}

```

**Comment by gdi2290** [comment]
awesome thanks!

**Comment by samvloeberghs** [comment]
didn't know yet about that :host selector! nice

**Comment by MikaAK** [comment]
I tried this and am still getting errors. My full loader query is `'to-string!css?sourceMap' + (isProd ? '&minimize' : '') + '!postcss!sass?sourceMap'`. I also tried prepending `raw` to it to see if that would work but I'm still met with the error below.

```      Invalid CSS after "...load the styles": expected 1 selector or at-rule, was "content = requi..."```

**Comment by Spittal** [comment]
It must be the order of the loaders, but I can't see why. Try removing loaders and putting them back in one by one and see when in the chain it breaks.
