### ISSUE TITLE
Working BDD Test Examples - Missing dependencies

### ISSUE THREAD

**Issue by MartinMuzatko** [AngularClass/angular2-webpack-starter#317]
Hello there!
First of all: thank you a lot for creating this awesome starter package, it sure helped me to understand how BDD can't run with Jasmine alone - especially if you are going to test in typescript.

I'm talking about the current `app.spec.ts` example, there is describe missing in the import.

https://github.com/AngularClass/angular2-webpack-starter/blob/master/src/app/app.spec.ts
Otherwise, Jasmine will not be able to find describe.

In home.spec.ts you should add `describe` to the list of imports.

I found other tests that do not have sufficient providers/imports.

test/sanity-test.spec.ts
test/injector.spec.ts
etc

Thanks again for compiling this package, this is a great learning resource :)

**Comment by samvloeberghs** [comment]
So what's going wrong here you believe? I just tested and he tests are running fine on my side. Try npm run test.

Perhaps your IDE is complaining that it doesn't find describe? Just guessing :)

For BDD and CucumberJs ( for example ) checkout this example project:
https://github.com/samvloeberghs/protractor-gherkin-cucumberjs-angular2

I'll be updating / providing this with more details on a blogpost soon, if I find the time :)

**Comment by ebeal** [comment]
please re-open if this is still an issue
