### ISSUE TITLE
rimraf missing on Windows platform

### ISSUE THREAD

**Issue by pdSquirrel** [AngularClass/angular2-webpack-starter#318]
Today when cloning the repo I had problems running 'npm install'. Got errors when typings was suppossed to be installed. Turned out I needed to install 'rimraf' globally before I got it to work. Known issue or just my setup?

**Comment by dsebastien** [comment]
Weird, rimraf is in the devDependencies within package.json so if you run `npm install --no-optional` it should be there.

What was the error?

**Comment by pdSquirrel** [comment]
The interesting thing is that it looks like rimraf is a dependency for typings, and based on this error I reinstalled typings globally and still got the error. Had to install rimraf by itself globally to get it to work.

```
> angular2-webpack-starter@2.0.0 fix:ng2-clean C:\Users\rono7329\projects\serviceplate\frontend
> rimraf node_modules/angular2/manual_typings node_modules/angular2/typings node_modules/angular2/bundles/typings

'rimraf' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by pdSquirrel** [comment]
Some more error output:
`npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\nodejs\\node.exe" "C:\\Users\\rono7329\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "fix:ng2-clean"
npm ERR! node v5.3.0
npm ERR! npm  v3.5.3
npm ERR! code ELIFECYCLE
npm ERR! angular2-webpack-starter@2.0.0 fix:ng2-clean: `rimraf node_modules/angular2/manual_typings node_modules/angular2/typings node_modules/angular2/bundles/typings`
npm ERR! Exit status 1`

**Comment by dsebastien** [comment]
The culprit is probably there: https://github.com/AngularClass/angular2-webpack-starter/blob/master/package.json#L37

Try to change that line to ` "fix:ng2-clean": "rimraf node_modules/angular2/manual_typings node_modules/angular2/typings node_modules/angular2/bundles/typings",`

**Comment by pdSquirrel** [comment]
So what we are doing by that change is using the global rimraf instead of the local node_module one?

**Comment by dsebastien** [comment]
Nope, actually when an npm script executes, all the scripts located under node_modules/.bin are available in the "path" and if there are conflicts with the global path (which contains your global node modules), then the local version has precedence.

**Comment by pdSquirrel** [comment]
Ohhh.. thanks for the enlightenment. I did not know.

Well, it seems to be a Windows problem. Did a clone at home tonight under Linux and did not see this problem.

**Comment by gdi2290** [comment]
I removed fix:ng2-clean in the latest changes. I probably need to include ` node_modules/.bin` again for windows. I'm going to close this but if you run into another issue feel free to open another one
