### ISSUE TITLE
TSD is deprecated

### ISSUE THREAD

**Issue by Somiks** [AngularClass/angular2-webpack-starter#323]
npm WARN deprecated tsd@0.6.5: TSD is deprecated in favor of Typings (https://gi
thub.com/typings/typings) - see https://github.com/DefinitelyTyped/tsd/issues/26
9 for more information

**Comment by gdi2290** [comment]
thanks, fixed via https://github.com/AngularClass/angular2-webpack-starter/commit/97896e31703bfbd583c37faa7f7a31edd8960608
