### ISSUE TITLE
htmlWebpackPlugin

### ISSUE THREAD

**Issue by Somiks** [AngularClass/angular2-webpack-starter#324]
URIError: Failed to decode param '/%7B%=o.htmlWebpackPlugin.files.css[css]%20%%7
D'
    at decodeURIComponent (native)

**Comment by gdi2290** [comment]
can you download latest

**Comment by gdi2290** [comment]
this should be resolved in the latest changes. feel free to open the issue again if you still have a problem

**Comment by Somiks** [comment]
@gdi2290 
 I still have this issue.
and also have this message in the top of windows 
ERROR in ./~/zone.js/lib/patch/geolocation.ts
(4,14): error TS2339: Property 'navigator' does not exist on type 'Global'.

ERROR in ./~/zone.js/lib/core.ts
(122,14): error TS2339: Property 'zone' does not exist on type 'Global'.

**Comment by Somiks** [comment]
@gdi2290 
I can't reopen this issue.

**Comment by Somiks** [comment]
@gdi2290 
ups, i forgot to update index.html. thanks it works
