### ISSUE TITLE
Getting hashingUnhandled type error when running build:prod

### ISSUE THREAD

**Issue by lanocturne** [AngularClass/angular2-webpack-starter#326]
I am getting below errors when trying to build prod dist
```
75% hashingUnhandled rejection TypeError: Reduce of empty array with no initial value
    at Array.reduce (native)
    at Compilation.<anonymous> (/ui/node_modules/webpack-md5-hash/plugin/webpack_md5_hash.js:27:82)
    at Compilation.applyPlugins (/ui/node_modules/webpack/node_modules/tapable/lib/Tapable.js:26:37)
```
Build dev dist works. My webpack.prod.config.js is updated and modified similar to webpack.config.js

Could anyone guides where I should look onto?

**Comment by gdi2290** [comment]
can you see issue https://github.com/erm0l0v/webpack-md5-hash/issues/1

**Comment by dsebastien** [comment]
Hey @gdi2290 what's the actual reason for using webpack-md5-hash? To get less risk of collisions? If so, apparently it's possible to simply pass a different hashing algorithm in the output options as per the last comment there: https://webpack.github.io/docs/long-term-caching.html

**Comment by dsebastien** [comment]
I think I've got it. It's possible to pass an initialValue to the reduce function: http://es5.github.io/#x15.4.4.21

With it I think the issue will be fixed.

**Comment by dsebastien** [comment]
FYI I've created a sibling project with SHA rather than MD5: https://www.npmjs.com/package/webpack-sha-hash

**Comment by lanocturne** [comment]
@gdi2290 Thank you! After updating md5-hash to 0.0.5 it shows me the useful error stack.
