### ISSUE TITLE
Errors in /typings/browser/ambient/

### ISSUE THREAD

**Issue by chriscurnow** [AngularClass/angular2-webpack-starter#327]
Hi I'm hoping someone can help me out of hole here.

I'm sure I solved this problem recently but I can't remember how.

Yesterday I tried running Angular 2.0.0 beta 5 but it gave me lots of errors so I just switched back to beta 3. This gave me even more errors so I ended up deleting my whole node-modules directory and re-installing.

After this most of my errors went away but now I am getting stack of errors in the /typings/browser/ambient/ directory.

This doesn't seen to affect anything when I run from the web pack server but when I try to build, the build result doesn't produce anything meaningful when I run it from a browser. (FYI I get 
`Loading... <% if (webpackConfig.metadata.ENV === 'development') { %> <% } %>`)

Any ideas on where I'm going wrong would be most appreciated.

**Comment by gdi2290** [comment]
can you update to latest changes

**Comment by chriscurnow** [comment]
Thanks @gdi2290.

I found how to fix the problem.

Delete the Typings directory.

Run npm install.

This, of course, recreates the Typings directory correctly.
