### ISSUE TITLE
typescript lint error does not lead to exit code != 0 (jenkins)

### ISSUE THREAD

**Issue by clouless** [AngularClass/angular2-webpack-starter#328]
I am using the build chain inside jenkins.

Normally I do this to fail the job if a npm run exits with exit code != 0:

```
npm run build:prod
if [ $? -ne 0 ]
then
   echo "ERROR. EXIT."
   exit 1
fi
```

But here somehow if I am having linting errors it does not fail with an error code != 0.

When I do

```
npm run lint
if [ $? -ne 0 ]
then
   echo "ERROR. EXIT."
   exit 1
fi
```

It tells me I have no lint errors.

But when running `build:prod` at the end of webpacking stage it fails silently with exit code 0.

![image](https://cloud.githubusercontent.com/assets/12599965/13003542/6d0b50d0-d176-11e5-85df-25656631ec79.png)

**Comment by jmiazga** [comment]
+1 Same problem with Teamcity.

![image](https://cloud.githubusercontent.com/assets/181441/13184942/a8e6fab4-d70c-11e5-955b-a0294fdb6eee.png)
