### ISSUE TITLE
Observables need tests

### ISSUE THREAD

**Issue by saldoukhov** [AngularClass/angular2-webpack-starter#329]
After pulling the latest (https://github.com/AngularClass/angular2-webpack-starter/commit/29855431272a3cabb8044ebee4332d75794b8632) Observables are not working. I suggest adding a unit test to prevent this from happening in the future.

**Comment by gdi2290** [comment]
can you apply this change https://github.com/AngularClass/angular2-webpack-starter/blob/master/src/polyfills.ts and see if it works

**Comment by samvloeberghs** [comment]
@saldoukhov you should check which features of RxJs you need.
For example I needed to add the share package of RxJs to get my observables implementation to work!

**Comment by robwormald** [comment]
note that if you want *all* the operators, you can do `import 'rxjs/Rx'` and it'll bring all all the ones you have listed there. It's a lot of bytes, but easier to maintain for this case.

**Comment by saldoukhov** [comment]
@gdi2290 Yes, bringing back polyfills has fixed the Rx problem... Please note, that this issue is not about broken observables, it is about that fact going unnoticed in CI...

**Comment by gdi2290** [comment]
I removed all the operators in dev mode so there will be an error if there is a missing operator. feel free to open another issue
