### ISSUE TITLE
angular2 on CDN

### ISSUE THREAD

**Issue by marekpw** [AngularClass/angular2-webpack-starter#332]
Would it be possible to make Angular 2 load from cdnjs? It doesn't make sense to compile the entire library (which is huge) with the app bundle.

Webpack allows to do this using the externals config option. I tried doing something like this:

```
externals: {
    'angular2/core': "System.import('angular2/core')",
    'angular2/router': "System.import('angular2/router')",
    'angular2/common': "System.import('angular2/common')",
    'angular2/platform/browser': "System.import('angular2/platform/browser')",
    'angular2/http': "System.import('angular2/http')"
}
```

And adding the cdnjs sources to the HTML template as such:
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/systemjs/0.19.20/system.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/2.0.0-beta.2/angular2.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/2.0.0-beta.2/router.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/2.0.0-beta.2/http.min.js"></script>
```

But I'm getting some errors, so it would be cool to see how you implement it.

**Comment by devcube** [comment]
+1 I am also interested in this. It would be nice to see this incorporated into the production configuration of this repo.

**Comment by tsm91** [comment]
Maybe it is also possible to create a third vendor entry point? I am not sure if this will help the compilation time or not.

**Comment by yjaaidi** [comment]
+1

**Comment by arnarp** [comment]
+1

**Comment by maxim25** [comment]
+1

**Comment by gdi2290** [comment]
all you would need to do is noParse and alias the files to the minified versions

**Comment by yjaaidi** [comment]
This will include the angular 2 files into the generated JS files.
It would be nice to be able to use angular 2 from public CDNs

**Comment by CumpsD** [comment]
So, how do we do this? Loading angular2 from a CDN using webpack.
