### ISSUE TITLE
A grid for webpack-starter?

### ISSUE THREAD

**Issue by chriscurnow** [AngularClass/angular2-webpack-starter#336]
I've just spent some time searching through the issues here and can't find anything regarding a grid.

Grids are very important for my project.

Has anyone tried implementing a grid? If so, which grid and how did you go about it?

I have been looking at ag-grid and it looks interesting.

I'd be happy to have a go at implementing it but I've got no idea how to go about it in webpack.

It looks like I would have to add a loader in webpack.config and then a require in my code. But I'm really only thrashing around in the dark.

Any experience, thoughts, advice or help would be much appreciated.

Best regards
Chris

**Comment by chriscurnow** [comment]
Duh, it helps if you read the documentation:(

Just read the docs for ag-grid and they have specific instructions for setting up in Angular2.

Just tried it out and it works fine if you do everything they say!!!

Regards
Chris

**Comment by gdi2290** [comment]
can you edit this wiki page on how to include it in the starter https://github.com/AngularClass/angular2-webpack-starter/wiki/How-to-include-ag-grid
