### ISSUE TITLE
Image optimization for production configuration.

### ISSUE THREAD

**Issue by Siwady** [AngularClass/angular2-webpack-starter#337]
Currently, the image folder are copied to the assets folder without any optimization with the production configuration. I'd like optimize and reduce the size of the image for the production configuration, How can I do that? , I have tried this pluggin: https://github.com/tcoopman/image-webpack-loader ,but I haven't  succeded.

**Comment by ebeal** [comment]
please see the image-webpack-loader repo for help on this

**Comment by rjlee7** [comment]
@Siwady Trying to do the same thing. Were you able to figure this out?
