### ISSUE TITLE
npm start fails

### ISSUE THREAD

**Issue by Successful** [AngularClass/angular2-webpack-starter#345]
Hi, i have cloned the repo and installed all the global dependencies, but when i run npm start i get error.

Still can reach localhost:3000 but it looks ugly, maybe thats the starter look :) Cant se any css so i guess thats ok.

Here is my error:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\******\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.7.3
3 info using node@v5.5.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle angular2-webpack-starter@3.0.0~prestart: angular2-webpack-starter@3.0.0
6 silly lifecycle angular2-webpack-starter@3.0.0~prestart: no script for prestart, continuing
7 info lifecycle angular2-webpack-starter@3.0.0~start: angular2-webpack-starter@3.0.0
8 verbose lifecycle angular2-webpack-starter@3.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle angular2-webpack-starter@3.0.0~start: PATH: C:\Users\******\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Dev\Projects\App\App.Planr\src\App.Planr\node_modules\.bin;C:\Program Files\nodejs;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\Git\bin;C:\Program Files (x86)\MySQL\MySQL Fabric 1.5 & MySQL Utilities 1.5\;C:\Program Files (x86)\MySQL\MySQL Fabric 1.5 & MySQL Utilities 1.5\Doctrine extensions for PHP\;C:\Program Files (x86)\Meld;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Common Files\lenovo\easyplussdk\bin;C:\Program Files (x86)\WinMerge;C:\Users\******\curl;C:\Program Files\Redis\;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\dotnet\bin;C:\Program Files\nodejs\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\Git\cmd;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Users\******\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc2-16357\bin;C:\Users\******\.dnx\bin;C:\Program Files (x86)\Git\bin;C:\Users\******\curl;"C:\Program Files\nodejs";C:\Users\******\AppData\Roaming\npm;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Microsoft VS Code\bin
10 verbose lifecycle angular2-webpack-starter@3.0.0~start: CWD: C:\Dev\Projects\App\App.Planr\src\App.Planr
11 silly lifecycle angular2-webpack-starter@3.0.0~start: Args: [ '/d /s /c', 'npm run server:dev' ]
12 silly lifecycle angular2-webpack-starter@3.0.0~start: Returned: code: 1  signal: null
13 info lifecycle angular2-webpack-starter@3.0.0~start: Failed to exec start script
14 verbose stack Error: angular2-webpack-starter@3.0.0 start: `npm run server:dev`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\******\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:239:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\******\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:821:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid angular2-webpack-starter@3.0.0
16 verbose cwd C:\Dev\Projects\App\App.Planr\src\App.Planr
17 error Windows_NT 10.0.10586
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\******\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v5.5.0
20 error npm  v3.7.3
21 error code ELIFECYCLE
22 error angular2-webpack-starter@3.0.0 start: `npm run server:dev`
22 error Exit status 1
23 error Failed at the angular2-webpack-starter@3.0.0 start script 'npm run server:dev'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular2-webpack-starter package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run server:dev
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs angular2-webpack-starter
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls angular2-webpack-starter
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by emin93** [comment]
How did you fix this problem?

**Comment by emin93** [comment]
Okay found the problem, compass wasn't installed. Don't know if it's the same with you, but it fixed it for me.

**Comment by kishorek129** [comment]
Hi all,

I'm facing same problem. I have verified that all the packages are installed which are listed in package.json

can any one help me ?

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.9.5
3 info using node@v6.2.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle angular2-webpack-starter@5.0.5~prestart: angular2-webpack-starter@5.0.5
6 silly lifecycle angular2-webpack-starter@5.0.5~prestart: no script for prestart, continuing
7 info lifecycle angular2-webpack-starter@5.0.5~start: angular2-webpack-starter@5.0.5
8 verbose lifecycle angular2-webpack-starter@5.0.5~start: unsafe-perm in lifecycle true
9 verbose lifecycle angular2-webpack-starter@5.0.5~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;E:\APA Check outs\PN3.5\angular2-webpack-starter-master\node_modules\.bin;C:\Program Files\nodejs;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Dell\DW WLAN Card;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\WIDCOMM\Bluetooth Software\;C:\Program Files\WIDCOMM\Bluetooth Software\syswow64;C:\Program Files\MySQL\MySQL Server 5.5\bin;C:\Program Files\TortoiseSVN\bin;C:\Program Files (x86)\gradle-2.11\bin;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\Java\jdk1.8.0_73\bin;C:\Program Files\Java\jdk1.8.0_73\bin\javaw.exe;C:\Program Files\Java\jre1.8.0_73\bin;C:\Program Files\Java\jre1.8.0_73\bin\javaw.exe;C:\Program Files\Apache\apache-maven-3.3.9\bin;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Python34;C:\Program Files (x86)\gradle-2.11\bin;C:\Users\kishore\AppData\Roaming\npm
10 verbose lifecycle angular2-webpack-starter@5.0.5~start: CWD: E:\APA Check outs\PN3.5\angular2-webpack-starter-master
11 silly lifecycle angular2-webpack-starter@5.0.5~start: Args: [ '/d /s /c', 'npm run server:dev' ]
12 silly lifecycle angular2-webpack-starter@5.0.5~start: Returned: code: 1  signal: null
13 info lifecycle angular2-webpack-starter@5.0.5~start: Failed to exec start script
14 verbose stack Error: angular2-webpack-starter@5.0.5 start: `npm run server:dev`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:245:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid angular2-webpack-starter@5.0.5
16 verbose cwd E:\APA Check outs\PN3.5\angular2-webpack-starter-master
17 error Windows_NT 6.1.7600
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v6.2.2
20 error npm  v3.9.5
21 error code ELIFECYCLE
22 error angular2-webpack-starter@5.0.5 start: `npm run server:dev`
22 error Exit status 1
23 error Failed at the angular2-webpack-starter@5.0.5 start script 'npm run server:dev'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular2-webpack-starter package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run server:dev
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs angular2-webpack-starter
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls angular2-webpack-starter
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by alvipeo** [comment]
Are you using VSCode?

**Comment by kishorek129** [comment]
No, I'm not using VSCode. I'm using webstorm 10.0.5.
