### ISSUE TITLE
Try to load http://localhost:3000/webpack-dev-server.js on dev environment

### ISSUE THREAD

**Issue by Somiks** [AngularClass/angular2-webpack-starter#350]
I see this error msg in chrome console.
I used watcher to build application and deploy using winscp sinchronization
[blocked] The page at 'https://domain1.lv/static/loan/index.html#/credit-details/HEAD-CLB-002%20%2F2010' was loaded over HTTPS, but ran insecure content from 'http://localhost:3000/webpack-dev-server.js': this content should also be loaded over HTTPS.

**Comment by gdi2290** [comment]
change the `http` to `https`
https://github.com/AngularClass/angular2-webpack-starter/blob/master/src/index.html#L56

**Comment by gdi2290** [comment]
I'm closing this for now. If you still have the problem feel free to open another issue
