### ISSUE TITLE
Uncaught reflect-metadata shim is required when using class decorators

### ISSUE THREAD

**Issue by omerbenamram** [AngularClass/angular2-webpack-starter#353]
getting this error on master branch.
using npm start

**Comment by simonturner** [comment]
You can workaround this for the time being by adding the following to the top of your polyfills.ts

`import 'zone.js';`
`import 'reflect-metadata';`

**Comment by omerbenamram** [comment]
It ended up working when i used it in main.ts and not polyfills.
I must say i'm not completely certain on why this is happening.

**Comment by skrywus** [comment]
Did you find any solution?

**Comment by gdi2290** [comment]
@skrywus can I see your repo

**Comment by gdi2290** [comment]
can you pull latest and open another issue if you still have a problem thanks

**Comment by brunolm** [comment]
> import 'zone.js';
> import 'reflect-metadata';

With `"zone.js": "^0.6.12"` TypeScript won't allow me to `import 'zone.js';`, but I could import the other one.

How can I workaround it to include zone?

**Comment by gdi2290** [comment]
see polyfills
https://github.com/AngularClass/angular2-webpack-starter/blob/master/src/polyfills.browser.ts
it's `import 'zone.js/dist/zone';`

**Comment by happyvig** [comment]
Still, its not working for me. I used `import 'zone.js/dist/zone'`. I have the exact code similar to angular2-webpack-starter.

Any updates on this issue ?

**Comment by gdi2290** [comment]
are you using npm version 3.x.x?
`npm --version`

**Comment by happyvig** [comment]
3.10.5 it is.

**Comment by umasgn** [comment]
When i try to bundle reflect-metadata with webpack i'm getting lot of warnings along with the following errors. Should i ignore these errors for my production build ?
![errors](https://cloud.githubusercontent.com/assets/12139440/17494652/490943e2-5dd3-11e6-9970-d489d5611ecf.png)

**Comment by brunolm** [comment]
@umasgn add this on top of your entry file:

    /// <reference path="../node_modules/typescript/lib/lib.es6.d.ts" />

For some reason webpack needs this

**Comment by umasgn** [comment]
Thank you very much for your reply. I modified file as you mentioned, this time getting different errors 'duplicate identifier .....'.

**Comment by radusuciu** [comment]
Not sure if we had the same issue but I was getting this exception even though the shim was being packaged and loaded before the vendor bundle. This worked for me:

```javascript
    new webpack.ProvidePlugin({
      Reflect: 'core-js/es7/reflect'
    })
```

**Comment by valdemarrolfsen** [comment]
I'm having this issue when I try to user decorators in my e2e tests. Should it still be enough to import zone.js and reflect-metadata in the polyfills-file when running tests? 

I literally tried everything, and I am feeling that I am shooting in the dark here. Whatever I do I get the same error

```
[15:22:41] I/direct - Using ChromeDriver directly...
[15:22:41] I/launcher - Running 1 instances of WebDriver
[15:22:48] E/launcher - Error: reflect-metadata shim is required when using class decorators
[15:22:48] E/launcher - Process exited with error code 100
```

**Comment by gromatl** [comment]
Thanks @radusuciu , thats fix the problem for me

**Comment by syedfarrukhqamar** [comment]
Dear all i am getting the same error

every thing was working fine and then the error started. Is there any quick fix for it. I am new in this and its getting very hard to fix it. Thanks

keywords if/then/else require v5 option
module.js:472
    throw err;
    ^

Error: Cannot find module 'reflect-metadata'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/_____/HybridApps/testing/betaProject/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:4:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

**Comment by rajinder-yadav** [comment]
I got it working using the following vendor imports:

## vendor.ts
```js
// Polyfills
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/set';
import 'core-js/es6/reflect';
import 'core-js/es7/reflect';

import 'zone.js/dist/zone';

// Angular 2
import '@angular/platform-browser';
import '@angular/platform-browser-dynamic';
import '@angular/core';
import '@angular/common';
import '@angular/http';
import '@angular/router';

import 'rxjs';
import '@angularclass/hmr';

// Other vendors for example jQuery, Lodash or Bootstrap
// You can import js, ts, css, sass, ...
```

My webpack entry looks like this:

```js
  entry: {
    app: "<path/to/your/ng-app>",
    vendor: "./vendor.ts"
  },
```

**Comment by julenr** [comment]
Use React. It solves all your problems and left you time to enjoy the life

**Comment by Phmager** [comment]
For me it seems like the main.js is loaded before the polyfills.js.
When I look at the index.html generated from aot, it generated this:

```
<script type="text/javascript" src="main.a130bdc74703d2271538.bundle.js" async></script>
<script type="text/javascript" src="polyfills.be2d4f0d81ef9285cbb7.bundle.js"></script>
```

when I turn it around to this:

```
<script type="text/javascript" src="polyfills.be2d4f0d81ef9285cbb7.bundle.js"></script>
<script type="text/javascript" src="main.a130bdc74703d2271538.bundle.js" async></script>
```

it works correctly.

**Comment by Akkusativobjekt** [comment]
@Phmager I can't thank you enough! I spend working days solving this issue and was about to give up.  I do not understand why this nasty bug (race condition style) doesn't generate more noise/attention. 

If you were not already in Munich, I would send you a beer over as reward for solving the issue :wink:

**Comment by kotpal** [comment]
Running into the same issue on TOH Part 6 sample and following the steps at https://angular.io/guide/aot-compiler

@Phmager : Where are the aot index.html and HtmlWebpackPlugin? I can't find them.

This is so frustrating that a standard example and guidelines on angular.io aren't working right off the bat.

**Comment by soromamadou** [comment]
Thanks very much @Phmager . I work fine. Good job

**Comment by TaylorPzreal** [comment]
when i use in ```Chromium```,i get this error,i found the order of scripts:
```
<script type="text/javascript" src="http://localhost:9000/manifest.js"></script>
<script type="text/javascript" src="http://localhost:9000/vendor.js"></script>
<script type="text/javascript" src="http://localhost:9000/app.js"></script>
<script type="text/javascript" src="http://localhost:9000/polyfills.js"></script>
```
when i use in ```Chrome```, it's success and order is this:
```
<script type="text/javascript" src="http://localhost:9000/manifest.js"></script>
<script type="text/javascript" src="http://localhost:9000/vendor.js"></script>
<script type="text/javascript" src="http://localhost:9000/polyfills.js"></script>
<script type="text/javascript" src="http://localhost:9000/app.js"></script>
```
I thought this error maybe becauseof browser and order.
so i changed the webpack config of HtmlWebpackPlugin and it works correct.
```
    new HtmlWebpackPlugin({
      template: 'src/index.html',
      chunksSortMode: 'dependency'
    }),
```

**Comment by darincardin** [comment]
Same issue when i run a npm build with the production flag:
webpack -p --progress

**Comment by singhmohancs** [comment]
@Phmager Thank you for a solution. Resolved issue.

**Comment by CodeSaysItBetter** [comment]
Thanks brunolm - Had this problem that solved the problem
