### ISSUE TITLE
Loading 3rd-party modules

### ISSUE THREAD

**Issue by alexey-ulashchick** [AngularClass/angular2-webpack-starter#355]
Hi! Can someone help/explain how to properly add/use external modules to this project?
For example, I'm adding `immutable` using: 
`npm install immutable --save`

After that, I'm trying to link that module inside a component:
```
import * as immutable from 'immutable';
import {List} from 'immutable';
```

Nothing helps, it always returns `TS2307: Cannot find module 'immutable'.` The same for `moment` for example.

**Comment by gdi2290** [comment]
you also need to include the type definitions with `typings`

**Comment by gdi2290** [comment]
you need to include the type definition and can read a little bit about it in the `custom-typings.d.ts` file. thanks for opening an issue and if you have anymore feel free to open another one
