### ISSUE TITLE
Dynamically load remote js file

### ISSUE THREAD

**Issue by mburger81** [AngularClass/angular2-webpack-starter#356]
I need to create different widgets for our dashboard which are all components. Some of this widgets need to load external javascript files, how can I load this files from component dynamically. I don't want to load them all from index.html, I would load them only on using the component so is there a possibility to load it  from component on require?
Should I try to do that with systemjs?

thx

**Comment by ysqi** [comment]
+1

**Comment by gdi2290** [comment]
load the component with es6-promise loader and make sure the imports to the js files are only in the entry file of the component

**Comment by ebeal** [comment]
please open again if this is still an issue

**Comment by anuteja** [comment]
any working example ?

**Comment by EloyYaniel** [comment]
one example, please
