### ISSUE TITLE
A hot reload is too slow?

### ISSUE THREAD

**Issue by xgrommx** [AngularClass/angular2-webpack-starter#358]

**Comment by gdi2290** [comment]
it is slow because it's experimental. It's faster just to have turn it off and stick with reloading

**Comment by matthieu-D** [comment]
Indeed, this should not be active by default or at least 'how to turn it off' should be in the documentation.

**Comment by gdi2290** [comment]
hot reloading should be faster after the update to awesome-typescript-loader
