### ISSUE TITLE
npm run build:dev fails

### ISSUE THREAD

**Issue by nathasm** [AngularClass/angular2-webpack-starter#360]
It looks like the error stems from `Output filename not configured`

And it looks like because the output information was removed. This fixes it for me:

```
  output: {
    path: helpers.root('dist'),
    filename: '[name].bundle.js',
    sourceMapFilename: '[name].map',
    chunkFilename: '[id].chunk.js'
  },
```

**Comment by gdi2290** [comment]
Sorry about that, thanks for opening an issue about it. I was trying to make the config more simple
