### ISSUE TITLE
Question: How do the scripts get into the html in the current build?

### ISSUE THREAD

**Issue by nelo112** [AngularClass/angular2-webpack-starter#362]
Hi,

when I forked the start pack the index.html had something like this:
```
<% for (var chunk in htmlWebpackPlugin.files.chunks) { %>
<script src="<%= htmlWebpackPlugin.files.chunks[chunk].entry %>"></script>
<% } %>
```

Now in the current build I can't figure out, where exactly the webpack chunks get added into the index.html

**Comment by samvloeberghs** [comment]
I'm not sure but I think Webpack just injects them in the HTML on runtime.

**Comment by mastertinner** [comment]
That's done by the `html-webpack-plugin`. It is configured in the `webpack.config.*` files and automatically injects `CSS` by default in the `<head>` and `HTML` at the end of `<body>`: https://github.com/ampedandwired/html-webpack-plugin#configuration

**Comment by gdi2290** [comment]
I changed the setup to remove this line because it was too confusing so now I'm relying on the inject feature of html webpack plugin.
