### ISSUE TITLE
template vs templateUrl

### ISSUE THREAD

**Issue by kargenc** [AngularClass/angular2-webpack-starter#363]
i am using templateUrl, and stylesUrl in my component with same direcroty with component, but build script cant copy this html and css file to dist 

how can i do copy this html css for components with WD

**Comment by timkindberg** [comment]
Webpack isn't normally used for file moving/copying but you can make it do so by using the CopyWebpackPlugin. They are actually already using it for the /assets folder. Look in the webpack.config.js down around line 72 in the plugins section. Maybe you can copy that line and adjust it for your needs. But I'd say you are going off the seed's prescribed path. Why not just do the templates and styles the way the seed does them? Why add arbitrary http requests when that is completely unneeded?

**Comment by DocBradfordSoftware** [comment]
Does this project not support templateURL in production mode?

**Comment by gdi2290** [comment]
using template: and require() is preferred since in production you would want to do that anyways

**Comment by gdi2290** [comment]
there is no benefit using templateUrl since you can't use relative urls which is something that is supported by `require`
