### ISSUE TITLE
How about to switch to Ava?

### ISSUE THREAD

**Issue by alvipeo** [AngularClass/angular2-webpack-starter#364]
I checked out the [Ava](https://github.com/sindresorhus/ava), thanks to Gleb Bahmutov. And it's way better from an Observable testing stand point. Should we give it a go?

Angular 2 is all about Observables...

**Comment by gdi2290** [comment]
yeah, it's probably a good idea. I rather have a wiki page explaining how to include it. I don't want to go too far out of what the Angular team is advocating (Jasmine, Karma, Protractor) at least not until more people understand Angular 2

**Comment by jgodi** [comment]
I would love to see this, so some examples. I tried to get Angular2 to jive with Ava and ran aground on it myself.

**Comment by alvipeo** [comment]
Can you speak English please? :))) I almost went to buy a good translator to understand this. (No, I like learning)

**Comment by LiTiang** [comment]
Hi, @jgodi 

Can u please share how to integrate _AVA_ with _angular2-webpack-starter_ ?

Because i have a question : 

when we use `npm run server:dev:hmr`

we cant see any transpiled javascript from typescript

then ... how can _AVA_ test that ???? 

It so confused for me ...
