### ISSUE TITLE
Crypto.randomBytes is not a function–an uncaught TypeError

### ISSUE THREAD

**Issue by SimonHawesome** [AngularClass/angular2-webpack-starter#365]
Hi there,

The error I am receiving: 
**Crypto.randomBytes is not a function** 
seems to derive from the 
**./~/es7-reflect-metadata/src/helper/gen-randombytes.ts** file

gen-randonbytes.ts file includes:

```
import * as crypto from "crypto";
import {BufferLike} from "./interfaces";

export function genRandomBytes(size: number): BufferLike {
  return crypto.randomBytes(size); //Here is where the error occurs
}
```

**I am running:**
es7-reflect-metadata: ^1.5.5,
typescript: 1.7.5,
angular2: 2.0.0-beta.7,
npm: 3.8.0,
node: 5.6.0

Thanks in advance for your help!

Simon

**Comment by gdi2290** [comment]
can you update es7-reflect-metadata 1.6.0 and typescript to 1.8.2

**Comment by gdi2290** [comment]
you might have to pull latest changes

**Comment by sumigoma** [comment]
Seeing the same thing with latest changes.

**Comment by SimonHawesome** [comment]
Updating **es7-reflect-metadata** to 1.6.0 and 
**typescript** to 1.8.2 and 
pulling the latest **pollyfills.ts** seemed to have fixed the issue!

Thanks for your help and quick reply!

**Comment by sumigoma** [comment]
Can confirm, latest polyfills and webpack config fixes the issue. Please close.

**Comment by SimonHawesome** [comment]
Hooray!
