### ISSUE TITLE
Hot Module Reloading does not retain state in services

### ISSUE THREAD

**Issue by timkindberg** [AngularClass/angular2-webpack-starter#369]
With Hot Module Reloading I was expecting that only the file/component that I made a change to would be swapped out. However, if you have a service injected into the changed component that is holding some state, that state is refreshed to it's beginning state again.

**Setup:**
ServiceA has a data property that starts as 'foo'
ComponentA injects ServiceA as public
ComponentA.template = `<h1>{{serviceA.data}}</h1><button (click)="serviceA.data = 'bar' ">Click</button>`;
ComponentA button click changes 'data' to 'bar'.

**Steps:**
Launch app
Click button
Make an edit to ComponentA

**Actual:**
h1 shows 'foo'

**Expected:**
h1 to show 'bar'

**Comment by gdi2290** [comment]
I didn't create proxies for any of the components or service because the implementation is a simple one since there are many core changes planned I didn't want to create one only to refactor it many times over. I'm closing this for now to keep the issues down

**Comment by samuel-kollat** [comment]
Could you point me in the right direction how to hold state in components/services with HMR and also how not to reload whole page/state after CSS (Sass) file update ?

**Comment by gdi2290** [comment]
I this working now I just need to push it up later

**Comment by gdi2290** [comment]
if you use `npm start:hmr` you will have HMR with state management using a decorator
