### ISSUE TITLE
Failed at the angular2-webpack-starter@3.0.0 typings-install script 'typings install'.

### ISSUE THREAD

**Issue by herclogon** [AngularClass/angular2-webpack-starter#370]
Revision: 95b7eccf34f8c38b4180dfe1bd6cb2b600bfea7f

<pre>
> npm install -g

> angular2-webpack-starter@3.0.0 postinstall /home/dmitry.golubkov/Projects/angular2-webpack-starter/.env/lib/node_modules/angular2-webpack-starter
> npm run typings-install

> angular2-webpack-starter@3.0.0 typings-install /home/dmitry.golubkov/Projects/angular2-webpack-starter/.env/lib/node_modules/angular2-webpack-starter
> typings install

sh: 1: typings: not found

npm ERR! Linux 3.13.0-35-generic
npm ERR! argv "/home/dmitry.golubkov/Projects/angular2-webpack-starter/.env/bin/node" "/home/dmitry.golubkov/Projects/angular2-webpack-starter/.env/bin/npm" "run" "typings-install"
npm ERR! node v5.7.0
npm ERR! npm  v3.7.5
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! angular2-webpack-starter@3.0.0 typings-install: `typings install`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the angular2-webpack-starter@3.0.0 typings-install script 'typings install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-webpack-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     typings install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-webpack-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-webpack-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/dmitry.golubkov/Projects/angular2-webpack-starter/.env/lib/node_modules/angular2-webpack-starter/npm-debug.log
npm ERR! Linux 3.13.0-35-generic
npm ERR! argv "/home/dmitry.golubkov/Projects/angular2-webpack-starter/.env/bin/node" "/home/dmitry.golubkov/Projects/angular2-webpack-starter/.env/bin/npm" "install" "-g"
npm ERR! node v5.7.0
npm ERR! npm  v3.7.5
npm ERR! code ELIFECYCLE

npm ERR! angular2-webpack-starter@3.0.0 postinstall: `npm run typings-install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular2-webpack-starter@3.0.0 postinstall script 'npm run typings-install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-webpack-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run typings-install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-webpack-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-webpack-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/dmitry.golubkov/Projects/angular2-webpack-starter/npm-debug.log
</pre>

**Comment by gdi2290** [comment]
can you run `npm install -g typings`

**Comment by herclogon** [comment]
Of course, I can do it. But I think it should works from the box.

**Comment by gdi2290** [comment]
This is a problem with npm for windows. During post-install the typings-install task is meant to run and use the local version of typings.

**Comment by chriscurnow** [comment]
@herclogon – what box? Angular2-webpack-starter is a beta package based on a beta of Angular2 provided as a service to the community. Most of us would be wandering around hopelessly without this package. As the world around Angular2 changes, some things will stop working here. We all have to use workarounds until things settle down a bit.

**Comment by ollwenjones** [comment]
Just ran into this in a different project. No matter how I tried to get windows to run the local version of typings (1.x) it kept running the global one (8.x at the time), which installed nothing, of course. Had to bite the bullet and upgrade the other projects.
