### ISSUE TITLE
How to disable websockets

### ISSUE THREAD

**Issue by AndrewLosikhin** [AngularClass/angular2-webpack-starter#383]
I found the we have a request to 
ws://localhost:3000/sockjs-node/655/klzv3wni/websocket
ws://localhost:3000/sockjs-node/445/4d3wrbei/websocket

What component need it and please provide any solution how to disable that.
Thank you.

**Comment by samvloeberghs** [comment]
This is due to the "live reloading" on development mode.
This will not happen in your production.

Or do you have a specific request on why not to do this?

**Comment by AndrewLosikhin** [comment]
Ok, I understand. If it won't be in the prod mode I'm fine with it. Thank you.

**Comment by arvind-das** [comment]
the only problem I see is the continuous failing websocket connections and is very annoying. would like to know how to disable them
