### ISSUE TITLE
Best way to pass variables through Webpack?

### ISSUE THREAD

**Issue by louisscruz** [AngularClass/angular2-webpack-starter#386]
Simple question, but I'm a little lost with the way `webpack.DefinePlugin` interacts with the application. 

For my `http` calls, I'd like to have a variable that is dynamic based on the `process.env.ENV`. What's the best way to define a variable in both my webpack.config.js and webpack.prod.config.js files? And what's the best way to make them global variables in the application?

**Comment by rbao** [comment]
Not sure if this is the best way, but here is how I do it in both `webpack.config.js` and `webpack.prod.config.js`:
```
new webpack.DefinePlugin({
  'process.env': {
    'ENV': JSON.stringify(metadata.ENV),
    'NODE_ENV': JSON.stringify(metadata.ENV),
    'HMR': HMR,
    'API_URL': JSON.stringify(process.env.API_URL)
  }
})
```

Then you can just use it in the code
```
this._http.get(process.env.API_URL, sessionedOptions);
```
For development I use [dotenv](https://github.com/motdotla/dotenv) to set the environment variable.
For production just set environment variable as usual.

**Comment by louisscruz** [comment]
Perfect. Thanks!

**Comment by gdi2290** [comment]
@rbao is correct. @rbao can you make a wiki page to talk briefly about this https://github.com/AngularClass/angular2-webpack-starter/wiki

**Comment by jshamley** [comment]
Don't forget to restart Webpack after adding the environment variables or the system won't recognize them.

**Comment by marek1** [comment]
I did all those things mentioned above, but

when running npm start i get a process object that contains an EMPTY env object

**Comment by m-mital** [comment]
I do it like this: 
```
new webpack.DefinePlugin({
     XMPP_HOST: JSON.stringify(process.env.XMPP_HOST || "http://localhost"),
    XMPP_PORT: JSON.stringify(process.env.XMPP_PORT || 5280)
})
```
and then in JS:
```
export const XMPP_SERVER_URL = `${XMPP_HOST}:${XMPP_PORT}/http-bind`;
```

**Comment by Remco75** [comment]
@marek1 I noticed the same, there is a strange behaviour: When I de `console.log(process)` there is an empty env object .

When I do `console.log(process.env)` it is filled with the proper stuff. I think it has to do with the string 'process.env' we set in the DefinePlugin

**Comment by nmccready** [comment]
> @marek1 I noticed the same, there is a strange behaviour: When I de console.log(process) there is an empty env object .

This strange behavior becomes clear when you look at the packed webpack file. Basically process does not get added to the global scope what so ever. Webpack does a search and replace for anything that is process.env and fills it in with that object specifically everywhere. So essentially it is a new instance of that config object every time. I think this was to not pollute the global space, but for minify purposes seems like a waste.

Is there a option to make it part of the global namespace?


Example:

```js
new webpack.DefinePlugin({
  '__PROCESS__': {
    'ENV': 'production',
  }
})
```

client code (source mapped):
```js
if(__PROCESS__.ENV === 'production'){
//do something
}
```

Real Packed Code:

client code (source mapped):
```js
if(({"ENV":"production"}).ENV === 'production'){
//do something
}
```

It is not what you assumed it was 
```js
window.__PROCESS = {"ENV":"production"};
```

**Comment by nmccready** [comment]
Also this is talked about in some detail here https://github.com/webpack/webpack/issues/868

To get this working a little nicer for consuming your config objects I wrote this:
```js
function packinize(obj){
  _.each(obj, (v, i) => {
    if(_.isString(v))
      obj[i] = JSON.stringify(v)
    else if(_.isObject(v) && !_.isFunction(v))
      packinize(v)
  })
  return obj
}

const configPlugin = new webpack.DefinePlugin({
  __CONFIG__: packinize(frontendConfig)
})
```

**Comment by jianghai** [comment]
So, how could I do if `__LANG__` is not defined by `DefinePlugin` ? Like this
```js
const module = __LANG__ ? require('./' + __LANG__) : require('./zh-cn')
````

**Comment by vdzundza** [comment]
I tried this https://github.com/AngularClass/angular2-webpack-starter/issues/386#issuecomment-256963898 solution in my project. I am using webpack configuration from angular docs. When I am trying to console.log I have this error
```
Uncaught SyntaxError: Unexpected token :
    at Object.503 (app.js:505)
    at __webpack_require__ (polyfills.js:51)
    at eval (eval at 501 (app.js:491), <anonymous>:14:21)
    at Object.501 (app.js:491)
    at __webpack_require__ (polyfills.js:51)
``` 

Looks like definePlugin breaks build.

**Comment by HendrikRoth** [comment]
Why not just this?

```js
new webpack.DefinePlugin({
  'process.env': process.env
})
```

**Comment by megamindbrian** [comment]
Is @jianghai 's method possible?  None of these instructions are clear with the use of TypeScript.

**Comment by al-the-x** [comment]
@hendrikroth please don't ever do this, as you've just exposed the environment of the process that you built with to your bundle... And subsequently the internet. Many sensitive values are Prentiss contained therein, unless `DefinePlugin` is sanitizing them somehow... Although I can't imagine how.

**Comment by gezichenshan** [comment]
@al-the-x  so it means the webpack.DefinePlugin rewrites the process.env as a global variable in a webpack project?
`
new webpack.DefinePlugin({
  'process.env': require('../config/dev.env')
})
`
**../config/dev.env:**
`
module.exports = {
  NODE_ENV: process.env.NODE_ENV,
  BASE_URL : process.env.BASE_URL,
  MULTILOAN: process.env.MULTILOAN
}
`
