### ISSUE TITLE
Production Build: RangeError: Maximum call stack size exceeded Loop?

### ISSUE THREAD

**Issue by nigeman** [AngularClass/angular2-webpack-starter#389]
Apologies in advance for posting an issue that could just be related to me and not the repo, but I am running out of ideas since these last few updates to this setup.

I seem to be running into this loop error when building production and running the "prod" server command. My app works perfectly fine when running npm run server:dev.

One thing to note that I do that maybe related is that I do the DI work around that @brandonroberts devised to expose the @canActivate Decorator with angular2  modules. my bootstrap looks like this:

```
export function main() {
    return browser.bootstrap(Main, [
            ...ENV_PROVIDERS,
            ...HTTP_PROVIDERS,
            ...ROUTER_PROVIDERS,
            AnimationHelper,
            DataService,
            provide(LocationStrategy, { useClass: HashLocationStrategy })
        ]).then((appRef: ComponentRef) => {
            // store a reference to the application injector
            appInjector(appRef.injector);
        })
        .catch(err => console.error(err));
}
```

This is the callstack I get:

```
browser_adapter.ts:73RangeError: Maximum call stack size exceeded
    at e.getDependency (element.ts:363)
    at e._getByDependency (injector.ts:910)
    at e._instantiate (injector.ts:801)
    at e._instantiateProvider (injector.ts:770)
    at e._new (injector.ts:759)
    at e.instantiateProvider (injector.ts:247)
    at e.init (element.ts:638)
    at new e (element.ts:319)
    at viewFactory_e0 (viewFactory_e:472)
    at viewFactory_e0 (viewFactory_e:474)t.logError @ browser_adapter.ts:73e.call @ exception_handler.ts:53(anonymous function) @ application_ref.ts:257e._notifyOnError @ ng_zone.ts:454t.onError @ ng_zone.ts:355e.run @ vendor.8dd3d20….bundle.js:7613(anonymous function) @ ng_zone.ts:371(anonymous function) @ vendor.8dd3d20….bundle.js:7586R @ vendor.8dd3d20….bundle.js:6834I @ vendor.8dd3d20….bundle.js:6846E @ vendor.8dd3d20….bundle.js:6817(anonymous function) @ vendor.8dd3d20….bundle.js:6489n @ ng_zone.ts:410e.run @ vendor.8dd3d20….bundle.js:7609(anonymous function) @ ng_zone.ts:371(anonymous function) @ vendor.8dd3d20….bundle.js:7586y @ vendor.8dd3d20….bundle.js:6628
app.ts:47 RangeError: Maximum call stack size exceeded(…)(anonymous function) @ app.ts:47e.run @ vendor.8dd3d20….bundle.js:7609(anonymous function) @ vendor.8dd3d20….bundle.js:7586e.run @ vendor.8dd3d20….bundle.js:7609(anonymous function) @ vendor.8dd3d20….bundle.js:7586R @ vendor.8dd3d20….bundle.js:6834I @ vendor.8dd3d20….bundle.js:6846E @ vendor.8dd3d20….bundle.js:6817k @ vendor.8dd3d20….bundle.js:6767(anonymous function) @ vendor.8dd3d20….bundle.js:6489n @ ng_zone.ts:410e.run @ vendor.8dd3d20….bundle.js:7609(anonymous function) @ ng_zone.ts:371(anonymous function) @ vendor.8dd3d20….bundle.js:7586y @ vendor.8dd3d20….bundle.js:6628
```

Can anyone give me any ideas in what might be causing this? I feel it might have something to do with the html templates? I require my html files the exact same way as the example app does with:

`template: require('./main.html')`

I really do not like resorting to the issues tab in github for this kind of stuff but I want to see if anyone else is having difficulties or could point me in the correct direction?

Cheers,
Nigel

**Comment by nigeman** [comment]
Just a quick update. In Uglify, mangling is breaking something in my app. I will continue to investigate what it is. Probably another module needs to be added in the array of exception because its probably breaking a reference to a dependency.

**Comment by daddywoodland** [comment]
+1

I'm also getting a call stack exceeded exception when building in production mode.  I've no ideas just yet but will keep looking and post if I find anything.

**Comment by nigeman** [comment]
@daddywoodland goto the webpack.prod config.js and try setting mangle: false. Worked for me for now. But will be related to some referencing issue with another module when mangling.

**Comment by daddywoodland** [comment]
Thanks @nigeman.

I'd actually grabbed the latest code down and the call stack exceeded exception has been replaced by - 

'EXCEPTION: TypeError: this.directive_0_0.ngOnInit is not a function in [null]'

Swapping out the debug & prod UglifyJsPlugin options in webpack.prod.config highlighted that 'mangle' is causing this problem too.  For now I'll just leave mangle as false in production I think.

**Comment by lanocturne** [comment]
+1

**Comment by gdi2290** [comment]
I pushed a workaround so pull latest changes. feel free to open the issue again if you still have it

**Comment by nigeman** [comment]
@gdi2290 checking this out now. Was gonna make a pull request but only  got about half way with the exceptions to list. Seems to be mangling without problems now. Thank you so much for your support- this repo is a lifesaver for angular2.
