### ISSUE TITLE
Bootstrap 4 + Sass setup fails on fresh install

### ISSUE THREAD

**Issue by louisscruz** [AngularClass/angular2-webpack-starter#392]
I just ran through the steps to install bootstrap [in the wiki](https://github.com/AngularClass/angular2-webpack-starter/wiki/How-to-use-Bootstrap-4-and-Sass-(and-jQuery)). It fails with three errors:

It states that `vendor.ts does not exist`

It gives the following message:

```
ERROR in ./~/css-loader!./~/postcss/lib/postcss.js!./~/resolve-url-loader!./~/sass-loader?sourceMap!./~/bootstrap-loader/lib/bootstrap.styles.loader.js!./~/bootstrap-loader/no-op.js
Module build failed: Error: /*! normalize.css v3.0.3 | MIT License | github.com/necolas/normalize.css */
````

Also, it seems to be spitting out the whole bootstrap.css file and stating `is not a PostCSS plugin`.

It looks like the wiki file just needs to be updated for the current setup. I'll get the ball rolling with a fix for the `vendor` entry to a `vendor` entry.

**Comment by 0x1e240** [comment]
The setup is incompatible with the current version of bootstrap-loader (v1.0.9). Since it was updated it doesn't work. A workarround is to use bootstrap-loader v1.0.8. It works in dev-mode. But in prod-mode it gives this message:

`ReferenceError: jQuery is not defined`

I've updated the wiki.

**Comment by louisscruz** [comment]
Wow, thanks for figuring that one out!

There's another issue. There are some breaking changes with the changes made to `index.html` in this (this)[47c2604adaf2c4b4d7c987ca767f5d19fb15ba5d]. I'm going to update the `webpack.config` to what's currently working for me.

**Comment by louisscruz** [comment]
Any idea if there's a workaround for the `jQuery is not defined` error?

**Comment by DocBradfordSoftware** [comment]
Are you sure the jQuery is not defined, is not because you didn't copy the changes from webpack.config.js to webpack.prod.config.js?

**Comment by louisscruz** [comment]
Yikes. I thought I'd already added that but apparently not. That's no longer an issue.

However, now I get an error when trying to add jQuery and Tether to the `webpack.prod.config.js`.
```
new ProvidePlugin({
     jQuery: 'jquery',
     $: 'jquery',
     jquery: 'jquery',
     "Tether": 'tether',
     "window.Tether": "tether"
 })
```
When this line is given, the production server hangs and gives off a `Maximum call stack size exceeded` warning.

When I comment this block out, I get the loading screen saying that bootstrap requires tether.

How should this be set up?

**Comment by 0x1e240** [comment]
@DocBradfordSoftware Thanks. That was the problem. Now it's working for me in dev and prod mode. But I'am using the repository at [an older revision](https://github.com/AngularClass/angular2-webpack-starter/tree/091c567e515983855dd3bec4c7e236c728f3b5f8).

**Comment by GRoguelon** [comment]
Hi,

I add fixed the same issue in adding `ProviderPlugin` of webpack.production.config but when I build for production. I get also: `Maximum call stack size exceeded warning.`

I use the last commit of the repo at this time.

I also found an [issue](https://github.com/angular/angular/issues/5964) which could be related but i'm not sure

How can we try the origin of the bug?

**Comment by DocBradfordSoftware** [comment]
Yes, I am having the same "Maximum call stack size exceeded warning" issue,  I have a header component that works fine in dev mode, but in production mode it gets into an infinite loop. on startup

**Comment by technoSpino** [comment]
Why does 1.0.9 fail? Third party error? What should I follow to know when I can upgrade?

**Comment by louisscruz** [comment]
Has anyone had any success getting an app with the latest structure to work in production?

**Comment by DocBradfordSoftware** [comment]
I originally thought this was a bootstrap problem, but now I think, at least for me, this is a problem of trying to encapsulate a menu with RouterDirectives in a component.  I cannot for the life of me figure out how to put a navbar with ROUTERDIRECTIVES, in a component that I include on every page.  It will run in dev mode, but not in prod. I get an infinite loop.

**Comment by DocBradfordSoftware** [comment]
I fixed my issue with Bootstrap, by
1. You cannot have a navbar in a sub-component because mangling will interfere.
2. Since bootstrap uses jQuery but not for many things, I am using the bootstrap4.css but not importing jQuery.
I have a repository at https://github.com/jkevlin/angular2-bootstrap4-no-jquery as an example.

**Comment by louisscruz** [comment]
I'm going to give this a shot later today. Thanks for posting this!

In the meantime, is there any kind of configuration that could allow for navbar sub-components? Never would have guessed this to be the issue.

**Comment by GRoguelon** [comment]
Personally, the latest commits fixed my issue.

**Comment by louisscruz** [comment]
Confirmed! The latest fixes the issue for me too.

**Comment by d3viant0ne** [comment]
Resolving as a resolution exists in this issue
