### ISSUE TITLE
Fails on IE11 under Windows 10

### ISSUE THREAD

**Issue by saldoukhov** [AngularClass/angular2-webpack-starter#393]
Not just in PROD mode like described here https://github.com/AngularClass/angular2-webpack-starter/issues/354 but also in dev mode.

**Comment by gdi2290** [comment]
did you uncomment `ie-shim`?

**Comment by saldoukhov** [comment]
Oops, sorry my fault. I was thinking package dependency is enough ;)

**Comment by chenfengami** [comment]
Thanks!
