### ISSUE TITLE
Is the development experience supposed to be that slow?

### ISSUE THREAD

**Issue by onlyann** [AngularClass/angular2-webpack-starter#396]
Let me first say thanks for providing a starter kit for angular 2 and webpack.
The good part is that running `npm install` and `npm run server` succesfully runs the sample application.

The less so good is that it takes more than 10 seconds to reflect a change on a file (I changed `home.html`). Not sure if that is supposed to be that slow. It tried without the hot module reload for similar results.

Beside changing the one file and updating TypeScript package version to 1.8.7, I left the rest unchanged

My environment is Windows and the CPU is an Intel Core i5-4300U 1.9Ghz.

Here's an extract of the webpack-dev-server output :
```
webpack: bundle is now VALID.
webpack: bundle is now INVALID.
810ms build modules
76ms seal
196ms optimize
24ms hashing
40ms create chunk assets
19ms additional chunk assets
8724ms optimize chunk assets
236ms optimize assets
98ms emit
Hash: a23b9391ca22cca137f2
Version: webpack 1.12.14
```

**Comment by hollanderbart** [comment]
could be related to: https://github.com/AngularClass/angular2-webpack-starter/issues/372

**Comment by fxck** [comment]
clean install of angular2-webpack-starter takes about 5 secs to build for me, but it's getting increasingly slow with more stuff you add, now with a couple of components, services and routes I'm at about 40 seconds or crash, as described in #372

**Comment by gdi2290** [comment]
Thanks for the issue. Can update to latest and reopen if you still have this issue. The problem was ts-loader so I switched to awesome-typescript-loader so I'm closing this now

**Comment by sumigoma** [comment]
@gdi2290 Are you going to restore the changes involving the default webpack config file?

**Comment by gdi2290** [comment]
@sumigoma ya I might

**Comment by onlyann** [comment]
Modifying `home.html` or `home.ts` still takes more than 10 seconds to reflect the changes.
```
559ms build modules
28ms seal
 73% optimize[default] Checking started in a separate process...
[default] Ok, 0.029 sec.
281ms optimize
31ms hashing
132ms create chunk assets
54ms additional chunk assets
9822ms optimize chunk assets
250ms optimize assets
85ms emit
Hash: 5621345838a01a1b0215
Version: webpack 1.12.14
```

**Comment by gudh** [comment]
same thing here, takes 10+ seconds every time a file is changed, either css, html or ts

**Comment by avgalon** [comment]
+1 on that
I have the latest....
when running $ npm run server:dev:hmr i wait almost a minute.....and only 40% of the project is ready.
please advise
