### ISSUE TITLE
Prod build crashes after today's changes

### ISSUE THREAD

**Issue by saldoukhov** [AngularClass/angular2-webpack-starter#397]
It compiles just fine, but throws a lot of exceptions when trying to run it.

https://github.com/AngularClass/angular2-webpack-starter/commit/fe37a03b6e86fa7ceeb9c76e0cc59db3eb2b8d83 broke it

**Comment by jmiazga** [comment]
+1
![image](https://cloud.githubusercontent.com/assets/181441/13603773/8e5439fa-e50d-11e5-8a64-18b24c365300.png)

**Comment by jmiazga** [comment]
e00aac92d112a56fc57e08717f9451107265c8f6 fixed the issue for me

**Comment by gdi2290** [comment]
can you pull latest and see if it's still broken

**Comment by louisscruz** [comment]
The latest works for me. Cloned, installed, built and served.

**Comment by gdi2290** [comment]
thanks, closing now. update to latest and reopen if there is an issue
