### ISSUE TITLE
IE11 is still broken in Prod with uglify plugin

### ISSUE THREAD

**Issue by saldoukhov** [AngularClass/angular2-webpack-starter#398]
I tried to set mangle etc. to false which did not hep - but commenting out UglifyJsPlugin altogether fixed the problem.

**Comment by gdi2290** [comment]
can you uncomment `ie-shim` and pull latest

**Comment by saldoukhov** [comment]
Nope, still happening. Same as before, commenting out Uglify fixes it.

**Comment by gfaceless** [comment]
+1, even switching its `beautify` to `true` fixes this.

**Comment by AndrewLosikhin** [comment]
+1 updating to the last version doesn't help

**Comment by coldshower** [comment]
Hey all,
Was the solution for this issue ever found?
