### ISSUE TITLE
No original files in Debugging Tools after hot-reload

### ISSUE THREAD

**Issue by RemKolomna** [AngularClass/angular2-webpack-starter#401]
Hello! I pull latest updates from this repository and found annoying issue:

After starting dev server I can open Chrome Debugging Tools and find all TypeScript files in "Sources" tab inside webpack://./src/

However after first hot module reload event this folder becomes empty and contains last changed file with hash prefix only, all other files become missing.

**Comment by RemKolomna** [comment]
Do anyone else experience this issue? I updated webpack to latest version and search internet with same problems with no luck.

Steps to reproduce:
1)npm run start
2)Open Chrome Developer Tools and browse to folder webpack://./src/ - it containt list of all project files with subfolders
3)change home.html to trigger hot module reload
4)Go to Chrome Developer Tools and press F5 to update them. webpack://./src/ - this folder contains home.html file only and nothing else.

**Comment by RemKolomna** [comment]
Changing devTool inside webpack config from **'source-map'** to **'cheap-module-eval-source-map'** fixes the problem.  Maybe maintainer can change it too to improve debug experience?

**Comment by gdi2290** [comment]
thanks, merged via https://github.com/AngularClass/angular2-webpack-starter/commit/5e24f11d141305f6b142967702ad4c2c21f1576b
