### ISSUE TITLE
Kendo? Grid?

### ISSUE THREAD

**Issue by chriscurnow** [AngularClass/angular2-webpack-starter#406]
Has anyone had any experience trying to integrate Kendo-UI?

I pretty well could do without the whole of Kendo except for the Kendo Grid to which there seems nothing in the same class.

**Comment by Siafu** [comment]
The guys at Telerik are working on this. [site](http://www.telerik.com/blogs/announcing-the-telerik-kendo-ui-r2-2016-roadmap).

**Comment by chriscurnow** [comment]
Thanks, yes I'm following the kendo site.

**Comment by chriscurnow** [comment]
I am going to have a go at doing this. If I work it out I will post a Wiki article about it. Regardless, we can close this issue now.
