### ISSUE TITLE
Websockets and proxy

### ISSUE THREAD

**Issue by mburger81** [AngularClass/angular2-webpack-starter#410]
Hello,

I use for the devServer an proxy and it works great, anything which comes from /api/* will be redirect to my server.
```
proxy: {
        '/api/*': {
            target: 'http://192.168.1.1/abc/',
            secure: false,
        }
    }
```
so this
`this.http.post('/api/v1/sensors'`

will redirected to
`http://192.168.1.1/abc/api/v1/sensors''`

but how can I do the same thing for Websockets?
`this.ws = new WebSocket('ws://api/v1/sensorsws');`

thx
 Michael

**Comment by gdi2290** [comment]
@siready is correct. you can open another issue if you have any more problems with the repo thanks
