### ISSUE TITLE
PrimeNG integration

### ISSUE THREAD

**Issue by bPopovska** [AngularClass/angular2-webpack-starter#411]
Does anyone have experience with integrating the primeNG library in a webpack based project?
Trying to integrate it in this starter results in the following error:

`Error: No Directive annotation found on Button
    at new BaseException (http://localhost:3000/main.bundle.js:1318:24)
    at DirectiveResolver.resolve (http://localhost:3000/main.bundle.js:11928:16)
    at RuntimeMetadataResolver.getDirectiveMetadata (http://localhost:3000/main.bundle.js:32492:52)
    at http://localhost:3000/main.bundle.js:32549:63
    at Array.map (native)`

**Comment by gdi2290** [comment]
there are two versions of Angular 2 installed. they need to update their angular2 dep or set as a peerDep

**Comment by gdi2290** [comment]
see https://github.com/primefaces/primeng/pull/86

**Comment by cagataycivici** [comment]
Merged now, thank you.

https://github.com/primefaces/primeng/issues/88

**Comment by gdi2290** [comment]
@cagataycivici thanks

**Comment by Sicaine** [comment]
@bPopovska did you get it running? We have basics running but datepicker makes trouble :(

**Comment by bPopovska** [comment]
@Sicaine Still running into issues. Can't get primeng to work when source maps are enabled.

**Comment by Luchillo** [comment]
@bPopovska Are the widget styles issues you talk about related to the images urls of the style? i'm using sass-loader and as it just process the import statement as if that theme content were copied to the importing file, it breaks the images urls since now that content is in a different folder.

**Comment by cagataycivici** [comment]
I've done a fork to add PrimeNG for the UI;

https://github.com/cagataycivici/angular2-webpack-starter

**Comment by Luchillo** [comment]
@cagataycivici Does dialogs work in yours? the errors above i fixed using the url loader but now i have issues when using the Dialog and seems related to jquery.

**Comment by cagataycivici** [comment]
Yes, it works for me in my fork above.

**Comment by zigzag95** [comment]
I don't use assets for Css I just do a require on node modules in app.ts

Envoyé de mon iPhone

**Comment by Luchillo** [comment]
@cagataycivici Maybe my error is related to the way jquery is loaded due to me using the NgUpgrade package to try and update an Ng1 app? i'll take a deeper look at your starter and see what's the issue. 😄

**Comment by Luchillo** [comment]
@cagataycivici I made a fork of yours and made some changes in helpers, however when i go to pull request it shows me the original AngularClass repo, why yours not showing in the pull request options?
