### ISSUE TITLE
[(ngModel)] directive is not working in production mode.

### ISSUE THREAD

**Issue by meiblorn** [AngularClass/angular2-webpack-starter#415]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Report a bug

* **What is the current behavior?**
App is not working. Exception in logs: [ng2-webpack.txt](https://github.com/AngularClass/angular2-webpack-starter/files/170644/ng2-webpack.txt)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**:
 1.  Open https://github.com/AngularClass/angular2-webpack-starter/blob/master/src/app/home/home.html file
 2. Comment 3rd line
 3. Uncomment 7th line
 4. Build project in production mode (npm run build:prod)
 5. Open app. It's not working. Watch exception in logs

* **What is the expected behavior?**
App is working!

* **What is the motivation / use case for changing the behavior?**
It's usual ng2 directive.

* **Please tell us about your environment:**
Latest code from master, Chrome, MacOS.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
See attachments.

**Comment by gdi2290** [comment]
see changes https://github.com/AngularClass/angular2-webpack-starter/commit/7780e22f90dc643f72c1e094b2c228c2176eacc6#diff-1a19ad1ad8c7b53ba23a02dcba546ee8
it might be better to turn mangle off
