### ISSUE TITLE
How to debug unit and e2e tests?

### ISSUE THREAD

**Issue by a76** [AngularClass/angular2-webpack-starter#416]
I need to debug karma end e2e tests. 
How it is possible?

**Comment by RemKolomna** [comment]
I simply add task to package.json:
"watch:testd": "karma start --auto-watch --no-single-run --browsers=Chrome"
and commented Istanbul loader from webpack.test.config.js
Run watch:testd task and it opens a new chrome window with karma, here press debug button and another page will open. Open Developer Tools on that page, put breakpoint where you need it and press F5

**Comment by a76** [comment]
Awesome :) - Thank you for advise. 
It may be reasonable to include this task to the source code.
What do you think?
Do you know how debug e2e tests?

**Comment by Devgaze** [comment]
How can we debug e2e tests? It seems that browser.debugger() is not working and when I use browser.pause() I can use only `c` command to continue, no support for listing current lines of code? I know that certain things are not supported anymore with Angular2 apps (like model binding), but was unable to find is the same case for debugger?
