### ISSUE TITLE
Uncaught (in promise) TypeError: object is not a constructor(…)

### ISSUE THREAD

**Issue by mastertinner** [AngularClass/angular2-webpack-starter#417]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
When running the app in my browser, I get `Uncaught (in promise) TypeError: object is not a constructor(…)` but the app runs fine.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).
Just run the app with `npm start`.

* **What is the expected behavior?**
No error messages ;-)

* **What is the motivation / use case for changing the behavior?**
Running the app without changing anything shouldn't result in any errors or warnings in the browser.

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.9
- Browser: Chrome 49

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by burzum** [comment]
Getting the same problem.

**Comment by samvloeberghs** [comment]
My 2 cents:
this seems to be a browser issue in some way. I had the same on Chrome 49, but in my Canary 51 the error is not popping up.

**Comment by gdi2290** [comment]
yup I see it's a problem in chrome 49 probably due an outdated es6-promise

**Comment by gdi2290** [comment]
see issue https://github.com/angular/angular/issues/7601 and fix https://github.com/AngularClass/angular2-webpack-starter/commit/5bf36a62ceb0356d96cd954732985f4038d6d36e
