### ISSUE TITLE
router-active.ts is not necessary anymore 

### ISSUE THREAD

**Issue by MurhafSousli** [AngularClass/angular2-webpack-starter#420]
Angular2 beta 9 has a new feature that adds "router-link-active" class to the activated menu item without configuration.

> Feature: angular1_router: Add ng-link-active class to active ng-link (11e8aa2), closes #6882

you may want to deprecate the file.

**Comment by gdi2290** [comment]
that's for angular1

**Comment by MurhafSousli** [comment]
@gdi2290  no it's for angular2, and I've tried it
https://github.com/angular/angular/blob/master/CHANGELOG.md

**Comment by sasidhar** [comment]
@MurhafSousli You are correct. 

> router: router-link-active CSS class support (36eb9d3), closes #3209

We have "router-link-active" available in Angular 2 from 2.0.0-alpha.37 (2015-09-09)

I tried on my local machine and its working fine without router-active directive.

**Comment by gdi2290** [comment]
router link is fine. when you want the active class on the parent that's a problem
```html
<li class="active">
  <a href="#"></a>
</li>
```

**Comment by sasidhar** [comment]
@gdi2290 Ok.

Then we need `router-active.ts`

**Comment by goodmind** [comment]
@gdi2290 why it is removed? how can I set class on parent now?
