### ISSUE TITLE
error TS2339: Property 'context' does not exist on type 'NodeRequire'.

### ISSUE THREAD

**Issue by GarrettVD** [AngularClass/angular2-webpack-starter#434]
* **I'm submitting a ...**
[* ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
When attempting to use [require.context](https://webpack.github.io/docs/context.html), after executing `npm start`, an exception is thrown. 

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
In ```src/app/app.ts```, enter the following: ```var testContext = require.context('./home', true, /\.ts/);```.  When attempting a build, you will receive the error: ```error TS2339: Property 'context' does not exist on type 'NodeRequire'```.

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.8
- Browser: [all]

**Comment by gdi2290** [comment]
should be fixed via https://github.com/AngularClass/angular2-webpack-starter/commit/c811a45d099bdca04e3337ec230c89c2a73559d1 can you pull latest and make sure you run `typings install`

**Comment by gvandyk-r7** [comment]
Thanks

**Comment by gdi2290** [comment]
I'm going to close this but if you still have the error please reopen or create another issue, thanks!

**Comment by GarrettVD** [comment]
Thanks, just testing it now
