### ISSUE TITLE
Karma fails with Cannot find module "zone.js/dist/zone-microtask.js"

### ISSUE THREAD

**Issue by Spittal** [AngularClass/angular2-webpack-starter#437]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[ X ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
When running `npm run test` I get this log.

```
18 03 2016 11:40:58.050:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
18 03 2016 11:40:58.061:INFO [launcher]: Starting browser PhantomJS
18 03 2016 11:40:59.172:INFO [PhantomJS 2.1.1 (Mac OS X 0.0.0)]: Connected on socket /#6zQZ90HQqMMr24RgAAAA with id 95487023
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  Error: Cannot find module "zone.js/dist/zone-microtask.js"
  at /Users/jamie/web/angular2-webpack-starter/spec-bundle.js:118

Finished in 0.149 secs / 0 secs

SUMMARY:
✔ 0 tests completed

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/Cellar/node/5.4.0/bin/node" "/usr/local/bin/npm" "run" "test"
npm ERR! node v5.4.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! angular2-webpack-starter@3.0.0 test: `karma start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-webpack-starter@3.0.0 test script 'karma start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-webpack-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     karma start
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular2-webpack-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jamie/web/angular2-webpack-starter/npm-debug.log
```

I believe this may be related to https://github.com/AngularClass/angular2-webpack-starter/issues/436

* **What is the expected behavior?**
For tests to run.

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.10
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by gdi2290** [comment]
thanks! I updated the repo
