### ISSUE TITLE
include angular2 material components

### ISSUE THREAD

**Issue by gdi2290** [AngularClass/angular2-webpack-starter#443]
Angular 2 Material 2 (currently problems with the modules)

**Comment by asafyish** [comment]
How is that going to affect applications who are not using angular material ?

**Comment by gdi2290** [comment]
material 2 seems to have a few problems in the alpha 1 release

**Comment by asafyish** [comment]
Is it going to bundled into the production js ?

**Comment by gdi2290** [comment]
you can remove them from the starter if you wanted. At the moment the material components have styles/templates inline

**Comment by gdi2290** [comment]
I pushed up the changes but the comments are commented out for now until it's fixed upstream

**Comment by msegers** [comment]
They seemed to work fine for me on friday, what kind of issues does it have?

**Comment by msegers** [comment]
They've released alpha2. so might be able to continue

**Comment by gdi2290** [comment]
I updated the repo to use angular2-material2-alpha.2
