### ISSUE TITLE
Worth looking at I guess (not an issue)

### ISSUE THREAD

**Issue by alvipeo** [AngularClass/angular2-webpack-starter#444]
https://medium.com/@vivainio/with-latest-typescript-you-may-not-need-webpack-417d2ef0e773#.o6j5sz10o

**Comment by gdi2290** [comment]
there are many features in webpack that we are using. The most important pending feature is in webpack 2 (tree shaking) and will be merged with this repo once Webpack 2 is more stable
https://github.com/gdi2290/angular2-webpack2-starter/
