### ISSUE TITLE
Load appInjector after promise on bootstraping

### ISSUE THREAD

**Issue by mburger81** [AngularClass/angular2-webpack-starter#446]
on main.ts I try to load my appInjector in .then, this is working fine on DEVELOPMENT but on PRODUCTION this doesn't work anymore, but I'm sure before migrating on 3.0.0 this works fine

How can I load my global appInjector, I need this on handle on @CanActivate if user is logged in using the http and router service

```
export function main() {
  return browser.bootstrap(App, [
    ...APPLICATION_PROVIDERS,
    ngCore.provide(ngCore.PLATFORM_DIRECTIVES, {useValue: APPLICATION_DIRECTIVES, multi: true}),
    ngCore.provide(ngCore.PLATFORM_PIPES, {useValue: APPLICATION_PIPES, multi: true})
  ])
  .then((appRef: ngCore.ComponentRef) => {
        // store a reference to the application injector
        appInjector(appRef.injector);
  })
  .catch(err => console.error(err));
}
```

**Comment by zarkosusnjar** [comment]
+1

**Comment by mburger81** [comment]
sorry I opened the problem twice time, same issue as discussed here #451
