### ISSUE TITLE
Changing to core-js for polyfills cause annotation inheritance to break in angular2

### ISSUE THREAD

**Issue by user414** [AngularClass/angular2-webpack-starter#450]
I'm sure it's a side effect of something else, but restoring es6-shim instead of core-js polyfills fix it for me. Here is the angular2 issue with plunker

https://github.com/angular/angular/issues/5415

**Comment by user414** [comment]
Another observation is that the mangling that was turned on with the except also break the annotation inheritance so add to remove that from the prod configuration as well

**Comment by abadakhshan** [comment]
hi
How your "@ViewChild in base class in Webpack (angular cli)"  problem  solved?
I have similar problem
tanx

**Comment by user414** [comment]
@abadakhshan look at this thread

https://github.com/angular/angular/issues/5415

particularly comments

https://github.com/angular/angular/issues/5415#issuecomment-212588714
https://github.com/angular/angular/issues/5415#issuecomment-253509453

We kept using es6-shim instead of core-js. However, saw recently that this was finally implemented in the latest trunk/beta

https://github.com/angular/angular/issues/11606

via this commit

https://github.com/angular/angular/commit/f5c8e0989d85bc064f689fc3595207dfb29413f4

and have not tried it since. There's a high likelihood that the workaround and/or using es6-shim instead of core-js is no longer needed but have not tried it yet.
