### ISSUE TITLE
bootstrap(App, [....]).then((appRef: ComponentRef) is not called for production

### ISSUE THREAD

**Issue by mburger81** [AngularClass/angular2-webpack-starter#451]
In my main.ts i do this

```
export function main() {
  return browser.bootstrap(App, [
    ...APPLICATION_PROVIDERS,
    ngCore.provide(ngCore.PLATFORM_DIRECTIVES, {useValue: APPLICATION_DIRECTIVES, multi: true}),
    ngCore.provide(ngCore.PLATFORM_PIPES, {useValue: APPLICATION_PIPES, multi: true})
  ])
  .then((appRef: ngCore.ComponentRef) => {
      console.log('ABCDEF');
        // store a reference to the application injector
        appInjector(appRef.injector);
  })
  .catch(err => console.error(err));
}
```

but on running npm run build:prod the ".then" is not called and so my appInject is not called

**Comment by gdi2290** [comment]
I was able to get it working. can you try with the latest changes?

**Comment by mburger81** [comment]
@gdi2290 Yesterday evening I downloaded the last version, and on last version it seams to work but I'm not realy sure. On having a empty project it works but including my app I have the same issue as discussed in #456 , and so I'm not able to test if it works realy.
