### ISSUE TITLE
ideas behind the new folder structure ?

### ISSUE THREAD

**Issue by fxck** [AngularClass/angular2-webpack-starter#454]
what goes where? 

for example which providers go here https://github.com/AngularClass/angular2-webpack-starter/blob/master/src/platform/browser/providers.ts only those coming from angular?

and which here https://github.com/AngularClass/angular2-webpack-starter/blob/master/src/main.browser.ts#L25 only those from my own app?

**Comment by gdi2290** [comment]
the platform folder will be the new vendor workflow

**Comment by fxck** [comment]
ok, so my own services go to bootstrap still

**Comment by gdi2290** [comment]
You can put them all in bootstrap within APP_PROVIDERS the platform is there for Universal modules support for when you have different environments or platforms. Basically I wanted a workflow that works for both advanced and simple case. If you don't want to look or use platform you don't have to

**Comment by fxck** [comment]
and if I have vendor provider that requires my own files(ngrx/store `provideStore`), what place would be better for it?

**Comment by fxck** [comment]
also you are actually adding app's directives(RouterActive) thru the platform folder, so I'm a little confused... is it something temporary?

**Comment by gdi2290** [comment]
you would add provideStore in main.browser just as I'm doing with HMR

**Comment by gdi2290** [comment]
RouterActive was meant to live in a common folder but I didn't want to confuse more devs with platform/common/environment I can move it back to app

**Comment by fxck** [comment]
Ok, so vendors go to platforms, vendors that require anything from my actual code go to main.browser and my global directives / components / services go there as well.. How about changing "APPLICATION_PROVIDERS" to something like VENDOR_PROVIDERS.. to distinguish it from APP_PROVIDERS?

**Comment by gdi2290** [comment]
well they're available application wide so that's why it's named application_providers. app_providers is there for when you need a quick way to include application providers or if you need to dynamically create the provider with initial state. but you're right it's a little bit confusing. There needs to be more comments

**Comment by d3viant0ne** [comment]
Ancient and no longer an issue ( it's commented )
