### ISSUE TITLE
PhantomJS error on spec-bundle.js

### ISSUE THREAD

**Issue by lanocturne** [AngularClass/angular2-webpack-starter#462]
* **I'm submitting a ...**
[ x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

After updating to latest commit(config files refactor), I am getting this error when run test.
```bash
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  ReferenceError: Can't find variable: process
  at /ui/config/spec-bundle.js:46189
```

Notice that start dev server works fine. I wander is this related to port occupied issue?

**Comment by lanocturne** [comment]
Add back 
```ts
'process.env': {
        'ENV': JSON.stringify(ENV),
        'NODE_ENV': JSON.stringify(ENV)
      },
```
to DefinePlugin, and it's working again. Any idea where I am missing?

**Comment by akaztp** [comment]
I see that commit 5ee01f697ddc05283c81a7398038cb73b5d06e22 is for fixing this issue but I've just cloned the repository with commit f78aeb4fe4f6bd4bd25b1e09ff5792fc2e23215a (the latest at this time) and I got exactly the error reported in this issue. Any thoughts?

**Comment by samvloeberghs** [comment]
change:

```
node: {
    global: 'window',
    process: false,
    crypto: 'empty',
    module: false,
    clearImmediate: false,
    setImmediate: false
  }
```

to 

```
node: {
    global: 'window',
    process: true,     // FALSE -> TRUE
    crypto: 'empty',
    module: false,
    clearImmediate: false,
    setImmediate: false
  }
```
