### ISSUE TITLE
How to integrate new 3rd party libraries into a project

### ISSUE THREAD

**Issue by mbcooper** [AngularClass/angular2-webpack-starter#467]
i seem to spend hours fiddling with the starter template to add new external libraries that are supposed to be Angular 2 friendly.  But it appears that many are not.

I wrestled with an older version of ng2-translate, which failed because it's entry point had exports from adjacent translate directories -- and webpack did not resolve them properly.

Now, I wrestling once again with ng2-idle, which follows a similar pattern .. and I get a truckload of errors just trying to add import 'ng2-idle' to vendor.ts.

Am I missing some magic formula for doing something as basic as adding a new dependency library?

**Comment by valorkin** [comment]
@mbcooper try this one https://github.com/valor-software/ng2-bootstrap/blob/master/README.md

**Comment by HackedByChinese** [comment]
I'm not much of a webpack user, so I apologize for the probable user error. Trying to help @mbcooper (I'm the owner of ng2-idle). I don't know what I'm missing here, I can't even properly bootstrap the application in the way I've done for non-webpack Angular2 apps.

https://github.com/HackedByChinese/ng2-idle/issues/3

**Comment by kahboom** [comment]
I agree, I think documentation can really be improved here as the shift to Angular 2 is bringing in a bunch of technologies that developers may not have worked with previously, such as TypeScript, webpack, and obviously Angular 2. Not that we should document for each of those, but just better general documentation about how to add external libraries and how that is handled, etc. specific to this project I think would be helpful.
