### ISSUE TITLE
Common config forces development mode to every build 

### ISSUE THREAD

**Issue by saldoukhov** [AngularClass/angular2-webpack-starter#477]
In webpack.common.js:
const ENV = process.env.ENV = process.env.NODE_ENV = 'development';

**Comment by tobek** [comment]
Just added a PR that fixes this #478

**Comment by gdi2290** [comment]
should be fixed via https://github.com/AngularClass/angular2-webpack-starter/pull/478 if you still have the problem please reopen the issue
