### ISSUE TITLE
Got clean repo now = Broken

### ISSUE THREAD

**Issue by alvipeo** [AngularClass/angular2-webpack-starter#479]
If you clone a repo now and do 'npm run build' you'll get the following:

>>> angular2-webpack-starter@4.0.0 build:dev d:\Documents\Visual Studio 2015\Projects\angular2-webpack-starter
> node --max-old-space-size=4096 node_modules/.bin/webpack --config config/webpack.dev.js --progress --profile --colors --display-error-details --display-cached

d:\Documents\Visual Studio 2015\Projects\angular2-webpack-starter\node_modules\.bin\webpack:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:142:18)
    at node.js:939:3

Guys, let's make sure when you commit something you don't break the essentials.

**Comment by gdi2290** [comment]
@alvipeo can you apply these changes or pull latest
https://github.com/AngularClass/angular2-webpack-starter/commit/216fa0db6c7e4092cfdf22b25aafb9b0bdfaba95

**Comment by alvipeo** [comment]
Thank you!
