### ISSUE TITLE
core-js increase the build size massively

### ISSUE THREAD

**Issue by jmsegrev** [AngularClass/angular2-webpack-starter#484]
Importing **core-js** increases the module count and size of the webpack build massively, compared to the previous polyfills libs used (es6-shim, es7-reflect-metadata). I think it would be good to only import the angular2 specific dependencies from core-js instead of the entire library. If the user would like to use another particular polyfill, he could import it the same way its done with RxJs operators.

**Comment by samvloeberghs** [comment]
agree, I'm noticing this to..
Can you list which specific parts are needed?

**Comment by jmsegrev** [comment]
Sorry for the late reply, but importing es6 and es7 reflect, will satisfy the dependencies for angular2 and the starter. Its reduces the module count by 100+, compared to the default import (based on webpack --json, on the starter).

``` 
import 'core-js/es6';
import 'core-js/es7/reflect';
```

**Comment by gdi2290** [comment]
@jmsegrev can you make a PR?

**Comment by samvloeberghs** [comment]
I did a first test, and doing this change resultet in the following:

```
main		        3.774 kb	->	506 kb
polyfills	        834 kb	->	92 kb
vendor		3.696 kb	->	642 kb
```

**Comment by jmsegrev** [comment]
The size of the polyfill bundle doesn't seam to change much, but the reductions of the modules count, does affect the build time. With the starter repo, as is, the reduction in build time cant be perceived, but with any app that has more dependencies it will show, I can vouch for this.   

**Prod build of master starter repo (webpack --config config/webpack.prod.js --profile)**

|                                       Asset | Size(full) | Size(partial)|
|---------------------------------------------|------------|--------------|
|    polyfills.6a6c2a288d71315f6fe6.bundle.js |   103 kB   |   93.8 kB|
|       vendor.6ab9071851998368fef2.bundle.js |   657 kB   |    656 kB|
|         main.8464060d2c637ae39e01.bundle.js |   156 kB   |    156 kB|
|   polyfills.6a6c2a288d71315f6fe6.bundle.map |   796 kB   |    723 kB|
|           1.7837cb5d3cae6aaed587.bundle.map |  6.64 kB   |   6.64 kB|
|      vendor.6ab9071851998368fef2.bundle.map |  3.81 MB   |   3.81 MB|
|        main.8464060d2c637ae39e01.bundle.map |   503 kB   |    503 kB|
|        1.7837cb5d3cae6aaed587.bundle.map.gz |  2.16 kB   |   2.16 kB|
|      main.8464060d2c637ae39e01.bundle.js.gz |  22.4 kB   |   22.4 kB|
| polyfills.6a6c2a288d71315f6fe6.bundle.js.gz |    33 kB   |   30.4 kB|
|     main.8464060d2c637ae39e01.bundle.map.gz |  83.8 kB   |    139 kB|
|    vendor.6ab9071851998368fef2.bundle.js.gz |   139 kB   |   83.8 kB|
|polyfills.6a6c2a288d71315f6fe6.bundle.map.gz |   182 kB   |    167 kB|
|   vendor.6ab9071851998368fef2.bundle.map.gz |   769 kB   |    769 kB|


**Dev build**

|                Asset | Size(full) | Size(partial) |
|----------------------|------------|-------------|
|  polyfills.bundle.js |   851 kB   |  770 kB|
|     vendor.bundle.js |  3.79 MB   | 3.79 MB|
|       main.bundle.js |   542 kB   |  542 kB|

**Comment by gdi2290** [comment]
@jmsegrev thanks for looking into it
