### ISSUE TITLE
feature request : add socket.io lib

### ISSUE THREAD

**Issue by lastnod** [AngularClass/angular2-webpack-starter#486]

**Comment by alvipeo** [comment]
hm.. what if someone doesn't need it in his project? the repo is a little bit fat already

**Comment by gdi2290** [comment]
the repo is fat because of testing and e2e

**Comment by alvipeo** [comment]
what I'm saying is let's not add features that not everyone needs.

**Comment by mastertinner** [comment]
@lastnod, you can see how to add it in my tutorial here: https://github.com/AngularClass/angular2-webpack-starter/wiki/How-to-use-with-FeathersJS
