### ISSUE TITLE
livereload of css and HMR not working

### ISSUE THREAD

**Issue by rvetere** [AngularClass/angular2-webpack-starter#488]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
It feels like a bug to me but i don't want to stress anybody - the HMR thing is still in developement i guess and maybe it is just work-in-progress..?

* **What is the current behavior?**
Three weeks ago i've initialized a new project with this skeleton project - and the css livereload was working fine. By livereload i mean, he can inject the new css directly into the browser without reloading the page. Now i've upgraded my project with all the new changes and the livereload is broken now, he always reloads the page - on css changes and in typescript (in typescript it was kind of working with the HMR back those days.. it wasn't made with this new angular2-hmr package).

* **Steps to reproduce**
* 1. checkout the repo as a new project and `npm i`, `npm start`
  2. goto `localhost:3000`
  3. open up home.css for example and add some css like `body { color: red; }`
  4. watch webpack rebuilding the package and as soon as he is ready -> the page reloads

* **What is the expected behavior?**
page should not reload at least with css - what the state is with HMR i don't really know.

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.13
- latest variant for now with HMR 0.5.1

**Comment by gdi2290** [comment]
in the readme you have to run `npm start:hmr` hmr is off by default

**Comment by gdi2290** [comment]
the css for components are also scoped so if you include `body { color: red; }` it's not going to work since there is not body tag within the home component. You would need to turn off css encapsulation for the component or use a different style value like `form { color: red; }`

**Comment by gdi2290** [comment]
I"m going to close this issue to keep them issue count down but if you still have this problem please reopen it. thanks!

**Comment by rvetere** [comment]
Thanks for your replies! Everything clear so far.. but, how would i turn off css encapsulation for a component?

My problem is, i try to use Sass together with Bootstrap. I know it would be perfect in ES6 modules to import the css for every component directly in the components code. But then i don't know all the variables/classes inside my component script - then i have to import everything needed over and over again in every component (which is not wrong as i read about ES6 modules). But this results in having bootstrap included several times in the final package - and then i have to de-dup everything? This feels totally wrong to me.

So i got another approach - i'm importing my scss only at one single point in the whole app - in my bootstrapping "main.browser.ts" -> and my basic scss is importing bootstrap, and all subsequent scss files of all components. This way i end up having all classes/variables everywhere available and i import boostrap only once and don't have to de-dup in the end. Now the only thing "disturbing" here is the css encapsulation i guess.

Isn't the encapsulation controlled by the imports...? Or is there really an optional flag or something for my webpack configuration?
