### ISSUE TITLE
IE9 : requestAnimationFrame : Adding shims from angular 2 repository

### ISSUE THREAD

**Issue by sasidhar** [AngularClass/angular2-webpack-starter#490]
In IE9, we are facing issues with `requestAnimationFrame`.

As of now, I am copying that from `angular2` repository (`./node_modules/angular2/ts/src/testing/shims_for_IE.js`) to `/assets` and including the same in index.html for IE browsers. But, I might need to update this folder after every update in `angular2`.

Is there any other way of including this?

If this is fine, I will update the README and send a PR. Might be useful for developers considering IE9 support.

**Comment by gdi2290** [comment]
you can include `ie-shim` in polyfills

**Comment by smith64fx** [comment]
Anybody found a workaround?

**Comment by gdi2290** [comment]
include ie-shim in polyfills
