### ISSUE TITLE
How to disable css encapsulation?

### ISSUE THREAD

**Issue by rvetere** [AngularClass/angular2-webpack-starter#492]
Sorry, as i can't reopen issues here (or i just don't know how), i'm referencing to the closed issue: https://github.com/AngularClass/angular2-webpack-starter/issues/488#event-610552866

Thanks for your replies! Everything clear so far.. but, how would i turn off css encapsulation for a component?

My problem is, i try to use Sass together with Bootstrap. I know it would be perfect in ES6 modules to import the css for every component directly in the components code. But then i don't know all the variables/classes inside my component script - then i have to import everything needed over and over again in every component (which is not wrong as i read about ES6 modules). But this results in having bootstrap included several times in the final package - and then i have to de-dup everything? This feels totally wrong to me.

So i got another approach - i'm importing my scss only at one single point in the whole app - in my bootstrapping "main.browser.ts" -> and my basic scss is importing bootstrap, and all subsequent scss files of all components. This way i end up having all classes/variables everywhere available and i import boostrap only once and don't have to de-dup in the end. Now the only thing "disturbing" here is the css encapsulation i guess.

Isn't the encapsulation controlled by the imports...? Or is there really an optional flag or something for my webpack configuration?

**Comment by joaogarin** [comment]
Encapsulation is controlled by the angular components themselves. You would set on your component : 

encapsulation : ViewEncapsulation.None,

You can also set ViewEncapsulation.Emulated (default) or ViewEncapsulation.Native (shadowDom)

See more about it here : https://angular.io/docs/js/latest/api/core/ViewEncapsulation-enum.html

Also a good article can be found here : http://blog.thoughtram.io/angular/2015/06/29/shadow-dom-strategies-in-angular2.html

**Comment by rvetere** [comment]
Thanks this does the trick :)

**Comment by NathanWalker** [comment]
@rvetere @joaogarin This is also a very flexible (scalable and powerful) way to do this globally for all components that use this custom decorator:
https://gist.github.com/NathanWalker/36930bba00ceac289186843da50c33e2

**Comment by Nerdowski** [comment]
@joaogarin  Good bless you man !!!

**Comment by spottedmahn** [comment]
new url for [ViewEncapsulation enum](https://angular.io/api/core/ViewEncapsulation)

@joaogarin can you edit your post and I'll delete mine?

**Comment by spottedmahn** [comment]
[This angular.io doc](https://angular.io/guide/component-styles#view-encapsulation) has some useful info about it.
