### ISSUE TITLE
angular2-hmr has no exported member 'WebpackState'.

### ISSUE THREAD

**Issue by Somiks** [AngularClass/angular2-webpack-starter#494]
* **I'm submitting a ...**
[ ] bug report

* **Please tell us about your environment:**
- Angular version: 2.0.0-beta.13

I just updated newer version of webpack. I can see this module in node_modules

ERROR in [default] C:/new_project/src/app/app.service.ts:2:8 
Module '"C:/new_project/node_modules/angular2-hmr/dist/index"' has no exported member 'WebpackState'.

ERROR in [default] C:/new_project/src/main.browser.ts:5:8 
Module '"C:/new_project/node_modules/angular2-hmr/dist/index"' has no exported member 'provideInitialState'.

**Comment by gdi2290** [comment]
@Somiks can you check the latest changes?
https://github.com/AngularClass/angular2-webpack-starter/blob/master/src/main.browser.ts#L53...L54
https://github.com/AngularClass/angular2-webpack-starter/blob/master/src/app/app.service.ts#L2...L7

**Comment by Somiks** [comment]
@gdi2290 
yeah, now all works fine. Looks like zip version of the project updates a little bit later. Because I used zip version yesterday and there was not last changes.
