### ISSUE TITLE
a failing test cause npm run-script e2e error 

### ISSUE THREAD

**Issue by jplo** [AngularClass/angular2-webpack-starter#497]
I' m submitting an issue I have when I launch npm run-script e2e, in a context where there is a failing e2e test.
Thanks.
I have the following result :

[ ] bug report

/usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js run-script e2e

> angular2-webpack-starter@4.0.0 pree2e /Users/jp/angular2-webpack-starter2
> npm run webdriver:update -- --standalone

> angular2-webpack-starter@4.0.0 webdriver:update /Users/jp/angular2-webpack-starter2
> npm run webdriver-manager update "--standalone"

> angular2-webpack-starter@4.0.0 webdriver-manager /Users/jp/angular2-webpack-starter2
> webdriver-manager "update"

selenium standalone is up to date.
chromedriver is up to date.

> angular2-webpack-starter@4.0.0 e2e /Users/jp/angular2-webpack-starter2
> npm run protractor

> angular2-webpack-starter@4.0.0 protractor /Users/jp/angular2-webpack-starter2
> protractor

root directory: /Users/jp/angular2-webpack-starter2
Using ChromeDriver directly...
[launcher] Running 1 instances of WebDriver
Started
F.....

Failures:
1) App should have a title
  Message:
    Expected 'Angular2 Webpack Starter by @gdi2990 from @AngularClass' to equal 'Angular2 Webpack Starther by @gdi2990 from @AngularClass'.
  Stack:
    Error: Failed expectation
        at Object.<anonymous> (app.e2e.ts:11:21)
        at /Users/jp/angular2-webpack-starter2/node_modules/jasminewd2/index.js:96:23
        at new Promise (/Users/jp/angular2-webpack-starter2/node_modules/selenium-webdriver/lib/promise.js:1043:7)
        at controlFlowExecute (/Users/jp/angular2-webpack-starter2/node_modules/jasminewd2/index.js:82:18)
        at TaskQueue.execute_ (/Users/jp/angular2-webpack-starter2/node_modules/selenium-webdriver/lib/promise.js:2790:14)
        at TaskQueue.executeNext_ (/Users/jp/angular2-webpack-starter2/node_modules/selenium-webdriver/lib/promise.js:2773:21)
        at /Users/jp/angular2-webpack-starter2/node_modules/selenium-webdriver/lib/promise.js:2697:25
        at /Users/jp/angular2-webpack-starter2/node_modules/selenium-webdriver/lib/promise.js:639:7
        at process._tickCallback (node.js:402:9)

6 specs, 1 failure
Finished in 3.982 seconds
[launcher] 0 instance(s) of WebDriver still running
[launcher] chrome #01 failed 1 test(s)
[launcher] overall: 1 failed spec(s)
[launcher] Process exited with error code 1

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "protractor"
npm ERR! node v5.6.0
npm ERR! npm  v3.8.5
npm ERR! code ELIFECYCLE
npm ERR! angular2-webpack-starter@4.0.0 protractor: `protractor`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular2-webpack-starter@4.0.0 protractor script 'protractor'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-webpack-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     protractor
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-webpack-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-webpack-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jp/angular2-webpack-starter2/npm-debug.log

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/bin/npm-cli.js" "run-script" "e2e"
npm ERR! node v5.6.0
npm ERR! npm  v3.8.5
npm ERR! code ELIFECYCLE
npm ERR! angular2-webpack-starter@4.0.0 e2e: `npm run protractor`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular2-webpack-starter@4.0.0 e2e script 'npm run protractor'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-webpack-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run protractor
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-webpack-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-webpack-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jp/angular2-webpack-starter2/npm-debug.log

Process finished with exit code 1

* **Do you want to request a *feature* or report a *bug*?**

Bug report

* **What is the current behavior?**

Bug

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**

No bug

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.13
- Browser: Chrome Version 51.0.2700.0 canary (64-bit)

**Comment by daddywoodland** [comment]
Hi @jplo,

I can't see in the history of the app component or it's end to end test where _'Starther'_ comes from.

Expected 'Angular2 Webpack Starter by @gdi2990 from @AngularClass' to equal 'Angular2 Webpack **_Starther_** by @gdi2990 from @AngularClass'.

Did you make any changes to the test or could you try correcting it in your code as it looks ok in the repository now?

**Comment by ebeal** [comment]
@jplo  If the text is in fact identical and was not just a typo it's likely that the failure is coming from the img that is in the same element or the href. The results look identical but aren't. I made updates to this particular test today that should fix any issues so it should be fixed when you pull latest.
