### ISSUE TITLE
Size of app

### ISSUE THREAD

**Issue by zwhitchcox** [AngularClass/angular2-webpack-starter#498]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[x] question about the decisions made in the repository

So the size of the compiled app, even built for production is like 6MB. Is this normal? Is this the expected behavior? This seems pretty large to me.

Angular version: 2.0.0-beta.X
Chrome OS X

**Comment by abdulhaq-e** [comment]
Are you sure you have the latest code?

Have you imported any external libraries? Perhaps you loaded all Rxjs.

**Comment by zwhitchcox** [comment]
Just recloned the library and installed...It's at about 5MB...is this normal?

![screen shot 2016-04-06 at 3 39 31 pm](https://cloud.githubusercontent.com/assets/4328800/14332159/d9bfc30c-fc0d-11e5-8dca-92dc0d5c6526.png)

**Comment by abdulhaq-e** [comment]
There is something wrong with your setup. Here is a screenshot of a production build with a fresh clone of this repo.

![size](https://cloud.githubusercontent.com/assets/2532125/14333436/edc71684-fc4e-11e5-8500-78991531cb1a.png)

**Comment by gdi2290** [comment]
the size is the inline source-maps and hot module replacement. if you change `devtool` to `source-map` and remove hmr you will see the size go down to 1.5mb

**Comment by zwhitchcox** [comment]
Ok, yes, it went down to <1MB
