### ISSUE TITLE
Documentation Generator Enhancement

### ISSUE THREAD

**Issue by abhishekisnot** [AngularClass/angular2-webpack-starter#51]
It would be great if starter can provide a way to generate project documentation from source code.

A quick search yields multitude of generator libraries/frameworks:
https://github.com/angular/dgeni
https://github.com/jsdoc3/jsdoc
http://jashkenas.github.io/docco/
https://wiki.appcelerator.org/display/guides2/ScriptDoc+(SDOC)+2.0+Specification
http://yui.github.io/yuidoc/
http://www.naturaldocs.org/
http://dojotoolkit.org/reference-guide/1.8/util/doctools/generate.html
https://github.com/senchalabs/jsduck

**Comment by gdi2290** [comment]
@abhishekisnot can you submit a PR with jsdoc?

**Comment by sumigoma** [comment]
how about typedoc? http://typedoc.io/

**Comment by gdi2290** [comment]
done via https://github.com/AngularClass/angular2-webpack-starter/commit/b785b7fe9c58ea8401821a3308118f0fea6906b6#diff-c036ca0f2d0a158e642472aae98dabce

**Comment by vogloblinsky** [comment]
Hi @gdi2290 ,

Disclaimer : i am the maintainer of compodoc ;)

Did you think interesting switching from typedoc to [compodoc](https://github.com/compodoc/compodoc) for the generated documentation ?

Here is a test : https://compodoc.github.io/angular2-webpack-starter/

The routes page will be redesigned this week. (https://github.com/compodoc/compodoc/issues/17#issuecomment-271153786)

Regards

**Comment by d3viant0ne** [comment]
@vogloblinsky - It's been up for discussion more than once. I've personally run into a few snags in larger projects with it ( complete understandable given it's age ) but overall I feel `compodoc` as significant potential once it's matured.

While Blake is doing his best to pick up the slack on Typedoc, it's maintenance has been slow & I don't see a lot of features in it's future so the real question is remove doc generation entirely and let users and what they will or replace the existing `typedoc` with `compodoc`.

I'll open an issue for discussion with the maintainers and the community and we can decide this in an issue a bit more visible.
