### ISSUE TITLE
Error running on Chrome version 50

### ISSUE THREAD

**Issue by jneveux** [AngularClass/angular2-webpack-starter#511]
Hi,

I've just installed the latest version and I'm getting an error when trying to run on Chrome Version 50.0.2661.75 (64-bit) / MAC OS X 10.11.4 (I had a similar issue on version 49)

Console logs:
Uncaught TypeError: Cannot read property 'replace' of null
Uncaught reflect-metadata shim is required when using class decorators
Uncaught TypeError: decorators_1.Injectable is not a function

Everything runs fine on Safari and FireFox.

Thanks,

Jean

**Comment by jneveux** [comment]
Note this only happens on dev build, it works on prod build.

**Comment by gdi2290** [comment]
@jneveux in this file can you change https://github.com/AngularClass/angular2-webpack-starter/blob/master/src/polyfills.ts
```
import 'core-js/es6';
import 'core-js/es7/reflect';
```
to
```
import 'core-js';
```

**Comment by jneveux** [comment]
@gdi2290 Thanks for your answer. 

I found the issue, I had an extension running called "Popup Blocker Pro 1.3.5". It is actually injecting "script" tags in the page, which is throwing off WebPack...

**Comment by gdi2290** [comment]
@jneveux  what's the script tag? so I can make sure it's not a problem for others

**Comment by jneveux** [comment]
@gdi2290 I found that WebPack code is the cause: 
angular2-webpack-starter/node_modules/webpack-dev-server/client/index.js
`var scriptHost = scriptElements[scriptElements.length-1].getAttribute("src").replace(/\/[^\/]+$/, "");`

The code above fails because Popup Blocker Pro adds a script tag at the end of the index page:
`<script>function inject(){function a(){function a(a){parent.postMessage({type:"blockedWindow",args:JSON.stringify(a)},l)}function b(a){var b=a[1];return null!=b&&["_blank","_parent","_self","_top"].indexOf(b)<0?b:null}function e(a,b){var c;for(c in a)try{void 0===b[c]&&(b[c]=a[c])}catch(d){}return b}var g=arguments,h=!0,j=null,k=null;if(null!=window.event&&(k=window.event.currentTarget),null==k){for(var m=g.callee;null!=m.arguments&&null!=m.arguments.callee.caller;)m=m.arguments.callee.caller;null!=m.arguments&&m.arguments.length>0&&null!=m.arguments[0].currentTarget&&
...
</script>`

**Comment by gdi2290** [comment]
can you create an issue at https://github.com/webpack/webpack-dev-server/issues and provide a link to this issue?
