### ISSUE TITLE
angular2+webpack build error:Cannot resolve module 'angular2/platform/browser'

### ISSUE THREAD

**Issue by Dreampie** [AngularClass/angular2-webpack-starter#530]
http://stackoverflow.com/questions/36791957/angular2webpack-build-errorcannot-resolve-module-angular2-platform-browser

someone help？

**Comment by t0rrro** [comment]
are you importing angular2/platform/browser in vendors.ts?

**Comment by Dreampie** [comment]
I resolve this，add extensions ·.js·
···json
resolve: {
      modulesDirectories: ['node_modules'],
      extensions: ['', '.html', '.less', '.js', '.ts']
    },
···

**Comment by t0rrro** [comment]
This should be closed. Angular 2 rc0 has since moved this to @angular/platform-browser
