### ISSUE TITLE
Coverage doesn't work with remap-istanbul

### ISSUE THREAD

**Issue by brechtbilliet** [AngularClass/angular2-webpack-starter#531]
The codecoverage outputs es5 code.
In theory it should be possible to remap the tested code back to typescript (based by the sourcemaps).
I saw that istanbul-remap is in the package.json but my coverage reports are all in es5 code

**Comment by antonybudianto** [comment]
take a look at my [starter](https://github.com/antonybudianto/angular2-starter) config

**Comment by stefanrinderle** [comment]
I tried a lot to get this work, but was not able to use the remap-istanbul. Anything i try, i get 
[Error: Could not find source map for: "...XXX.ts"]

antonybudianto's project is build with gulp ans has no spec-bundle file and i think I'm missing to convert the starter config to this project.

It would be great if anyone could write an explanation or even better could integrate this in the project. Thanks

**Comment by gdi2290** [comment]
closing for https://github.com/AngularClass/angular2-webpack-starter/issues/178
