### ISSUE TITLE
nav bar broken in IE10

### ISSUE THREAD

**Issue by MFateen** [AngularClass/angular2-webpack-starter#534]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**

Report a bug

* **What is the current behavior?**

when you open your template in IE10 it doesn't load the name, Angular 2 Webpack Starter, and in general the nav bar is broken, but when I tried to write my own component it loaded fine

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

just open it in IE10 and you'll see 

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.15
- Browser: [ IE 10  ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by MarkPieszak** [comment]
It's probably Material2 - which is only meant for IE11 and the newest browsers.

**Comment by t0rrro** [comment]
This should be closed. This is an issue with material2. There are plenty of issues open there with bugs related to IE
