### ISSUE TITLE
cannot use fonts or images from stylesheets

### ISSUE THREAD

**Issue by MurhafSousli** [AngularClass/angular2-webpack-starter#535]
I have problem using fonts and images from style sheets, for example I have the following structure

 src / assets / images / blue-background.svg
 src / assets / css / rio-font.css
 src / assets / fonts / font-awesome
   ---------------------  / rio-font
   ---------------------  / roboto

in rio-font.css

 ```
@font-face {
  font-family: "rio";
  src:url("../fonts/rio.eot");
  src:url("../fonts/rio.eot#iefix") format("embedded-opentype"),
    url("../fonts/rio.woff") format("woff"),
    url("../fonts/rio.ttf") format("truetype"),
    url("../fonts/rio.svg#rio") format("svg");
  font-weight: normal;
  font-style: normal;
}
```
all fonts and images paths I use from the style sheets, it gives 404 error! how can I fix it?

**Comment by gdi2290** [comment]
`/assets/fonts/` make sure you use `/assets`

**Comment by MurhafSousli** [comment]
@gdi2290 but `rio-font.css` is already inside `/assets` directory

**Comment by MurhafSousli** [comment]
@gdi2290 Thank you I fixed it by overriding the style with `assets/fonts`
