### ISSUE TITLE
application in the subfolder

### ISSUE THREAD

**Issue by oktango** [AngularClass/angular2-webpack-starter#536]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[ ] bug report
[X ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**

feature

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**

How can I put the whole application to the subfolder (eg http://mysite.com/app/) and use HTML5 routing instead of hash routing?

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Firefox

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by MarkPieszak** [comment]
Currently it's set up to use the `HashLocationStrategy` simply change it to `PathLocationStrategy` during the angular2 `bootstrap()` process.

[Change this line in provider.ts](https://github.com/AngularClass/angular2-webpack-starter/blob/1205e1a3bdd1c693a8e31d2d38548d11e8333123/src/platform/browser/providers.ts#L29)

Change it to: (make sure you import it from 'angular2/router' as well)

    provide(LocationStrategy, { useClass: PathLocationStrategy })

**Comment by oktango** [comment]
Thank you. What about putting the application in subfolder?

**Comment by oktango** [comment]
Thank you. About putting application in the subfolder I found the solution:
1. change balseUrl:'/app/' in webpack.common.js
2. add  '/app/' to the links in index.html

**Comment by techhysahil** [comment]
I have write solution for above problem as it occur to me too. Check http://blog.techhysahil.com/angular-2/deploy-angular-2-project-subdirectory/ for full detail.
