### ISSUE TITLE
lots of warnings with primeng

### ISSUE THREAD

**Issue by MurhafSousli** [AngularClass/angular2-webpack-starter#541]
Hi, I'm trying to integrate PrimeNG in my project, It works fine, but I get a lot of warnings (+75 warnings).

warning:
`Cannot find source file 'uitreenode.ts': Error: Cannot resolve 'file' or 'directory' ./uitreenode.ts in C:\myproject\node_modules\primeng\components\tree`

How can I remove them?

**Comment by MarkPieszak** [comment]
This is a PrimeNG issue not something with the starter, please look there:

https://github.com/primefaces/primeng/issues

**Comment by MurhafSousli** [comment]
@MarkPieszak I've already opened the [issue](https://github.com/primefaces/primeng/issues/201) there, they told me to open it here!

**Comment by gdi2290** [comment]
the warning are a problem with their source maps. you need to ignore them here https://github.com/AngularClass/angular2-webpack-starter/blob/master/config/webpack.common.js#L110...L115
I also made a branch for primeng
https://github.com/AngularClass/angular2-webpack-starter/tree/primeng

**Comment by MurhafSousli** [comment]
Thank you so much @gdi2290 problem solved.
I have a noob question, how is primeng branch different from the master, is that branch have primeng integrated or it's only meant for opening primeng related issues?

**Comment by gdi2290** [comment]
I created the primeng branch for anyone who wants to debug the issue. I'll have an offical branch later in the month

**Comment by truongnmt** [comment]
how to fix in webpack.dev.js file? Mine run in webpack dev enviroment and I dont know where to fix, here is my webpack.dev.js file:  http://pastie.org/10875854 @gdi2290

**Comment by gdi2290** [comment]
can you exclude it `helpers.root('node_modules/primeng'),` from sourcemaps

https://github.com/AngularClass/angular2-webpack-starter/blob/4a07eef656df71c8fc48d125f7b6a670a1e96046/config/webpack.common.js#L120...L124

**Comment by truongnmt** [comment]
Ahh got it, got the suggestion and it worked [link](http://stackoverflow.com/questions/8199204/adding-st-nd-rd-th-to-jquery-datepicker)
