### ISSUE TITLE
npm run test - Out of memory (again)

### ISSUE THREAD

**Issue by alvipeo** [AngularClass/angular2-webpack-starter#546]
Just got the latest of the repo and getting Out of Memory again when running tests :( Sigh...

Why this time? Does anybody know?

**Comment by alvipeo** [comment]
upgraded to beta.17, still have this #$%#$%:

>> angular2-webpack-starter@5.0.4 test d:\Documents\Visual Studio 2015\Projects\UniGalleryCode
> node --max-old-space-size=4096 node_modules/karma/bin/karma start


<--- Last few GCs --->

      15 ms: Mark-sweep 2.0 (19.6) -> 1.9 (19.6) MB, 1.1 / 0 ms [allocation failure] [GC in old space requested].
      15 ms: Mark-sweep 2.0 (19.6) -> 2.0 (19.6) MB, 1.1 / 0 ms [allocation failure] [GC in old space requested].
      15 ms: Mark-sweep 2.0 (19.6) -> 2.0 (19.6) MB, 1.0 / 0 ms [allocation failure] [GC in old space requested].
      15 ms: Mark-sweep 2.0 (19.6) -> 2.0 (19.6) MB, 1.0 / 0 ms [last resort gc].
      15 ms: Mark-sweep 2.0 (19.6) -> 1.9 (19.6) MB, 1.0 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 1D785C51 <JS Object>
    2: emitTwo(aka emitTwo) [events.js:100] [pc=1B21BB3D] (this=1D7080C9 <undefined>,handler=2A8288E9 <JS Function (SharedFunctionInfo 1D74F7B9)>,isFn=1D708129 <true>,self=1D79909D <a process with map 3890EB11>,arg1=1D790CF9 <String[14]: removeListener>,arg2=2A828939 <JS Function (SharedFunctionInfo 1D74F549)>)
    3: emit [events.js:185] [pc=1B21B78F] (this=1D79909D <a process with map 3890EB11>,typ...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

WTF??? Is it me or no one else running tests?

**Comment by eosrei** [comment]
FWIW The current checkout with Angular 2.0.0-rc.0 runs tests correctly after a minor update to angular2-hmr for the `@angular/core` change.
```
$ node --max-old-space-size=4096 node_modules/karma/bin/karma start
root directory: /home/example/angular2-webpack-starter

START:
(node) crypto.createCredentials is deprecated. Use tls.createSecureContext instead.
(node) crypto.Credentials is deprecated. Use tls.createSecureContext instead.
02 05 2016 23:57:49.246:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
02 05 2016 23:57:49.250:INFO [launcher]: Starting browser PhantomJS
02 05 2016 23:57:49.829:INFO [PhantomJS 2.1.1 (Linux 0.0.0)]: Connected on socket /#_tQw-hYV-1YKxHZ5AAAA with id 40883460
PhantomJS 2.1.1 (Linux 0.0.0) LOG: '`About` component loaded asynchronously'
  About
    ✔ should log ngOnInit
  App
    ✔ should have a url
  Home
    ✔ should have default data
    ✔ should have a title
    ✔ should log ngOnInit
  Title
    ✔ should have http
    ✔ should get data from the server
  x-large directive
    ✔ should sent font-size to x-large

Finished in 0.208 secs / 0.184 secs

SUMMARY:
✔ 8 tests completed

=============================== Coverage summary ===============================
Statements   : 77.7% ( 108/139 )
Branches     : 25% ( 4/16 )
Functions    : 54.05% ( 20/37 )
Lines        : 76.34% ( 100/131 )
================================================================================

```
