### ISSUE TITLE
Issue installing

### ISSUE THREAD

**Issue by softvar** [AngularClass/angular2-webpack-starter#547]
npm WARN package.json angular2-webpack-starter@5.0.4 scripts['server'] should probably be scripts['start'].
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2

npm ERR! Invalid name: "@angular2-material/card"
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/softvar/angular2-webpack-starter/npm-debug.log

**Comment by t0rrro** [comment]
The name is correct. This isn't an issue with the project. This is on your end. I'd suggest updating Node and retrying.

I suggest you close this issue
