### ISSUE TITLE
Error in angular2-hmr, new module syntax for Angular rc 0

### ISSUE THREAD

**Issue by turkingj** [AngularClass/angular2-webpack-starter#561]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[X ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**
node_modules/angular2-hmr/dist/hmr-store.d.ts
Error:(1, 29) TS2307: Cannot find module 'angular2/core'.

/node_modules/angular2-hmr/dist/index.d.ts
Error:(1, 26) TS2307: Cannot find module 'angular2/core'.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**
@angular/core

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by sentyaev** [comment]
To workaround this issue you can install angular2-hmr like that "angular2-hmr": "git+https://github.com/bobesa/angular2-hmr.git" (it's from my package.json, probably you also need to build this package manually).

Or you can wait until andgular2-hmr will apply pull request (it's already couple pull requests waiting for merge)

This https://github.com/gdi2290/angular2-hmr/pull/9 should fix this issue.

**Comment by turkingj** [comment]
@sentyaev good stuff, will wait for pull request
