### ISSUE TITLE
New router killed webpack 

### ISSUE THREAD

**Issue by zigzag95** [AngularClass/angular2-webpack-starter#572]
After watching ngConf and new router implementation. New router is based on string and directory structure  to reference child components. This won't work after bundling:(

**Comment by randhirlakavathu** [comment]
+1

**Comment by jonesmac** [comment]
+1

**Comment by kam3n** [comment]
+1

**Comment by robwormald** [comment]
the new router has a pluggable resolution service that can be replaced for any implementation you'd like, so it would be simple enough to implement a webpack compatible version.

**Comment by phiphou** [comment]
So, any example on how to use new router and webpak ?

**Comment by zigzag95** [comment]
It worked for me but I had to remove rooterActive

**Comment by zigzag95** [comment]
Async loader don't work with new router

**Comment by phiphou** [comment]
> It worked for me

having lazy loading with webpack (and separate chunk per lazyloaded comps) and the new router (not the deprecated one) working ? If so, can you show me ? 

> Async loader don't work with new router

that's the issue. So, I don"t understand if you have succeed in making it work or not (have webpack named chunks for lazy loaded comp using only the new router, and not the depracated one).

When you say 

> It worked for me but I had to remove rooterActive

are you talking about [this repo](https://github.com/zigzag95/angular2-webpack-starter) ? 

I'm french, so, please forgive me for my bad english ;)

**Comment by zigzag95** [comment]
Désolé 
J'utilise le répond webpack starter d'angularClass.
Je disais que j'ai pu remplacer le deprecated par le nouveau mais j'ai dû désactiver le chargement es6 et la directive routerActive.

Pour le chargement asynchrone si j'ai bien compris, il faut créer une classe spécialisée pour le mapping des routes et y rajouter la propriété loader. Mais ça je ne sais pas faire car le nouveau router n'est pas documenté.
