### ISSUE TITLE
npm run watch:test error!

### ISSUE THREAD

**Issue by keyiis** [AngularClass/angular2-webpack-starter#578]
when i exec "npm run watch:test " error occur!

10 05 2016 17:11:58.103:INFO [launcher]: Starting browser PhantomJS
10 05 2016 17:11:58.110:ERROR [launcher]: No binary for PhantomJS browser on your platform.
  Please, set "PHANTOMJS_BIN" env variable.
10 05 2016 17:11:58.116:ERROR [launcher]: [TypeError: Cannot read property 'stderr' of undefined]
TypeError: Cannot read property 'stderr' of undefined

**Comment by theotow** [comment]
try to install phantomjs.org this should set the PHANTOMJS_BIN var and make it work http://phantomjs.org/download.html

**Comment by ebeal** [comment]
@phevose did this work?

**Comment by phevose** [comment]
@theotow thanks reply! let me try.

**Comment by BrainCrumbz** [comment]
In our team we fixed this issue adding the following instruction at the beginning of `karma.conf.js`:

```js
process.env.PHANTOMJS_BIN = 'node_modules/phantomjs-prebuilt/bin/phantomjs';
```

Note that we have *phantomjs-prebuild* installed as a local dev dependency. In case, adapt your path as needed.
