### ISSUE TITLE
How do you change angular 2 material default colours in this seed project?

### ISSUE THREAD

**Issue by CristyTarantino** [AngularClass/angular2-webpack-starter#580]
Hi,

I am starting to use Angular2 material component used in your seeds. At the moment it is using a teal colour as default theme. How do you override it using your own or another colour palette?

Thanks in advance for your help.

**Comment by ebeal** [comment]
You can change a few things in the app.components file, remove instances of the color="primary" attribute on the md items and any css that is referencing a color or you can use the [material theme configuration tool](https://material.angularjs.org/latest/Theming/03_configuring_a_theme). 

I'm planning on making this way easier to do sometime in the next couple of weeks so you can also wait for that. Would this be easier in general if you didn't have the material design components or are they useful?

**Comment by CristyTarantino** [comment]
I'd love to use the full pack of material design. I find it extremely useful. I am in the process to use a md-select :)

**Comment by shawnrmoss** [comment]
How can you integrate the material theme configuration  tool into an angular2 project?  I would love to be able to do that

**Comment by ebeal** [comment]
Please see the material theme config docs linked above for instructions on how to implement them changes.

**Comment by goelinsights** [comment]
@ebeal you've linked to a material 1 spec...does this also work in angular2-material?  Can't find

**Comment by ebeal** [comment]
@goelinsights So it looks like they don't have any kind of theming implemented in angular2-material but I believe it will be the same as what they did in the material 1 spec. Thanks for catching that.

**Comment by mLaird** [comment]
I am able to set text color in toolbar with CSS, e.g., <md-toolbar class="headerFooter">, and likewise, I can set text color in icons.  However, I cannot set text color in list, e.g., <md-list-item class="sideLabels">LANGUAGE</md-list-item> does nothing.   Is this an alpha.8-2 problem, or am I doing something wrong?
