### ISSUE TITLE
adding CleanWebpackPlugin

### ISSUE THREAD

**Issue by morriq** [AngularClass/angular2-webpack-starter#592]
Could we add it to starter? https://github.com/johnagan/clean-webpack-plugin

In webpack.common.js

```
new CleanWebpackPlugin(['*'], {
      root: helpers.root('dist')
    }),
```

**Comment by IAMtheIAM** [comment]
You could do the same with just NPM scripts. Just add a "prestart" task, and add a "clean:dist" task
```

    "prestart": "npm run clean:dist",
    "clean:dist": "npm run rimrafl -- dist",
```

Now anytime you execute ```start```, it will clean the "dist" folder first

**Comment by morriq** [comment]
Nice :). Thx. I have made this modification.

**Comment by IAMtheIAM** [comment]
You're Welcome :-)
