### ISSUE TITLE
Webpack Hot Module Replacement not disposing of Old <style></style> and <script></script> tags

### ISSUE THREAD

**Issue by IAMtheIAM** [AngularClass/angular2-webpack-starter#596]
HMR does work to add new code to the page live, but it just piles new tags with all their css and JS to the head.

So I end up with the old styles and scripts, PLUS the new styles and scripts, and each time I save I get more and more appended to the head.

Isn't HMR supposed to "dispose" of the old styles and scripts before appending the new ones? What am I missing to make HMR properly dispose of old and tags?

![hmr not disposing of old code](https://cloud.githubusercontent.com/assets/13709948/15306177/41eaaee0-1b7d-11e6-8c59-1fed825de5d5.png)

**Comment by gdi2290** [comment]
sorry I can fix that

**Comment by IAMtheIAM** [comment]
Ok great, thanks! I'll wait for an update from you.

**Comment by Ledzz** [comment]
+1 to this issue

**Comment by gdi2290** [comment]
this is fixed in the latest release with `removeNgStyles` from `@angularclass/hmr`

**Comment by gdi2290** [comment]
the script tags are there because they're patches
