### ISSUE TITLE
Question about vendor size

### ISSUE THREAD

**Issue by alapasset** [AngularClass/angular2-webpack-starter#602]
Hello everybody,

My vendor.ts file : 

```
// Angular 2
import '@angular/platform-browser';
import '@angular/platform-browser-dynamic';
import '@angular/core';
import '@angular/common';
import '@angular/http';
import '@angular/router-deprecated';

// RxJS
import 'rxjs/Observable';
import 'rxjs/Subscription';
import 'rxjs/add/operator/map';

// Lightning
import 'ng-lightning/ng-lightning';
```

After build:prod :

>                                                   Asset     Size  Chunks             Chunk Names
               polyfills.0a5fa375cda8df736015.bundle.js  96.6 kB       0  [emitted]  polyfills
                    main.6e6905ba942b74785c81.bundle.js  8.84 kB       2  [emitted]  main
              polyfills.0a5fa375cda8df736015.bundle.map   745 kB       0  [emitted]  polyfills
                 vendor.4ab78283fe6e1485d3f2.bundle.map  5.74 MB       1  [emitted]  vendor
                   main.6e6905ba942b74785c81.bundle.map  43.6 kB       2  [emitted]  main
                 main.6e6905ba942b74785c81.bundle.js.gz   2.9 kB          [emitted]  
                main.6e6905ba942b74785c81.bundle.map.gz  9.71 kB          [emitted]  
            polyfills.0a5fa375cda8df736015.bundle.js.gz  31.2 kB          [emitted]  
               vendor.4ab78283fe6e1485d3f2.bundle.js.gz   196 kB          [emitted]  
           polyfills.0a5fa375cda8df736015.bundle.map.gz   173 kB          [emitted]  
              vendor.4ab78283fe6e1485d3f2.bundle.map.gz  1.08 MB          [emitted]  
                  vendor.4ab78283fe6e1485d3f2.bundle.js   927 kB       1  [emitted]  vendor
                                             index.html  1.65 kB          [emitted]  

I want know if 927kB isn't too large for my vendors ?

Thx

**Comment by IAMtheIAM** [comment]
Depends who you're serving to. Most people can download youtube vids no problem, so I don'y see anything wrong with 1mb. But might want to ask yourself why your app needs to load all vendors during app bootstrap. You should serve the vendor bundles that you need "on demand" as your app needs them. Just require() the stuff you need inside the components you need and webpack and angular2 take care of the rest.

**Comment by ebeal** [comment]
Your question is a little unclear but 927 kb looks about right, in prod build without ng-lightning I'm seeing it at 863 kb. If you're concerned about the size you can do as @IAMtheIAM suggested and instead of bundling all of the vendor files into one chunk them for async loading. [more info](https://webpack.github.io/docs/code-splitting.html)
