### ISSUE TITLE
HMR doesn't works

### ISSUE THREAD

**Issue by xgrommx** [AngularClass/angular2-webpack-starter#603]
Looks like HMR doesn't works. When I make some changes in `app.css` I have full refresh whole page instead of hot swap.

**Comment by xgrommx** [comment]
Sorry, not reloading just loosing my state of application. For example make recall to server.

**Comment by IAMtheIAM** [comment]
Need console log output to give any help. Also webpack config settings.

**Comment by xgrommx** [comment]
I use it only with standard settings from this repo.

**Comment by ebeal** [comment]
I'm pretty sure you need something like [style-loader](https://github.com/webpack/style-loader ) and/ or [css-loader](https://github.com/webpack/css-loader) to do this. I'll take a look into this more though.

**Comment by ebeal** [comment]
confirmed, see [webpack docs](https://webpack.github.io/docs/stylesheets.html) for more info on implementing and using these to do hmr with css

**Comment by gdi2290** [comment]
you need to run `npm run start:hmr`

**Comment by xgrommx** [comment]
@gdi2290 but I use `npm run server:dev:hmr`
