### ISSUE TITLE
Any chance you can update this to show how to include bootstrap and jquery from bower?

### ISSUE THREAD

**Issue by ctindel** [AngularClass/angular2-webpack-starter#61]
I am having a heck of a time modifying this example to loop in bootstrap.js, bootstrap.css, and jquery.  I was trying to use the bower-webpack-plugin to get it going but I just can't seem to pull it all together for some reason.

Any help you can offer would be awesome.  I'm not sure how to do the equivalent of:

require('bootstrap');
require('bootstrap.css');

Since this project is using ts instead of raw js.

**Comment by gdi2290** [comment]
good point I'll see what I can do about showing how to add it

**Comment by VPusher** [comment]
:+1

**Comment by gdi2290** [comment]
require('bootstrap.css'); goes in the top-level component with encapsulation set to None while require('bootstrap') goes in vendor.ts

**Comment by Vadorequest** [comment]
Yep, I'm trying to use some stuff using bower and I'm having a hard time figuring out how to require those files with this setup.
