### ISSUE TITLE
Router

### ISSUE THREAD

**Issue by zigzag95** [AngularClass/angular2-webpack-starter#611]
What are we waiting to use real router?
Material2 is already using it.

**Comment by gdi2290** [comment]
the repo has been updated to the latest router including lazy routes

**Comment by zigzag95** [comment]
Great but I can't see how app.routes.ts is called.

**Comment by gdi2290** [comment]
that's by design just as you don't know how app.component or app.service are called
it's being imported here https://github.com/AngularClass/angular2-webpack-starter/blob/master/src/platform/browser-providers.ts#L28...L29

**Comment by zigzag95** [comment]
I found it
/
export const APPLICATION_PROVIDERS = [
  // new Angular 2 forms
  disableDeprecatedForms(),
  provideForms(),

  provideRouter(routes),
  provideWebpack(asyncRoutes),

  ...HTTP_PROVIDERS,

  { provide: LocationStrategy, useClass: HashLocationStrategy }
];

**Comment by zigzag95** [comment]
Wonderful 
Just missing routActive directive
