### ISSUE TITLE
 Many devDependencies are part of build process, these should be moved to dependencies

### ISSUE THREAD

**Issue by paynoattn** [AngularClass/angular2-webpack-starter#614]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)
- **I'm submitting a ...**
  [x] bug report
  [x] feature request
  [x] question about the decisions made in the repository
- **Do you want to request a _feature_ or report a _bug_?**
  Bug
- **What is the current behavior?**
  Currently when node is in production mode on certain remote servers such as heroku, devDependencies are not installed. Therefore, many of these dependencies should be moved to the dependencies list.
- **What is the expected behavior?**
  Application should deploy without 'module "webpack" not found' messages in production environments.
- **What is the motivation / use case for changing the behavior?**
  Your app should work in production.
- **Please tell us about your environment:**
- Angular version: 2.0.0-rc1
- Browser: N/A

I have already fixed this [here](https://github.com/paynoattn/angular2-webpack-starter/commit/627ea042b8eced6c79c56f89376dd055fcc57ed2). I can create a pull request if this is approved.

**Comment by paynoattn** [comment]
I also removed dependencies not being used anywhere in the code, such as style-loader and several others. I can moved this into a seperate issue.

**Comment by yann-stepienik-cko** [comment]
Somebody correct me if I'm wrong, but this is the attended behavior, you're supposed to build your code on your dev machine and only deploy the built version (So no need for those dependencies).

**Comment by paynoattn** [comment]
Sorry I'm new to this package so I'm not sure what the intention should be since it's not spelled out, I assumed that this package was meant for deployment automation, given many of the of the scripts steps in ```package.json``` such as ```postinstall``` and ```build:prod``` and ```server:prod```.

IMHO the idea of 'build on your dev machine and only deploy the built version' is not good practice. The only way to deploy then is either use ftp/scp or something similar, or check in your ```dist/``` directory. I don't like either of those options.

In a node production environment everything could be automated by moving these dependencies, using git to checkout your latest code in production, and running your build and either ```npm run server:prod``` or adding a ```server.js``` and creating a simple express app that serves your ```dist``` folder.

**Comment by yann-stepienik-cko** [comment]
On my side I have a fully automated process for deployment. I run "npm run deploy" and it's going to call the build task + uploading the result to a server (and then remotly call npm install on it) everything via SSH. The result is a much lighter deployment (It would takes ages to upload ALL the dependencies, node's dependencies are not meant to be moved anyway, there're too much files).

**Comment by yann-stepienik-cko** [comment]
On my side the deployment is still automated, I call the deployment, it builds everything and cause the upload via SSH of the dist/ resulted (and remotely call npm install). I think deployment is much lighter that way (which makes sense for production) as you move only a bunch of files instead of your whole source code (that is not going to be used anyway after the build) also, you cut global dependencies like Typescript.
You might as well not want your original source code to be uploaded to a production server.
Another argument would be that building your source code on the target server will make it busy for a much higher time, and will totally break things if the build fail (meanwhile if your local build fail, nothing gets uploaded).

**Comment by paynoattn** [comment]
I see your point about build failure but you're making a lot of assumptions about your ng2 app and your production environment. There are a number of use cases where you would want or need to build in production, such as if you are trying to integrate your ng2 app with a node app, or that the security team for your company has disabled ssh traffic in the network, or any other number of reasons.

We could argue all day which use case is more important/popular but since my changes don't effect your ability to deploy your way at all and gives others such as me the ability to build in production it seems kind of an irrelevant argument to have for me. 

The purpose of a starter is to help as many use cases as possible, not just yours. :D

**Comment by anthonyraymond** [comment]
I don't get your point @paynoattn, why in any way would you like to install 'building' dependencies in a production environment? Building is a oneshot action, and the libraries would remains useless after it.

If you would like to build on production environment:
``` sh
npm install
#Build your app
rm -rf ./node_modules
npm install --production
```

**Comment by paynoattn** [comment]
I don't get your point. If the intention is to not have unused build code in production then having dependencies seperated by devDependencies make no sense because NONE of this repositories node_modules will be used post-build.

**Comment by seiyria** [comment]
@paynoattn if you don't want to do a "manual deploy" then add an npm task to do it.

**Comment by d3viant0ne** [comment]
The devDependencies are exactly how they need to be. You don't deploy development builds to a production server. i.e there is no need for `webpack` to be in a deployment no any of it's loaders.

It's JavaScript, which is served as static assets with something like `nginx` or using `angular universal` rendered on the server.

**Comment by fer662** [comment]
If you want heroku to build the production site and serve it you can try the following in package.json.

```
    "heroku-prebuild": "npm install --dev",
    "heroku-postbuild": "npm run build:prod"
    "start": "npm run server:prod",
```

**Comment by seza443** [comment]
> Just giving my opinion here because my build is failing as well

Personally I deploy using Flynn, that is based on buildpack, like Heroku.
And I think that it does not make sense that `npm run build:prod` fails after doing `npm install --only=production`.
The dependencies needed to *build production* assets should be included in the *production dependencies*.
