### ISSUE TITLE
Errors. Can not find components.

### ISSUE THREAD

**Issue by maxkarpovets** [AngularClass/angular2-webpack-starter#616]
When I try to use come components, a always got errors
EXCEPTION: Error: Uncaught (in promise): No Directive annotation found on DatePickerComponent (or another) 

How I can fix this issue?? ?

"ng2-bootstrap": "^1.0.16", ( from package.json )

**Comment by IAMtheIAM** [comment]
Show the code of the component so we can debug.

**Comment by maxkarpovets** [comment]
This component. And majority ng2-bootstrap components. 
https://github.com/valor-software/ng2-table

What angular2 version should i use with ng2-bootstrap?

**Comment by IAMtheIAM** [comment]
You'll want to talk to the ng2-table repo and start an issue there, because this project repo does not use ng2-table and therefore it out of scope here.
