### ISSUE TITLE
JQuery typings - how to install and use.

### ISSUE THREAD

**Issue by kamilszkutnik** [AngularClass/angular2-webpack-starter#619]
How can I install typings for jquery, and how to use it.

`typings search jquery`
It shows me:
`jquery                        dt     http://jquery.com/                                                    1        2016-04-17T21:32:36.000Z`

But when i want to install it with command:
`typings install jquery --save`
 or with
`typings install jquery -- ambient --save`

i got this:
` Unable to find "jquery" ("npm") in the registry. Did you want to try searching another source? `

I using typings version 1.0.4

I also need typings for mCustomScrollbar, maybe someone know how to add this plugin with jquery in the best way. Now i only add it in index.html, and i think it is not good when we using typescript.

**Comment by abdulhaq-e** [comment]
Try this:

> typings install jquery=github:DefinitelyTyped/DefinitelyTyped/jqeury/jquery.d.ts#4cdfbe96b666eec5e1defbb519a62abf04e96764 -SG

**Comment by ebeal** [comment]
please see #231
