### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by neokeats** [AngularClass/angular2-webpack-starter#62]
Hi, 
I think a starter pack should provide a way to know if a user is logged in or not. 
Thought the authentication process could just mock the calls to a server. 
There is not an real word application that doesn't need to know if the user can or not do the action.

A clean way to handle login and permissions with the best practice of how to handle such middleware will make it a perfect starter pack. 
Just adding : https://github.com/auth0/angular2-authentication-sample
is not enough since the code is not generic enough.

**Comment by gdi2290** [comment]
I might keep this repo as client only and move features such as this into the fullstack-angular2-starter. I can give an example of auth with cookies/jwt (prefered jwt) but the router also needs to be stable. With that said would you be fine with two starter repos (simply one client only and the other fullstack with more opinions) ? 

Previously the `examples/` were merged into the initial app but quickly became too complex for people when starting angular2

**Comment by neokeats** [comment]
Hi, 
it seems great to separate both.

The middleware problem is not limited to client/server. i ve looked into angular 2, they are some things i actually doesn't see how to handle yet.
More generally how to replace the rootScope behavior. 
Let's say we have an app, some stats are shown, we have a date range or datepicker somewhere. 
eveything is neat and separated so we have a component that show user stats and another his team stats or country stats. 
So differents/separated components, that need to know the user status(has a team or not to show him teams stats menu or no data since you have no team, same for country...)  and the separated datepicker value.
From angular2-authentication-sample they extend the router to know if the user is auth or not. 
But this cannot be applied to all middleware situations. A more simple case is the breadcrumb or menu active problem.
All the examples i've found doesn't show real case like this. 
Maybe it can't be done yet with angular2. 
The only way i see it actually is to use a singleton/localstorage to pass values between components.

**Comment by valorkin** [comment]
it is fixed https://github.com/auth0/angular2-authentication-sample/pull/38
so you can try now

**Comment by gdi2290** [comment]
the fullstack repo will have jwt authentication I'll revisit the issue when we publish it
