### ISSUE TITLE
Error with Node v6.x

### ISSUE THREAD

**Issue by smith64fx** [AngularClass/angular2-webpack-starter#622]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[ x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**

When I run
```
npm run build:prod
```

I get this error:
```
5972ms additional chunk assets
2503ms optimize chunk assets
 90% optimize assetsError in bail mode: [default] /home/smith/container/wp.schmid.digital/www/angular/node_modules/@angular/common/src/directives/ng_class.d.ts:72:34
Cannot find name 'Set'.
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**
Should work same like with Node v5!

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by Krisa** [comment]
Had the same issue, ensure you are not missing any dependency, especially one of these 3: es6-promise, es6-shim and/or es7-reflect-metadata

**Comment by kushwahashiv** [comment]
I also get the same issue when I tried to run 
`npm run build:prod`

`90% optimize assetsError in bail mode: [default] /Users/xxxxx/projects/xxxxx/node_modules/@angular/common/src/directives/ng_class.d.ts:72:34 
Cannot find name 'Set'.

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/bin/npm-cli.js" "run-script" "build:prod"
npm ERR! node v5.11.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! WizeWorks@0.1.6 build:prod: `webpack --config config/webpack.prod.js  --progress --profile --colors --display-error-details --display-cached --bail`
npm ERR! Exit status 1`

**Comment by kushwahashiv** [comment]
@Krisa I ensured the it has all 3 installed and it didn't worked for me :(

**Comment by Krisa** [comment]
@kushwahashiv yeah, I had the same problem yesterday when I tried to install that on Heroku. The above step I mentioned solved only a part of it but finally I managed to solve it by:
1- Remove the --bail flag => it doesn't solve anything but the error stack was much more meaningful when it's gone.
2- In my Heroku build, I forgot to install the typings on Heroku. Check whether you have not forgotten to do that either.

Regarding Typings, I had also another problem, in the newest version (typings > 1), it looks now different. Finally my current (successful) typings file looks like that
```
{
  "globalDependencies": {
    "angular-protractor": "registry:dt/angular-protractor#1.5.0+20160425143459",
    "core-js": "registry:dt/core-js#0.0.0+20160524134847",
    "es6-shim": "registry:dt/es6-shim#0.31.2+20160317120654",
    "hammerjs": "registry:dt/hammerjs#2.0.4+20160417130828",
    "jasmine": "registry:dt/jasmine#2.2.0+20160505161446",
    "mime": "registry:dt/mime#0.0.0+20160316155526",
    "node": "registry:dt/node#6.0.0+20160524002506",
    "selenium-webdriver": "registry:dt/selenium-webdriver#2.44.0+20160317120654",
    "source-map": "registry:dt/source-map#0.0.0+20160317120654",
    "uglify-js": "registry:dt/uglify-js#2.6.1+20160316155526",
    "webpack": "registry:dt/webpack#1.12.9+20160523035535",
    "zone.js": "registry:dt/zone.js#0.0.0+20160316155526"
  },
  "devDependencies": {},
  "ambientDependencies": {}
}
```

(Please note you are using node v5, but not the v6, even so the problem is probably not related to Node, but my typings is for node v6 so be careful)

**Comment by kushwahashiv** [comment]
@Krisa
Thanks for reply. I was having typings already installed on my machine.
here are my observations:
1) `--bail` removal is basically allowing build to proceed to show actual errors which I fixed.
2) Although I have following version of node - v6.2.0 and npm- v3.8.9 this should not be an issue
3) you can remove dev and ambient dependencies sections from typings.ts  as these has been replaced by `"globalDependencies"`

**Comment by tobek** [comment]
FWIW, I had the same issue and fixed it by updating to the latest version of this repo, which uses Typescript 2 and updated type definitions for various libraries (make sure to delete `node_modules/typescript` and run `npm install` again after updating.

@gdi2290 I think this issue can be closed.
