### ISSUE TITLE
Updating to Beta-17

### ISSUE THREAD

**Issue by yann-stepienik-cko** [AngularClass/angular2-webpack-starter#623]
* **I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**
Currently Angular is RC-1

* **What is the motivation / use case for changing the behavior?**

Several major fix have been made on Beta-17 such as #8148 and #6573.

**Comment by mastertinner** [comment]
According to https://github.com/angular/angular/blob/master/CHANGELOG.md 2.0.0-rc.1 is newer than 2.0.0-beta.17. Please close this issue.
