### ISSUE TITLE
Support RC1 new router

### ISSUE THREAD

**Issue by phiphou** [AngularClass/angular2-webpack-starter#629]
Hi,

With router-deprecated, here is what I was doing for lazy load components : 

```
import {Component} from '@angular/core';
import {RouteConfig, ROUTER_DIRECTIVES, ROUTER_PROVIDERS} from '@angular/router-deprecated';
import {ClassicComponent} from './comps/classic.component';

@Component({
    selector: 'app',
    providers: [ROUTER_PROVIDERS],
    directives: [ROUTER_DIRECTIVES],
    template: require('./app.html')
})
@RouteConfig([
    { path: '/classic', name: 'Classic', component: ClassicComponent, useAsDefault: true },
    { path: '/lazy', name: 'Lazy', loader: () => require('es6-promise?global,chunk-name!./comps/lazyloaded.component')('Lazy') }
])
export class AppComponent {
  ...
}
```

and in Webpack ;

```
config.output = {
    chunkFilename: 'js/[name].chunk.js' 
};
```

I was using [es6-promise-loader](https://github.com/gdi2290/es6-promise-loader ) , that can expose this `name `property for webpack

So, everything worked well, I got my lazyloaded comp working, and in a separate named chunk.

But, as you can see, I was using the deprecated router.

Trying to update to new RC1 router, I can't make it working anymore.

I obviously apply the changes (`@Routes` instead of `RouteConfig`, no more route `name`, etc.) but I can't figure out how I can handle the "missing loader issue" (there's no more `loader `property in the new router, no?). 

I tried  this : 

```
@Routes([
    { path: '/classic', component: ClassicComponent, },
    { path: '/lazy', component: () =>  require('es6-promise?global,chunkname!./comps/lazyloaded.component')('Lazy') }
])
```

but got this error : 

`Error: Uncaught (in promise): No Directive annotation found on component`

and also tried this : 

```
@Routes([
    { path: '/classic', component: ClassicComponent, },
    { path: '/lazy', component: require('es6-promise?global,chunkname!./comps/lazyloaded.component')('Lazy') }
])
```
and now got this error: 

`Uncaught (in promise): No Directive annotation found on [object Object]`

So, can anybody help me to achieve this ? Thanks.

**Comment by TobiasKrogh** [comment]
Have not yet tried it by myself (was just not ready), but have you checked out [AsyncRoute](https://angular.io/docs/js/latest/api/router/AsyncRoute-class.html)?

I would be interested on using the not deprecated router as well.

**Comment by phiphou** [comment]
`AsyncRoute `is for the depracated router ;)

I've seen something called `ComponentResolver `in latest commits, that should be  what we're waiting for.

It will probably be available in next release, I hope it'll be documented enough...

**Comment by zigzag95** [comment]
I think ComponentResorver will be used to find a component by its name. Maybe we can do lazy loading in it.

**Comment by ivanmayes** [comment]
+1 a little disappointing to switch over from the cli and see it behind in the latest code.

**Comment by gdi2290** [comment]
the repo has been updated to the latest router including lazy routes

**Comment by phiphou** [comment]
Glad to see it is now available in the repo ;) I've tried it and it works well !

I'm just wondering if the new `@angularclass/webpack-toolkit` module is planned to be include in `Angular2 `, and so renamed in `@angular/webpack-toolkit` ?
