### ISSUE TITLE
Got an error after the steps in "How to use Bootstrap 4 and Sass (and jQuery)"

### ISSUE THREAD

**Issue by aaronchen2k** [AngularClass/angular2-webpack-starter#633]
box-sizing: border-box; }
 is not a PostCSS plugin
    at Processor.normalize (/Users/aaron/tinypace/code/testspace/client/node_modules/postcss/lib/processor.js:60:23)
    at new Processor (/Users/aaron/tinypace/code/testspace/client/node_modules/postcss/lib/processor.js:23:29)
    at Object.postcss (/Users/aaron/tinypace/code/testspace/client/node_modules/postcss/lib/postcss.js:55:12)
 @ ./src/app/components/ui-tree/style/ui-tree.scss 4:14-195 13:2-17:4 14:20-201
Child html-webpack-plugin for "index.html":
    chunk    {0} index.html 519 kB [rendered]

**Comment by aaronchen2k** [comment]
It works well now!
Pls refer to https://github.com/aaronchen2k/testspace/tree/master/client 

`      { test: /^(?!.*cmp).*\.scss$/, loaders: ['style', 'css', 'postcss', 'sass'] },

      { test: /\.cmp\.scss$/, loaders: ['raw', 'postcss', 'sass'] },
      { test: /\.(png|jpg|gif)$/, loader: 'url?limit=30000' },
      { test: /\.(woff2?|ttf|eot|svg)$/, loader: 'url?limit=10000' },
      { test: /bootstrap\/dist\/js\/umd\//, loader: 'imports?jQuery=jquery' }

// global style
import 'assets/css/global.scss';

// component style
styles: [require('./style/ui-tree.cmp.scss')],
`

**Comment by ebeal** [comment]
Was it just the addition of the loaders that made it work?

**Comment by aaronchen2k** [comment]
@ebeal  yes

**Comment by lvauvillier** [comment]
I have a the same issue here : https://github.com/postcss/postcss-loader/issues/74
Can you please explain what exactly was wrong ?

Thanks !
