### ISSUE TITLE
Don't use outdated "namespace"

### ISSUE THREAD

**Issue by mastertinner** [AngularClass/angular2-webpack-starter#635]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
We are using the outdated `namespace` in `src/custom-typings.d.ts`.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**
According to https://palantir.github.io/tslint/rules/no-namespace/ this shouldn't be used anymore because it's outdated.

* **What is the motivation / use case for changing the behavior?**
To comply with the tslint rules.

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by gdi2290** [comment]
thanks, done via https://github.com/AngularClass/angular2-webpack-starter/commit/9df5eff93ca3ee027324e42d8d01fc8a7b84fe7c
