### ISSUE TITLE
webpack-dev-server.js:1 Uncaught TypeError: Cannot read property 'replace' of null

### ISSUE THREAD

**Issue by rdroft** [AngularClass/angular2-webpack-starter#638]
* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
report a bug 

* **What is the current behavior?**
the starter application not working properly 
there is 2 errors like this
webpack-dev-server.js:1 Uncaught TypeError: Cannot read property 'replace' of null
app.component.ts:66 Initial App State Object

and intial application loaded without images and some tags are not substituted 
like
<% if (webpackConfig.metadata.ENV === 'development') { %> <% } %>

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
git clone
cd angular2-webpack-starter
npm install 
npm start

open chrome browser and navigate to localhost:3000
open dev tab

* **What is the expected behavior?**
No errors on console
All resources loaded 

* **Please tell us about your environment:**

- Angular version: 2.0.0-rc1
- Browser: [ All ]

* **Other information** 
Uncaught TypeError: Cannot read property 'replace' of null(anonymous function) @ webpack-dev-server.js:1e @ webpack-dev-server.js:1(anonymous function) @ webpack-dev-server.js:1(anonymous function) @ webpack-dev-server.js:1
client:35 [WDS] Warnings while compiling.

**Comment by gdi2290** [comment]
the build has changed a lot in the past few days can you try again and reopen the issue if you're still running into the problem? thanks
