### ISSUE TITLE
CSS pre-processor such as Stylus, Less

### ISSUE THREAD

**Issue by leonardoanalista** [AngularClass/angular2-webpack-starter#641]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[ ] bug report
[x ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
feature

* **What is the current behavior?**
plain CSS

* **What is the motivation / use case for changing the behavior?**
It would be great to have a working example of CSS pre-processor configures and also, be able to scope the processed CSS to a component. Basically achieve CSS modules with a pre-processor as well

great work guys! really appreciate the effort.

Leonardo

**Comment by paynoattn** [comment]
Adding a css preprocesser is incredibly easy. 

Simply install the corresponding css loader you want, for instance for less you can use https://github.com/webpack/less-loader.

```npm install less-loader```

In ```./config/webpack.common.js``` change the loaders entry from 

```
      {
        test: /\.css$/,
        loader: 'raw-loader'
      },
```
to 

```
    {
      test: /\.less$/,
      loader: 'raw-loader!less-loader`
    }
```

then inside your component

```
@Component({
     selector: 'my-component'
     styles: require('./styles.less')
})
```

The procedure here is the same for sass, or styles. You could also use pre-css/autoprefixer, as I am here: https://github.com/paynoattn/paynoattn-angular2/blob/master/config/webpack.common.js

**Comment by ebeal** [comment]
I'm also working on putting an example of this into the material branch but we have a wiki on it as well: [How to include SCSS in components](https://github.com/AngularClass/angular2-webpack-starter/wiki/How-to-include-SCSS-in-components)

**Comment by leonardoanalista** [comment]
awesome! thanks guys
