### ISSUE TITLE
Bootstrap 3 and glyphicons (fonts)

### ISSUE THREAD

**Issue by alvipeo** [AngularClass/angular2-webpack-starter#642]
I finally found the setup that works with Bootstrap (I had problems with tests when using Bootstrap 4 alpha). So now I use Bootstrap 3 and _almost_ everything works - the app and the tests.

The only issue I have now with glyphicons and bootstrap fonts. For example, when I use
```
<span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
```
the icon is not loaded and here's what I get in the console:
>> browser_adapter.js:170 GET http://192.168.1.2:3000/node_modules/bootstrap/fonts/glyphicons-halflings-regular.woff2  - **404**

Obviously, nothing like 'node_modules/...' exists so how do I set it up with webpack?

Currently, I use .less and these loaders:
```
 {test: /\.less$/, loader: 'raw-loader!less-loader'},
      {test: /\.(png|jpg|gif)$/, loader: 'file-loader'},
      //{ test: /\.(png|woff|woff2|eot|ttf|svg)$/, loader: 'url-loader?limit=100000' }
      {
        test: /\.woff(\?v=\d+\.\d+\.\d+)?$/,
        loader: "url?limit=10000&minetype=application/font-woff"
      }, {
        test: /\.woff2(\?v=\d+\.\d+\.\d+)?$/,
        loader: "url?limit=10000&minetype=application/font-woff"
      }, {
        test: /\.ttf(\?v=\d+\.\d+\.\d+)?$/,
        loader: "url?limit=10000&minetype=application/octet-stream"
      }, {
        test: /\.eot(\?v=\d+\.\d+\.\d+)?$/,
        loader: "file"
      }, {
        test: /\.svg(\?v=\d+\.\d+\.\d+)?$/,
        loader: "url?limit=10000&minetype=image/svg+xml"
      }
```

Please help with this one. That's the only issue (for now) that stops me from using term 'an ideal web app setup for Angular 2' :)

**Comment by ebeal** [comment]
This is a duplicate of #508

**Comment by alvipeo** [comment]
ok, added link to bootstrap css and got it working! thanks!

**Comment by owwo** [comment]
@alvipeo Can you tell me how to do it?

**Comment by alvipeo** [comment]
I just added <link href="..."> to bootstrap cdn in my index.html

**Comment by owwo** [comment]
@alvipeo But I hope that can be referenced in the project. What better way thing?

**Comment by alvipeo** [comment]
I couldn't make glyphicons work. Only referencing bootstrap css from index.html.

**Comment by trsh** [comment]
+1. Anybody?

**Comment by gjdass** [comment]
+1, I referenced ng2-bootstrap which is working (loading the NgModule into app.module and it's fine, all component loaded everywhere). But 404 on icons -> GET 
http://localhost:3000/fonts/bootstrap/glyphicons-halflings-regular.woff2

Any idea ? I don't wanna use remote ones by inserting a line in index. I wanna use those stored in node_modules. Is there a way to tell webpack to copy fonts from node_modules or something ?

**Comment by ShakurOo** [comment]
+1, same problem here...

**Comment by herohoner** [comment]
+1 user bootstrap4 ,not add .bootstraprc file. the glyphicons is build  , but browsers add `<span class="glyphicon ..."></sapn>` not show .
