### ISSUE TITLE
AutoPrefixing with PostCSS / CSSnext not working on production build

### ISSUE THREAD

**Issue by Tre665** [AngularClass/angular2-webpack-starter#644]
* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
I want to report a problem with the current integration of the PostCSS / SASS Loader

* **What is the current behavior?**
The Post CSS matching works great in Development mode, but not when the app is build for production.
Currently the generated css misses the -webkit prefixes (at least for display: flex) when the app is build with the `npm run build:prod` command.   

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via

Here is a fork of the current material2 branch with added PostCss / Sass support to replicate the problem:

`git clone -b postcss --depth 1 --single-branch https://github.com/Tre665/angular2-webpack-starter.git`

These are the steps to add PostCss/Sass to the project:

1. clone the current version of the material2 branch 
`git clone -b material2 --depth 1  --single-branch https://github.com/angularclass/angular2-webpack-starter.git` 

2. Follow the instructions to add SCSS support as described here: 
[https://github.com/AngularClass/angular2-webpack-starter/wiki/How-to-include-SCSS-in-components](https://github.com/AngularClass/angular2-webpack-starter/wiki/How-to-include-SCSS-in-components)

3. Follow the instructions to add PostCSS / SCSS support as described here:
[https://github.com/AngularClass/angular2-webpack-starter/wiki/How-to-include-PostCSS](https://github.com/AngularClass/angular2-webpack-starter/wiki/How-to-include-PostCSS)

The File config/webpack.common.js looks afterwards like this (added only the important parts, all other already existing config is unchanged)

```javascript
.....
 module: {
 ........
   loaders: [
   ........   
     {
          test: /\.scss$/,
          exclude: /node_modules/,
          loader: 'to-string!css-loader!postcss-loader!sass-loader'
     }
  ]
  .....
  .....
  postcss: [
     require('postcss-cssnext')({
        browsers: ['ie >= 10', 'last 3 versions']
     })
   ],
}
```
4. Add some css that needs to be processed for older browsers.
(e.g I changed the app.css to app.scss, changed the reference in app.component.ts and added the css property  `display: flex;` to the html, body { } block at the top.

* **What is the expected behavior?**
The auto prefixing via post css should also work for the production build. 
The best case would be that the output of the production build is always the same as the dev build (except for the explicit changes that are made in the webpack.dev and webpack.prod files) 

* **What is the motivation / use case for changing the behavior?**
Being able to deploy the production build :-) 

* **Please tell us about your environment:**
- Mac OSX 10.10
- Angular version: 2.0.0-RC1
- Node v4.4.4
- NPM 3.9.0
- Browser: all

* **Other information** 
Hi there,
first things first: this project is amazing and I had a really good time to develop on top of it. Also I want to note that this is my first reported issue on Github. So please bear with me if I made some mistakes in the process.

I have successfully worked with the posted configuration for a while. Last week I decided to clone the newest version and migrate my project to it.

At first I had also problems with the dev build of my project (the same problems as reported now for the production build. That problem was easily fixed with an update of the postCss Configuration. It used to be 
```javascript
 postcss: [
     require('postcss-cssnext')({
        browsers: ['ie >= 10', 'last 2 versions']
     })
 ],
```
and I changed it to 
```javascript
 postcss: [
     require('postcss-cssnext')({
        browsers: ['ie >= 10', 'last 3 versions']
     })
 ],
```
With this change the `-webkit`prefixes was back in the generated css. However, recently i noted that this 'fix' will not work for the production build. 

I tried my best to get it also back to running here but unfortunately without success so far.

Here is what i tried:

* added the config explicitly also to the webpack.prod.js file
* compared the (for me) relevant npm packages that might have changes in it and downgraded the packages to the former working versions (including: node-sass, postcss-cssnext, postcss-loader)
* tried various configs for the browser matching pattern to get the `-webkit` prefix back
* removed the browser matching pattern completely
* removed the browser matching pattern completely and added a browserlist file with the config file as documented postcss documentation here [https://github.com/postcss/autoprefixer#no-prefixes-in-production](https://github.com/postcss/autoprefixer#no-prefixes-in-production)    
 
Unfortunately nothing above has fixed the issue.
I can only get 2 different states: With the above config it only adds the `-ms`prefixes but not the `-webkit` prefixes. And if i completely remove the browser matching pattern the, it adds the old `webkit` prefixes  
with `display: -webkit-box.

No matter what browser matching pattern i use, the resulted css is always the same. I also validated the expected results with this [http://autoprefixer.github.io](url) online tool and the filter 'last 3 versions' should work.

As a side node:
On the old project that i cloned initially the autoprefix plugin works also with the production build. 

I would really appreciate any help or comments on this issue.

**Comment by ebeal** [comment]
What version of postcss-cssnext are you currently using? What version of the old project were you using? Can you try using the ('ie >= 10, last 2 versions') version of the syntax? Are any of the other configurations not working?
I'll try and replicate this.

**Comment by Tre665** [comment]
Hi,

thank you for your response. 

I just tried your suggestion and changed the the syntax of the browser matching pattern to `'ie >= 10, last 3 versions'`. Unfortunately with the same result. 

I also made a new branch that just adds the sass and post css configuration to the project for easier replication of the problem. I used the current material2 branch as base. 
You can get it here `git clone -b postcss --depth 1 --single-branch https://github.com/Tre665/angular2-webpack-starter.git`

The new/non-working project uses the latest versions of the added npm dependencies

```javascript
    //angular webpack starter version
    "version": "5.0.5",

    "css-loader": "^0.23.1",
    "node-sass": "^3.7.0",
    "postcss-cssnext": "^2.6.0",
    "postcss-loader": "^0.9.1",
    "sass-loader": "^3.2.0",
    "to-string-loader": "^1.1.4",
``
and here are the relevant parts of the config of the old/working project 
```javascript
    //angular webpack starter version
    "version": "5.0.3",

    "css-loader": "^0.23.1",
    "node-sass": "^3.4.2",
    "postcss-cssnext": "^2.5.2",
    "postcss-loader": "^0.8.2",
    "sass-loader": "^3.2.0",
    "to-string-loader": "^1.1.4",
    "to-string-loader": "^1.1.3",
```

I didn't encounter any other issues with my real project yet after migrating to the current setup.

**Comment by ebeal** [comment]
okay thanks, I'll take a look today

**Comment by ebeal** [comment]
Sorry about the delay. I've narrowed this down to the uglifyjsplugin in the production config file. Can you confirm that removing this plugin (comment out or whatever) gives you the -webkit- prefix

**Comment by Tre665** [comment]
Hi,

i tested today your proposed fix and I can confirm that removing the uglifiyjs plugin from the production config gives the -webkit prefixes back!

I also searched about the problem and found an belonging issue in the postcss project:
[https://github.com/postcss/autoprefixer/issues/660](https://github.com/postcss/autoprefixer/issues/660)

and also here in the webpack repo:
[https://github.com/webpack/webpack/issues/2543](https://github.com/webpack/webpack/issues/2543)

The proposed solution/workaround works also for me. I changed the config from the webpack.common.config to include the `?minimize&-autoprefixer` option to disable the additional minifiyng of the CSS loader.
 
Here is the change:

```javascript
// old config with non working production build
{ 
        test: /\.scss$/,
        loader: 'to-string!css-loader!postcss-loader!sass-loader',
        exclude: /node_modules/
},

//new config that fixes the problem
{ 
        test: /\.scss$/,
        // here is the change
        loader: 'to-string!css-loader?minimize&-autoprefixer!postcss-loader!sass-loader',
        exclude: /node_modules/
},
```
 
Once again, thank you very much for your help! 

Should we update the [Post CSS Wiki](https://github.com/AngularClass/angular2-webpack-starter/wiki/How-to-include-PostCSS) with that fix? What do you think?

**Comment by ebeal** [comment]
Oh great, I didn't have time to look for any related issues, thanks for finding those. Can you make a pr with the update to the wiki?

**Comment by Remco75** [comment]
wow, I had been looking for soooo long, glad I finally found this..
This works
