### ISSUE TITLE
jquery typings broken

### ISSUE THREAD

**Issue by alvipeo** [AngularClass/angular2-webpack-starter#646]
I have to use jQuery and I tried to install typings for it, but I get
>> Unable to find "jquery" ("npm") in the registry.

It used to work. Does anybody know what happened? Am I missing something?

**Comment by mhheise** [comment]
Have you tried to use this
`typings search jquery`
followed by this?
`typings install dt~jquery --save --global`

There is no `jquery` definition in `npm`, only in `DefinitelyTyped`. You can find this information in the second column when you perform the `typings search [package]` command.

**Comment by ebeal** [comment]
This is outside of the scope of this repo

**Comment by alvipeo** [comment]
Thanks! I found it.
It's outside the scope of this repo but if someone needs a jquery they now have a hint.
