### ISSUE TITLE
Node 6.2.0 - warnings and extra output

### ISSUE THREAD

**Issue by alvipeo** [AngularClass/angular2-webpack-starter#648]
Installed Node 6.2.0 on my windows 10 laptop and built my prj. And here's what I get:

```
WARNING in (webpack)/buildin/module.js
There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.

WARNING in ./~/webpack/buildin/module.js
There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.
Child html-webpack-plugin for "index.html":
    chunk    {0} index.html 2.46 kB [rendered]
        [0] C:/Users/Alex/Documents/Visual Studio 2015/Projects/NewsNotifier/~/html-webpack-plugin/lib/loader.js!./src/index.html 2.46 kB {0} [built]
           factory:135ms building:16ms = 151ms
```

Also, when I open up the prj in a browser I get this extra at the bottom of every page:
>> <% if (webpackConfig.metadata.ENV === 'development') { %> <% } %>

Doesn't happen on Node 5.11.x. Anybody know the cause?

**Comment by RobCannon** [comment]
I am seeing the same issue.  Is the <% processing handled by webpack or some loader module?  An issue at the created in the repository of the appropriate module might get better results.

**Comment by thematan** [comment]
I have this issue as well,
cloned, windows 10, node v6.2.2
the warning:
`
WARNING in (webpack)/buildin/module.js
There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.

WARNING in ./~/webpack/buildin/module.js
There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.
Child html-webpack-plugin for "index.html":
    chunk    {0} index.html 1.43 kB [rendered]
        [0] F:/Promie/Code/CategoriesEditor2/~/html-webpack-plugin/lib/loader.js!./src/index.html 1.43 kB {0} [built]
           factory:83ms building:18ms = 101ms
webpack: bundle is now VALID.
[default] Checking started in a separate process...`

and all the template in index.html doesn't get compiled 
(<% if (webpackConfig.htmlElements.headTags) { %> <%= webpackConfig.htmlElements.headTags %> <% } %>)
