### ISSUE TITLE
WebpackMd5Hash causes polyfills to have the same name but different content

### ISSUE THREAD

**Issue by saldoukhov** [AngularClass/angular2-webpack-starter#649]
* **I'm submitting a ...**
[ X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

This is quite easy to reproduce.
1. Do a prod build on master
2. Copy aside polyfills bundle
3. Switch to material2 branch
4. Do a prod build
5. Compare the polyfills bundle to the one from step 2
6(optional). Repeat the above steps with WebpackMd5Hash commented out, the problem goes away.

Result: two files have the same name but different content
Expected: two files have different names

**Comment by davidmarquis** [comment]
I experienced the same issue. Removing the use of WebpackMd5Hash (and thus using the standard hashing mechanism of Webpack) removed the issue... why is `WebpackMd5Hash` used exactly?

**Comment by riddla** [comment]
We experienced the same issue just today. Removing the plugin "fixed" it, but why was this bug closed?
