### ISSUE TITLE
npm run e2e: TSError: Unable to compile TypeScript

### ISSUE THREAD

**Issue by holiber** [AngularClass/angular2-webpack-starter#651]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
`npm run e2e` fails

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

on clean project when I run `npm run e2e`:

`
[22:55:26] I/direct - Using ChromeDriver directly...
[22:55:26] I/launcher - Running 1 instances of WebDriver
[22:55:50] E/launcher - Error: TSError: ⨯ Unable to compile TypeScript
node_modules/@angular/common/esm/src/directives/ng_for.d.ts (7,5): Duplicate identifier 'readonly'. (2300)
node_modules/@angular/common/esm/src/directives/ng_for.d.ts (7,14): '=' expected. (1005)
node_modules/@angular/common/esm/src/directives/ng_for.d.ts (7,14): Cannot find name 'first'. (2304)
node_modules/@angular/common/esm/src/directives/ng_for.d.ts (7,19): ';' expected. (1005)
node_modules/@angular/common/esm/src/directives/ng_for.d.ts (7,21): Duplicate identifier 'boolean'. (2300)

and etc...
`

* **What is the expected behavior?**

e2e tests must works

* **What is the motivation / use case for changing the behavior?**

on previous version angular2-webpack-starter e2e tests worked without problems

* **Please tell us about your environment:**

- Angular version: 2.0.0-rc.1
- angular2-webpack-starter: 5.0.5
- Browser: Chrome 51

**Comment by TobiasKrogh** [comment]
Could this be a duplicate of https://github.com/AngularClass/angular2-webpack-starter/issues/615?

**Comment by holiber** [comment]
@TobiasKrogh It seems that this is the case
