### ISSUE TITLE
node-pre-gyp module access denied

### ISSUE THREAD

**Issue by qq83387856** [AngularClass/angular2-webpack-starter#652]
error AccessDenied when I `npm install`

**Comment by va4ok** [comment]
Hi, i have the same issue. Please see info below:

`D:\Projects\angular2-webpack-starter-master>npm i

> node-zopfli@1.4.0 install D:\Projects\angular2-webpack-starter-master\node_modules\node-zopfli
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://node-zopfli.s3.amazonaws.com/Release/zopfli-v1.4.0-node-v48-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@1.4.0 and node@6.2.1 (node-v48 ABI) (falling back to source compile with node-gyp)

D:\Projects\angular2-webpack-starter-master\node_modules\node-zopfli>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  e
lse (node "" clean )

D:\Projects\angular2-webpack-starter-master\node_modules\node-zopfli>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure
--fallback-to-build --module=D:\Projects\angular2-webpack-starter-master\node_modules\node-zopfli\lib\binding\node-v48-win32-x64\zopfli.node --module_name=zopfli --module_path=D:\Projects\angular2-webpack-starter-master\node_
modules\node-zopfli\lib\binding\node-v48-win32-x64 )  else (node "" configure --fallback-to-build --module=D:\Projects\angular2-webpack-starter-master\node_modules\node-zopfli\lib\binding\node-v48-win32-x64\zopfli.node --modu
le_name=zopfli --module_path=D:\Projects\angular2-webpack-starter-master\node_modules\node-zopfli\lib\binding\node-v48-win32-x64 )
`

**Comment by gdi2290** [comment]
can you try again I removed the compression-webpack-plugin
also related https://github.com/AngularClass/angular2-webpack-starter/issues/626

**Comment by flegros** [comment]
hello, I have the same issue with:
npm install -g node-zopfli
...
> node-pre-gyp install --fallback-to-build

node-pre-gyp http GET https://node-zopfli.s3.amazonaws.com/Release/zopfli-v2.0.0-node-v48-win32-x64.tar.gz
node-pre-gyp ERR! Tried to download: https://node-zopfli.s3.amazonaws.com/Release/zopfli-v2.0.0-node-v48-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@2.0.0 and node@6.5.0 (node-v48 ABI) (falling back to source compile with node-gyp)
node-pre-gyp http tunneling socket could not be established, statusCode=407

**Comment by flegros** [comment]
problem resolved today....
Something has changed ??

**Comment by flegros** [comment]
oups, it's ok for the 2.0.0 version but with the command:
npm install -g angular-cli@webpack
It try to download the 1.4.0 version :(
node-pre-gyp http GET https://node-zopfli.s3.amazonaws.com/Release/zopfli-v1.4.0-node-v48-win32-x64.tar.gz
node-pre-gyp http 403 https://node-zopfli.s3.amazonaws.com/Release/zopfli-v1.4.0-node-v48-win32-x64.tar.gz
node-pre-gyp ERR! Tried to download: https://node-zopfli.s3.amazonaws.com/Release/zopfli-v1.4.0-node-v48-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@1.4.0 and node@6.5.0 (node-v48 ABI) (falling back to source compile with node-gyp)
node-pre-gyp http 403 status code downloading tarball https://node-zopfli.s3.amazonaws.com/Release/zopfli-v1.4.0-node-v48-win32-x64.tar.gz

**Comment by yhqnh** [comment]
I have the same problem.
No body resolved?

**Comment by pradeepb6** [comment]
+1

**Comment by Meligy** [comment]
Most of my NPM install issues in general are often solved by adding `--no-optional` to the command, like `npm install --no-optional`.

Try it.

**Comment by StSquared** [comment]
+1
