### ISSUE TITLE
Add Electron branch

### ISSUE THREAD

**Issue by Jonatthu** [AngularClass/angular2-webpack-starter#655]
[x ] feature request

I want to integrate electron to this repo but with all the features like hmr and live reload, then if is possible debug the app with visual studio code as I'm already doing with this repo.
Do you know how to approach this?

**Comment by JonnyBGod** [comment]
I am currently working on a for with this feature. I currently have a private repo with it until it is stable.

If your interested in helping out I can invite you to it. Mainly I am mixing https://github.com/AngularClass/angular2-webpack-starter with https://github.com/NathanWalker/angular2-seed-advanced.

here is my plans for it and current state:

TODO
====

## Before internal use

- [ ] Fix unit tests
- [x] Fix E2E tests
- [x] Electron Builder
- [ ] Nativescript
- [ ] Fix async load components


## Before Open Sourcing

- [x] Change references to @JonnyBGod
- [x] Docs (typedoc)
- [x] Generate all icons and fix references in index.html
- [ ] Redo readme.md
	- [ ] Mention need for typescript@next
- [ ] CI release all platforms for demo app
- [x] Make it as easy as possible to extend


## Improvements

- [ ] Generate ApiService from swagger endpoint
- [ ] Generate ngrx/store reducer from swagger endepoint


## Extras (branches?)

- [ ] Windows Universal App
- [ ] Ionic
- [ ] React Native

**Comment by Jonatthu** [comment]
I'm Very interested add me as a collaborator and let's talk about what I can do for help.

**Comment by JonnyBGod** [comment]
Just sent you and invite for repo and skype. We can talk there to update you on it.

**Comment by bertofer** [comment]
Hi guys, I created a simple electron starter for angular2 and webpack, forked from https://github.com/preboot/angular2-webpack . It includes livereload for electron and I have planned to add e2e testing automated launching the electron executable instead of a browser. Maybe it can help somehow. The repo is https://github.com/bertofer/angular2-webpack-electron

**Comment by Infining** [comment]
Any news on this feature? This would be a great addition!

**Comment by JonnyBGod** [comment]
@Infining our repo with advance starter is still private. While it is working with electron, latest upstream updates have broken some parts and I need some time to fix everything before open sourcing it. If your interested in using or helping let me know and I will give you access.

**Comment by Infining** [comment]
@JonnyBGod I appreciate the great time and effort this all takes! I would be happy to help where I can.

**Comment by Chadley08** [comment]
I'd be very interested in this. I've had a heck of a time trying to get angular 2, and karma-jasmine to run with electron through webpack.

**Comment by Infining** [comment]
@Chadley08 if you want, I made a simple seed for my own work here: [angular2-webpack-electron](https://github.com/Infining/angular2-webpack-electron). It is very bare boned but it works for my purposes.

**Comment by bertofer** [comment]
Here another angular2-webpack-electron seed. Has e2e testing configured, even for travis (with a script to package current platform and use it in protractor), and also electron livereloading for developing. https://github.com/bertofer/angular2-electron. Could be helpful for solving this issue

**Comment by Chadley08** [comment]
Thanks very much for the link. I'll take a look.

**Comment by gdi2290** [comment]
electron will most likely be added to the fullstack universal starter that will be released at the end of the month

**Comment by Chadley08** [comment]
I've narrowed the issue I'm having down to using fs with this configuration. If I remove the components that use fs, I can run the unit tests with PhantomJS and in Chrome, but if fs is there I'm getting a "module not found" error and it refers to fs. Any insights into this? Let me know if you need more information and I can provide it.

**Comment by bertofer** [comment]
@Chadley08 You can try with [karma-electron-launcher](https://github.com/lele85/karma-electron-launcher). But i have a question, which modules use fs? I think you can only access Node.js modules from the main scripts of Electron, but not in the different windows opened. Does the app itself work with the fs modules, aside from the tests?

**Comment by israelg99** [comment]
Due to some difficulties with connecting many frameworks/tools (webpack, angular2, electron etc..) and after pull requests I did to help fix issues, I just created a [new repository that works](https://github.com/israelg99/Sofweb), it's a good starting point for cross-platform application development, I couldn't find other solutions like this so feel free to improve this one to make development more accessible to everyone.
