### ISSUE TITLE
Visual Studio Code Intellisense is unbearably slow

### ISSUE THREAD

**Issue by AmrN** [AngularClass/angular2-webpack-starter#660]
* **I'm submitting a ...**
[X] bug report

Visual Studio Code Intellisense is so slow when using this starter with typescript. I don't know if this is an issue with visual studio code or with some configuration, but when I change the paths format of the `exclude` list in **tsconfig.json** 
from:
```json
{
  "exclude": [
    "./node_modules",
    "./typings/main.d.ts",
    "./typings/main"
  ]
}
```
to (just removing the forward slashes): 
```json
{
  "exclude": [
    "node_modules",
    "typings/main.d.ts",
    "typings/main"
  ]
}
```
now when I restart Visual Studio Code its intellisense is working normally, I have no idea why this works or what the problem is though.

* **Please tell us about your environment:**

- Angular version: 2.0.0-rc.1

**Comment by fmoessle** [comment]
Thank you AmrN, my intellisense is now way faster!

**Comment by ebeal** [comment]
Closing since this seems fixed, although this was probably outside of the scope of this repo anyways
