### ISSUE TITLE
ReferenceError: __extends is not defined     at /Users/way/Desktop/angular2-webpack-starter/config/rules/importDestructuringSpacingRule.js:13:5

### ISSUE THREAD

**Issue by way1001** [AngularClass/angular2-webpack-starter#662]
After updating rules/importDestructuringSpacingRule.js is returning a function throws an error.

/Users/way/Desktop/angular2-webpack-starter/config/rules/importDestructuringSpacingRule.js:13
    __extends(Rule, _super);

**Comment by gdi2290** [comment]
thanks, this was fixed after updating codelyzer
