### ISSUE TITLE
 Remove # from url http://localhost:3000/#/about

### ISSUE THREAD

**Issue by itranga** [AngularClass/angular2-webpack-starter#665]
I need  remove # from url http://localhost:3000/#/about

**Comment by samvloeberghs** [comment]
Use PathLocationStrategy instead of HashLocationStrategy

**Comment by itranga** [comment]
Thanks . It's working

**Comment by haisaco** [comment]
It's working but when I f5 refresh page has error 404 not found

**Comment by itranga** [comment]
Please restart app using npm start

**Comment by nimat-netlinks** [comment]
@haisaco , I have the same problem, did you find any solutions ?

**Comment by nimatullah** [comment]
@haisaco same here.

**Comment by nnavaseelan** [comment]
same issue here also... any solid fix ?

plz help

**Comment by nimatullah** [comment]
@nnavaseelan are you using mean stack ?

**Comment by nnavaseelan** [comment]
i am using only angular 5 module wise lazy loading. 
all the URLs working with "#" key perfectly, useHash=false has the issue in Prod build

**Comment by nimatullah** [comment]
do you have github repository for it ?

**Comment by wptd** [comment]
Same here, CTRL+ F5 or browser Refresh...it says, Not found

**Comment by nimatullah** [comment]
Bro, you need to add a repository to see your code.

**Comment by alamgircsebd** [comment]
Still i am also searching this solution. any one get any luck?

**Comment by nimatullah** [comment]
@alamgircsebd, please create a minimal  repository of your mean stack

**Comment by Javohir-code** [comment]
I deleted my react-app project, but localhost:3000 is still available. I am going to create react-app in again from zero. Should I delete localhost:3000 also?

**Comment by Pulpul999** [comment]
how to remove # from the http://localhost:3000/#/products/1/15
