### ISSUE TITLE
Production build - requests from main.js every 2 sec - why and how to turn it off?

### ISSUE THREAD

**Issue by alvipeo** [AngularClass/angular2-webpack-starter#670]
So I built a prod version of my project and when I run it I see these XHR requests sent every 2 sec:

>> GET /06170190-7F42-9E44-AE65-1179F1EF1E3D/CA5CD42C-0705-A347-84F5-AEDCA2B3E1AC/from HTTP/1.1
Host: [whatever]
Connection: keep-alive
Origin: http://localhost:7734
Accept: */*
Referer: http://localhost:7734/
Accept-Encoding: gzip, deflate, sdch
Accept-Language: ru-RU,ru;q=0.8,en-US;q=0.6,en;q=0.4

What is the purpose of this? and why? and how to turn it off?
Thanks!

**Comment by alvipeo** [comment]
You may look at the prj here http://nng2.azurewebsites.net/. Open dev tools and go to Network tab to see what I'm talking about.

Why is it polling server? How to get rid of it?

**Comment by ebeal** [comment]
Are you using a particular browser? Not seeing this behavior.

**Comment by alvipeo** [comment]
Oh, that's my antivirus! damn...

**Comment by ebeal** [comment]
Hah okay cool.
