### ISSUE TITLE
Error with typedoc 0.4.2 and typescript 1.8.10

### ISSUE THREAD

**Issue by KanaguH** [AngularClass/angular2-webpack-starter#676]
### When running typedoc --mode modules --out /d/doc/ src

It gives errors as like below

`Cannot find name 'Set'.
Error: D:/Kanagu/Projects/angular2-webpack-starter-master/node_modules/@angular/common/src/facade/async.d.ts(26)
 Cannot find name 'Promise'.
Error: D:/Kanagu/Projects/angular2-webpack-starter-master/node_modules/@angular/common/src/facade/async.d.ts(27)
 Cannot find name 'Promise'.
Error: D:/Kanagu/Projects/angular2-webpack-starter-master/node_modules/@angular/common/src/facade/lang.d.ts(3)
 Cannot find name 'Map'.
Error: D:/Kanagu/Projects/angular2-webpack-starter-master/node_modules/@angular/common/src/facade/lang.d.ts(4)
 Cannot find name 'Set'.
Error: D:/Kanagu/Projects/angular2-webpack-starter-master/node_modules/@angular/common/src/facade/lang.d.ts(69)
 Cannot find name 'Map'.
Error: D:/Kanagu/Projects/angular2-webpack-starter-master/node_modules/@angular/common/src/facade/promise.d.ts(1)
 Cannot find name 'Promise'.
Error: D:/Kanagu/Projects/angular2-webpack-starter-master/node_modules/@angular/common/src/facade/promise.d.ts(7)
 Cannot find name 'Promise'.
Error: D:/Kanagu/Projects/angular2-webpack-starter-master/node_modules/@angular/common/src/facade/promise.d.ts(8)
 Cannot find name 'Promise'.
Error: D:/Kanagu/Projects/angular2-webpack-starter-master/node_modules/@angular/common/src/facade/promise.d.ts(9)
 Cannot find name 'Promise'.
Error: D:/Kanagu/Projects/angular2-webpack-starter-master/node_modules/@angular/common/src/facade/promise.d.ts(9)
 Cannot find name 'Promise'.
Error: D:/Kanagu/Projects/angular2-webpack-starter-master/node_modules/@angular/common/src/facade/promise.d.ts(10)
 Cannot find name 'Promise'.
Error: D:/Kanagu/Projects/angular2-webpack-starter-master/node_modules/@angular/common/src/facade/promise.d.ts(10)
 Cannot find name 'Promise'.
Error: D:/Kanagu/Projects/angular2-webpack-starter-master/node_modules/@angular/common/src/facade/promise.d.ts(11)
 Cannot find name 'Promise'.
Error: D:/Kanagu/Projects/angular2-webpack-starter-master/node_modules/@angular/common/src/facade/promise.d.ts(11)
 Cannot find name 'Promise'.
Error: D:/Kanagu/Projects/angular2-webpack-starter-master/node_modules/@angular/common/src/facade/promise.d.ts(12)
 Cannot find name 'Promise'.
Error: D:/Kanagu/Projects/angular2-webpack-starter-master/node_modules/@angular/common/src/forms/directives/select_control_value_accessor.d.ts(17)
 Cannot find name 'Map'.
Error: D:/Kanagu/Projects/angular2-webpack-starter-master/node_modules/@angular/common/src/pipes/async_pipe.d.ts(28)
 Cannot find name 'Promise'.
Error: D:/Kanagu/Projects/angular2-webpack-starter-master/node_modules/@angular/common/src/pipes/async_pipe.d.ts(34)
 Cannot find name 'Promise'.
Error: D:/Kanagu/Projects/angular2-webpack-starter-master/node_modules/@angular/common/src/pipes/async_pipe.d.ts(36)
 Cannot find name 'Promise'.
Error: D:/Kanagu/Projects/angular2-webpack-starter-master/node_modules/@angular/common/src/pipes/async_pipe.d.ts(38)
 Cannot find name 'Promise'.
Error: D:/Kanagu/Projects/angular2-webpack-starter-master/node_modules/@angular/compiler/src/directive_normalizer.d.ts(9)
 Cannot find name 'Promise'.
Error: D:/Kanagu/Projects/angular2-webpack-starter-master/node_modules/@angular/compiler/src/directive_normalizer.d.ts(10)
 Cannot find name 'Promise'.
Error: D:/Kanagu/Projects/angular2-webpack-starter-master/node_modules/@angular/compiler/src/facade/lang.d.ts(3)
 Cannot find name 'Map'.
Error: D:/Kanagu/Projects/angular2-webpack-starter-master/node_modules/@angular/compiler/src/facade/lang.d.ts(4)
 Cannot find name 'Set'.
Error: D:/Kanagu/Projects/angular2-webpack-starter-master/node_modules/@angular/compiler/src/facade/lang.d.ts(69)
 Cannot find name 'Map'.
Error: D:/Kanagu/Projects/angular2-webpack-starter-master/node_modules/@angular/compiler/src/offline_compiler.d.ts(31)
 Cannot find name 'Promise'.
Error: D:/Kanagu/Projects/angular2-webpack-starter-master/node_modules/@angular/compiler/src/offline_compiler.d.ts(33)
 Cannot find name 'Promise'.
Error: D:/Kanagu/Projects/angular2-webpack-starter-master/node_modules/@angular/compiler/src/output/output_ast.d.ts(416)
 Cannot find name 'Set'.
Error: D:/Kanagu/Projects/angular2-webpack-starter-master/node_modules/@angular/compiler/src/runtime_compiler.d.ts(27)
 Cannot find name 'Promise'.
Error: D:/Kanagu/Projects/angular2-webpack-starter-master/node_modules/@angular/compiler/src/selector.d.ts(50)
 Cannot find name 'Map'.
Error: D:/Kanagu/Projects/angular2-webpack-starter-master/node_modules/@angular/compiler/src/selector.d.ts(52)
 Cannot find name 'Map'.
Error: D:/Kanagu/Projects/angular2-webpack-starter-master/node_modules/@angular/compiler/src/template_parser.d.ts(36)
 Cannot find name 'Set'.
Error: D:/Kanagu/Projects/angular2-webpack-starter-master/node_modules/@angular/compiler/src/view_compiler/compile_view.d.ts(40)
 Cannot find name 'Map'.
Error: D:/Kanagu/Projects/angular2-webpack-starter-master/node_modules/@angular/compiler/src/view_compiler/compile_view.d.ts(42)
 Cannot find name 'Map'.
Error: D:/Kanagu/Projects/angular2-webpack-starter-master/node_modules/@angular/compiler/src/view_resolver.d.ts(9)
 Cannot find name 'Map'.
Error: D:/Kanagu/Projects/angular2-webpack-starter-master/node_modules/@angular/compiler/src/xhr.d.ts(5)
 Cannot find name 'Promise'.
Error: D:/Kanagu/Projects/angular2-webpack-starter-master/node_modules/@angular/compiler/testing/test_component_builder.d.ts(76)
 Cannot find name 'Promise'.
Error: D:/Kanagu/Projects/angular2-webpack-starter-master/node_modules/@angular/compiler/testing/test_component_builder.d.ts(88)
 Cannot find name 'Map'.
Error: D:/Kanagu/Projects/angular2-webpack-starter-master/node_modules/@angular/compiler/testing/test_component_builder.d.ts(90)
 Cannot find name 'Map'.
Error: D:/Kanagu/Projects/angular2-webpack-starter-master/node_modules/@angular/compiler/testing/test_component_builder.d.ts(92)
 Cannot find name 'Map'.
Error: D:/Kanagu/Projects/angular2-webpack-starter-master/node_modules/@angular/compiler/testing/test_component_builder.d.ts(94)
 Cannot find name 'Map'.
`
I am using node version 5.9.10 and npm version 3.7.3

**Comment by jiverson** [comment]
Same anyone have a fix?

**Comment by b0bi79** [comment]
I have the same problem

**Comment by therealcodesailor** [comment]
Same on OS X

**Comment by b0bi79** [comment]
#840 This is resolved by f71d4e6.
