### ISSUE TITLE
momentjs breaks sourcemaps

### ISSUE THREAD

**Issue by holiber** [AngularClass/angular2-webpack-starter#686]
* **I'm submitting a ...**
[x] bug report

* **What is the current behavior?**
When I import momentjs in clean project all sourcemaps became broken

how to reproduce:
1) install project from repo
2) install momentjs: `npm install moment`
3) in app.component.ts: 
add import
`import * as moment from 'moment/moment';` 
in ngOnInit method add momentjs usage:
`var date = moment(new Date()).format();`
4) run 'npm start'
5) try to open 'home.component.ts' in chrome devtools:
<img alt="screenshot" src="http://i66.tinypic.com/jrqy3o.png"/>
home.component.ts contains main.browser.ts

Any idea how to fix? Maybe it's momentjs problem, or webpack config?

- Angular version: 2.0.0-rc.1
- Browser: Chrome 51

**Comment by holiber** [comment]
import with 'const moment = require('moment/moment')' also no helps

**Comment by gdi2290** [comment]
can you set
`devtool: 'cheap-module-source-map',`
to
`devtool: 'source-map',`
in 
`webpack.dev.js`
https://github.com/AngularClass/angular2-webpack-starter/blob/master/config/webpack.dev.js#L53

**Comment by holiber** [comment]
@gdi2290 with `devtool: 'source-map'` now I got error in browser console
`Failed to parse SourceMap: http://localhost:3000/main.map`

[main.map.txt](https://github.com/AngularClass/angular2-webpack-starter/files/314938/main.map.txt)

There is an opinion, that this problem caused with some localization characters in map file

**Comment by gdi2290** [comment]
can you add moment to be ignored
`helpers.root('node_modules/moment')`
https://github.com/AngularClass/angular2-webpack-starter/blob/4a07eef656df71c8fc48d125f7b6a670a1e96046/config/webpack.common.js#L120...L124

**Comment by holiber** [comment]
@gdi2290 with 'node_modules/moment' in source-map-loader excludes also no effect. Furthermore, moment definitions still present in main.map file.

**Comment by gdi2290** [comment]
do you have [Disable Cache] on? I can't reproduce it
<img width="694" alt="screen shot 2016-06-15 at 9 34 47 am" src="https://cloud.githubusercontent.com/assets/1016365/16088535/6c28e3c2-32dc-11e6-8109-fa39b715af3c.png">


<img width="1192" alt="screen shot 2016-06-15 at 9 35 21 am" src="https://cloud.githubusercontent.com/assets/1016365/16088553/853ee5e6-32dc-11e6-8eff-688a4e499c80.png">

**Comment by holiber** [comment]
Yes, my browser cache was disabled. So, after few experiments I found, what it's google chrome  v51.0 problem. On chrome "canary" all source maps are valid. @gdi2290, thanks for your answer!

**Comment by holiber** [comment]
But it's still strange what `helpers.root('node_modules/moment')` in sourcemap-loader excludes has no effect =/

**Comment by yangmillstheory** [comment]
@holiber how did you find out that this is a Chrome 51 problem? How did you fix it?

Using `git bisect` today, I found out that the introduction of `momentjs` into our builds broke source maps on Chrome Version 51.0.2704.103 (64-bit).

Webpack config has `devtool: 'cheap-module-source-map'`.

A fix for us was to include `new webpack.ContextReplacementPlugin(/moment[\/\\]locale$/, /en-us/)` in the `plugins` array in our Webpack plugins list. 

Ping @lanceharper @ccastarivale; this happened in https://github.com/trueprint/arivale-coach-client/commit/37b7a12b54e4068613b5d487c6cb12bda7a77823.

**Comment by holiber** [comment]
@yangmillstheory, I installed "Chome Canary" - version of Google Chrome that contains all last changes and bugfixes. Canary Chrome has no problems with sourcemaps. I don't know how to fix it in Chrome 51.0.
