### ISSUE TITLE
awesome-typescript-loader 1.0.0 broke the tests

### ISSUE THREAD

**Issue by lpalli** [AngularClass/angular2-webpack-starter#687]
* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**

This [commit](https://github.com/AngularClass/angular2-webpack-starter/commit/8bbf0447c193172b48e270ab242efaf71e75d1de) brake the tests.

* **What is the current behavior?**
If you run `npm test` a lot of logs are reported (see on the bottom), the problem is related to the `awesome-typescript-loader` update from `"~0.17.0"` to `"^1.0.0"`, going back to `"~0.17.0"` seems to correct the problem.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 

Just run `npm test`.

* **What is the expected behavior?**

The tests must run normally.

* **What is the motivation / use case for changing the behavior?**

Be able to run tests.

* **Please tell us about your environment:**

- Angular version: 2.0.0-rc.1
- Browser: not relevant

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

    ...
    START:
    Error: Unknown file /Users/luca/Git/angular2-webpack-starter/src/app/home/home.component.ts Error: Unknown file /Users/luca/Git/angular2-webpack-starter/src/app/home/home.component.ts
        at State.fastEmit (/Users/luca/Git/angular2-webpack-starter/node_modules/awesome-typescript-loader/dist.babel/host.js:300:23)
    ...

The full logs:
[logs.txt](https://github.com/AngularClass/angular2-webpack-starter/files/312016/logs.txt)

**Comment by oryam** [comment]
+1 same for me
It was fine on May-31

**Comment by abdulhaq-e** [comment]
It works fine for me. There were errors at the beginning but it then continued normally. What really broke the tests for me is the following line in `package.json`:

> "pretest": "npm run lint",

Running the linter this way (or manually using `npm run lint`) brakes the tests even though it runs fine when `karma` runs it.

**Comment by iomgi** [comment]
Same problem here.

**Comment by appssunset** [comment]
+1

Going back to "~0.17.0" solved the problem.

**Comment by gdi2290** [comment]
thanks, reverted to 0.17.0 until it's fixed https://github.com/AngularClass/angular2-webpack-starter/commit/4d7a9838677401996c195ae09d95831d213c1316
