### ISSUE TITLE
how to remove the random attributes added on the components template?

### ISSUE THREAD

**Issue by qk44077907** [AngularClass/angular2-webpack-starter#690]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**
the rendered html of the components is auto attached some attributes like "_ngcontent-xxx-x",I guess this is to achieve the scoped css because my css seletor is also compiled to something like my-component[_ngcontent-xxx-x]{......}.However i don't like this way.how can i turn off this feature?

**Comment by gdi2290** [comment]
add this to your component metadata
`encapsulation: ViewEncapsulation.None,`
thanks

**Comment by gaurav150493** [comment]
According to an article `ViewEncapsulation.None` removes encapsulation to any css style. By any chance will it effect performance?
