### ISSUE TITLE
Typings install issue

### ISSUE THREAD

**Issue by wizjack** [AngularClass/angular2-webpack-starter#691]
Installing node packages freezes after npm run typings --install > typings "install"

I've node version 5.4.1 with npm version 3.3.12. If I run the application it stops with an error 

error in [default] app.component.ts, cannot find name require. 
I'm using the zip downloaded from the repo.

**Comment by gdi2290** [comment]
are you on windows?
`npm install typings -g`
and
`typings install`

**Comment by wizjack** [comment]
I already have typings in the global but I did it again still not working.

Typings version is 1.1.0 and yes I'm on windows 10.

**Comment by ebeal** [comment]
I've found issues with the current version of typings on windows, try downgrading to 0.8.1

**Comment by gdi2290** [comment]
cc @blakeembrey

**Comment by blakeembrey** [comment]
What's the issue? Feel free to open an issue on Typings with a full description, but all tests for Typings Core are currently passing on Windows.

**Comment by wizjack** [comment]
Though I'm not a wiz at this so please bear with me. As far as my guess goes as I'm not able to install necessary type definitions or typings through typings: the compiler is complaining while running the application which it should.

For example https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/requirejs/require.d.ts file wasn't downloaded, now as I add it manually the require errors are gone! If this helps.

**Comment by wizjack** [comment]
@ebeal Thanks for the suggestion :) but I think there are some breaking changes with that version, so I'd want to defer downgrading for now.

**Comment by blakeembrey** [comment]
@wizjack The `require` keyword should be coming from `node.d.ts` - the `require.d.ts` file you're using is a definition for RequireJS.
