### ISSUE TITLE
Docker: Cannot find name 'Promise', 'Set', 'Map', ...

### ISSUE THREAD

**Issue by smith64fx** [AngularClass/angular2-webpack-starter#695]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
When I try to use docker, to deploy I get lots of errors.
```
[default] /site/node_modules/@angular/common/src/directives/ng_class.d.ts:72:35
    Cannot find name 'Set'.
[default] /site/node_modules/@angular/common/src/facade/async.d.ts:27:33
    Cannot find name 'Promise'.
[default] /site/node_modules/@angular/common/src/facade/async.d.ts:28:45
    Cannot find name 'Promise'.
[default] /site/node_modules/@angular/common/src/facade/lang.d.ts:4:17
    Cannot find name 'Map'.
[default] /site/node_modules/@angular/common/src/facade/lang.d.ts:5:17
    Cannot find name 'Set'.
[default] /site/node_modules/@angular/common/src/facade/lang.d.ts:70:59
    Cannot find name 'Map'.
[default] /site/node_modules/@angular/common/src/facade/promise.d.ts:2:14
    Cannot find name 'Promise'.
[default] /site/node_modules/@angular/common/src/facade/promise.d.ts:8:32
    Cannot find name 'Promise'.
[default] /site/node_modules/@angular/common/src/facade/promise.d.ts:9:38
    Cannot find name 'Promise'.
[default] /site/node_modules/@angular/common/src/facade/promise.d.ts:10:35
    Cannot find name 'Promise'.
[default] /site/node_modules/@angular/common/src/facade/promise.d.ts:10:93
    Cannot find name 'Promise'.
[default] /site/node_modules/@angular/common/src/facade/promise.d.ts:11:34
    Cannot find name 'Promise'.
[default] /site/node_modules/@angular/common/src/facade/promise.d.ts:11:50
    Cannot find name 'Promise'.
[default] /site/node_modules/@angular/common/src/facade/promise.d.ts:12:32
    Cannot find name 'Promise'.
[default] /site/node_modules/@angular/common/src/facade/promise.d.ts:12:149
    Cannot find name 'Promise'.
[default] /site/node_modules/@angular/common/src/facade/promise.d.ts:13:43
    Cannot find name 'Promise'.
[default] /site/node_modules/@angular/common/src/forms/directives/select_control_value_accessor.d.ts:18:17
    Cannot find name 'Map'.
[default] /site/node_modules/@angular/common/src/pipes/async_pipe.d.ts:29:29
    Cannot find name 'Promise'.
[default] /site/node_modules/@angular/common/src/pipes/async_pipe.d.ts:35:38
    Cannot find name 'Promise'.
```
And so on....

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
```
git clone https://github.com/AngularClass/angular2-webpack-starter/
cd angular2-webpack-starter
docker run -it -v "`pwd`:/site" schmidigital/angular2-webpack-docker bash
```
(We are now inside Docker Container)
```
cd /site
npm install
npm start
```
Here you get the errors!

* **What is the expected behavior?**
Usually, Webpack should not throw errors! Tested on local environment on linux/mac

* **What is the motivation / use case for changing the behavior?**
Making Angular 2 Production Ready with Docker!

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by smith64fx** [comment]
I found a solution!
```
typings install
```

And then adding this to the src/main.browser.ts file:
/// <reference path="../typings/index.d.ts" />

Can we merge this to the master?

**Comment by gdi2290** [comment]
thanks, I added this to the read me via https://github.com/AngularClass/angular2-webpack-starter/commit/4e3b87d71eac2468b66d6bf93ce7ddb375fcca24

**Comment by vivekwisdom** [comment]
In the latest version of the starter package changing **tsconfig.js**

`"target": "es6",`

Solves the issue.
