### ISSUE TITLE
Upgrade the router from router-deprecated to router

### ISSUE THREAD

**Issue by itrethan** [AngularClass/angular2-webpack-starter#704]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[ ] bug report
[ X] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Feature

**Comment by michabbb** [comment]
I tried latest alpha of the router, but never got it running with the webpack :-( would be happy to see an example....

**Comment by asadsahi** [comment]
Check [this](https://github.com/asadsahi/AspNetCoreSpa) out:

Note: this is a .net project, but if you switch to new-router branch i have the new router implemented.

Still looking into implementing lazy loading though.

**Comment by gdi2290** [comment]
the repo has been updated including lazy routes

**Comment by asadsahi** [comment]
Good job @gdi2290 :+1: 

Question about lazy loading implemenation. What is the role of provideWebpack function? Cannot find any documentation around how to implement lazy loadin with new router. Can you point to any resource you come across?

Thanks

**Comment by gdi2290** [comment]
I created `provideWebpack` as a way to do lazy loading for webpack as it's a `CompoentResolver`. It's more of a workaround until the router allows for a function rather than a string for the component type in route config

**Comment by TobiasKrogh** [comment]
@gdi2290 Hi, great work 👍

I saw that you added the routes using `provideRouter`...

```
  provideRouter(routes),
  provideWebpack(asyncRoutes),
```

I am wondering though how to use this for sub routes or whether it is currently possible at all as with router-deprecated the application RouteConfig could be applied via decorator to the main component and using `/...` for one route marks this route as parent for sub routes being applied to another component adding its own RouteConfig

Do you see any way to do this? Or maybe this is not intended (yet) with the new router? Can you give me some advice?

Cheers

**Comment by itrethan** [comment]
I think it's not fully closed yet, the material 2 repo still use router
