### ISSUE TITLE
Android Browser: has no method 'animationRequestFrame'

### ISSUE THREAD

**Issue by smith64fx** [AngularClass/angular2-webpack-starter#706]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
Android Browser and IE 9 throw error '...has no method 'animationRequestFrame'
![image](https://cloud.githubusercontent.com/assets/3246782/16151740/efe0d8b4-349e-11e6-99b2-afcafd3d7fb7.png)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Just run the Angular 2 Webpack Starter on the native Android Browser on Lollipop

* **What is the expected behavior?**
Should run

* **What is the motivation / use case for changing the behavior?**
Customer are criticizing quality of the WebApp because it's not running on their devices.

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by smith64fx** [comment]
I addded a solution for this.

Add this to the index.html
```
<script src="https://npmcdn.com/angular2@2.0.0-beta.17/es6/dev/src/testing/shims_for_IE.js"></script>
```

**Comment by gdi2290** [comment]
thanks, I left `ie-shim` commented out for this reason

**Comment by smith64fx** [comment]
Where can I find it?
Greets
Smith

Von meinem iPhone gesendet

**Comment by gdi2290** [comment]
in polyfills commented out
https://github.com/AngularClass/angular2-webpack-starter/blob/master/src/polyfills.browser.ts#L3

**Comment by smith64fx** [comment]
@gdi2290 thanks bro!
