### ISSUE TITLE
@types declaration files

### ISSUE THREAD

**Issue by scttcper** [AngularClass/angular2-webpack-starter#708]
* **I'm submitting a ...**
[ ] bug report
[X] feature request
[X] question about the decisions made in the repository

Would like to use typescript "official" types on npm as seen in the recent blog https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/ 

I've gotten it working (removed all typings) with:
```
"@types/core-js": "^0.9.22-alpha",
"@types/jasmine": "^2.2.22-alpha",
"@types/node": "^4.0.22-alpha",
"@types/protractor": "^1.5.11-alpha",
"@types/selenium-webdriver": "^2.44.20-alpha",
"@types/source-map": "^0.1.20-alpha",
"@types/uglify-js": "^2.0.21-alpha",
"@types/webpack": "^1.12.22-alpha",

typescript update:
"typescript": "^1.9.0-dev.20160617-1.0",
```

except i had to set my tsconfg target to es6 to get rid of errors like `Cannot find name 'Promise'` coming from inside @angular libraries. 
```
"compilerOptions": {
    "target": "es6",
}
```

Was wondering if anyone else here has tried these out and had success with es5 and if this repository planned on changing over.

Edit: this repo would probably need @types/hammerjs too. I don't happen to use it.

Edit 2: I've added the following and no longer get errors.
packages
```
"@types/es6-shim": "0.0.22-alpha",
"@types/es6-promise": "0.0.22-alpha",
```
tsconfig (note the types array)
```
"compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "sourceMap": true,
    "noEmitHelpers": true,
    "types": ["es6-shim"]
  },
```

I think the question still stands on if this repo will switch. I think using only npm is nice.

**Comment by gdi2290** [comment]
I'll switch when typescript 2.0 is released
