### ISSUE TITLE
webpack plugin for html changed

### ISSUE THREAD

**Issue by anant-singh** [AngularClass/angular2-webpack-starter#710]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[ * ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
I want to report a bug

* **What is the current behavior?**
After cloning the repo once you do `npm install` and then `npm start` it will throw an error looking for `webpack-shell-plugin`.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

See above. In short `clone -> npm install -> npm start` and it will throw an error.

* **What is the expected behavior?**

It should not throw an error. Either the webpack-shell-plugin be changed to original or just added as dependency.

* **What is the motivation / use case for changing the behavior?**

It breaks the current app.

* **Please tell us about your environment:**

- Angular version: 2.0.0-rc.1
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by mclouvem** [comment]
I`ve got same issue here. After install webpack-shell-plugin and run "npm run server:dev:hmr" I visit localhost:3000 and I get only a text "<% if (webpackConfig.htmlElements.headTags) { %> <%= webpackConfig.htmlElements.headTags %> <% } %> Loading... <% if (webpackConfig.metadata.isDevServer) { %> <% } %>"

**Comment by gdi2290** [comment]
thanks, should be fixed via https://github.com/AngularClass/angular2-webpack-starter/commit/a24dd05ea513025972c7dc2834453814ff2359e3
