### ISSUE TITLE
Double dependence on istanbul-instrumenter-loader in package.json

### ISSUE THREAD

**Issue by lpalli** [AngularClass/angular2-webpack-starter#712]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**

Error when checking the package.json file.

* **What is the current behavior?**

The package.json file contain 2 references to `"istanbul-instrumenter-loader": "^0.2.0"` starting from this [commit](https://github.com/AngularClass/angular2-webpack-starter/commit/f1c4ce76dc48f56d098549883bb1d494567d80f6).

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

Just fetch the last master branch.

* **What is the expected behavior?**

Remove one of the references.

* **What is the motivation / use case for changing the behavior?**

Have a correct pakage.json file.

* **Please tell us about your environment:**

Not relevant.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by gdi2290** [comment]
can you create a PR to fix this?

**Comment by kulshekhar** [comment]
created PR #715

**Comment by Luchillo** [comment]
This dependency is fixed with the PR, can close this issue.

**Comment by gdi2290** [comment]
thanks
