### ISSUE TITLE
Error on npm install:  'Unable to read typings for "angular2-beta-to-rc-alias"

### ISSUE THREAD

**Issue by doug-wood** [AngularClass/angular2-webpack-starter#716]
running node version 6.2.2,  on WIndows 10
after cloning repo:
1) npm install -g typings webpack-dev-server rimraf webpack
2) npm install , I got the error during this:

```
typings ERR! message Unable to read typings for "angular2-beta-to-rc-alias". You should check the entry paths in "typings.d.ts" are up to date
typings ERR! caused by ENOENT: no such file or directory, open 'C:\Users\me\Dev\angular2-webpack-starter\node_modules\@angularclass\angular2-beta-to-rc-alias\s
rc\beta-17\typings.d.ts'
```

Any ideas ?

**Comment by datatypevoid** [comment]
Same error after pulling the latest changes with `RC.3`. After running `npm run clean` and `npm i`, I get: 

```
ERROR in [default] D:/Sites/vulgar/typings/globals/angular2-beta-to-rc-alias/index.d.ts:20:16
Cannot find module '@angular/router-deprecated'.
```

**Comment by gdi2290** [comment]
can you remove it
https://github.com/AngularClass/angular2-webpack-starter/commit/8e93ae998e76efbd7166e0b0c531396098bd4e34
it was only there to help with 3rd party modules still using the beta17 apis

**Comment by datatypevoid** [comment]
Yeah that fixed it, thanks for your incredible work as always @gdi2290 :+1:

**Comment by gdi2290** [comment]
also remove it from typings https://github.com/AngularClass/angular2-webpack-starter/commit/918a2c912533b98da9bdc17c906ff2a96189aaab

**Comment by doug-wood** [comment]
thanks ! worked
