### ISSUE TITLE
Uncaught TypeError: o.HmrState is not a function

### ISSUE THREAD

**Issue by ayubali** [AngularClass/angular2-webpack-starter#717]
when i build this application for prod mode
 **npm run build:prod**  is executed without error
then i run command "npm run server:prod" 
it is alo executed with out error. but in broser console it is showing 
app.service.ts:7Uncaught TypeError: o.HmrState is not a function

**Comment by gdi2290** [comment]
what version of angular/angular2-hmr do you have or did you download a fresh version of the repo

**Comment by unsafecode** [comment]
+1 (cloned the repo this evening)

**Comment by gdi2290** [comment]
is everyone using npm 3?

**Comment by gdi2290** [comment]
or on windows

**Comment by gdi2290** [comment]
can you revert this change be keep the angular2-hmr version
https://github.com/AngularClass/angular2-webpack-starter/commit/24a19a9f05b1840a28cfa5a013e2e9d254f4f43f#diff-d1535ca6497b532e66b6b853f99dc1f7L174


from
helpers.root('node_modules/angular2-hmr/prod.js')
to
helpers.root('config/modules/angular2-hmr-prod.js')

**Comment by unsafecode** [comment]
@gdi2290 Works now (npm 3.8.7 on Windows)

**Comment by gdi2290** [comment]
kk done via https://github.com/AngularClass/angular2-webpack-starter/commit/3ddddee3923f0b2a473bdd7364ec639a99c22f7b
