### ISSUE TITLE
Karma does not reload files after removing file Glob

### ISSUE THREAD

**Issue by abdulhaq-e** [AngularClass/angular2-webpack-starter#718]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[X ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**

Bug. 

* **What is the current behavior?**

I'm using Karma with the `singleRun` option set to `false` because I write the tests then reload the tab in Chrome (or I can set `autowatch` to `true`). So if I had the file with the below code (or any .ts file, spec or not):

```
it('should do simple maths', () => {
    expect(1+1).toEqual(2);
}
``` 

Then if I run Karma and edited the file (say I add more tests). The console changes (it seems that Karma picks up the file change) but when reloading the test tab the changes are not there! So if I add 100 tests to the above. Karma will only run that one test unless I close Karma and open it again.

* **What is the expected behavior?**

Before #https://github.com/AngularClass/angular2-webpack-starter/commit/8add16dd55279b358e1a54af3541e1698354d323#diff-e5e546dd2eb0351f813d63d1b39dbc48 things weren't like this. I open Karma, edit my code, give it a few milliseconds to reload the files and then refresh the web page to see the test results.

I solved this by redoing the changes made in that commit, so that `ts.config` will look similar to this:

```
   ...
  "exclude": [
    "node_modules"
  ],
  "filesGlob": [
    "./src/app/**/*.ts",
    "./src/platform/**/*.ts",
    "!./node_modules/**",
    "./src/custom-typings.d.ts",
    "./typings/index.d.ts"
  ],
 ....
```

Why was `fileGlob` removed anyway?

**Comment by abdulhaq-e** [comment]
Removing `fileGlob` has nothing to do with the problem. The issue persists even after reinserting `fileGlob`.

**Comment by abdulhaq-e** [comment]
Exact issue: https://github.com/AngularClass/angular2-webpack-starter/issues/725

**Comment by JonnyBGod** [comment]
Getting same problem.
