### ISSUE TITLE
Add support for angular-universal

### ISSUE THREAD

**Issue by sabbirrahman** [AngularClass/angular2-webpack-starter#720]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[ ] bug report
[*] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**

Feature

It would be great if you integrate angular-universal with this starter. I think everybody love server side rendering. If not possible in the master branch then try to create a separate branch like the material2 branch. Thank You.

**Comment by Marabyte** [comment]
Hi @sabbirrahman 

Check the discussion about Angular-Universal here : #576 

Cheers,
