### ISSUE TITLE
Look into DLLPlugin for our vendors. 

### ISSUE THREAD

**Issue by TheLarkInn** [AngularClass/angular2-webpack-starter#721]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[x] feature request

* **What is the current behavior?**
A bunch of our vendors stay the same, and they can contribute to longer build times. 

* **What is the expected behavior?**
Use premade Webpack DLL bundles for vendors and polyfill. This essentially would remove all the parse time from the build process. 

* **What is the motivation / use case for changing the behavior?** Since our vendor files don't typically change, and since mine, @preboot, and your webpack starters including my fork of the CLI all use the same vendors, we could have a vendor and polyfill Dll bundle that maybe we can keep in @angularclass/webpack-toolkit and keep everyone in sync with.

**Comment by gdi2290** [comment]
I also need to move hmr into toolkit. I'll add you to the repo

**Comment by TheLarkInn** [comment]
Sounds good. :shipit:
