### ISSUE TITLE
How to import from "node_modules" in sass file

### ISSUE THREAD

**Issue by MurhafSousli** [AngularClass/angular2-webpack-starter#727]
I have installed [bourbon](http://bourbon.io/) library through npm, but it's not working when I import it in my stylesheet

app.scss
```
@import "bourbon";
```
How can I add "node_modules" path to the Sass files?

**Comment by sabbirrahman** [comment]
I use less and import files from node_modules like this.

`@import "~bootstrap/less/variables";`

I guess it will work for you the same way too. Give it a try.

`@import "~bourbon";`

**Comment by Luchillo** [comment]
I have this in my config side to side with the node configs in `config/webpack.common.js`:
```js
  /**
   * Config sassLoader paths for imports from node_modules, bower components
   * and app folder.
   *
   * See: https://github.com/jtangelder/sass-loader
   */
  sassLoader: {
    includePaths: [
      'node_modules', 'bower_components', 'src', '.'
    ]
  },
  /*
   * Include polyfills or mocks for various node stuff
   * Description: Node configuration
   *
   * See: https://webpack.github.io/docs/configuration.html#node
   */
  node: {
    global: 'window',
    crypto: 'empty',
    module: false,
    clearImmediate: false,
    setImmediate: false
  }
```

Which basically tells the sass compiler to search in those paths as well for the package you're looking, however the solution @sabbirrahman should be easier to set "and i guess maybe faster since you're explicitly saying sass loader that those imports are from node_modules", here's the docs related:
https://github.com/jtangelder/sass-loader#imports

**Comment by MurhafSousli** [comment]
Thanks alot guys, @sabbirrahman's solution worked for me.

**Comment by djorborn** [comment]
for webpack 4 add this option to your sass loader

```
{
            loader: 'sass-loader',
            options: {
              "includePaths": [
                require('path').resolve(__dirname, 'node_modules')
              ]
            }
          }

**Comment by luchillo17** [comment]
As far as i know it's been decided that any path that should go to `node_modules` must be preceded by `~`.

**Comment by igimanaloto** [comment]
I prefer @djorborn's suggestion. I had to deal with a lot of ruby-sass files!

**Comment by notVitaliy** [comment]
@lnunno the `~` prefix will also reslove any aliases you may have setup in webpack, not just `node_modules`.

**Comment by randre70** [comment]
Please reopen.
See https://github.com/sass/libsass/issues/1724#issue-116571627

**Comment by farwaali8434** [comment]
> loader: 'sass-loader',
>             options: {
>               "includePaths": [
>                 require('path').resolve(__dirname, 'node_modules')
>               ]
>             }

I tried this but got an error
![image](https://user-images.githubusercontent.com/41327806/77067592-03d7a180-6a07-11ea-948d-8b71fc5c8337.png)

**Comment by drugoi** [comment]
@farwaali8434 sass-loader got new options and now you can pass `includePaths` like this:

```js
          {
            loader: 'sass-loader',
            options: {
              sassOptions: {
                includePaths: [
                  require('path').resolve(__dirname, 'node_modules')
                ]
              }
            }
          }
```

**Comment by vicnguyenqt** [comment]
> I use less and import files from node_modules like this.
> 
> `@import "~bootstrap/less/variables";`
> 
> I guess it will work for you the same way too. Give it a try.
> 
> `@import "~bourbon";`

You save my day !
