### ISSUE TITLE
vendor.....ts

### ISSUE THREAD

**Issue by q1101151** [AngularClass/angular2-webpack-starter#732]
// import 'semantic-ui/dist/semantic.min.css';
// import 'bootstrap/dist/css/bootstrap.min.css';
?????
How to Set Up

**Comment by MurhafSousli** [comment]
just add `~` to point to `node_modules` directory
```
import '~semantic-ui/dist/semantic.min.css';
import '~bootstrap/dist/css/bootstrap.min.css';
```
