### ISSUE TITLE
Remove # from the url with PathLocationStrategy

### ISSUE THREAD

**Issue by Mandersen21** [AngularClass/angular2-webpack-starter#736]
Can any tell me how I can remove the hash (#) from the URL?

Right now it looks like this: http://localhost:3000/#/home

Have tried bootstrap the APP_BASE_HREF like this:

`export function main(initialHmrState?: any): Promise<any> {

  return bootstrap(App, [
    ...PLATFORM_PROVIDERS,
    ...ENV_PROVIDERS,
    ...APP_PROVIDERS,
    ...ROUTER_PROVIDERS
    { provide: APP_BASE_HREF, useValue: '/' }
  ])
    .then(decorateComponentRef)
    .catch(err => console.error(err));

}` 

Problem here is that (ROUTER_PROVIDERS) is not available in the @angular/router, only the old angular2 router version (I'm using version - "@angular/router": "3.0.0-alpha.7",).

Have also tried putting this line of code (<base href="/">) into the index.html file. Any help?

**Comment by gdi2290** [comment]
remove this line
https://github.com/AngularClass/angular2-webpack-starter/blob/master/src/platform/browser-providers.ts#L35

**Comment by Mandersen21** [comment]
Thanks man.

**Comment by gdi2290** [comment]
no problem, feel free to open another issue if you have a question or problem
