### ISSUE TITLE
Angular2 start page taking approximately 10 seconds in mobile phones and 3 to 4 seconds in computer browser.

### ISSUE THREAD

**Issue by Sangamesha** [AngularClass/angular2-webpack-starter#737]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

I'm submitting a 
feature request

I am using node.js 5.12.0 and NPM 3.8.6

When i open my site in System browser its taking 3 to 4 seconds to load/open.
Same site if i open in mobile phones its taking 8 to 10 seconds.
I want to reduce the time taken by load the app second time. 2nd time files are serving from cache. 
If all files serving from cache also taking same time to load page. 
I have used webpack to remove chunk. so now js file only 200kb(zip).

Most of the time user open site in mobile phones with 2g/3g speed. so user feel that site is taking more time to open, so in mobile phones site should open in max 3-4 seconds.

site link:- staging.aakashitutor.com

- Angular version: 2.0.0-rc.3
- Browser: Google chrome 51.0.2704.103 m (64-bit), Mobile latest chrome browser

**Comment by gdi2290** [comment]
you have a ton of assets on the page that is the real problem here.  if you remove the listener that waits for the dom to be ready before bootstraping then that would help you for now
https://github.com/AngularClass/angular2-webpack-starter/blob/master/src/main.browser.ts#L58
I also can't login and there's a server error

**Comment by Sangamesha** [comment]
gdi2290 thanks for the reply,
I did this one. But there is not major difference gdi2290.

You can login with these credentials here.

http://staging.aakashitutor.com/home

User name:-  sangamesh@tribytetech.com
Password:- test

**Comment by samvloeberghs** [comment]
it's quite fast after the initial page load here ..
![pl](https://cloud.githubusercontent.com/assets/231618/16519517/cde91eb0-3f89-11e6-8852-7b5ab74a97c3.png)

**Comment by Sangamesha** [comment]
Its working faster in system browser samvloeberghs, its taking 15-18 seconds in android 4.x cellphones and 10 seconds in 10 inch tablets.

My motto is to improve 1st page loading time in smaller devices.

**Comment by gdi2290** [comment]
you also have bootstrap and jQuery loading. The app itself isn't a single page app since you click on a link and it goes straight to the server. What you're looking for is angular universal. Here's a blog post on it http://blog.angular-university.io/angular-2-universal-meet-the-internet-of-the-future-seo-friendly-single-page-web-apps/

**Comment by FatihHyusein** [comment]
Any updates about angular 2 initial loading on mobile devices?

#samvloeberghs - 3/4 seconds is for desktop, but not mobile devices.
From nexus 4 for example (android 5.1.1, 2gb ram 1.5 quad cpu, wireless network) initial loading is about 14 seconds  - for the mentioned website (http://staging.aakashitutor.com)

**Comment by d3viant0ne** [comment]
@FatihHyusein - There are more reasons why I can count why mobile performance would be bad, none of them have anything to do with the starter. Check you payload, check if something is blocking the main thread, yada yada yada.

This really isn't the forum to discuss mobile performance as it's almost entirely specific to the implementation.

**Comment by gomesNazareth** [comment]
my app too is very slow on android  devices .Is there  any other  forum to discuss mobile performance  for angular2

**Comment by devcer** [comment]
Did anyone found about fixing this? I was able to run a prod build in Android webview in 4 seconds but want to get it further down to <1sec. it takes 800ms in desktop browser anyway.
