### ISSUE TITLE
Async child routing is not working for any other child route than default route

### ISSUE THREAD

**Issue by dhrumil4u360** [AngularClass/angular2-webpack-starter#738]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)
- **I'm submitting a ...**
  [X] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
- **Do you want to request a _feature_ or report a _bug_?**

Reporting a bug
- **What is the current behavior?**

If we add another child under "+detail" dynamic route, we get "Cannot find primary outlet to " error when access through link and 404 if accessing directly.
- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 

Add another child component under "+detail" and try routing to it.
- **What is the expected behavior?**

It should load any other child than default child route.
- **What is the motivation / use case for changing the behavior?**

General support for child routing through webpack.
- **Please tell us about your environment:**

I am using latest seed version as of today.
- Angular version: 2.0.0-rc.3
- Browser: [all ]
- **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Not applicable.

**Comment by gdi2290** [comment]
can you provide a link to repo that reproduces the problem?

**Comment by dhrumil4u360** [comment]
Sure. I just forked today's version and added one simple "child2" route to "Detail" route. Rest of the source is as clean as current starter pack version.

https://github.com/dhrumil4u360/angular2-webpack-starter

Please run this and go to "detail" route. You will see link to "Child2" route there and issue can be reproduced when you click on it.

**Comment by phiphou** [comment]
Don't you simply forget to add a second  `<router-outlet>` in the `Detail` comp? 

```
 @Component({
  selector: 'detail',
  directives: [ROUTER_DIRECTIVES],
  template: `
    <h1>Hello from Detail</h1>
    This is default chld page of Detail. Please click on this link to go to another child:
     <span>
        <a [routerLink]="['./child2']">
          Child2
        </a>
      </span>
      <router-outlet></router-outlet>
  `
}) 
```

Try this and let us know ;)

**Comment by gdi2290** [comment]
I checked it out. I think this is a problem with the router or the way that I'm updating the route config

**Comment by dhrumil4u360** [comment]
@phiphou  Adding `<router-outlet>` will avoid  exception but that is something we don't expect. We want to keep it like 

Detail
|--Child1 (consider it as default component which is detail.component)
|--Child2

So main route will have 2 children. In that case, `<router-outlet>` should be there in parent only. If we put it in "detail.component.ts", structure will result in something like this :

Detail
|--Child1 
       |--Child2

@gdi2290 Thank you. Looking forward to hear updates.

**Comment by gdi2290** [comment]
I have a current workaround until it's fixed https://github.com/AngularClass/angular2-webpack-starter/commit/d4ecb3f2214e8725e708c65b6c1d503e4b311ce4

**Comment by phiphou** [comment]
@dhrumil4u360 Sorry for the misunderstood, @gdi2290 's workaround should work.

**Comment by dhrumil4u360** [comment]
@gdi2290 Thank you for work around. I am able to integrate work around successfully. Looking forward to permanent fix.  May be, if possible, something in which we don't have to list all component level child routes at app.routes level. 

Thanks in advance :+1:

**Comment by gdi2290** [comment]
thanks, the permanent fix will be rc.5 with AppModule

**Comment by shlomiassaf** [comment]
I think this is obsolete...

re-open if not.
