### ISSUE TITLE
The example of resolved data route break the test

### ISSUE THREAD

**Issue by lpalli** [AngularClass/angular2-webpack-starter#743]
* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**

The "example of resolved data route" [commit](https://github.com/AngularClass/angular2-webpack-starter/commit/4234996f3ac3dbe1c838f23b18cf59a48f845947) break the test

* **What is the current behavior?**

Running tests using `npm test` fail on the tests `should log ngOnInit` from the `about.spec.ts` file.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 

Just run `npm test` on master branch (commit [4234996f](https://github.com/AngularClass/angular2-webpack-starter/commit/4234996f3ac3dbe1c838f23b18cf59a48f845947) or later).

* **What is the expected behavior?**

All the 8 tests run correctly.

* **What is the motivation / use case for changing the behavior?**

To have a full running tests implementation.

* **Please tell us about your environment:**

- Angular version: 2.0.0-rc.4
- Browser: not relevant

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

`FAILED TESTS:`
`  About`
`    × should log ngOnInit`
`      Chrome 51.0.2704 (Windows 10 0.0.0)`
`    Error: No provider for ActivatedRoute! (About -> ActivatedRoute)`
`    Error: DI Exception`
`        at NoProviderError.BaseException [as constructor] (C:/Projects/angular2-webpack-starter/config/spec-bundle.js:27055:24 <- webpack:///~/@angular/core/src/facade/exceptions.js:27:0)`

See the error log file for a more complete version: [error.txt](https://github.com/AngularClass/angular2-webpack-starter/files/343214/error.txt)

**Comment by gdi2290** [comment]
thanks, fixed via https://github.com/AngularClass/angular2-webpack-starter/commit/b305c9a8071465ee0817a59093c9f73fd1cc7278
