### ISSUE TITLE
Bootstrap and Slack comunity

### ISSUE THREAD

**Issue by AndersonDev** [AngularClass/angular2-webpack-starter#746]
Hi guys. Sory for support question here but slack and registration on site not working.

I whant to use **scss**, **Bootstrap 4** (**WITHOUT** _js_ components and _jquery_) and custom **fonts**.

Here is guide to do add Bootstrap and I tried it. However I had an errors:

![image](https://cloud.githubusercontent.com/assets/6890368/16541995/e9526eac-409e-11e6-814a-facda64ecb15.png)

![image](https://cloud.githubusercontent.com/assets/6890368/16542504/a9bc1a1c-40b3-11e6-82cd-8294d3e160c8.png)

I think they caused by this code:

```
{ test: /\.scss$/, loaders: ['style', 'css', 'postcss', 'sass'] },
{
    test: /\.scss$/,
    exclude: /node_modules/,
    loaders: ['raw-loader', 'sass-loader'] // sass-loader not scss-loader
},
{ test: /\.(woff2?|ttf|eot|svg)$/, loader: 'url?limit=10000' }
```

How to make this right? My old approach was by adding bootstrap-min.css to my app and all.

Thanks!!!

**Comment by ebeal** [comment]
Looks like the css loaders need to be installed. Either install them with npm manually or update your package.json to include them and run an npm install. This should fix this issue, however if you don't have a reason to use a non minified, non css version of bootstrap don't (you can still use custom fonts and no js). If installing the loaders fixes this issue please close this. Thanks :)

**Comment by AndersonDev** [comment]
@ebeal I instaled them firstly) 
You think it will be ok to import bootstrap .css in vendors? Is it "Best Practice"?

**Comment by ebeal** [comment]
It looks like it may be an issue with the current version of the sass-loader [#254](https://github.com/jtangelder/sass-loader/issues/254) Although the error is not exactly the same the setup sounds similar. Are you using components from bootstrap? Are you talking about the vendors.ts?
This issue [#7](https://github.com/bholloway/resolve-url-loader/issues/7) is related.

**Comment by AndersonDev** [comment]
@ebeal I do the steps 1 to 1 as in guide. I have Import in vendor. Tomorrow I will include min.css and all. I just want to now is it necessary to worry about that?
