### ISSUE TITLE
import all scss file doesn't work.

### ISSUE THREAD

**Issue by georgi-kovachev** [AngularClass/angular2-webpack-starter#749]
I cloned this repository and I update webpack.common.js to include scss file.

{
     test: /\.scss$/,
     exclude: /node_modules/,
     loaders: ['raw-loader', 'sass-loader'] // sass-loader not scss-loader
}

And I imported file 
@import "../../node_modules/@angular2-material/core/style/*";

And i have this error.
Module build failed: 
@import "../../node_modules/@angular2-material/core/style/*";
^
      File to import not found or unreadable: ../../node_modules/@angular2-material/core/style/*
Parent style sheet: /src/app/_variables.scss

But when I change to one scss file it works
@import "../../node_modules/@angular2-material/core/style/variables";

**Comment by IAMtheIAM** [comment]
In your loader it says `exclude: /node_modules/` - but then you are trying to import directly from `node_modules` - that could be your problem. Try removing the exclude and see if it works.

**Comment by IAMtheIAM** [comment]
Also, that is not the correct way to use angular2-material. You should be importing those files into your `vendor.ts` file like this

```
// Angular 2 Material 2
require('@angular2-material/button');
require('@angular2-material/card');
require('@angular2-material/checkbox');
require('@angular2-material/sidenav');
require('@angular2-material/input');
require('@angular2-material/list');
require('@angular2-material/radio');
require('@angular2-material/progress-bar');
require('@angular2-material/progress-circle');
require('@angular2-material/toolbar');
```

**Comment by georgi-kovachev** [comment]
it is using import in material2 branch and I think import is fine.
https://github.com/AngularClass/angular2-webpack-starter/blob/material2/src/vendor.browser.ts

**Comment by georgi-kovachev** [comment]
Any idea?
And why <md-content> is not using predefined css settings from node_modules/@angular2-material but we should define it in app.scss file?

**Comment by ebeal** [comment]
What exactly are you trying to do?
