### ISSUE TITLE
async router bug: async route with multiple children throws exception if you page load with full url path

### ISSUE THREAD

**Issue by ncfx** [AngularClass/angular2-webpack-starter#750]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
If you have an async route that has multiple children, and you attempt to load the page with the full URL (i.e. www.mydomain.com/route/childroute/params), an unhandled exception will be thrown for "ChildRoute component cannot be found". Execution continues, but it looks like the router reverts to the base href /.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**
Router should not throw exception and a full URL path with child routes should be supported.

* **What is the motivation / use case for changing the behavior?**
This is a standard feature of any router

* **Please tell us about your environment:**
June 30th build of angular2-webpack-starter. Running on mac, Chrome 51.0.2704.106

- Angular version: 2.0.0-beta.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by JohannesRudolph** [comment]
same as #751 - should this be closed?

**Comment by gdi2290** [comment]
yup, same as https://github.com/AngularClass/angular2-webpack-starter/issues/751
