### ISSUE TITLE
CSS and SCSS

### ISSUE THREAD

**Issue by AndersonDev** [AngularClass/angular2-webpack-starter#754]
Hi guys. Sory for second support theme but I don't now where to write.

I need to use CSS and SCSS in my Angular 2 components. I used [https://github.com/preboot/angular2-webpack](url) before. And it was simple.

I tried to follow several guides and comments in this repo. I aded different loaders and postCss. Hovewer I have errors( 

May you help my with this? Thanks!

**Comment by mhheise** [comment]
Would you mind posting an example of your relevant webpack configs and the errors that you are seeing? Which loaders and postcss plugins are you trying to use?

**Comment by ebeal** [comment]
I'm closing this, please re-open if you would like to add additional information
