### ISSUE TITLE
Integrating lodash

### ISSUE THREAD

**Issue by zigzag95** [AngularClass/angular2-webpack-starter#758]
Can someone help me with an example how to add lodash
I did this
` typings install lodash --save --ambiant`

but 
` import * as _ from 'lodash'`
doesn't work

**Comment by samvloeberghs** [comment]
works fine here. Only installing the typings will not work, you need the library as well:

```
npm install --save lodash
typings install lodash --save --ambiant
import * as _ from 'lodash'
```

**Comment by zigzag95** [comment]
Thanks

**Comment by StefH** [comment]
`typings install lodash --save --ambient`
`typings ERR! deprecated The "ambient" flag is deprecated. Please use "global" instead`

?

**Comment by brud** [comment]
`npm i @types/lodash --save-dev`
`npm i lodash --save`

when i import lodash in my code
`import * as _ from "lodash";`

`_` is empty - what i'm doing wrong?
