### ISSUE TITLE
Make code coverage for unit tests

### ISSUE THREAD

**Issue by tamascsaba** [AngularClass/angular2-webpack-starter#76]
I try https://github.com/deepsweet/istanbul-instrumenter-loader, but not useful for typescript :(

**Comment by gdi2290** [comment]
If you can get code coverage working in a PR I'll merge it

**Comment by gdi2290** [comment]
done via https://github.com/AngularClass/angular2-webpack-starter/compare/12e6e1fbf82232daed7f584938f0f597fe81144e...master
