### ISSUE TITLE
For consideration: easy-webpack

### ISSUE THREAD

**Issue by niieani** [AngularClass/angular2-webpack-starter#761]
* **I'm submitting a feature request**

I'm the author of [Easy Webpack](https://github.com/easy-webpack/core), which is now used as the default configurator by the official Webpack starter kit for the Aurelia Framework. 
If you like the concept, it could be used to clean-up the Webpack config files used by the Webpack starter and possibly delegate parts of the config to a separate package that could be npm updated by your users. Feel free to consult [the docs](https://github.com/easy-webpack/core) and decide on your own if this is something you would be interested in using.

Awesome starter kit, btw! 👍

**Comment by IAMtheIAM** [comment]
Very cool man, thanks. I'll definitely check this out, because learning webpack was quite the chore. Although, now that my configs are solid and stable, I'm curious how it can be of benefit. It does seem to have a bit of its own learning curve, but its flexibility looks quite nice.

**Comment by gdi2290** [comment]
While this seems like a good idea I don't think angular developers who are new to having a build step would like to learn yet another abstraction. With easy-webpack you must know about webpack for it to be easy otherwise it's just magic. With webpack it's magic but there's docs and lots of online resources. You should also update your examples to es6 for webpack 2.
```es6
import configEnvProduction from '@easy-webpack/config-env-production');
import configAngular2 from '@easy-webpack/config-aurelia');
import configTypescript from '@easy-webpack/config-typescript');
import configHtml from '@easy-webpack/config-html');
// etc

export default function webpackConfig (options) {
  return generateConfig(
    configEnvProduction({ compress: true }),
    configAngular2({ title: 'My Awesome Website' }),
    configTypescript(),
    configHtml()
    // etc
  );
}

```
If you like to maintain a branch of `easy-webpack` in this repo that might be a great compromise if you're interested we can see if devs prefer it etc

**Comment by niieani** [comment]
@gdi2290 No problem. 

Actually, `easy-webpack` doesn't need to be used in combination with the "magical", external config packages that you cite above: all the configs can be inlined, it can be used as a more advanced `webpack-merge`, which as I see, you already use. 

Aurelia is recommending either RequireJS via the aurelia-cli or Webpack. JSPM is still an option, but it turned out to be just too messy at times to be used well in production.

**Comment by gdi2290** [comment]
kool, I'll add you to the repo so you can create a branch

**Comment by niieani** [comment]
@gdi2290 I'm pretty busy ATM, but I'll add it to my backlog. :)
