### ISSUE TITLE
Uncommenting lodash import breaks ENV and HMR declarations in custom_typings.d.ts

### ISSUE THREAD

**Issue by tkw722** [AngularClass/angular2-webpack-starter#771]
In the custom_typings.d.ts file, if we add the line `import * as _ from 'lodash';` we end up getting an error at compile time saying `Cannot find name 'ENV'`. Anyone else run across this?

**Comment by gdi2290** [comment]
that was meant as an example of where you would use it within app not custom-typings.d.ts the line you're looking for is
```typescript
declare module "lodash" {
  var lodash: any;
  namespace lodash {}
  export = lodash;
}
```
but you're better off just installing it from typings
`typings install dt~lodash --save --global`
then you should be able to use it within your `app/` so long as you also install it via `npm install lodash`
