### ISSUE TITLE
load assets when the app is located in subdirectory

### ISSUE THREAD

**Issue by MurhafSousli** [AngularClass/angular2-webpack-starter#772]
Hi, I'm trying to use this starter as a wordpress theme, I got it to work but I have a problem with loading assets files and relative paths, since it is designed to be loaded from root directory, and I know supporting wordpress is out of the scope of this repo but I was wondering if I can add custom paths to webpack so it can recognize them and load them from the theme directory instead of root directory.

for example let's say that the url is `http://example.com` but the app is located in `http://example.com/wp-content/themes/angular2-webpack-starter`, is it possible to get it to work?

**Comment by gdi2290** [comment]
you would just set the baseUrl correct
`<base href="/wp-content/themes/angular2-webpack-starter">`

**Comment by marsanla** [comment]
@gdi2290 I had the same problem and i solved doing what you said. But when i am loading the page, the url automatically change to http:www.example.com/wp-content/themes/angular2-webpack-starter.

How can fix this.

Thanks :)

**Comment by dereklin** [comment]
@marsanla not sure if this will help, but in your webpack.prod.js, in the output block, set 
```
publicPath: '/wp-content/themes/angular2-webpack-starter/' 
```
And for example, in your img tags like <img [src]="angularclassLogo" width="25%">, use instead of 

```
public angularclassLogo = 'assets/img/angularclass-avatar.png';
```
do 
```
public angularclassLogo = require('assets/img/angularclass-avatar.png');
```
