### ISSUE TITLE
Jquery Plugin

### ISSUE THREAD

**Issue by oktango** [AngularClass/angular2-webpack-starter#777]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)
- **I'm submitting a ...**
  [ ] bug report
  [X ] feature request
  [ ] question about the decisions made in the repository
- **Do you want to request a _feature_ or report a _bug_?**
- **What is the current behavior?**
- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
  https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).
- **What is the expected behavior?**

How to add Jquery Plugin (datatables.net) ?
- **What is the motivation / use case for changing the behavior?**
- **Please tell us about your environment:**
- Angular version: 2.0.0-beta.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
- **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by reach4thelasers** [comment]
I've been trying to add a jQuery plugin to this seed literally for a week.  I've spent around 60 hours looking at this, dug through blog posts tried every plugin imaginable but it doesn't work  and have now given up and am going to try other options.

My plugin is a commercial stock charting product.  It has many dependencies on other jQuery plugins and Modernizr/Detectizr etc and nothing I can do can get Webpack to play nice with it.

I wish I could get it to work but I just can't.  Frustratingly the System.js angualr 2 seed doesn't support debugging in vscode.

**Comment by phiphou** [comment]
You definitely should have a look to #723 and the [Wiki](https://github.com/AngularClass/angular2-webpack-starter/wiki/How-to-include-jQuery) ;)
