### ISSUE TITLE
Errors/Warnings in the check process after starting the development server

### ISSUE THREAD

**Issue by lpalli** [AngularClass/angular2-webpack-starter#780]
* **I'm submitting a ...**
[X] bug report

* **Do you want to request a *feature* or report a *bug*?**

Errors/Warnings in the check process after starting the development server.

* **What is the current behavior?**

After starting the development server using `npm start` in the checking process a lot errors and/or Warnings are reported.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

Take [this commit](https://github.com/AngularClass/angular2-webpack-starter/commit/2f441d924f5fc02f0bff1e40c6ce854ffd83d648) on the master branch and execute `npm run clean`, `npm install` and finally `npm start` to show the errors/warnings on the console.

* **What is the expected behavior?**

The checking process verify the code whitout errors/warnings.

* **What is the motivation / use case for changing the behavior?**

Avoid errors/warnings when running/checking the application.

* **Please tell us about your environment:**

Not relevant.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by gdi2290** [comment]
what editor are you using? you may need to update it to check for the latest version of typescript

**Comment by lpalli** [comment]
I just verified to have the last version of node, npm and the global dependencies. I don't use an editor to reproduce the error, I just use this commands from the terminal:
```
npm run clean
npm install
```
to be sure to have the last versions of dependencies
`npm run server`
The app start and work correctly but after the starting in the console a lot of warning/errors are reported, example:
```
[default] C:/Projects/angular2-webpack-starter/node_modules/@types/core-js/index.d.ts:21:14 
    Duplicate identifier 'PropertyKey'.
```

The warnings/errors:
[error.txt](https://github.com/AngularClass/angular2-webpack-starter/files/370942/error.txt)

**Comment by gdi2290** [comment]
@lpalli remove `typings/` folder

**Comment by cristianurbano** [comment]
I have the same issue ...     a lot of errors from core-js

**Comment by lpalli** [comment]
Effectively removing the `typings/` folder as removed the problem until [commit](https://github.com/AngularClass/angular2-webpack-starter/commit/1fb53d6eb84f4b5b804efebb11191f0cf96e2e83).
