### ISSUE TITLE
tsconfig invalid?

### ISSUE THREAD

**Issue by Martin-Wegner** [AngularClass/angular2-webpack-starter#781]
Since 2f441d924f5fc02f0bff1e40c6ce854ffd83d648 Visual Studio Code has a problem with the tsconfig.json. Please have a look at: https://github.com/Microsoft/vscode/issues/8069

**Comment by oers** [comment]
Similar problems with atom:
https://github.com/TypeStrong/atom-typescript/issues/1009

**Comment by mhheise** [comment]
Try overriding the `typescript.tsdk` property in your `settings.json` file to look like this:

```json
{
  "typescript.tsdk": "%YOUR_PROJECT_ROOT%/node_modules/typescript/lib"
}
```

It may be that your `typescript@next` install from the referenced commit is conflicting with the version that is shipped with VS Code. This will instead point to the `typescript` path that contains the newer version of `tsserver` as bundled with the newer version of `typescript`.

**Comment by Martin-Wegner** [comment]
Cool thanks that helped :)

**Comment by Dekeyras** [comment]
Don't forget to turn it off and on again. I had to restart VSCode to get the errors to go away after updating the setting...

**Comment by reach4thelasers** [comment]
this worked for me also.  Specifically:     `"typescript.tsdk": "node_modules/typescript/lib"`

**Comment by katallaxie** [comment]
ee0c85e1483b7f77ad728ab8c177d4370eb07250
