### ISSUE TITLE
Cannot Find Module 'webpack-merge' on npm start

### ISSUE THREAD

**Issue by ttecho** [AngularClass/angular2-webpack-starter#782]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
Cannot run 'npm run build:prod' or even 'npm start'

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

```> ProjectUI@0.0.1 server:dev C:\Users\Projects\Project\ProjectUI_PCF
> webpack-dev-server --config config/webpack.dev.js --inline --progress --profile --colors --watch --display-error-details --display-cached --content-base src/

module.js:442
    throw err;
    ^

Error: Cannot find module 'webpack-merge'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Projects\Project\ProjectUI_PCF\config\webpack.dev.js:6:22)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)```



* **What is the expected behavior?**
Should start the server


* **What is the motivation / use case for changing the behavior?**
In order to develop we need this functionality


* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.X
- Browser: all
- Windows 10



* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by mhheise** [comment]
Can you please try to run this? `npm i -D webpack-merge`

**Comment by gdi2290** [comment]
can you update to node 6

**Comment by ashwinirajput** [comment]
mytasklist@1.0.0 start /Users/ashwini/Documents/mytasklist/client
> webpack-dev-server --inline --progress --port 8080

module.js:327
    throw err;
    ^

Error: Cannot find module './config/webpack.dev.js'

**Comment by JediSange** [comment]
This is still happening for me. I created a script to reproduce this with reliability.

Versions:
node v11.13.0
npm v6.9.1

Script:

```
#!/bin/bash
npx create-nx-workspace@latest something --preset=empty --cli=nx
cd something
npm install --save-dev @nrwl/nest
nx g @nrwl/nest:app api --directory=""
nx serve
```
