### ISSUE TITLE
"npm run docs" throws Error: Unknown option errors

### ISSUE THREAD

**Issue by Dekeyras** [AngularClass/angular2-webpack-starter#786]
* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
I pull down the latest version of the codebase and run npm install. 

* **What is the current behavior?**
When you run "npm run docs", it fails with the following error: 
> typedoc "--options" "typedoc.json" "--exclude" "'**/*.spec.ts'" "./src/"

Error: Unknown option `lib.0`.
Error: Unknown option `lib.1`.
Error: Unknown option `strictNullChecks`.
Error: Unknown option `baseUrl`.
Error: Unknown option `types.0`.
Error: Unknown option `types.1`.
Error: Unknown option `types.2`.
Error: Unknown option `types.3`.
Error: Unknown option `types.4`.
Error: Unknown option `types.5`.
Error: Unknown option `types.6`.
Error: Unknown option `types.7`.
Error: Unknown option `types.8`.

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "...\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "typedoc" "--" "--options" "typedoc.json" "--exclude" "'**/*.spec.ts'" "./src/"
npm ERR! node v5.2.0
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! angular2-webpack-starter@5.0.5 typedoc: `typedoc "--options" "typedoc.json" "--exclude" "'**/*.spec.ts'" "./src/"`
npm ERR! Exit status 1

* **What is the expected behavior?**
I expected the script to complete successfully.

* **Please tell us about your environment:**
Windows 10

**Comment by gdi2290** [comment]
typedoc isn't working for typescript 2 :/

**Comment by asgerjensen** [comment]
See also https://github.com/TypeStrong/typedoc/issues/234
