### ISSUE TITLE
favicons loaded every route change

### ISSUE THREAD

**Issue by zigzag95** [AngularClass/angular2-webpack-starter#787]
* **I'm submitting a ...**
[x ] bug report

* **What is the current behavior?**
favicons loaded every route change

![image](https://cloud.githubusercontent.com/assets/7827225/16900975/f06afffe-4c35-11e6-8d77-7b44ba3f0b3b.png)

**Comment by poizoncc** [comment]
same problem

**Comment by MaZZly** [comment]
I had a similar problem with AngularJS and solved it by changing the order of the favicons.

Now testing with my app in Angular I managed to get rid of extra favicon requests by modifying `config/head-config.common.js` to have the favicons in the following order:

```Javascript
    { rel: 'icon', type: 'image/png', sizes: '16x16', href: '/assets/icon/favicon-16x16.png' },
    { rel: 'icon', type: 'image/png', sizes: '96x96', href: '/assets/icon/favicon-96x96.png' },
    { rel: 'icon', type: 'image/png', sizes: '32x32', href: '/assets/icon/favicon-32x32.png' },
```

Note that I had to restart the dev server for the changes to take effect..

**Comment by Doeke** [comment]
@MaZZly Changing the order of the favicon link tags fixed it for me. I'm using VueJS so I'm not sure it's related to angular.

**Comment by MaZZly** [comment]
@Doeke I remember vaguely when researching this for AngularJS that it was a browser bug, meaning it would happen to any page that has favicons in odd order..

Nonetheless this starter-pack could have use of a fix like this..

**Comment by tuoitrexuquang** [comment]
same issue, i'm using Angular 5 + webpack. Pls for me ask: What's root cause and how to fix it?
