### ISSUE TITLE
use canActivate to secure router

### ISSUE THREAD

**Issue by linger123** [AngularClass/angular2-webpack-starter#788]
when a use  interface canActivate to secure a route, console give me this message 

> 
 zone.js:260 Uncaught Invalid provider - only instances of Provider and Type are allowed, got: undefined
> 
 some body know why?

**Comment by gdi2290** [comment]
you can't use an interface because they get removed after build. you need to use a service that has the method and you need to provide the service on the root or in this case the APP_RESOLVER_PROVIDERS
