### ISSUE TITLE
Components using TemplateUrl fail in Unit Tests when being built with TestComponentBuilder

### ISSUE THREAD

**Issue by Spittal** [AngularClass/angular2-webpack-starter#796]
- **I'm submitting a ...**
  [ X ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
- **What is the current behavior?**
  When using the Test Component Builder in unit tests, any component that uses `templateUrl` fails.
- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
  Here is a gif of first, the beahaviour commented out, so it works. and then using TestComponentBuilder and the test failing.

http://imgur.com/a/q5hnr

You can replicate locally by just adding

``` typescript
  it('should not fail', async(inject([ TestComponentBuilder ], (tcb) => {
    tcb.createAsync(Home).then((fix) => {
      expect(true).toBe(true);
    });
  }));
```

to the home.spec.ts file and then running `npm run test`
- **What is the expected behavior?**
  That the component builds.
- **What is the motivation / use case for changing the behavior?**
  I need to run component based tests.
- **Please tell us about your environment:**
- Angular version: 2.0.0-beta.4
- Browser: [all ]
- **Stacktrace**

```
FAILED TESTS:
  Home
    ✖ should not fail
      Chrome 51.0.2704 (Mac OS X 10.11.5)
    Failed: Uncaught (in promise): Failed to load home.template.html
    Error: Uncaught (in promise): Failed to load home.template.html
        at AsyncTestZoneSpec._failCallback (/Users/jamie/web/fillbeer-ng2/config/spec-bundle.js:22327:39 <- webpack:///~/@angular/core/testing/async.js:34:0)
        at AsyncTestZoneSpec.onHandleError (/Users/jamie/web/fillbeer-ng2/config/spec-bundle.js:8255:24 <- webpack:///~/zone.js/dist/async-test.js:86:0)
        at ZoneDelegate.handleError (/Users/jamie/web/fillbeer-ng2/config/spec-bundle.js:6920:41 <- webpack:///~/zone.js/dist/zone.js:327:0)
        at Zone.runGuarded (/Users/jamie/web/fillbeer-ng2/config/spec-bundle.js:6826:46 <- webpack:///~/zone.js/dist/zone.js:233:0)
        at _loop_1 (/Users/jamie/web/fillbeer-ng2/config/spec-bundle.js:7080:53 <- webpack:///~/zone.js/dist/zone.js:487:0)
        at drainMicroTaskQueue (/Users/jamie/web/fillbeer-ng2/config/spec-bundle.js:7087:23 <- webpack:///~/zone.js/dist/zone.js:494:0)
        at XMLHttpRequest.ZoneTask.invoke (/Users/jamie/web/fillbeer-ng2/config/spec-bundle.js:7019:23 <- webpack:///~/zone.js/dist/zone.js:426:0)

```

**Comment by benshack** [comment]
I am also experiencing the issue above.

**Comment by vespertilian** [comment]
You need to add.  `angular2-template-loader` to the webpack test config, otherwise templates are not loaded in the spec-bundle.js. Seems to require commenting out remove comments. 

### webpack.test.js
```
    loaders: [

      /**
       * Typescript loader support for .ts and Angular 2 async routes via .async.ts
       *
       * See: https://github.com/s-panferov/awesome-typescript-loader
       */
      {
        test: /\.(scss|sass)$/,
        exclude: /node_modules/,
        loaders: ['raw', 'sass']
      },
      {
        test: /\.ts$/,
        loaders: ['awesome-typescript-loader', 'angular2-template-loader'],
        // loader: 'awesome-typescript-loader',
        // query: {
        //   compilerOptions: {
        //
        //     // Remove TypeScript helpers to be injected
        //     // below by DefinePlugin
        //     removeComments: true
        //
        //   }
        // },
        exclude: [/\.e2e\.ts$/]
      },
```

**Comment by abdulhaq-e** [comment]
You can still pass the `removeComments` option to `awesome-typescript-loader` using query strings.

```
loaders: ['awesome-typescript-loader?removeComments=true', 'angular2-template-loader'],
```

**Comment by abdulhaq-e** [comment]
@vespertilian Perhaps you can submit a PR to solve this issue.

**Comment by bhamde** [comment]
@abdulhaq-e  how about being able to use inline sourcemaps in this case? for "karma-remap-coverage" reporter
