### ISSUE TITLE
Just check out this repo and getting error in about.ts file

### ISSUE THREAD

**Issue by vivdkool** [AngularClass/angular2-webpack-starter#801]
Error:Error: Parse tsconfig error [{"messageText":"Unknown compiler option 'lib'.","category":1,"code":5023},{"messageText":"Unknown compiler option 'strictNullChecks'.","category":1,"code":5023},{"messageText":"Unknown compiler option 'baseUrl'.","category":1,"code":5023},{"messageText":"Unknown compiler option 'paths'.","category":1,"code":5023},{"messageText":"Unknown compiler option 'types'.","category":1,"code":5023}]

Please help me

**Comment by abdulhaq-e** [comment]
Delete the `node_modules/typescript` folder and run `npm install` again. You're probably getting this error because the TypeScript version is still < 2.0

**Comment by gdi2290** [comment]
what @abdulhaq-e said is correct. we're on ts 2.0 which can be installed via `npm run typescript@beta` that should fix your issue. feel free open another issue if you run into another one

**Comment by kaveh981** [comment]
I'm still get this error
Unknown compiler option 'lib'. (5023)
Unknown compiler option 'types'. (5023)

I removed typescript from node_module didn't work
used npm uninstall typescript and npm install -g typescript didn't work again
used npm uninstall -g typescript npm install -g typescript didn't work again

any idea?

**Comment by gdi2290** [comment]
@kaveh981 can you create a new issue

**Comment by SekThang** [comment]
how come you can say that is new issue??? As Kaveh981 said what option which you have said is not working... Its not a new issue.. Its existing one..
