### ISSUE TITLE
#801 

### ISSUE THREAD

**Issue by vivdkool** [AngularClass/angular2-webpack-starter#812]
Regarding 801 @abdulhaq-e i checked the typescript version in node modules is 2.0 beta 
even @gdi2290 i tried your suggestion but no luck.

i am not sure others are facing this.

Regards

**Comment by vivdkool** [comment]
HI I am using webstorm version 2016.2 and 

when i am setting tsc compiler to node modules typescript it displaying me lots of error like following

Please help me here

/Users/vitiwary/Documents/workSpaces/ise_scale_poc/ISE_SPOG_WP/node_modules/@types/core-js/index.d.ts
Error:(21, 14) TS2300: Duplicate identifier 'PropertyKey'.
Error:(58, 5) TS2687: All declarations of 'name' must have identical modifiers.
Error:(118, 5) TS2403: Subsequent variable declarations must have the same type.  Variable '[Symbol.unscopables]' must be of type '{ copyWithin: boolean; entries: boolean; fill: boolean; find: boolean; findIndex: boolean; keys: ...', but here has type 'any'.
Error:(235, 5) TS2687: All declarations of 'flags' must have identical modifiers.
Error:(249, 5) TS2687: All declarations of 'EPSILON' must have identical modifiers.
Error:(284, 5) TS2687: All declarations of 'MAX_SAFE_INTEGER' must have identical modifiers.
Error:(291, 5) TS2687: All declarations of 'MIN_SAFE_INTEGER' must have identical modifiers.
Error:(430, 5) TS2403: Subsequent variable declarations must have the same type.  Variable '[Symbol.toStringTag]' must be of type '"Symbol"', but here has type 'string'.
Error:(430, 5) TS2687: All declarations of '[Symbol.toStringTag]' must have identical modifiers.
Error:(437, 5) TS2687: All declarations of 'prototype' must have identical modifiers.
Error:(465, 5) TS2687: All declarations of 'hasInstance' must have identical modifiers.
Error:(471, 5) TS2687: All declarations of 'isConcatSpreadable' must have identical modifiers.
Error:(477, 5) TS2687: All declarations of 'iterator' must have identical modifiers.
Error:(483, 5) TS2687: All declarations of 'match' must have identical modifiers.
Error:(489, 5) TS2687: All declarations of 'replace' must have identical modifiers.
Error:(495, 5) TS2687: All declarations of 'search' must have identical modifiers.
Error:(501, 5) TS2687: All declarations of 'species' must have identical modifiers.
Error:(507, 5) TS2687: All declarations of 'split' must have identical modifiers.
Error:(513, 5) TS2687: All declarations of 'toPrimitive' must have identical modifiers.
Error:(519, 5) TS2687: All declarations of 'toStringTag' must have identical modifiers.
Error:(525, 5) TS2687: All declarations of 'unscopables' must have identical modifiers.
Error:(582, 5) TS2403: Subsequent variable declarations must have the same type.  Variable '[Symbol.toStringTag]' must be of type '"Math"', but here has type 'string'.
Error:(582, 5) TS2687: All declarations of '[Symbol.toStringTag]' must have identical modifiers.
Error:(586, 5) TS2403: Subsequent variable declarations must have the same type.  Variable '[Symbol.toStringTag]' must be of type '"JSON"', but here has type 'string'.
Error:(586, 5) TS2687: All declarations of '[Symbol.toStringTag]' must have identical modifiers.
Error:(601, 5) TS2687: All declarations of 'size' must have identical modifiers.
Error:(607, 5) TS2687: All declarations of 'prototype' must have identical modifiers.
Error:(618, 5) TS2687: All declarations of 'size' must have identical modifiers.
Error:(624, 5) TS2687: All declarations of 'prototype' must have identical modifiers.
Error:(639, 5) TS2687: All declarations of 'prototype' must have identical modifiers.
Error:(653, 5) TS2687: All declarations of 'prototype' must have identical modifiers.
Error:(665, 5) TS2687: All declarations of 'value' must have identical modifiers.
Error:(777, 5) TS2687: All declarations of 'prototype' must have identical modifiers.
/Users/vitiwary/Documents/workSpaces/ise_scale_poc/ISE_SPOG_WP/node_modules/typescript/lib/lib.es2015.core.d.ts
Error:(17, 14) TS2300: Duplicate identifier 'PropertyKey'.

**Comment by abdulhaq-e** [comment]
What about the global TypeScript binary?

Run `tsc -v` in a terminal.

**Comment by vivdkool** [comment]
@abdulhaq-e 
thats also 2.0

**Comment by gdi2290** [comment]
https://github.com/AngularClass/angular2-webpack-starter/blob/master/tsconfig.json
see if this works. replace es6 with es5

**Comment by vivdkool** [comment]
@gdi2290 it solves the problem but can you please explain whats going on for my understanding.

**Comment by gdi2290** [comment]
core-js and es6 both are providing es6 type definitions and they're conflicting

**Comment by borysn** [comment]
@gdi2290 I don't thing tsconfig target pulls in typings, it's just for the compiler right? I'm not seeing this resolve the issue. Could something else be pulling type definitions? I keep running into these odd ball issues.

**Comment by Krisa** [comment]
Was having the same issue, thanks for the solution... Nonetheless, could we update tsconfig.json accordingly since probably everyone is having/going to have the same problem?

**Comment by borysn** [comment]
I resolved my issue my adding es6 target in tsconfig, removing @types/core-js, and keeping core-js dependency.

**Comment by katallaxie** [comment]
I think this is resolved with ee0c85e1483b7f77ad728ab8c177d4370eb07250. But, you should not change the target from `es5` to `es6` as because of best browser support. See [Compiler Options](https://www.typescriptlang.org/docs/handbook/compiler-options.html).

**Comment by davidmarquis** [comment]
It is indeed resolved by removing `core-js` from the `types` array in `tsconfig.json`.
No need to resort to changing the compiler target to `es6`.

**Comment by soumyagangamwar** [comment]
![image](https://cloud.githubusercontent.com/assets/16099491/22617946/9d12deac-eaf6-11e6-9f73-e467ba798e0e.png)

I have same issue,If I change target es5 to es6 I am getting these error in browser, My application is not loaded ,Please help me,
