### ISSUE TITLE
Webpack 2?

### ISSUE THREAD

**Issue by spock123** [AngularClass/angular2-webpack-starter#813]
This is just for discussion/clearing up: is there any technical reason for not using Webpack2?

Missing modules/loaders/plugins?

I am especially interested in the tree shaking feature. 
Did anyone give it a shot?

Just curious before I throw myself under the bus in the attempt to use WP2.. any experiences/considerations?

Thanks guys

PS: Ng2-CLI is based on Webpack2 so it must be kinda ready...

**Comment by gdi2290** [comment]
this is planned. I was working with the ng team to get the cli working with webpack
I have it working here with an updated method of async loading
https://github.com/gdi2290/angular2-webpack2-starter

**Comment by spock123** [comment]
Cool, great stuff dude!
