### ISSUE TITLE
syntax error in custom.typings.d.ts

### ISSUE THREAD

**Issue by duderdice** [AngularClass/angular2-webpack-starter#828]
Currently the first non-comment line in custom.d.ts is as follows 

`declare module "*";` 

but that seems to give a syntax error on the semicolon with the message '{ expected', as the compiler expects a curly brace.  Changing it to the following seems to fix it

`declare module "*" {}`

Is that a valid fix?

**Comment by AJLiu** [comment]
IntelliJ has been complaining about this for me as well. I'd love to know what's the proper way of resolving this..

**Comment by sky-coding** [comment]
I have a related problem with `declare module "*";`, when included my WebStorm fails to provide TypeScript support for all other modules, and trying to jump any module results in jumping to this line. Is this line necessary?

**Comment by AJLiu** [comment]
https://youtrack.jetbrains.com/issue/WEB-22697

**Comment by sky-coding** [comment]
Awesome, thanks.

I'm also getting `Unresolved type` on things like `Promise` and `require`. I feel like these recent changes aren't quite usable for us yet so we'll be using https://github.com/AngularClass/angular2-webpack-starter/commit/6789db99ebc16370d67ac2ceb815da09145018d7 to seed new projects for now. Hopefully these problems won't deter new adopters looking for a "turn-key" seed.

**Comment by ankeshdave** [comment]
Did you try VS Code
I had the same problem, I changed tsdk used by VS Code to point to Typescript 2.0, ie in the node modules folder, you can do that per workspace no unresolved types in Vs Code now

**Comment by katallaxie** [comment]
Does ee0c85e1483b7f77ad728ab8c177d4370eb07250 resolves your issue?

**Comment by maxisam** [comment]
use visual studio 2015 with typescript 2.02 beta, this problem still exists.
