### ISSUE TITLE
get null 404 error on production

### ISSUE THREAD

**Issue by MurhafSousli** [AngularClass/angular2-webpack-starter#832]
Hi, I have my app working on local machine without any errors, once I built for production and published the app on my domain, I got this error (which doesn't effect the app)

```
GET http://murhafsousli.com/null 404 (Not Found)     null:1 
```

I looked in my code for hours I didn't find any get request, why is it happening!
and when I test production on local by adding `enableProdMode();` in app component, I get this error instead of the previous one:

```
TypeError: Cannot read property 'probe' of undefined(…)
```

I think the problem is in `_decorateComponentRef` in `environment.ts` but I don't know how to fix it.

**Comment by TheSaturn** [comment]
Have you string ` enableProdMode();` in your dev branch in enviroment.ts? I had same error due to have same string

**Comment by m44rt3np44uw** [comment]
+1 having the same error(s).
