### ISSUE TITLE
Cannot build  - no appropriate loader to handle this file type

### ISSUE THREAD

**Issue by MichalZalecki** [AngularClass/angular2-webpack-starter#84]
```bash
ERROR in ./src/app/bootstrap.ts
Module parse failed: /home/michal/WebstormProjects/angular2-webpack-starter/src/app/bootstrap.ts Line 4: Unexpected token
You may need an appropriate loader to handle this file type.
| 
| // Angular 2
| import {bootstrap} from 'angular2/angular2';
| /*
|  * Bindings provided by Angular
 @ multi app
```

I'm trying to get project up and running but I come across with *no appropriate loader* error after very first `npm start`. I have all global dependencies installed. I've tried with node `v0.12.5` and `v4.1.0` on `Ubuntu 14.04 LTS`. Have you got any idea what might be the problem? `webpack.config.js` looks fine (didn't change it).

**Comment by gdi2290** [comment]
thanks for opening an issue. Let me look into it. It might be the version of Webpack

**Comment by gsans** [comment]
Having the same issue. Updated node to `v4.1.1` and npm `3.3.5`.

**Comment by jimthedev** [comment]
@gsans Are you saying are still having the issue on node 4.1.1 and 3.3.5 or it is resolved?

**Comment by gdi2290** [comment]
I'm unable to replicate the issue :/

**Comment by gsans** [comment]
It didn't work even after upgrading node and npm. I'll try again and report back if anything changes.

**Comment by jimthedev** [comment]
Did you blow away node_modules after updating?

**Comment by gdi2290** [comment]
this might help

* `npm cache clean`
* delete node_modules
* update node
* `npm install -g npm@latest`
* `npm install`
* `npm start`

reinstall the repo

**Comment by byleaf** [comment]
I got these errors when "npm install" and it not work after npm cache clean and so on
```
9 errors generated.
make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/byleaf/.nvm/versions/node/v4.1.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/Users/byleaf/.nvm/versions/node/v4.1.1/bin/node" "/Users/byleaf/.nvm/versions/node/v4.1.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/byleaf/Documents/test/angular2-webpack-starter/node_modules/protractor/node_modules/selenium-webdriver/node_modules/ws/node_modules/bufferutil
gyp ERR! node -v v4.1.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN optional dep failed, continuing utf-8-validate@1.1.0
npm WARN optional dep failed, continuing bufferutil@1.1.0
```
Finally, when I run "npm start",  same issue happened
```
ERROR in ./src/app/bootstrap.ts
...
```

**Comment by dotcs** [comment]
For me the current setup works with node 4.2.1 and npm 2.14.7 on Mac OS X 10.10. @gsans, @byleaf Can you update node and npm and give us an update if everything works fine now?

If the dependencies have been installed with node 0.x and later node 4.x is being used to update the packages, this might indeed be a problem that leads to an inconsistent state. The easiest solution here is to delete `node_modules` as mentioned above and re-install dependencies using the latest npm.

**Comment by SekibOmazic** [comment]
Have same setup as @dotcs and for me it works fine.

**Comment by moberg** [comment]
I'm getting the same error. node 4.2.1, nvm 3.3.10

```
chunk    {2} app.js, app.js.map (app) 40 bytes {1} [rendered]
    [0] multi app 40 bytes {2} [built] [1 error]

ERROR in ./src/app/bootstrap.ts
Module parse failed: /Users/peter/Development/test/ng2/angular2-webpack-starter/src/app/bootstrap.ts Line 6: Unexpected token
You may need an appropriate loader to handle this file type.
|  * Providers provided by Angular
|  */
| import {bootstrap, FORM_PROVIDERS, ELEMENT_PROBE_PROVIDERS} from 'angular2/angular2';
| import {ROUTER_PROVIDERS} from 'angular2/router';
| import {HTTP_PROVIDERS} from 'angular2/http';
 @ multi app
```

**Comment by iuliust** [comment]
Same problem for me. Cache cleaned, fresh install, node 4.2.1, npm 3.3.10, and `npm start` fails at the line 6.

chunk    {2} app.js, app.js.map (app) 40 bytes {1} [rendered]
    [0] multi app 40 bytes {2} [built] [1 error]

ERROR in ./src/app/bootstrap.ts
Module parse failed: /home/julien/WebstormProjects/ng2test/src/app/bootstrap.ts Line 6: Unexpected token
You may need an appropriate loader to handle this file type.
|  * Providers provided by Angular
|  */
| import {bootstrap, FORM_PROVIDERS, ELEMENT_PROBE_PROVIDERS} from 'angular2/angular2';
| import {ROUTER_PROVIDERS} from 'angular2/router';
| import {HTTP_PROVIDERS} from 'angular2/http';
 @ multi app

**Comment by gdi2290** [comment]
should be fixed via https://github.com/AngularClass/angular2-webpack-starter/commit/79aef4702a10fbb294b92b6bd6bcdc30b43cbab4
