### ISSUE TITLE
npm start fails

### ISSUE THREAD

**Issue by b0bi79** [AngularClass/angular2-webpack-starter#840]
**I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

**Do you want to request a feature or report a bug?**
Bug

**What is the current behavior?**
`npm start` fails

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

On clean project when I run `npm start`:
...
  [759] ./src/app/app.style.css 160 bytes {4} [built]
       [0] 4274ms -> [549] 52ms -> [542] 270ms -> factory:640ms building:970ms = 6206ms
  [760] ./src/app/home/home.style.css 51 bytes {4} [built]
       [0] 4274ms -> [552] 23ms -> [378] 68ms -> [375] 21ms -> [544] 60ms -> [543] 749ms -> factory:889ms building:127ms = 6211ms
Child html-webpack-plugin for "index.html":
    chunk    {0} index.html 525 kB [rendered]
        [0] ./~/html-webpack-plugin/lib/loader.js!./src/index.html 2.06 kB {0} [built]
           factory:33ms building:40ms = 73ms
        [1] ./~/lodash/lodash.js 523 kB {0} [built]
           [0] 73ms -> factory:433ms building:769ms = 1275ms
        [2] (webpack)/buildin/module.js 251 bytes {0} [built]
           [0] 73ms -> [1] 1202ms -> factory:127ms building:717ms = 2119ms
webpack: bundle is now VALID.
_[default] Checking started in a separate process..._
[default] D:/Sources/asr/angular2-webpack-starter/node_modules/@angular/common/src/directives/ng_class.d.ts:81:35
    **Cannot find name 'Set'.**
[default] D:/Sources/asr/angular2-webpack-starter/node_modules/@angular/common/src/facade/async.d.ts:34:33
    **Cannot find name 'Promise'.**
[default] D:/Sources/asr/angular2-webpack-starter/node_modules/@angular/common/src/facade/async.d.ts:35:45
    **Cannot find name 'Promise'.**
[default] D:/Sources/asr/angular2-webpack-starter/node_modules/@angular/common/src/facade/lang.d.ts:11:17
    **Cannot find name 'Map'.**
...

**My steps:**
git clone --depth 1 https://github.com/angularclass/angular2-webpack-starter.git
cd angular2-webpack-starter
npm install
npm start

**Comment by scrapcupcake** [comment]
I'm having this same issue; however, when I actually go to localhost:3000, the site works; I just get this message spew as well. I suspect it is a 3rd party issue (duh), but haven't the faintest idea where to start looking.

**Comment by david1983** [comment]
Same for me.

Child html-webpack-plugin for "index.html":
    chunk    {0} index.html 525 kB [rendered]
        [0] ./~/html-webpack-plugin/lib/loader.js!./src/index.html 1.96 kB {0} [built]
           factory:21ms building:33ms = 54ms
        [1] ./~/lodash/lodash.js 523 kB {0} [built]
           [0] 54ms -> factory:195ms building:442ms = 691ms
        [2] (webpack)/buildin/module.js 251 bytes {0} [built]
           [0] 54ms -> [1] 637ms -> factory:31ms building:179ms = 901ms
webpack: bundle is now VALID.
[default] Checking started in a separate process...
[default] /home/callum/1_develop/angular2-webpack-starter/node_modules/@angular/common/src/directives/ng_class.d.ts:81:35 
    Cannot find name 'Set'.
[default] /home/callum/1_develop/angular2-webpack-starter/node_modules/@angular/common/src/facade/async.d.ts:34:33 
    Cannot find name 'Promise'.
[default] /home/callum/1_develop/angular2-webpack-starter/node_modules/@angular/common/src/facade/async.d.ts:35:45 
    Cannot find name 'Promise'.
[default] /home/callum/1_develop/angular2-webpack-starter/node_modules/@angular/common/src/facade/lang.d.ts:11:17 
    Cannot find name 'Map'.
[default] /home/callum/1_develop/angular2-webpack-starter/node_modules/@angular/common/src/facade/lang.d.ts:12:17 
    Cannot find name 'Set'.
[default] /home/callum/1_develop/angular2-webpack-starter/node_modules/@angular/common/src/facade/lang.d.ts:68:59 
...
It continues for other 90 lines, if you guys wants the whole log I can send it.

Btw the server runs

**Comment by david1983** [comment]
Update - 
I've switched to branch material2 and I've done a npm install ... npm start worked with no errors

**Comment by b0bi79** [comment]
@scrapcupcake I go to localhost:3000 and get Connection broken error.

**Comment by b0bi79** [comment]
@david1983 David, material2 this is older code branch. There's still used typings. In the latest version of the master branch that is already do not have.

**Comment by sky-coding** [comment]
Confirmed on fresh install. What happened to typings?

**Comment by richyrb00** [comment]
I've got 2 different versions running. the older works fine ( typings 2.0.0-beta). this new one using 1.8.0 typescript has this same issue as above.

**Comment by sky-coding** [comment]
This is resolved by https://github.com/AngularClass/angular2-webpack-starter/commit/f71d4e6495d0cbc8e42549be355e024d6d78f518.

**Comment by b0bi79** [comment]
@sky-coding Thank you
