### ISSUE TITLE
Cannot find name 'Promise'. In Visual Studio Code

### ISSUE THREAD

**Issue by xielongjiang** [AngularClass/angular2-webpack-starter#845]
I use visual studio code  will have an error message.

Cannot find name 'Promise'.

Open the path to the \node_modules\@angular\router\src

This error message will be displayed
![qq 20160811012709](https://cloud.githubusercontent.com/assets/7290992/17563681/0e452fb4-5f63-11e6-9213-77bb06f7de15.jpg)

**Comment by psolidgold** [comment]
Can confirm that this is happening to me as well.

**Comment by ankeshdave** [comment]
Did you try, pointing VS Code to Typescript 2.0.
Add workspace settings file for 'tsdk' to point to 'node_modules/typescript/lib' 

You can google on how to change typescript version  VS code is using

**Comment by LosD** [comment]
Not sure if this helps, but it sounds a lot like how IntelliJ IDEA acted until I changed it to use EcmaScript 6, could it be something similar?

**Comment by bufke** [comment]
Using Typescript 2.0 fixed it for me. I had to install it globally for it to work for some reason.

**Comment by jiverson** [comment]
Add `"typescript.tsdk": "node_modules/typescript/lib/"` to your Preferences -> User Settings in VS Code.

**Comment by xielongjiang** [comment]
@jiverson ok,Your operation is feasible.Problem has been solved.

**Comment by katallaxie** [comment]
See ee0c85e1483b7f77ad728ab8c177d4370eb07250 which includes the `settings.json`.

**Comment by zigzag95** [comment]
We are not all using vscode
I use Atom

**Comment by katallaxie** [comment]
Yep, but the issue was regarding VS.
