### ISSUE TITLE
SSL setup in webpack

### ISSUE THREAD

**Issue by nekkon** [AngularClass/angular2-webpack-starter#848]
Hello, I would like to know to setup webpack.prod.js so that the server will use https instead of simple http.

**Comment by ferredel** [comment]
Maybe I'm wrong but: When you do a `npm run build:prod` you get the _webpacked_ version of you angular2 App. Then when you will use something to serve the static files (express, apache, nginx, ISS).

In that moment, when you serve the file, you should configure the server to work over HTTPS.

I hope this can help you.

**Comment by nekkon** [comment]
Thank you
