### ISSUE TITLE
VS Code Launch.json

### ISSUE THREAD

**Issue by crh225** [AngularClass/angular2-webpack-starter#851]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[ ] bug report
[ X] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Can someone share their Launch.json for visual studio code?

**Comment by katallaxie** [comment]
See ee0c85e1483b7f77ad728ab8c177d4370eb07250 which includes VS Code config and reference to [Chrome Debugger for VS Code](https://github.com/Microsoft/vscode-chrome-debug).
