### ISSUE TITLE
Link to slack chat broken (404)

### ISSUE THREAD

**Issue by cmermingas** [AngularClass/angular2-webpack-starter#852]
The [readme](https://github.com/AngularClass/angular2-webpack-starter/tree/material2#support-questions-or-feedback) and the [issue template](https://github.com/AngularClass/angular2-webpack-starter/blob/master/.github/ISSUE_TEMPLATE.md) point to a broken link:

  http://angularclass.com/member-join/

A minor problem but I figure you'd like to track it.

**Comment by maciejsobala** [comment]
@katallaxie 

The link is still not working. Could You fix it, or reopen the bug?

**Comment by ajcastro** [comment]
How can I join the slack??? The link is not working.
