### ISSUE TITLE
Uncaught Error: Missing: SyncTestZoneSpec

### ISSUE THREAD

**Issue by vesteraas** [AngularClass/angular2-webpack-starter#862]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

To reproduce the problem:

```
git clone https://github.com/AngularClass/angular2-webpack-starter
cd angular2-webpack-starter
npm install
./node_modules/karma/bin/karma start
```

* **What is the current behavior?**

```
START:
17 08 2016 14:48:48.065:WARN [karma]: Port 9876 in use
17 08 2016 14:48:48.068:INFO [karma]: Karma v0.13.22 server started at http://localhost:9877/
17 08 2016 14:48:48.073:INFO [launcher]: Starting browser Chrome
17 08 2016 14:48:48.975:INFO [Chrome 52.0.2743 (Mac OS X 10.11.6)]: Connected on socket /#VgAMBBLGjB7qy76XAAAA with id 2168046
Chrome 52.0.2743 (Mac OS X 10.11.6) ERROR
  Uncaught Error: Missing: SyncTestZoneSpec
  at /Users/werner/work/angular2/angular2-webpack-starter/config/spec-bundle.js:8207 <- webpack:///~/zone.js/dist/jasmine-patch.js:66:0

Finished in 0.397 secs / 0 secs

SUMMARY:
✔ 0 tests completed
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 2.0.0-RC.4

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

After some research, I found that uncommenting the `require('zone.js/dist/jasmine-patch');` in `/config/spec-bundle.js` 'fixes' the problem.

**Comment by mhheise** [comment]
@vesteraas What version of `zone.js` do you have installed? Could you try locking the dependency to version 0.6.12?

**Comment by yuanfeiz** [comment]
I ran into this issue too moment ago. 

Angular version: 2.0.0-rc5
zone.js: zone.js@0.6.14

**Comment by vesteraas** [comment]
@mhheise Locking to zone.js@0.6.14 solved the problem.

**Comment by binarious** [comment]
Bug in zone.js: https://github.com/angular/zone.js/issues/404

**Comment by gtsopour** [comment]
I can verify that locking to zone.js@0.6.12 solved the problem for me too.

**Comment by yuanfeiz** [comment]
@gtsopour check out the merged PR above, this reorder of the import should have solved the issue and you're good to upgrade to zone.js@0.6.17

**Comment by mdocter** [comment]
Note. `require('zone.js/dist/proxy-zone');` doesn't exist in my `zone.js@0.6.17` package. 
It's just `require('zone.js/dist/proxy');`

**Comment by dessalines** [comment]
I got this error again in `zone.js@0.6.26`.

**Comment by kamil-kielczewski** [comment]
I got this error too!  zone.js@0.6.26.

**Comment by kamil-kielczewski** [comment]
I check it precisely: it works for zone.js@0.6.12 and 13, but not works for zone.js@0.6.14-26

I use it for quite old version of angular2-starter (from June) where is @angular/core": "2.0.0-rc.3" .
