### ISSUE TITLE
typings.json

### ISSUE THREAD

**Issue by Pandan** [AngularClass/angular2-webpack-starter#867]
Really sorry for posting a support questions here. But the slack registration is not working :(
I am trying to use GSAP (http://greensock.com/) in angular2-webpack-starter
In the GSAP forum I found a ts typing file.
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/greensock/greensock.d.ts
But in the angular2-webpack-starter I can really find a typings.json file to add it to. 
Any suggestions? Thanks

**Comment by clementprevot** [comment]
As far as I understand this, the Webpack Starter is not using (anymore) Typings, but instead the "@types" that comes with the new version of typescript.

So to solve your problem, first look if there is a "@types" for GSAP.

Else, you can try to paste the content of you ".d.ts" file in the "custom-typings.d.ts" of the Webpack Starter.

**Comment by Pandan** [comment]
Thanks for the quick reply.
Didn't find much about @types and GSAP, don think they support it officially.
I tried moving the content from the .d.ts film to custom-typings. But it created some other issues.
But think I got GSAP to work without typings, so for now I will just do it this way.
Thanks

**Comment by orizens** [comment]
I encountered in my app http://github.com/orizens/echoes-ng2.
for getting youtube api support, i installed: 
```shell
npm i @types/youtube @types/gapi @types/gapi.youtube
``` 
then, i added these to custom.typings.d.ts: 
```es6
import '@types/gapi.youtube';
import '@types/gapi';
import '@types/youtube';
```

**Comment by gdi2290** [comment]
@orizens can you make a PR explaining this for users who have problems with @types

**Comment by orizens** [comment]
@gdi2290 sure. 
should I add it to Readme.md?

**Comment by gdi2290** [comment]
ya
