### ISSUE TITLE
Cannot resolve component using 'About'. Is Async resolving broken?

### ISSUE THREAD

**Issue by Jacke** [AngularClass/angular2-webpack-starter#877]
* **I'm submitting a bug**
[x] bug report

* **What is the current behavior?**
Fresh install git clone && npm install && npm start
```
hello `Home` component
about.component.ts:9`About` component loaded asynchronously
index.ts:4`Detail` bundle loaded asynchronously
browser_adapter.js:93EXCEPTION: Error: Uncaught (in promise): Cannot resolve component using 'About'.

```
If I edit app.routes manually and put Component object instead of 'Component's async resolving string it works.

- Fresh clone
- Angular version: 2.0.0-beta.rc5
- Browser: [all]

**Comment by gdi2290** [comment]
ya, async is broken in this repo until I move over the changes from
https://github.com/angularclass/angular2-seed

**Comment by Jacke** [comment]
Oh, fresh software is changing rapidly :smile:  Thanks for info.Is async routes resolving some kind of best practice for angular 2?

**Comment by fristys** [comment]
@gdi2290 what's the ETA on the move?

**Comment by gdi2290** [comment]
the repo is updated to rc5. but not with the changes from the seed so we're still using the old way to async load
