### ISSUE TITLE
Type  '({ path: string; component: typeof ... is not assignable to type 'Route[]'

### ISSUE THREAD

**Issue by IAMtheIAM** [AngularClass/angular2-webpack-starter#889]
After updating to the latest RC5, I get a typescript compile error.  What type declaration is missing for this error to stop?
```
webpack: bundle is now VALID.
[default] ~/app/app.routes.ts:23:14 
    Type '({ path: string; component: typeof LoginComponent; } | { path: string; component: typeof HomeComp...' is not assignable to type 'Route[]'.
  Type '{ path: string; component: typeof LoginComponent; } | { path: string; component: typeof HomeCompo...' is not assignable to type 'Route'.
    Type '{ path: string; loadChildren: () => any; }' is not assignable to type 'Route'.
      Types of property 'loadChildren' are incompatible.
        Type '() => any' is not assignable to type 'string'.
```

**Comment by StefH** [comment]
Please post full TS code.

**Comment by gdi2290** [comment]
thanks for reporting this. Alright, I updated my router fork so see if you can try again. Please reopen this issue if it's not fixed

**Comment by IAMtheIAM** [comment]
@StefH it is just the code in the [app.routes.ts](https://github.com/AngularClass/angular2-webpack-starter/blob/817ea488f6edb7f271728487d873dead72efd8b8/src/app/app.routes.ts) file

@gdi2290 Your updated fork fixed the problem. Thanks.

**Comment by didadan** [comment]
In my case I spelled the Component right but after 1-2 hours of research and hair pulling finally found that I missed the `component: ` before. Arrgh.

So instead of writing 

    {
        path: 'somepath',
        component: SomeComponent,
    }

By mistake I had

    {
        path: 'somepath',
        SomeComponent,
    }

Very easy to miss.
