### ISSUE TITLE
Dependencies not updated

### ISSUE THREAD

**Issue by OmgImAlexis** [AngularClass/angular2-webpack-starter#892]
The current dependencies using commit a4536f7ff6feef0ab02b7e5e2e095e26f3706575 are outdated and should be updated to fix security issues.

```
npm WARN deprecated wrench@1.5.8: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
```

**Comment by gdi2290** [comment]
thanks, some dependencies have outdated dependencies. I can't do anything about it really. You should open an issue with those repos. you can look into the node_modules to track which dependencies are outdated and see which packages are using them. I'm going to close this issue to keep the issue count low

**Comment by OmgImAlexis** [comment]
Adding refs to here so you know when you can update.

https://github.com/tschaub/gh-pages/issues/114

**Comment by gdi2290** [comment]
thanks
