### ISSUE TITLE
Error in latest checkin which used webpack2

### ISSUE THREAD

**Issue by StefH** [AngularClass/angular2-webpack-starter#898]
* **I'm submitting a**
[ x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Solution**
The project.json is missing:
`"string-replace-loader": "^1.0.3"`

**Comment by Luchillo** [comment]
Made a pull request: https://github.com/AngularClass/angular2-webpack-starter/pull/900

**Comment by StefH** [comment]
Solved by https://github.com/AngularClass/angular2-webpack-starter/pull/899
