### ISSUE TITLE
ERROR in multi polyfills

### ISSUE THREAD

**Issue by alvipeo** [AngularClass/angular2-webpack-starter#903]
Just cloned this repo and run it (npm start). Got this:

> ERROR in multi polyfills
> Module not found: Error: Can't resolve 'string-replace-loader?{"search":"(System|SystemJS)(.*[\\n\\r]\\s*\\.|\\.)import\\((.+)\\)","replace":"$1.import($3).then(mod => mod.__esModule ? mod.default : mod)","flags":"g"}' in 'e:\Documents\Visual Studio 2015\Projects\angular2-webpack-starter'
>  @ multi polyfills
> 
> ERROR in multi vendor
> Module not found: Error: Can't resolve 'string-replace-loader?{"search":"(System|SystemJS)(.*[\\n\\r]\\s*\\.|\\.)import\\((.+)\\)","replace":"$1.import($3).then(mod => mod.__esModule ? mod.default : mod)","flags":"g"}' in 'e:\Documents\Visual Studio 2015\Projects\angular2-webpack-starter'
>  @ multi vendor
> 
> ERROR in multi main
> Module not found: Error: Can't resolve 'string-replace-loader?{"search":"(System|SystemJS)(.*[\\n\\r]\\s*\\.|\\.)import\\((.+)\\)","replace":"$1.import($3).then(mod => mod.__esModule ? mod.default : mod)","flags":"g"}' in 'e:\Documents\Visual Studio 2015\Projects\angular2-webpack-starter'
>  @ multi main

Now sure what this all about.

Node 6.4.0
Windows 10

**Comment by codespicelabs** [comment]
yep, seems one broken dependency
https://www.npmjs.com/package/string-replace-loader or similar forks/builds

**Comment by alvipeo** [comment]
Cool, thanks! That fixed it.
