### ISSUE TITLE
[Production build] Inputs not recognized

### ISSUE THREAD

**Issue by j3ddesign** [AngularClass/angular2-webpack-starter#917]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**
I built my app in prod with 0 errors (although there are a tonne of warnings). When running the page, no component input's are recognized. 

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

Create a component with inputs, build for prod, run.

* **What is the expected behavior?**
The components should behave as they do in dev

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

- Chrome & Chrome Canary
- Webpack Starter Kit v5.0.5
- Windows 10

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
```
"Error: Template parse errors:↵Can't bind to 'recentSub' since it isn't a known property of 'l1-subcombo'.↵1. If 'l1-subcombo' is an Angular component and it has 'recentSub' input, then verify that it is part of this module.↵2. If 'l1-subcombo' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message.↵ ("<div class="topRow">
↵  <l1-subcombo [ERROR ->][recentSub]="recentSub"></l1-subcombo>
↵</div>
↵<div class="bottomRow">
↵"):
```
^ That's just the first input, there are about 4 more for this app.

**Comment by binarious** [comment]
https://github.com/angular/angular/issues/10618

**Comment by j3ddesign** [comment]
Thanks, I followed that issue and managed to get this resolved, hadn't seen that in my searches yesterday!

The fix was to set line 160 in `config/webpack.prod.js` to `mangle: {screw_ie8 : true, keep_fnames: true }, //prod`  and my build was successful and working as intended.

**Comment by binarious** [comment]
Should have been fixed with https://github.com/AngularClass/angular2-webpack-starter/commit/e2552b8dc7f98e0abc9f2c4a9063c86d093ae0e6.

**Comment by j3ddesign** [comment]
Thanks!
