### ISSUE TITLE
"There are multiple modules with names that only differ in casing"

### ISSUE THREAD

**Issue by dyh333** [AngularClass/angular2-webpack-starter#926]
i cloned one project to local and npm install, npm start. but found below warning. 
my dev environment is in windows 10 system

WARNING in (webpack)/buildin/module.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* E:\GitHub\angular2-webpack-starter\node_modules\webpack\buildin\module.js
    Used by 2 module(s), i. e.
    E:\GitHub\angular2-webpack-starter\node_modules\punycode\punycode.js
* e:\GitHub\angular2-webpack-starter\node_modules\webpack\buildin\module.js
    Used by 1 module(s), i. e.
    e:\GitHub\angular2-webpack-starter\node_modules\rxjs\util\root.js

**Comment by inska** [comment]
Same here

**Comment by junyun0516** [comment]
me too ㅠㅠ

**Comment by Junik** [comment]
Same behavior

**Comment by PatrickJS** [comment]
/\ this is an OS (windows) problem. Please see the solution above via @Junik

**Comment by alvipeo** [comment]
@gdi2290 well, there are lots of us...

**Comment by gdi2290** [comment]
this is a problem with node and windows so I can't do anything about it

**Comment by zigzag95** [comment]
On Windows, stop naming files with upper case. Here we use kebab case

**Comment by Luchillo** [comment]
I'm having the same warning except it's in Mac:
```js
WARNING in ./~/rxjs/add/operator/map.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* /Users/aplicaciones2/Documents/Luchillo-tech-showcase/node_modules/string-replace-loader/index.js?{"search":"var sourceMappingUrl = extractSourceMappingUrl\\(cssText\\);","replace":"var sourceMappingUrl = \"\";","flags":"g"}!/Users/aplicaciones2/Documents/Luchillo-tech-showcase/node_modules/Rxjs/add/operator/map.js
    Used by 1 module(s), i. e.
    /Users/aplicaciones2/Documents/Luchillo-tech-showcase/node_modules/string-replace-loader/index.js?{"search":"var sourceMappingUrl = extractSourceMappingUrl\\(cssText\\);","replace":"var sourceMappingUrl = \"\";","flags":"g"}!/Users/aplicaciones2/Documents/Luchillo-tech-showcase/node_modules/Rxjs/Rx.js
* /Users/aplicaciones2/Documents/Luchillo-tech-showcase/node_modules/string-replace-loader/index.js?{"search":"var sourceMappingUrl = extractSourceMappingUrl\\(cssText\\);","replace":"var sourceMappingUrl = \"\";","flags":"g"}!/Users/aplicaciones2/Documents/Luchillo-tech-showcase/node_modules/rxjs/add/operator/map.js
    Used by 1 module(s), i. e.
    /Users/aplicaciones2/Documents/Luchillo-tech-showcase/node_modules/@angularclass/hmr-loader/index.js?pretty=true&prod=false!/Users/aplicaciones2/Documents/Luchillo-tech-showcase/node_modules/awesome-typescript-loader/dist/entry.js!/Users/aplicaciones2/Documents/Luchillo-tech-showcase/node_modules/angular2-template-loader/index.js!/Users/aplicaciones2/Documents/Luchillo-tech-showcase/node_modules/string-replace-loader/index.js?{"search":"(System|SystemJS)(.*[\\n\\r]\\s*\\.|\\.)import\\((.+)\\)","replace":"$1.import($3).then(mod => (mod.__esModule && mod.default) ? mod.default : mod)","flags":"g"}!/Users/aplicaciones2/Documents/Luchillo-tech-showcase/src/vendor.browser.ts
```

That one error is repeated aprox 52 times with different rxjs operators.

So as this happens to me in Mac OSX 'El Capitan', i don't think my issue is with the cd used, any ideas?

**Comment by luchillo17** [comment]
Ok found my issue, i'm importing like:

``` ts
import { Observable } from 'Rxjs/Observable';
import { Subscription } from 'Rxjs/Subscription';
import 'Rxjs/add/operator/debounceTime';
import 'Rxjs/add/observable/fromEvent';
```

When it should be like:

``` ts
import { Observable } from 'rxjs/Observable';
import { Subscription } from 'rxjs/Subscription';
import 'rxjs/add/operator/debounceTime';
import 'rxjs/add/observable/fromEvent';
```

Note the upper case R in rxjs.

**Comment by buddyackerman** [comment]
@Junik this fix didin't work for me as my path was already set with and upper case rive letter.  Is the casing in the full path critical as well?  I have mixed case in the folders of the path to my project directory.

e.g.   C:\Projects\Angular2\Blah\MyProject

**Comment by MarkPieszak** [comment]
@buddyackerman I just ran into this on one of my machines and realized I was using Node 6.4, I upgraded to 7.1 and the issues went away, could of been the way I was doing the directory as well, but I believe this has been fixed on the Node end (see https://github.com/nodejs/node/issues/6624)

**Comment by karocksjoelee** [comment]
I've encountered this issue today , I solve by checking the import components url . In my case is XXX.module.ts & XXX.routing.ts . the url after you import { Anyting } must all in lower case . 

Enviroment: MacOS , node 6.9.1

**Comment by Vishal-vash** [comment]
In my code I resolved this issue by updating:

import { Component, OnInit } from '@angular/Core';
to 
import { Component, OnInit } from '@angular/core';

**Comment by Babazon** [comment]
This is usually a result of a miniscule typo. If you are importing your modules like import angular from 'angular', import React from 'react' => Go through your files and check where you used < from 'React'> or <from 'Angular'>  The error descriptions should have been written more clearly, but what I explained has been the cause of  my problem each time I for this error on webpack commands.

**Comment by protoEvangelium** [comment]
@Babazon For me I had capitalized Radium like this:  `import Radium from 'Radium'` when I should have imported it like this: `import Radium from 'radium'`  

The error went away.

**Comment by mengdu** [comment]
这个应该是命令行的问题，我也遇到的，我今天改了cmder的启动路径
`cmd /k "%ConEmuDir%\..\init.bat"  -new_console:d:e:\`
然后也出现了类似的问题

```
* E:\lanyue\vue\admin-customer\node_modules\.2.2.1@webpack\buildin\global.js
    Used by 1 module(s), i. e.
    E:\lanyue\vue\admin-customer\node_modules\.2.2.1@vue\dist\vue.esm.js
* e:\lanyue\vue\admin-customer\node_modules\.2.2.1@webpack\buildin\global.js
    Used by 2 module(s), i. e.
    e:\lanyue\vue\admin-customer\node_modules\echarts\lib\echarts.js
```
原来是这个盘符写成小写了，于是我改成大写就好了

`cmd /k "%ConEmuDir%\..\init.bat"  -new_console:d:E:\`

**Comment by Razma333** [comment]
i had the same problem and i manage to fix it 
instead of importing the Observable from "rxjs/observable" like so:
`import { Observable } from "rxjs/observable";`

import it from "rxjs/Rx like so:
`import { Observable } from "rxjs/Rx";`

**Comment by birjitningomba** [comment]
Looks like anything after @angular in import statements should be in lower case.
e.g. @angular/core, @angular/router

Sometimes if you type @angular/Core or @angular/Router you may get this error. So check all the places where you have import @angular for incorrect case.

**Comment by namdeom** [comment]
I could resolve the issue after making all folder name small.Earlier I was using camel case and it was failing.

**Comment by zjh65204** [comment]
原来不是我一个人遇到这个问题！

**Comment by fygethub** [comment]
我也遇到了 发现就是一个import  路径的一个字母大小写写错了。

i got the issue like :
```code WARNING in ./app/component/Course/CourseList.jsx
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* /Users/fydor/Desktop/work/CongZhi/wex-front/node_modules/babel-loader/lib/index.js??ref--0-0!/Users/fydor/Desktop/work/CongZhi/wex-front/app/component/Course/CourseList.jsx
    Used by 1 module(s), i. e.
    /Users/fydor/Desktop/work/CongZhi/wex-front/node_modules/babel-loader/lib/index.js??ref--0-0!/Users/fydor/Desktop/work/CongZhi/wex-front/app/component/Course/CourseMore.jsx
* /Users/fydor/Desktop/work/CongZhi/wex-front/node_modules/babel-loader/lib/index.js??ref--0-0!/Users/fydor/Desktop/work/CongZhi/wex-front/app/component/course/CourseList.jsx
    Used by 3 module(s), i. e.
    /Users/fydor/Desktop/work/CongZhi/wex-front/node_modules/babel-loader/lib/index.js??ref--0-0!/Users/fydor/Desktop/work/CongZhi/wex-front/app/component/home/Home.jsx
```

 found my issue, i'm importing like:

//CourseList
import CourseMore from './component/Course/CourseMore.jsx';

the right is like：

//CourseList
import CourseMore from './component/course/CourseMore.jsx';
due to the 'c'

**Comment by fygethub** [comment]
我也遇到了 发现就是一个import  路径的一个字母大小写写错了。

i got the issue like :
```code WARNING in ./app/component/Course/CourseList.jsx
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* /Users/fydor/Desktop/work/CongZhi/wex-front/node_modules/babel-loader/lib/index.js??ref--0-0!/Users/fydor/Desktop/work/CongZhi/wex-front/app/component/Course/CourseList.jsx
    Used by 1 module(s), i. e.
    /Users/fydor/Desktop/work/CongZhi/wex-front/node_modules/babel-loader/lib/index.js??ref--0-0!/Users/fydor/Desktop/work/CongZhi/wex-front/app/component/Course/CourseMore.jsx
* /Users/fydor/Desktop/work/CongZhi/wex-front/node_modules/babel-loader/lib/index.js??ref--0-0!/Users/fydor/Desktop/work/CongZhi/wex-front/app/component/course/CourseList.jsx
    Used by 3 module(s), i. e.
    /Users/fydor/Desktop/work/CongZhi/wex-front/node_modules/babel-loader/lib/index.js??ref--0-0!/Users/fydor/Desktop/work/CongZhi/wex-front/app/component/home/Home.jsx
```

 found my issue, i'm importing like:

//CourseList
import CourseMore from './component/Course/CourseMore.jsx';

the right is like：

//CourseList
import CourseMore from './component/course/CourseMore.jsx';
due to the 'c'

**Comment by zjh65204** [comment]
我自己本机上是由于我写错了路径。全局中定义了 UTIL 变量是 uitls 目录的路径。在开发过程中，我通过UTILS 来调用 utils 目录里的脚本。将所有的 UTILS => UTIL，解决了这个问题！

**Comment by PleaseTryAgain** [comment]
the same problem to me!!
I use git bash to run a project. Then got this issue. then change to cmd run command line the success.
I found cmd root file is UPPER WORD like: 'F',  otherwise git bash root file is lower word like 'f'.
so change git bash to cmd,then issue solved

**Comment by shmup** [comment]
I'll append that using cmd.exe over something like msys2's Git Bash is definitely a solution that will work for many Windows devs.

**Comment by SunilJamkatel** [comment]
I had this error when I required a module with the first letter as capital. For example: I was doing 
`var React = require('React');`

while it should have been 

`var React = require('react');`

**Comment by AuthurWang** [comment]
same problem to me !
maybe webpack path is case-insensitive, if we import  from example.js or Example.js in different files, during compile, webpack will throw this warning.

**Comment by ewild** [comment]
I think I know why this happens. I created a component using the Angular CLI and then tried to created another component in the original folder. My ng lines looked like:

ng g c WorkersCompCode
ng g c workers-comp-code/LaborRole <<< Bad

I tried to add the new component to the filesystem folder. This jacked it up. When I redid the sub component like below it worked fine:

ng g c WorkersCompCode/LaborRole 

Also, if you put a -d for dry run, you can see it will put the component in the path you wanted on the file system.

**Comment by haisumkundi** [comment]
Resolved it, 
what i was doing:
import { ABC } from './guards/ABC'

what resolved the issue:
import { ABC } from './guards/abc'

the name of the file where i had defined ABC was 'abc' where as i was using 'ABC' in import.
Hope it helps

**Comment by Shenchuanhuan** [comment]
I also met this problem today.
I solved it by using @luchillo17 's method.
My system is macOS Sierra 10.12.6

**Comment by luchillo17** [comment]
@Shenchuanhuan Nice :smile:.

**Comment by maccurt** [comment]
I solved it by using @luchillo17 's method.

**Comment by sanazBG** [comment]
Using react .. It doesn't matter how you type the driver letter .. Any folder in my server directory(including the server directory) should be typed with small letters .. that fixed the warning for me and got a "Compiled Successfully" absolutely every warning came from my "client" directory .. thats on Windows.

**Comment by benjamin21st** [comment]
This is not just a windows-issue, I had the same issue on Mac when I wrote:

import { Observable } from 'rxjs/**O**bservable';
import { of } from 'rxjs/**O**bservable/of';

Notice that I used uppercase "O".

I fixed with

import { Observable } from 'rxjs/observable';
import { of } from 'rxjs/observable/of';

And it worked :)

**Comment by yussan** [comment]
i solved my warning the same as above by removing the file/folder name using capital to lowercase.

**Comment by jazzfog** [comment]
I had this issue on Windows and it was a funny one:

First I noticed that difference in case was in my path to my dev folder, not in app itself
```
d:\Web\JavaScriptApps\MyApp\node_modules\webpack\buildin\global.js
vs
d:\web\JavaScriptApps\MyApp\node_modules\webpack\buildin\global.js
```
`Web` folder is capital in first case, though real folder name is `web`.

Initially I thought that there is something wrong with `Webpack` or `Node` path resolver but later I noticed that path showing in the `console` window I was working in is actually `d:\Web\...`

Obviously it was wrong and as I opened new console with correct path - everything was fine with my app.

So I started to think how could it happen and I found that one of the shortcuts in my environment had wrong target path `d:/Web/...` because I copied it from my older desktop where `web` folder had actually capitalized name `Web`. So I got this wrong context and it confused the node app.

**Comment by dengshenkk** [comment]
I found this to be the result of a mix of windows and Mac development

**Comment by smoetje** [comment]
I have the same issue, it came just "out of the blue" without any reason.  It worked fine until yesterday evening.  Working on Windows 10 with latest node, mpm and git bash.  It was rather frustrating... but got it back to work when using the windows command, instead of git bash.  Interesting enough in my case, I work on Windows (7 & 10) only (no mac here).

` warning  in C:/Users/nicol/LaravelProjects/oostendezingt/node_modules/webpack/buildin/global.js

There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* C:\Users\nicol\LaravelProjects\oostendezingt\node_modules\webpack\buildin\global.js
    Used by 2 module(s), i. e.
    C:\Users\nicol\LaravelProjects\oostendezingt\node_modules\punycode\punycode.js
* C:\Users\nicol\Laravelprojects\oostendezingt\node_modules\webpack\buildin\global.js
    Used by 2 module(s), i. e.
    C:\Users\nicol\Laravelprojects\oostendezingt\node_modules\lodash\lodash.js

 warning  in C:/Users/nicol/LaravelProjects/oostendezingt/node_modules/webpack/buildin/module.js

There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* C:\Users\nicol\LaravelProjects\oostendezingt\node_modules\webpack\buildin\module.js
    Used by 1 module(s), i. e.
    C:\Users\nicol\LaravelProjects\oostendezingt\node_modules\punycode\punycode.js
* C:\Users\nicol\Laravelprojects\oostendezingt\node_modules\webpack\buildin\module.js
    Used by 1 module(s), i. e.
    C:\Users\nicol\Laravelprojects\oostendezingt\node_modules\lodash\lodash.js

 warning  in C:/Users/nicol/LaravelProjects/oostendezingt/node_modules/webpack/hot/emitter.js

There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* C:\Users\nicol\LaravelProjects\oostendezingt\node_modules\webpack\hot\emitter.js
    Used by 1 module(s), i. e.
    C:\Users\nicol\LaravelProjects\oostendezingt\node_modules\webpack-dev-server\client\index.js?http://localhost:8080
* C:\Users\nicol\Laravelprojects\oostendezingt\node_modules\webpack\hot\emitter.js
    Used by 1 module(s), i. e.
    C:\Users\nicol\Laravelprojects\oostendezingt\node_modules\webpack\hot\dev-server.js

 warning  in C:/Users/nicol/LaravelProjects/oostendezingt/node_modules/webpack/hot/log.js

There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* C:\Users\nicol\LaravelProjects\oostendezingt\node_modules\webpack\hot\log.js
    Used by 1 module(s), i. e.
    C:\Users\nicol\LaravelProjects\oostendezingt\node_modules\webpack\hot nonrecursive /^\.\/log$/
* C:\Users\nicol\Laravelprojects\oostendezingt\node_modules\webpack\hot\log.js
    Used by 2 module(s), i. e.
    C:\Users\nicol\Laravelprojects\oostendezingt\node_modules\webpack\hot\dev-server.js`

**Comment by BayuP** [comment]
i have same problem here when i create new react app this is always appear even when i open my old project i already use lowercase and i didnt know how to fix it

**Comment by YvonneD** [comment]
I think the reason is when you cd to the project file ,the name have Capital issue,such as you want to cd to your desktop,you should check the folder name in your computer,lower case or upper case. 
My computer is "Desktop",so I should type "cd ~/Desktop/projectname". Then it should be all done.

**Comment by HiIcy** [comment]
I have same problem here,but I am in Vue O(∩_∩)O. @mengdu 感谢，我也是用的cmder 发现竟然是盘符问题呜呜，给跪了

**Comment by George35mk** [comment]
I solved by moving the files that have the problem into another directory 
- then I checked for uppercase if I found some files with uppercase I renamed this files to lower case
- and then i paste the files back again.

**Comment by zhuy2018** [comment]
我也遇到这个问题了
 warning  in F:/Web/vue-cli/vue-examplel/node_modules/webpack/buildin/global.js

There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* F:\Web\vue-cli\vue-examplel\node_modules\webpack\buildin\global.js
    Used by 2 module(s), i. e.
    F:\Web\vue-cli\vue-examplel\node_modules\_sockjs-client@1.1.4@sockjs-client\dist\sockjs.js
* f:\Web\vue-cli\vue-examplel\node_modules\webpack\buildin\global.js
    Used by 1 module(s), i. e.
    f:\Web\vue-cli\vue-examplel\node_modules\vue\dist\vue.esm.js

应该怎么解决的？？

**Comment by zhuy2018** [comment]
我解决了，原来不是盘符原因，只要把文件删除了，然后重新导入就OK。
这坑踩的深，后面人跳过此坑！！！！！！！

**Comment by PietroLaGrotta** [comment]
Simply if you capitalize a file name that is already imported in ather files of you project, node js explodes. It become creazy. I returned the file name to lowercase and node js is returned to run happily :-)

**Comment by Tech007Harsh** [comment]
WARNING in ./node_modules/@Angular/common/fesm5/http.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a
filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* F:\CodeLoverTechnology\Development\Web_Development\NirmanIASWeb\NirmanIASPortal\node_modules\@Angular\common\fesm5\http.js
    Used by 16 module(s), i. e.
    F:\CodeLoverTechnology\Development\Web_Development\NirmanIASWeb\NirmanIASPortal\node_modules\@ngtools\webpack\src\index.js!F:\CodeLoverTechnology\Development\Web_Development\NirmanIASWeb\NirmanIASPortal\src\app\app.module.ts* F:\CodeLoverTechnology\Development\Web_Development\NirmanIASWeb\NirmanIASPortal\node_modules\@angular\common\fesm5\http.js
    Used by 4 module(s), i. e.
    F:\CodeLoverTechnology\Development\Web_Development\NirmanIASWeb\NirmanIASPortal\node_modules\@ngtools\webpack\src\index.js!F:\CodeLoverTechnology\Development\Web_Development\NirmanIASWeb\NirmanIASPortal\src\app\Services\SubCategoryService\sub-category-master.service.ts

**Comment by Tech007Harsh** [comment]
i am also encountering this problem.. i have services to post and get, two of them are working fine but others are not and showing 400 bad request ... but nothing is wrong in the code..i think i am encountering unexpected behavior while compiling,i am posting other service and the source is showing other html and hence giving 400 bad request.

**Comment by Isaquedias** [comment]
No meu caso eu tenha uma pasta
/Pages
troquei por
/pages

coloquei em minusculo

**Comment by ivan-nemtinov** [comment]
> There are multiple modules with names that only differ in casing.
A solution for VSCode users on Windows. The error appears when a default shell is "Command prompt", which uses small letters for drive names. So, (CTRL+P) open a command palette, enter a command  "Terminal: Select default shell", and choose Powershell or Bash.

**Comment by const-int** [comment]
In my case it was lowercase `user` folder in the path.

I changed `C:\users\admin\project` to `C:\Users\admin\project` and it works fine.

Windows 10, PowerShell

**Comment by vuongvgc** [comment]
> If u use VS Code try change path to project from
> c:[path to angular2-webpack-starter]
> to
> C:[path to angular2-webpack-starter]
> 
> in @dyh333 case fix:
> `e:\GitHub\angular2-webpack-starter> cd E:\GitHub\angular2-webpack-starter`
> `npm start`
> in your terminal or cli

thanks. This is my issue. So i can fix.

**Comment by ShahriarKh** [comment]
Had the same problem in a react project.
Solution: I was naming a css file in camelCase 😑

**Comment by naveenmorla1901** [comment]
I changed my project path 
ex:  C:\Users\name\documents\project\ to C:\Users\name\Documents\Project\
Check for the original format in the folder location and try changing it.
