### ISSUE TITLE
How to exclude the nested node_modules from loading jQuery?

### ISSUE THREAD

**Issue by daominhsangvn** [AngularClass/angular2-webpack-starter#932]
I'm trying to load a jQuery plugin into my project. But i found out the jQuery instance not loaded correctly. The jQuery plugin trying to load the jQuery instance from jQuery folder that placed inside the plugin (node_modules/jquery...). My main jQuery version is 3.1.0 but the plugin trying to load jQuery which is version 1.11.0

![2016-08-31_9-57-18](https://cloud.githubusercontent.com/assets/8254183/18114532/ede37e56-6f61-11e6-9e34-7dd61c195218.png)

Here my configuration
`webpack.common.js`
```
const node_dir = __dirname + '/node_modules';

...

resolve:{
      alias: {
        'jquery': node_dir + '/jquery/dist/jquery.js'
      }
    }

...

plugins:{

...

new webpack.ProvidePlugin({
      jQuery: 'jquery',
      $: 'jquery',
      jquery: 'jquery'
    })

...

}

```
`component.ts`
```
...

import * as $ from 'jquery';
require('jqvmap');

...

ngOnInit() {
     $(this.container).vectorMap(this.config)
}

...
```
Then i got the error in the browser console
`$(...).vectorMap is not a function`
It's because the jQuery instance between main module and the plugin are difference

How can i resolve this?

**Update 1:**
Tried to add more alias and use imports-loader to import jQuery to the plugin
alias: `'jq': require.resolve('jquery')`
import jQuery in `component.ts`: `require('imports?jQuery=jq!jqvmap')`
Then do `require('jq') in the jQuery plugin`. It's says `Cannot find module "jq"`

Update 2:
Kind of hacks and i dont like this way
This code will inject `var jQuery = require('./../../jquery')` into the plugin to make it load the same jquery with the webpack
`require('imports?jQuery=./../../jquery!jqvmap');`

**Comment by IAMtheIAM** [comment]
I think that's not correct how you're doing it. You should use `[expose-loader](https://github.com/webpack/expose-loader)` because it is meant for handling global libraries like jQuery

**Comment by rubenCodeforges** [comment]
better forgot about jQuery :P

**Comment by daominhsangvn** [comment]
Thanks @IAMtheIAM. I have tried your solution but it still not work either.
Anyway, I found the fix for my problem. The fix is simple.
```

entry: {
    'lib': [
      'jquery',
      'angular'
    ],
    'vendor': [/*angular vendor list*/],
    'main': './src/main.browser.js'
  },

...

plugins: [
   // This is magic code that fix my issue
   new CommonsPlugin({
      minChunks: 3,
      name: "lib"
    })
]

...
```

@rubenCodeforges : Yeah i know i should but some plugin still need jQuery i guest i will stick with him :dancer:

Closed!
