### ISSUE TITLE
Getting Error in running server:dev:hmr

### ISSUE THREAD

**Issue by mohsenvafa** [AngularClass/angular2-webpack-starter#933]
* **I'm submitting a ...**
[ ] bug report

I cloned the code and tried to run npm run server:dev:hmr but I get following error:
it was working a few days ago, but recently i get this issue

![image](https://cloud.githubusercontent.com/assets/5973501/18115052/01f5b916-6ef1-11e6-8167-9364fa581cc5.png)

**Comment by Avareto** [comment]
Same errors when running `npm start`

**Comment by jshamley** [comment]
same as this issue https://github.com/AngularClass/angular2-webpack-starter/issues/930

**Comment by katallaxie** [comment]
Same answer https://github.com/AngularClass/angular2-webpack-starter/issues/935#issuecomment-243697431. Could you try to run this on 59b4e04. The issue is related to `typescript`. This should be `typescript@2.0.0`.

**Comment by katallaxie** [comment]
https://github.com/AngularClass/angular2-webpack-starter/issues/934#issuecomment-243834589
