### ISSUE TITLE
Errors running 'npm run build:prod'

### ISSUE THREAD

**Issue by Avareto** [AngularClass/angular2-webpack-starter#934]
c:\Projects\angular2-webpack2-starter\angular2-webpack-starter>npm run build:prod

> angular2-webpack-starter@5.0.5 prebuild:prod c:\Projects\angular2-webpack2-starter\angular2-webpack-starter
> npm run clean:dist

> angular2-webpack-starter@5.0.5 clean:dist c:\Projects\angular2-webpack2-starter\angular2-webpack-starter
> npm run rimraf -- dist

> angular2-webpack-starter@5.0.5 rimraf c:\Projects\angular2-webpack2-starter\angular2-webpack-starter
> rimraf "dist"

> angular2-webpack-starter@5.0.5 build:prod c:\Projects\angular2-webpack2-starter\angular2-webpack-starter
> webpack --config config/webpack.prod.js  --progress --profile --6066ms building4ms a4961m1ms ch 94% asset optimizationError in bail mode: [default]
Cannot find global type 'Array'.

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build:prod"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! angular2-webpack-starter@5.0.5 build:prod: `webpack --config config/webpack.prod.js  --progress --profile --bail`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-webpack-starter@5.0.5 build:prod script 'webpack --config config/webpack.prod.js  --progress --profile --bail'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-webpack-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack --config config/webpack.prod.js  --progress --profile --bail
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-webpack-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-webpack-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\Projects\angular2-webpack2-starter\angular2-webpack-starter\npm-debug.log

**Comment by katallaxie** [comment]
See https://github.com/AngularClass/angular2-webpack-starter/issues/935#issuecomment-243697431

**Comment by Avareto** [comment]
Ok, changing es5 to es6 in tsconfig.json will let me run `npm start` successfully. But `npm run build:prod` still fails with the same error (see above). Its more webpack related than typescript, I guess. 

I also uninstalled nodejs 6.x (removed npm cache and all remaining files). Then I installed node 4.5 again, cloned the repro run `npm install` and than `npm start` then I received this error.

C:\Projects\angular2-webpack2-master\angular2-webpack-starter>npm install
npm WARN peerDependencies The peer dependency webpack@1.x.x || 2.x.x included from string-replace-loader will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency jasmine-core@* included from karma-jasmine will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency webpack@* included from html-webpack-plugin will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency webpack@* included from @angularclass/hmr will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN deprecated wrench@1.5.8: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
npm WARN peerDependencies The peer dependency webpack@* included from angular2-hmr will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN optional dep failed, continuing fsevents@1.0.14
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN peerDependencies The peer dependency @angular/core@* included from @angular/router will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency @angular/compiler@* included from @angular/router will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency @angular/common@* included from @angular/router will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency @angular/platform-browser@* included from @angular/router will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency @angular/platform-browser-dynamic@* included from @angular/router will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency rxjs@* included from @angular/router will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.

> execSync@1.0.2 install C:\Projects\angular2-webpack2-master\angular2-webpack-starter\node_modules\angular2-template-loader\node_modules\codecov\node_modules\execSync
> node install.js

[execsync v1.0.2] Attempting to compile native extensions.
{ [Error: spawn node-gyp ENOENT]
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn node-gyp',
  path: 'node-gyp',
  spawnargs: [ 'rebuild' ] }
[execSync v1.0.2]
    Native code compile failed!!
    Will try to use win32 extension.
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN optional dep failed, continuing fsevents@1.0.14
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package @angular/common@2.0.0-rc.5 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer @angular/forms@0.3.0 wants @angular/common@^2.0.0-rc.5
npm ERR! peerinvalid Peer @angular/platform-browser@2.0.0-rc.5 wants @angular/common@^2.0.0-rc.5
npm ERR! peerinvalid Peer @angular/platform-browser-dynamic@2.0.0-rc.5 wants @angular/common@^2.0.0-rc.5
npm ERR! peerinvalid Peer @angular/platform-server@2.0.0-rc.5 wants @angular/common@^2.0.0-rc.5
npm ERR! peerinvalid Peer @angular/router@3.0.0-rc.2 wants @angular/common@*

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Projects\angular2-webpack2-master\angular2-webpack-starter\npm-debug.log

**Comment by jshamley** [comment]
Try pulling down the latest code from the repo. I had this same issue, but it is working now after some code updates in the repo.

**Comment by katallaxie** [comment]
ok, your last error seems to be the problem of `npm` not to be `>= 3`. Is this `4.5.0`.

**Comment by Avareto** [comment]
It works, Thanks!
After
1. Uninstalling nodejs. 6.5 (including all remaining folder and files on the filesystem)
2. Installing nodejs 4.5
3. updateing npm via` npm -i npm -g `
4. cloning the current repro
5. `npm install`
`npm start` and `npm run build:prod` are running without any errors!
One last question: Is nodejs 4.5 mandatory?

**Comment by katallaxie** [comment]
No, it is just a suggestion. It runs with `6.5.0` as well.
