### ISSUE TITLE
Error when running webpack: No Directive annotation found on NKDatetime

### ISSUE THREAD

**Issue by lrezmeri082015** [AngularClass/angular2-webpack-starter#936]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a BUG
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
In the vendor.ts file I added this line: import 'ng2-datetime/ng2-datetime';
The build is successful but when the page loads I get an error that there is a missing directive (NKDatetime), although it appears in vendor.js
The error appears at this line: var metadata = typeMetadata.find(_isDirectiveMetadata);
_isDirectiveMetadata(type) returns false and metadata is null.
NKDatetime is actually a component.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via

* **What is the expected behavior?**
typeMetadata.find(_isDirectiveMetadata) should not return null.

* **What is the motivation / use case for changing the behavior?**
Cannot build webpack

* **Please tell us about your environment:**
Windows 7
- Angular version: 2.0.0-RC.5
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by wartab** [comment]
I have the same exact bug with that package, but it does not seem to be related to angular2-webpack-starter, since it also happens by just using webpack. I guess it's ng2-datetime that did not do something correctly (or at least is not compliant with RC5).

**Comment by lrezmeri082015** [comment]
It's not related to webpack, it's because NKDateTime dépends on angular RC4.
