### ISSUE TITLE
NativeScript Integration

### ISSUE THREAD

**Issue by smith64fx** [AngularClass/angular2-webpack-starter#937]
Hey guys,
We are currently trying to create native apps from our angular2 webpack starter created projects.

Is there an easy way to create an app from the webpack starter for iOS/Android, that behaves like the browser web app? (same but with fullscreen mode). 

It doesn't have to be nativescript, if there exists another possibility like Ionic 2.. Maybe somebody has good experiences with it.

**Comment by katallaxie** [comment]
Ionic 2 is build upon PhoneGap; so it is a glorified WebView on the various supported platforms. NativeScript 2.x has moved to same approach as ReactNative; which are both different animals. So, you have decide if you want to go with the Ionic approach, or the other. I would highly recommend second. There is a new an interesting project https://github.com/angular/react-native-renderer which essentially uses Angular 2 on the JavaScript UI Control Thread.

**Comment by smith64fx** [comment]
@katallaxie thank you!

The problem with the react-native-renderer approach ist, that we lose the advantage of webpack. I really like this repository as a boilerplate for angular2 apps.

**Comment by katallaxie** [comment]
With some additions, like icons, and somethings in the index.html you can use everything that is in `dist` deploy it via Cordova to any device. Perhaps you could draw something of https://github.com/katallaxie/generator-i-want-nice-ng-cordova which I created a while ago.

**Comment by smith64fx** [comment]
@katallaxie thx for your second proposal. but isn't there anything to consider when using webpack?

**Comment by katallaxie** [comment]
It just a glorified Browser 😄 .

**Comment by smith64fx** [comment]
![image](https://cloud.githubusercontent.com/assets/3246782/18180268/5f172382-7086-11e6-88a9-b0c837868160.png)

**Comment by katallaxie** [comment]
Cordova just wraps a WebView and opens the files in the filesystem with it.

**Comment by smith64fx** [comment]
ah okay, so webpack renders the stuff to the /dist folder and cordova takes the shit and wraps the awesome WebView! Sheeesh

**Comment by katallaxie** [comment]
Yep! 🎱 Again, you could take some generator and mix it with the starter.

**Comment by smith64fx** [comment]
![image](https://cloud.githubusercontent.com/assets/3246782/18180731/6b4237ee-7088-11e6-9d49-f4a45281c760.png)
