### ISSUE TITLE
the resulted vendor bundle is about 2.6mb, this is too large, how to fix that?

### ISSUE THREAD

**Issue by eslammostafa** [AngularClass/angular2-webpack-starter#943]
Hey Guys,

i have just cloned the repo, then installed the packages with npm install
then i started to make a build

`npm run build`

while looking at the resulted files, webpack says the vendor bundle is 2.5mb 

this is very large, isn't webpack2 usung tree-shaking by default ?

anyway, how to reduce the size of the vendor bundle, from 2.5mb to something like 200kb ?

**Comment by zigzag95** [comment]
npm run build:prod

**Comment by eslammostafa** [comment]
okay that dropped the vendor bundle to 972kb, its better than 2.6mb but its still large, is there more techniques to reduce that size?

**Comment by katallaxie** [comment]
You would probably deliver the `.js` with gzip. To reduce load on the server for this, you can use https://github.com/webpack/compression-webpack-plugin

**Comment by eslammostafa** [comment]
okay on it, but its unclear to me how to use the resulted *.gz files

**Comment by katallaxie** [comment]
E.g. http://nginx.org/en/docs/http/ngx_http_gzip_static_module.html

**Comment by katallaxie** [comment]
Beside, I have created #944 which seems to even more reduce the final size of Angular 2.
