### ISSUE TITLE
Code churn on Master

### ISSUE THREAD

**Issue by d3viant0ne** [AngularClass/angular2-webpack-starter#948]
* **I'm submitting a ...**
[X] question about the decisions made in the repository

@katallaxie

While the enthusiasm is great, just slamming home changes without others having the opportunity to vet those changes kind of defeats the point of `community` & `code review`. 30 Commits directly to master, to include those to fix or remove features that shouldn't have landed between 27 Sept & 01 Aug.

It also means that everyone that uses the webpack-starter as a base project has to pick up those changes and merge them into what is usually a modified project, it gets tedious quickly.

I'm suggesting you start delivering changes as `complete, tested & vetted sets of work` through the standard `pull request` workflow that everyone else uses thus making the update process less labor intensive and less prone to blowing up peoples forks (which happened to me last week). 

`Landing your own code` is generally `frowned upon` and for good reason. A second ( or multiple ) sets of eyes is never, ever a bad thing.

![screen shot 2016-09-02 at 8 23 50 am](https://cloud.githubusercontent.com/assets/8420490/18205263/a9dad192-70e6-11e6-8701-664f551ede99.png)

//cc @gdi2290

**Comment by katallaxie** [comment]
This was in my PR https://github.com/AngularClass/angular2-webpack-starter/pull/944. Which I had @gdi2290 ask to comment on.

**Comment by d3viant0ne** [comment]
Which you then merged yourself

**Comment by katallaxie** [comment]
Yep, if so this caused you trouble, then I apologize for that. I thought it would be best, as Angular is not final, to keep up with development to be stable or 'more' production ready as soon as possible. Perhaps it would be best to work with the gitflow and create a develop branch.

**Comment by d3viant0ne** [comment]
I'm not suggesting adding full `gitflow` as it usually feels like overkill, even for most of my professional stuff.

What I am suggesting is code not be committed directly to `origin/master` and rather using a standard `pull request workflow` where changes are PR'd, reviewed & then merged by a party != the authoring dev.

**Comment by katallaxie** [comment]
I fully agree on the review, and on the need to have all tests passed (fixed this with https://github.com/AngularClass/angular2-webpack-starter/commit/63b241953f9bf9d5c70fbb787b5738db7191989e), but I do not fully agree on the merge itself.
