### ISSUE TITLE
error while building my project

### ISSUE THREAD

**Issue by eslammostafa** [AngularClass/angular2-webpack-starter#949]
i am trying to build my project "angular rc6" on a digital ocean server, ubuntu 16.04

and i am getting this error

`Cannot read property 'glob' of undefined`

https://gist.github.com/eslammostafa/c0a556294ed06bf81e4e6650698f468f

any clue how to fix this?

**Comment by eslammostafa** [comment]
never mind, i had to clone the new rc6 repo and add my files again.

**Comment by bobRafat** [comment]
@eslammostafa I have the same issue. How did you fix it?
