### ISSUE TITLE
Provide a notes to upgrade from Angular RC2 to RC6

### ISSUE THREAD

**Issue by amitkverma** [AngularClass/angular2-webpack-starter#951]
When I have taken this project at that time when it was Angular RC2. I want to upgrade my project to Angular RC6 So please provide notes to update the project.

**Comment by binarious** [comment]
Just compare the commits. I've started three projects with this repo since the alpha phase and upgraded them to RC5 by noting the last commit hash I aligned my project to in the package.json and by comparing it then to the latest version here.

**Comment by codespicelabs** [comment]
IMO You will not be able to upgrade material2 webpack starter branch to Angular 2 RC.6 event with the latest Material2 (2.0.0-alpha.8-1) in bloodless and simple way, there are a lot of strange and buggy moments there.
I hope that in the nearest future angular-cli will do that in the right way for webpack and than we'll be able to reimplement all the caveats for this starter
see https://github.com/angular/angular-cli/pull/1937

**Comment by fxck** [comment]
Just start over.

**Comment by binarious** [comment]
@codespicelabs That's not true. I've just migrated an app with material2 2.0.0-alpha.8-1 to RC6.

**Comment by codespicelabs** [comment]
@binarious well then, will try to compare and figure out what's wrong with my configs and tool's versions.
i've spent a lot of time trying to migrate. thx for your response

**Comment by binarious** [comment]
@codespicelabs Good luck :). Ping me on Gitter if you need help.

**Comment by amitkverma** [comment]
Thank you.I guess I will make a note of upgrading after I will finish upgrading.

**Comment by IAMtheIAM** [comment]
You might want to wait until Angular 2 final comes out. It should happen in a few more weeks.

**Comment by amitkverma** [comment]
waiting for that 👍
