### ISSUE TITLE
@angular2-material 2.0.0-alpha.8 not working

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [AngularClass/angular2-webpack-starter#956]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[ x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
When using the latest release of angular2-webpack-starter with angular 2.0.0-rc.6, when trying to integrate angular2 material from the material branch, and using version: 2.0.0-alpha.8 I get:
(Running the app does not work, Is it possible to upgrade the material branch so I can see where the problem lies?)

WARNING in ./~/@angular2-material/sidenav/index.js
3:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/button-toggle/index.js
3:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/card/index.js
3:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/grid-list/index.js
3:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/icon/index.js
3:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/button/index.js
3:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/checkbox/index.js
3:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/list/index.js
3:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/input/index.js
3:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/menu/index.js
3:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/progress-circle/index.js
3:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/radio/index.js
3:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/progress-bar/index.js
3:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/slider/index.js
3:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/slide-toggle/index.js
3:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/toolbar/index.js
3:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/tooltip/index.js
3:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/tabs/index.js
3:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/sidenav/sidenav.js
20:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/button-toggle/button-toggle.js
15:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/grid-list/grid-list.js
15:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/card/card.js
12:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/checkbox/checkbox.js
12:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/icon/icon.js
17:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/input/input.js
17:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/list/list.js
12:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/button/button.js
17:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/menu/menu.js
12:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/progress-circle/progress-circle.js
17:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/progress-bar/progress-bar.js
12:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/radio/radio.js
15:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/slider/slider.js
12:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/slide-toggle/slide-toggle.js
12:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/tooltip/tooltip.js
12:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/toolbar/toolbar.js
12:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/tabs/tabs.js
12:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/grid-list/grid-tile.js
12:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/grid-list/tile-styler.js
8:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/grid-list/grid-list-errors.js
8:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/grid-list/grid-list-measure.js
3:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/grid-list/tile-coordinator.js
3:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/icon/icon-registry.js
17:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/menu/menu-item.js
12:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/menu/menu-trigger.js
12:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/menu/menu-directive.js
16:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/tabs/tab-content.js
17:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/tabs/tab-label-wrapper.js
12:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/tabs/ink-bar.js
12:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/tabs/tab-label.js
17:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/core/index.js
3:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/menu/menu-errors.js
8:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/core/core.js
12:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/core/line/line.js
12:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/core/rtl/dir.js
12:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/core/ripple/ripple.js
12:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/core/portal/portal-directives.js
17:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/core/portal/portal.js
8:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/core/portal/dom-portal-host.js
8:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/core/overlay/overlay-directives.js
12:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/core/overlay/overlay.js
12:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/core/overlay/overlay-ref.js
3:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/core/overlay/overlay-state.js
3:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/core/overlay/overlay-container.js
3:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/core/a11y/live-announcer.js
15:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/core/overlay/position/connected-position-strategy.js
3:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/core/overlay/position/connected-position.js
3:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/core/gestures/MdGestureConfig.js
17:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/core/coordination/unique-selection-dispatcher.js
12:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/core/style/apply-transform.js
3:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/core/errors/error.js
9:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/core/annotations/field-value.js
3:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/core/keyboard/keycodes.js
7:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/core/ripple/ripple-renderer.js
3:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/core/portal/portal-errors.js
8:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/core/overlay/position/overlay-position-builder.js
12:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/core/overlay/position/viewport-ruler.js
12:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/@angular2-material/core/overlay/position/global-position-strategy.js
3:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

**Comment by abdulhaq-e** [comment]
They've released `2.0.0-alpha.8-1`. I think you can also obtain it using `@latest`.

**Comment by LanderBeeuwsaert** [comment]
thanks, solved by using 2.0.0-alpha.8-1
