### ISSUE TITLE
Uncaught TypeError: t.match is not a function , in production mode only

### ISSUE THREAD

**Issue by eslammostafa** [AngularClass/angular2-webpack-starter#958]
* **I'm submitting a ...**
[*] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**
my app works correctly in development server, but when i try to run it in production
with

`npm run server:prod`

it generates errors in the web console, here is the full error:

https://gist.github.com/eslammostafa/14340268bc17040c049d8f1cc46da459

and here is my app.module.ts:

https://gist.github.com/eslammostafa/f33363431880de551556a11786ba9f46

environment:

- Angular version: 2.0.0-rc.6
- Browser: Chrome
- Operating System : tried on mac os x and on ubuntu 16.04

**Comment by kangw3n** [comment]
Same issues here, likely happened  in all build scripts

**Comment by smith64fx** [comment]
Needs definetely fix!

```
npm run server:dev
```

still works.

**Comment by eslammostafa** [comment]
it might worth mentioning that if i run
`npm run build:dev`
then
`npm run server:prod`

it runs fine without any errors, so the problem happens when we make a build for production
with
`npm run build:prod`

**Comment by eslammostafa** [comment]
this seems related but it was in rc.5, and they said that they have solved it in rc.6
https://github.com/angular/angular/issues/10618

**Comment by eslammostafa** [comment]
i managed to fix this temporarily with the help from this issue

https://github.com/angular/angular/issues/10626

in the file url_resolver.js in node_modules/
search for

`function _split(uri){`

and inside it add

`uri += ''`

the whole code will look like this
```
function _split(uri) {
    uri += '';
    return uri.match(_splitRe);
}
```

**Comment by smith64fx** [comment]
Why is this closed? The bug still exists!

**Comment by eslammostafa** [comment]
i guess its an angular 2 issue, should we reopen the issue in this repo ?

**Comment by RDalziel** [comment]
Also getting this problem - is there a better solution without making modifications inside node_modules?

**Comment by a-pavlov-parc** [comment]
Anyone found the solution? I still have the problem

**Comment by eslammostafa** [comment]
@RDalziel i didn't find anything yet, but i didn't try the final version of angular.

@a-pavlov-parc  there is this temporarily soultion i mentioned above in 

https://github.com/AngularClass/angular2-webpack-starter/issues/958#issuecomment-244923326

**Comment by norhamizan** [comment]
remove all module.id in your components

**Comment by florian-wahl** [comment]
Is there any fix? Cause removing the module.id from each component or adding .toString() after module.id (works also) is not a viable solution if you want to use someone else components...

Any proposition?

**Comment by eslammostafa** [comment]
it works for me in the final angular version without any changes needed

**Comment by xLama** [comment]
If you update Angular to 2.1 It show an error "module.id must be a string". I guess is a Angular issue because NodeModule.id is a string but it works if you write module.id.toString(). It has no sense.

**Comment by itayJoseph** [comment]
@norhamizan  Thank you very much . 
Removing all module.id's fixed the issue!.
I used a theme I bought and it seems they had those left somewhere so i removed it and it **worked**!.

**Comment by FilipLitwora** [comment]
Hi! I have the same bug but im using webpack, without angular/raect etc. Any ideas?
My config:
`const path = require("path");
const paths = {
  obj: path.join(__dirname, "./src/assets/")
};
module.exports = {
  mode: "production",
  entry: "./src/index.js",
  module: {
    rules: [
      {
        test: /\.(png|svg|jpg|gif)$/,
        use: ["file-loader"]
      },
      {
        test: /\.obj$/,
        loader: "url-loader",
        include: paths.obj
      }
    ]
  },
  output: {
    filename: "main.js",
    path: path.resolve(__dirname, "dist")
  }
};
`
