### ISSUE TITLE
Debugging from VSCode not working when the dev server uses https flag

### ISSUE THREAD

**Issue by Tre665** [AngularClass/angular2-webpack-starter#962]
* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**
The recent update of this repo includes the great addition to debug the app with VSCode out of the box. 
Unfortunately we need the dev server to serve the site from HTTPS domain because
- we authorize the user via OAuth2 / OpenId connect 
- our backend server only allow (authorized) connections via HTTPS / TLS 
To serve the app via SSL I added the `--https` flag to the startup flags of the WebPack dev server and added the following startup script to the `package.json` file.

`"server:dev:ssl": "npm run server:dev -- --https"`

With that change the login and the API calls work, but unfortunately the debugging from Visual Studio doesn't work anymore.

The output in the console is the following:

`  ›SourceMaps.loadSourceMapContents: Could not download sourcemap from https://localhost:3000/polyfills.map
  ›SourceMaps.loadSourceMapContents: Could not download sourcemap from https://localhost:3000/polyfills.bundle.js.map
  ›SourceMaps.loadSourceMapContents: Could not download sourcemap from https://localhost:3000/vendor.map
  ›SourceMaps.loadSourceMapContents: Could not download sourcemap from https://localhost:3000/vendor.bundle.js.map
  ›SourceMaps.loadSourceMapContents: Could not download sourcemap from https://localhost:3000/main.map
  ›SourceMaps.loadSourceMapContents: Could not download sourcemap from https://localhost:3000/main.bundle.js.map`

My first thought was that i missed a config or something and that the sourcemaps may be still served from http://localhost and not from https://localhost.
So I checked the Urls and it seams that the maps are generated correct. 
In the browser the requested URLs
- https://localhost:3000/polyfills.map
- https://localhost:3000/vendor.map
- https://localhost:3000/main.map
returns the sourcemaps correctly from https.

To further debug the issue i enabled the VSCode Chrome Debuggers diagnostic loging feature via the following addition in the config file for the debugger ( `.vscode/launch.json`). 

`"diagnosticLogging": true,`

Unfortunately with no new hints that could help to solve the issue.
I can post the logs if it somewhat helps.

As a side note: 
When I debug in Chrome the breakpoints are hit correctly (although not in my current project which is not updated to Webpack 2 yet, but it works with the current master) 

* **What is the expected behavior?**
That the breakpoints are also hit within VSCode with https enabled

* **Please tell us about your environment:**
- latest master
- node v 6.3
- npm 3.10.3
- Tested on Mac OSX 10.10.5 and Windows 10 (without the anniversary update)
- Angular RC6
- Browser: all
- Webpack 1 (OSX) and Webpack 2(Win)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

I am not sure if it is an issue of this repo or webpack dev server or the chrome debugger or that I made something wrong with the configuration (still learning webpack).
Because I think that this is a common requirement (use https) I hope that someone has also run into this issue which can help to solve the issue.
I also think that the https extension would be a good addition to this great repo.

**Comment by panuruj** [comment]
I am hitting the same issue as well with https and vscode. I did not have the problem with http webpack-dev-server.

**Comment by Tre665** [comment]
Hi, 
it seems this is / was a bug in the chrome-debugger extension itself which will be fixed in one of the next updates.

**Comment by NKjoep** [comment]
Any link or reference to the mentioned issue? @Tre665

**Comment by Tre665** [comment]
@NKjoep Sure, sorry that i forgot to link to it in the first place:

https://github.com/Microsoft/vscode-chrome-debug/issues/224
