### ISSUE TITLE
Errors after migration from RC4 to RC6 - length of null in component

### ISSUE THREAD

**Issue by bruno-serfe** [AngularClass/angular2-webpack-starter#970]
* **I'm submitting a ...**
[x] issue report (I don't know if this is a bug, I'm not sure)

* **What is the current behavior?**
With my current created components using previous version of angular2 webpack with angualr2 rc.4
This issue wasn't arise:

![error_angualr2_rc6](https://cloud.githubusercontent.com/assets/11821195/18315059/f1d4be5a-74eb-11e6-9ddf-6afa5b890791.png)

I'm receiving an error in the flatten function of this file: flatten (http://192.168.33.10:3000/vendor.bundle.js:8198:33)

Removing the html from the sidebar.component.html the component error disappear but the vendor.bundle.js error ORIGINAL EXCEPTION: Cannot read property 'length' of 'null' is still there.

Here is the function that throw the error on exaclty "a[i].length" part.

function flatten(a) {
	    var target = [];
	    for (var i = 0; i < a.length; ++i) {
	        for (var j = 0; j < a[i].length; ++j) {
	            target.push(a[i][j]);
	        }
	    }
	    return target;
	}

* **Please tell us about your environment:**

- Angular version: 2.0.0-rc.6
- Browser: [ Chrome 49 | Firefox 48 ]
- OS: Ubuntu 14.04

**Comment by IAMtheIAM** [comment]
It doesn't sound like an Angular error, since your code is custom. `a` is undefined either in the first loop, or the second loop. Did you try debugging the value at run time to see what it evaluates too? We need more code to debug.

**Comment by bruno-serfe** [comment]
HI, Thanks for the response, I've managed to resolve the error, it seems like was an error with a module, I've a lot of modules in the app and that error has lack of information to debug. Sorry for the false alarm. You can close this issue.
