### ISSUE TITLE
Can`t find @angular/common when update from RC4 to RC6

### ISSUE THREAD

**Issue by eugenebovkun** [AngularClass/angular2-webpack-starter#973]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)
- **I'm submitting a ...**
  [ x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
- **Do you want to request a _feature_ or report a _bug_?**
  Bug
- **What is the current behavior?**
  I`m trying to update project from RC4 to RC6 with changing package.json
  "dependencies": {
  "@angular/common": "2.0.0-rc.6",
  "@angular/compiler": "2.0.0-rc.6",
  "@angular/core": "2.0.0-rc.6",
  "@angular/forms": "^2.0.0-rc.6",
  "@angular/http": "2.0.0-rc.6",
  "@angular/platform-browser": "2.0.0-rc.6",
  "@angular/platform-browser-dynamic": "2.0.0-rc.6",
  "@angular/platform-server": "2.0.0-rc.6",
  "@angular/router": "3.0.0-rc.2",
  "@angularclass/conventions-loader": "^1.0.2",
  "@angularclass/hmr": "^1.0.1",
  "@angularclass/hmr-loader": "^1.0.1",
  "@angularclass/request-idle-callback": "^1.0.7",
  "@angularclass/webpack-toolkit": "^1.3.3",
  "core-js": "^2.4.1",
  "http-server": "^0.9.0",
  "ie-shim": "^0.1.0",
  "rxjs": "5.0.0-beta.11",
  "zone.js": "~0.6.17"
  },

after run npm install get such message: 
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\Program Files\nodejs\node.exe" "[path]\npm\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.6
npm ERR! code E404

npm ERR! 404 no such package available : @angular/common
npm ERR! 404
npm ERR! 404  '@angular/common' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'angular2-webpack-starter'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     [path]\npm-debug.log
- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
  https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).
  steps to reproduce just run npm install with this dependencies.
- **What is the expected behavior?**
  node_modules will be updated without any problem
- **What is the motivation / use case for changing the behavior?**
- **Please tell us about your environment:**
  Widhows 8 x64
  Webstorm 2016.2.3 terminal
- Angular version: 2.0.0-rc.4
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
- **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by IAMtheIAM** [comment]
Which version NPM and Node are you running? RC6 required me to update to NPM 3+ and Node 4.4.7

Try running:

1. `npm upgrade`
2. Then wipe out all node_modules
3. `npm install`

**Comment by katallaxie** [comment]
This appears to be a different problem as you seem to already run on `6.5.0`. Can you remove `node_modules` and to an `npm cache clean`. All packages specified also `@angular/common` are available https://www.npmjs.com/~angular
