### ISSUE TITLE
Error when running bootloader in a callback function

### ISSUE THREAD

**Issue by zigzag95** [AngularClass/angular2-webpack-starter#978]
I'm trying this in main.browser.ts:

```
google.charts.setOnLoadCallback(() => bootloader(main));
google.charts.load('current', {packages: ['orgchart']});
```

I get this error when running npm run build:prod

ERROR in ./src/main.browser.ts
Module parse failed: C:\Git\Promethee.FrontEnd\node_modules\@angularclass\hmr-loader\index.js?pretty=false&prod=true!C:\Git\Promethee.FrontEnd\node_modules\awesome-typescript-loader\dist\entry.js!C:\G
it\Promethee.FrontEnd\node_modules\angular2-template-loader\index.js!C:\Git\Promethee.FrontEnd\node_modules\string-replace-loader\index.js?{"search":"(System|SystemJS)(.*[\\n\\r]\\s*\\.|\\.)import\\((
.+)\\)","replace":"$1.import($3).then(mod => (mod.__esModule && mod.default) ? mod.default : mod)","flags":"g"}!C:\Git\Promethee.FrontEnd\src\main.browser.ts Unexpected token (23:102)
You may need an appropriate loader to handle this file type.
| }
| exports.main = main;
| google.charts.setOnLoadCallback(function () { return ;if (document.readyState === "complete") {   main); }() } else {   document.addEventListener("DOMContentLoaded", function() { main); }() }); };
| google.charts.load('current', { packages: ['orgchart'] });
| // bootloader(main);

PS:
It works when calling bootloader(main) without a callback

**Comment by gdi2290** [comment]
thanks fixed via https://github.com/AngularClass/angular2-webpack-starter/commit/2f614b45851056c2ec463133267cb7f8c36c994d
