### ISSUE TITLE
Runtime compiler performance issue

### ISSUE THREAD

**Issue by yuanfeiz** [AngularClass/angular2-webpack-starter#979]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**
It takes more than 20 seconds to render the first screen. In the meanwhile, the CPU usage is full.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Here is the profiling result:
![image](https://cloud.githubusercontent.com/assets/705367/18389904/a233a5aa-76da-11e6-8cad-bf3a5472f001.png)

* **What is the expected behavior?**
Lightspeed bootstraping.

* **Please tell us about your environment:**

- Angular version: 2.0.0-rc6
- Browser: [ Chrome 52.0.2743.116 | Safari XX ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by yuanfeiz** [comment]
Related to angular/angular#11371

**Comment by gdi2290** [comment]
thanks, should be fixed via https://github.com/AngularClass/angular2-webpack-starter/commit/74f99a3fb99f1957ad32182576e259b54001e5cb

**Comment by yuanfeiz** [comment]
Nice, thank you!
