### ISSUE TITLE
File Loading / Path Problems When Hosting Project

### ISSUE THREAD

**Issue by JimTheMan** [AngularClass/angular2-webpack-starter#980]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[ x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
I just need some help. lol

* **What is the current behavior?**

I am having trouble hosting the site live. It's working great when I use `npm run server` and check localhost:3000

![angular2_webpack_starter_by__gdi2290_from__angularclass](https://cloud.githubusercontent.com/assets/5354163/18410755/c6ad6c9c-7737-11e6-9a82-d3f5f6f90f4a.png)

and also when I run `npm run server:prod` and check localhost:8080:

![angular2_webpack_starter_by__gdi2290_from__angularclass](https://cloud.githubusercontent.com/assets/5354163/18410762/e9aae094-7737-11e6-85e1-be1c3a8b188c.png)

Nice! 

I then go to host the site through the Github gh-pages branch. My project is named "SafeFoods" and gh-pages adds an extra _SafeFoods_ into the path here in the address bar. The problem with this is that I have files looking to be loaded at a path that doesn't have _SafeFoods_ (but is otherwise identical). 

![angular2_webpack_starter_by__gdi2290_from__angularclass_and_webpack_common_js_-_ng-s_-____git-projects_safefoods_ng-s_](https://cloud.githubusercontent.com/assets/5354163/18410782/99423b6a-7738-11e6-9819-0aeee43a2461.png)

I have tried changing "baseUrl" in the webpack.common.js file, but this breaks the site when I run the dev server and prod server!

Does anyone know how I can make it so that the site works in all three situations?
thanks.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 

live hosted site: [https://jimtheman.github.io/SafeFoods/](https://jimtheman.github.io/SafeFoods/)
original repo: [https://github.com/JimTheMan/SafeFoods](https://github.com/JimTheMan/SafeFoods)

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

angular version: 2.0.0-rc.6
all browsers

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by i7326** [comment]
try <script src="./pathtofile">  same applies to all the files you load.. hope this helps :)

**Comment by JimTheMan** [comment]
Huh? Where is this code you are referring to??

**Comment by i7326** [comment]
your script/link tags & base url in dist/index.html should be like this



> tags


	<link rel="icon" type="image/png" sizes="16x16" href="./assets/icon/favicon-16x16.png">
	<link rel="manifest" href="./assets/manifest.json">
          
       
       <base href="." >
       <script type="text/javascript" src="./polyfills.b412f5443b5dfc15f5f9.bundle.js">

**Comment by JimTheMan** [comment]
ok thanks. This does technically work, but it's not a good solution because I really shouldn't need to go into the dist folder and manually change things after the project is built. 

Is there any way to have `gulp build` create a project with the relative paths instead of absolute?

**Comment by i7326** [comment]
Yes its not the right way.. and you should always host in root folder... this way you can avoid this issue...

'/' => root folder
'.' => current folder

base href="/" => states base folder is root ..

**Comment by JimTheMan** [comment]
Thanks. I made the change, but I'm still getting errors:

![angular2_webpack_starter_by__gdi2290_from__angularclass](https://cloud.githubusercontent.com/assets/5354163/18416752/cd1bebae-77ea-11e6-8158-fef92f0e0465.png)

**Comment by JimTheMan** [comment]
aha. Yep, I was missing vendor for some reason in that last push. I updated baseUrl to be '.' in config/webpack.common.js, pushed again, and it now seems to be working! Yes! Thanks @i7326. :)
