### ISSUE TITLE
No error trace on template errors

### ISSUE THREAD

**Issue by Ovidiu-S** [AngularClass/angular2-webpack-starter#982]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[ ] bug report
[ x] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
I think both.

* **What is the current behavior?**
Adding a custom element that is not a selector for any component, causes this error: 

`main.browser.ts:25 Error: Template parse errors:(…)(anonymous function) `

`@ main.browser.ts:25ZoneDelegate.invoke `

`@ zone.js:192Zone.run` 

`@ zone.js:85(anonymous function)`

`@ zone.js:451ZoneDelegate.invokeTask `

`@ zone.js:225Zone.runTask `

`@ zone.js:125drainMicroTaskQueue `

`@ zone.js:357ZoneTask.invoke `

`@ zone.js:297`

There is no trace to the actual element, and in a large app it makes it impossible to debug.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by zigzag95** [comment]
Just click on ...

**Comment by Ovidiu-S** [comment]
@zigzag95 thank you, my bad. This can be closed
