### ISSUE TITLE
Cannot find name error when running with target es5

### ISSUE THREAD

**Issue by gaurav2887** [AngularClass/angular2-webpack-starter#997]
Hi All,

I am getting following error when running the project  using npm run server:dev.

My tsconfig.json file: "target": "es5"

Error:
Cannot find name 'Map'.
Cannot find name 'Promise'.
Cannot find name 'Set'.

If I change target to es6 then error goes away but my app stopped working in Internet explorer. Is there any way I can get rid of these error keeping es5 target?

I have also tried typings install but no luck.

**Comment by exk0730** [comment]
Hey, I had this issue too using WebStorm. The problem is that the `lib` option doesn't seem to be supported (see [this issue](https://github.com/TypeStrong/atom-typescript/issues/1009)). What I did was remove the `lib` option and put `core-js` inside the `types` option. My tsconfig file looks like this:

```
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "sourceMap": true,
    "noEmitHelpers": true,
    "strictNullChecks": false,
    "baseUrl": "./src",
    "paths": {
        "core": ["app/core"],
        "shared": ["app/shared"]
    },
    "types": [
      "lodash",
      "core-js",
      "hammerjs",
      "jasmine",
      "node",
      "protractor",
      "selenium-webdriver",
      "source-map",
      "uglify-js",
      "webpack"
    ]
  },
  "exclude": [
    "node_modules",
    "dist"
  ],
  "awesomeTypescriptLoaderOptions": {
    "forkChecker": true,
    "useWebpackText": true
  },
  "compileOnSave": false,
  "buildOnSave": false,
  "atom": { "rewriteTsconfig": false }
}
```

If this isn't the best work-around, please let me know.

**Comment by gaurav2887** [comment]
@exk0730 - That was it.. It's working now with no errors.. Thanks a lot

**Comment by webia1** [comment]
better you upgrade the typescript version in WebStorm:

![update_typescriptversion_in_webstorm](https://cloud.githubusercontent.com/assets/2741558/19963035/e1af7d3e-a1ba-11e6-922a-03874ace521f.png)
